<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->headLink()->appendStylesheet('/theme/flatui/css/select2.min.css');
$this->headLink()->appendStylesheet('/theme/flatui/css/select2.custmized.css');
$this->inlineScript()->appendFile('/theme/flatui/js/lib/select2.min.js');
?>

<div class="form-group">
    <div class="col-sm-12 margin-top-15">
        <?php if ($this->element->getOption('required')) { ?>
            <div class="small grey bold-font pull-left margin-right-5">*</div>
        <?php } ?>
        <label class="form-label" for="<?= $this->element->getName() ?>">Tags</label>
    </div>
    <div class="col-sm-12">
        <select
                id="<?= $this->element->getName() ?>"
                name="<?= $this->element->getName() ?>[]"                
                multiple="true"
                class="taggingSelect2">
            <option value=""></option>
            <?php
            $element_value = $this->element->getValue();
            if(is_array($element_value))
            {
                $element_value = array_shift($element_value);
            }
            $value = empty($element_value) ? array() : explode(',',$element_value);            
            foreach ($value as $v) {
                echo '<option value="'.$v.'" selected="selected">'.$v.'</option>';                
            }            
            ?>         
        </select>
        <?php if ($this->element->getMessages()) {
            $errorHtml = '';
            foreach ($this->element->getMessages() as $currentError) {
                $errorHtml .= '<label id="<?=$this->escape($this->element->getName())?>-error" class="error" for="<?=$this->escape($this->element->getName())?>">' . $currentError . '</label>';
            }
            ?>
            <?php echo $errorHtml ?>
        <?php } ?>
    </div>
</div>


<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){       
            TagingProductSelect2.setup();            
        });
    ');