<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>

<style>
  @media (max-width:767px) {
    main#reg-page section#register-wrap {
      position: absolute;
      top: 150px;
      margin: 0;
      width: 90%;
      left: 5%;
    }
    main#reg-page section#register-wrap button#login {
      margin-top: 8px;
      width: 100%;
    }
    main#reg-page section#register-wrap #register #social-register {
      float: right;
      width: 100%;
      padding: 0;
    }
    main#reg-page section#register-wrap #register #social-register #social-login-elements {
      margin: 0;
    }
  }
</style>

<div id="login-form-box" class="well">
    <h3><?= $this->translate('Log into your account') ?></h3>

    <div id="error" class="center text-error help-block">
        <?php if ($this->error && isset($this->errorText)): ?>
            <p class="errors">
                <?= $this->translate($this->errorText) ?>
            </p>
        <?php endif; ?>
    </div>
    <form class="standard-form row-fluid center partialjson"
          action="<?= $this->formLogin->getAction(); ?>"
          method="<?= $this->formLogin->getMethod(); ?>"
          data-target="#register-box"
          data-load-state="#login"
    >
        <?=Default_Model_CsrfProtection::getFormCsrf('login_csrf'); ?>
        <?= $this->formLogin->redirect ?>
        <?= $this->formLogin->dologin ?>
        <?php
        if ($this->error) {
            $this->formLogin->mail->class = $this->formLogin->mail->class . ' has-error';
        }
        ?>
        <?= $this->formLogin->mail->setAttrib('placeholder', 'Email or Username')->setAttrib('class', 'inputbox email')->setAttrib('required','required') ?>
        <?= $this->formLogin->password->setAttrib('placeholder', 'Password')->setAttrib('class', 'inputbox password')->setAttrib('required', 'required') ?>
        <?= $this->formLogin->remember_me->setAttrib('class', 'btn btn-min-width btn-native')->setAttrib('type', 'submit'); ?>
        <?php /*$this->formLogin->login */ ?>
        <button name="<?= $this->formLogin->login->getName() ?>" id="<?= $this->formLogin->login->getId() ?>" type="submit" class="btn btn-min-width btn-native"><?= $this->formLogin->login->getLabel() ?> <i id="load-state" class="fa fa-spinner fa-pulse hidden" aria-hidden="true"></i></button>
    </form>

    <div class="small light lightgrey center margin-top-15">
        <a href="/password/request" class="lightblue"><?= $this->translate('Forgot your password?') ?></a>
    </div>

    <div class="small light lightgrey margin-top-15">
        * for github login, please use "<a href="/password/request" class="lightblue"><?= $this->translate('reset password') ?></a>" and then login with your username and new password

    </div>

</div>
