<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div id="register-form-box" class="well">
    <h3><?= $this->translate('Join the community') ?></h3>

    <div id="error" class="center text-error help-block">
        <?php if ($this->error && isset($this->errorText)): ?>
            <p class="errors">
                <?= $this->translate($this->errorText) ?>
            </p>
            <p class="errors">
                <?php echo $this->formErrors(); ?>
            </p>

        <?php endif; ?>
    </div>
    <form class="standard-form row-fluid center partialjson" id="<?= $this->formRegister->getAttrib('id'); ?>"
          action="<?= $this->formRegister->getAction(); ?>"
          method="<?= $this->formRegister->getMethod(); ?>"
          data-target="#register-box">
        <?= $this->formRegister->csrfRegister ?>
        <div class="form-group has-feedback"><?= $this->formRegister->username ?></div>
        <div class="form-group has-feedback"><?= $this->formRegister->mail ?></div>
        <div class="form-group has-feedback"><?= $this->formRegister->password1 ?></div>
        <div class="form-group has-feedback"><?= $this->formRegister->password2 ?></div>
        <?php /** <div class="form-group has-feedback"><?= $this->formRegister->realHuman ?></div>**/?>
        <div class="g-recaptcha" id="g-recaptcha"></div>
        
        <?= $this->formRegister->login ?>
    </form>

    <div class="small light lightgrey center">
        By clicking register you agree to the <br/>
        <a href="/content/terms"
           class="lightblue"><?= $this->translate('Terms &amp; Conditions') ?></a> <?= $this->translate('and') ?> <a
            href="/content/privacy" class="lightblue"><?= $this->translate('privacy policy') ?></a>
    </div>
</div>
