ALTER TABLE `member_download_history`  ADD COLUMN `HTTP_X_FORWARDED_FOR` VARCHAR(30);
ALTER TABLE `member_download_history`  ADD COLUMN `HTTP_X_FORWARDED` VARCHAR(30);
ALTER TABLE `member_download_history` ADD COLUMN `HTTP_CLIENT_IP` VARCHAR(30);
ALTER TABLE `member_download_history` ADD COLUMN `HTTP_FORWARDED_FOR` VARCHAR(30);
ALTER TABLE `member_download_history` ADD COLUMN `HTTP_FORWARDED` VARCHAR(30);
ALTER TABLE `member_download_history` ADD COLUMN `REMOTE_ADDR` VARCHAR(30);