<?php
/*
 *   ocs-webserver
 *
 *   Copyright 2016 by pling GmbH.
 *
 *     This file is part of ocs-webserver.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace ApplicationTest\Filter;

use Library\Filter\HtmlPurify;
use PHPUnit\Framework\TestCase;

class HtmlPurifyTest extends TestCase
{
    protected function setUp()
    {
        defined('APPLICATION_DATA') || define('APPLICATION_DATA', realpath(__DIR__ . '/../../../../data/'));
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testFilterEvilHtml()
    {
        echo (__DIR__ . "\n");
        echo(APPLICATION_DATA . "\n");
        $filter = new HtmlPurify(['schema' => HtmlPurify::ALLOW_HTML]);
        $this->assertEquals('x', $filter->filter('<iframe src="https://example.com">x</iframe><img src=x onerror=alert(1) />'));
    }

    public function testEmbedCode()
    {
        $filter = new HtmlPurify(['schema' => HtmlPurify::ALLOW_EMBED]);
        $this->assertEquals('<iframe width="560" height="315" src="https://www.youtube.com/embed/dh8zBcfsKX0" frameborder="0"></iframe>', $filter->filter('<iframe width="560" height="315" src="https://www.youtube.com/embed/dh8zBcfsKX0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'));

        $this->assertEquals('<iframe width="560" height="315" src="https://www.youtube.com/embed/_INLd1ugQ50" frameborder="0"></iframe>', $filter->filter('<iframe width="560" height="315" src="https://www.youtube.com/embed/_INLd1ugQ50" frameborder="0" allowfullscreen></iframe>'));

        $this->assertEquals('<iframe></iframe>', $filter->filter('<iframe src=http://tattooink.16mb.com/11896183_911790995548489_8918876135156281001_n.jpg"style"width:259px;height:445px;"width="890"height="360"framebordeer="0"allow="autoplay;encrypted-media"allowfullscreen></iframe>'));

        $this->assertEquals('<iframe src="https://player.vimeo.com/video/291229192" width="640" height="360" frameborder="0"></iframe>
 <p><a href="https://vimeo.com/291229192">Tevida- Improves Your Endurance And Staying Power</a> from <a href="https://vimeo.com/user89804835">klnjkhhyf Lee</a> on <a href="https://vimeo.com">Vimeo</a>.</p>',
                            $filter->filter('<iframe src="https://player.vimeo.com/video/291229192" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
 <p><a href="https://vimeo.com/291229192">Tevida- Improves Your Endurance And Staying Power</a> from <a href="https://vimeo.com/user89804835">klnjkhhyf Lee</a> on <a href="https://vimeo.com">Vimeo</a>.</p>'));

        $this->assertEquals('<iframe frameborder="0" width="700" height="400"></iframe>', $filter->filter('<iframe src="https://paktube.org/embed/VOMtPpZUdY13SJ9" frameborder="0" width="700" height="400" allowfullscreen></iframe>'));

        $this->assertEquals('<iframe width="100%" height="300" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/535593867&amp;color=%23ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true"></iframe>',
                            $filter->filter('<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/535593867&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>'));

        $this->assertEquals('<iframe src="https://player.vimeo.com/video/482814365" width="640" height="360" frameborder="0"></iframe>
 <p><a href="https://vimeo.com/482814365">kisskool</a> from <a href="https://vimeo.com/user81368677">kisskool</a> on <a href="https://vimeo.com">Vimeo</a>.</p>',
                            $filter->filter('<iframe src="https://player.vimeo.com/video/482814365" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
 <p><a href="https://vimeo.com/482814365">kisskool</a> from <a href="https://vimeo.com/user81368677">kisskool</a> on <a href="https://vimeo.com">Vimeo</a>.</p>'));
        $this->assertEquals('', $filter->filter(''));
        $this->assertEquals('', $filter->filter(''));
        $this->assertEquals('', $filter->filter(''));
        $this->assertEquals('', $filter->filter(''));
        $this->assertEquals('', $filter->filter(''));
    }

    public function testEmbedEvilCode()
    {
        $filter = new HtmlPurify(['schema' => HtmlPurify::ALLOW_EMBED]);
        $this->assertEquals('<iframe>x</iframe><img src="x" alt="x" />', $filter->filter('<iframe src="https://example.com">x</iframe><img src=x onerror=alert(1) />'));

        $this->assertEquals('<iframe>x</iframe>', $filter->filter('<iframe src="https://localhost/.wellknown/metadata/v1">x</iframe>'));

        $this->assertEquals('<iframe>x</iframe>', $filter->filter('<iframe src="https://www.opendesktop.org/p/998694/">x</iframe><script>alert("You\'re a dummy!");</script>'));

        $this->assertEquals('', $filter->filter(''));
        $this->assertEquals('', $filter->filter(''));
        $this->assertEquals('', $filter->filter(''));

    }

    public function testBBCode()
    {
        $filter = new HtmlPurify();

        $this->assertEquals('[URL=https://info.flagcounter.com/K1O8][IMG]https://s01.flagcounter.com/count2/K1O8/bg_FF7F00/txt_FFFFFF/border_FF007F/columns_8/maxflags_250/viewers_0/labels_1/pageviews_1/flags_0/percent_0/[/IMG][/URL]', $filter->filter('[URL=https://info.flagcounter.com/K1O8][IMG]https://s01.flagcounter.com/count2/K1O8/bg_FF7F00/txt_FFFFFF/border_FF007F/columns_8/maxflags_250/viewers_0/labels_1/pageviews_1/flags_0/percent_0/[/IMG][/URL]'));
        $this->assertEquals('more information news foollball and gambling visit my website
 thank[
 
 
 [b]bold[/b]
 [i]italic[/i]
 [u]underline[/u]
 [li]list[/li]
 [strike][/strike]
 [url]http://www.agensbobetlive.com/promosi/[/url]', $filter->filter('more information news foollball and gambling visit my website
 thank[
 
 
 [b]bold[/b]
 [i]italic[/i]
 [u]underline[/u]
 [li]list[/li]
 [strike][/strike]
 [url]http://www.agensbobetlive.com/promosi/[/url]'));

    }

    public function testSomeOther()
    {
        $filter = new HtmlPurify();

        $this->assertEquals('http://www.ecigbangkok.com/ - ร้านขายบุหรี่ไฟฟ้า ecig e-liquid (น้ำยาบุหรี่ไฟฟ้า) ราคาถูกมาก หากอยากเลิกบุหรี่ ทางร้านได้คัดสรรบุหรี่ไฟฟ้าดี มีคุณภาพ ปลอดภัย พร้อมราคาบุหรี่ไฟฟ้า อุปกรณ์เสริมทุกชนิด&amp;#13;&amp;#10;',
        $filter->filter('http://www.ecigbangkok.com/ - ร้านขายบุหรี่ไฟฟ้า ecig e-liquid (น้ำยาบุหรี่ไฟฟ้า) ราคาถูกมาก หากอยากเลิกบุหรี่ ทางร้านได้คัดสรรบุหรี่ไฟฟ้าดี มีคุณภาพ ปลอดภัย พร้อมราคาบุหรี่ไฟฟ้า อุปกรณ์เสริมทุกชนิด&amp;#13;&amp;#10;')
        );

        $this->assertEquals('Please, go to the download page and choose the size:
 [url]http://wallpaper.soa-admin.eu/show-0000000477.html[/url]', $filter->filter('Please, go to the download page and choose the size:
 [url]http://wallpaper.soa-admin.eu/show-0000000477.html[/url]'));
    }

    public function testBBCodeXSS()
    {
        $filter = new HtmlPurify();

        $this->assertEquals('
[b][/b]
[div class="javascript:alert(document);"]Attribute XSS prevention[/div]
[video="youtube" size="small"]"onload="alert(\'XSS\');" id="[/video]', $filter->filter('<script>alert("I can use XSS");</script>
[b]<script>alert(document.cookie);</script>[/b]
[div class="javascript:alert(document);"]Attribute XSS prevention[/div]
[video="youtube" size="small"]"onload="alert(\'XSS\');" id="[/video]'));

        $this->assertEquals('[img]http://localhost/doSomething.php?image=http://www.google.com/intl/en_ALL/images/srpr/logo1w.png[/img]', $filter->filter('[img]http://localhost/doSomething.php?image=http://www.google.com/intl/en_ALL/images/srpr/logo1w.png[/img]'));
    }
}
