

 <?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$updateTime = $this->printDate($this->project_changed_at);
$nr = $this->partialLoop()->nr++;
$nr++;
?>

<div class="explore-product col-lg-12 col-md-12 col-sm-12 col-xs-12 disply-flex rowproduct">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <div class="rank">
            <?=$nr?>
        </div>        
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 ">
        <a href="<?php echo $this->buildMemberUrl($this->username); ?>">
                <figure class="mostplingedcreators">
                    <img class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$this->member_id?>" src="<?php echo $this->Image($this->profile_image_url, array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
                </figure>
        </a>
    </div>
    <div class="col-lg-2">

        <?php echo $this->username; ?>
    </div>
    <div class="col-lg-2">
        <span class="small created_at" >                    
          <span class="small"><?=number_format($this->score,0,'.',',') ?><span class="small">
        </span>
    </div>
</div>



