   <?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$nr = $this->partialLoop()->nr++;
$nr++;
?>
  <div class="user ">
    <div class="u-wrap" >
        <a href="<?php echo $this->buildMemberUrl($this->username); ?>">
            <figure >
                <img class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$this->member_id?>" src="<?php echo $this->Image($this->profile_image_url, array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
            </figure>
            <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $this->username; ?></h3>                                        
            <span class="rank"><?=$nr?></span>
               <span class="small"><?=number_format($this->score,0,'.',',') ?><span class="small">                                                                 
        </a>
    </div>
</div>
