<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helpAddDefaultScheme = new Default_View_Helper_AddDefaultScheme();
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helpEncryptUrl = new Default_View_Helper_EncryptUrl();
$helpImage = new Default_View_Helper_Image();
$helpTruncate = new Default_View_Helper_Truncate();
$helpProductUrl = new Default_View_Helper_BuildProductUrl();
$helpBBCode = new Default_View_Helper_Bbcode2html();

$identity = Zend_Auth::getInstance()->getStorage()->read();

$loginUrl = '/login?redirect=' . $helpEncryptUrl->encryptUrl(Zend_Controller_Front::getInstance()->getRequest()
        ->getRequestUri(), true);
$viewSidebar = 'product/partials/productAboutSidebar.phtml';
$viewClaimBox = false;
if ($this->product->claimable == 1) {
    $viewClaimBox = 'product/partials/productClaimTopHeader.phtml';
}
$helpProjectFiles = new Default_View_Helper_ProjectFiles();
$productFileInfos = $helpProjectFiles->projectFiles($this->product->ppload_collection_id);

$this->product->title = Default_Model_HtmlPurify::purify($this->product->title);
$this->product->description = Default_Model_BBCode::renderHtml(Default_Model_HtmlPurify::purify($this->product->description));
$this->product->version = Default_Model_HtmlPurify::purify($this->product->version);
//$this->product->embed_code =Default_Model_HtmlPurify::purify($this->product->embed_code,Default_Model_HtmlPurify::ALLOW_EMBED);
$this->product->link_1 = Default_Model_HtmlPurify::purify($helpAddDefaultScheme->addDefaultScheme($this->product->link_1),Default_Model_HtmlPurify::ALLOW_URL);
$this->product->source_url = Default_Model_HtmlPurify::purify($this->product->source_url,Default_Model_HtmlPurify::ALLOW_URL);
$this->product->facebook_code = Default_Model_HtmlPurify::purify($this->product->facebook_code,Default_Model_HtmlPurify::ALLOW_URL);
$this->product->twitter_code = Default_Model_HtmlPurify::purify($this->product->twitter_code,Default_Model_HtmlPurify::ALLOW_URL);
$this->product->google_code = Default_Model_HtmlPurify::purify($this->product->google_code,Default_Model_HtmlPurify::ALLOW_URL);


$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);

$this->headMeta()->setName('description',
    $helpTruncate->truncate($this->product->description, 200, '...', false, true));
$this->headMeta()->setName('title',
    $helpTruncate->truncate($this->product->title, 200, '...', false, true));
$this->headMeta()->appendProperty('og:url', $helpProductUrl->buildProductUrl($this->product->project_id, '', null, true));
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', $this->product->title);
$this->headMeta()->appendProperty('og:description',
    $helpTruncate->truncate($this->product->description, 200, '...', false, true));
$this->headMeta()->appendProperty('og:image',
    $helpImage->Image($this->product->image_small, array('width' => 400, 'height' => 400)));
$tableProject = new Default_Model_Collection();

$tableProjectUpdates = new Default_Model_ProjectUpdates();
$this->updates = $tableProjectUpdates->fetchProjectUpdates($this->product->project_id);

$tableProjectRatings = new Default_Model_DbTable_ProjectRating();
$this->ratings = $tableProjectRatings->fetchRating($this->product->project_id);
$cntRatingsActive = 0;
 foreach ($this->ratings as $p) {
    if($p['rating_active']==1) $cntRatingsActive =$cntRatingsActive+1;
 }

if (Zend_Auth::getInstance()->hasIdentity()){
    $this->ratingOfUser = $tableProjectRatings->getProjectRateForUser($this->product->project_id,$identity->member_id);
}

$tableProjectFollower = new Default_Model_DbTable_ProjectFollower();
$this->likes = $tableProjectFollower->fetchLikesForProject($this->product->project_id);

$projectplings = new Default_Model_ProjectPlings();
$this->projectplings = $projectplings->fetchPlingsForProject($this->product->project_id);

$tagmodel = new Default_Model_Tags();

$helperUserRole = new Backend_View_Helper_UserRole();
$userRoleName = $helperUserRole->userRole();


$productJson = Zend_Json::encode(Default_Model_Collection::cleanProductInfoForJson($this->product->toArray()));
$helperCatXdgType = new Default_View_Helper_CatXdgType();
$xdgTypeJson = Zend_Json::encode($helperCatXdgType->catXdgType($this->product->project_category_id));

$isowner = false;
if(Zend_Auth::getInstance()->hasIdentity() && $identity->member_id==$this->product->member_id){
    $isowner = true;
}

?>
<style type="text/css">
    .collection-panels{
        background: none repeat scroll 0 0 #fff;
        height: auto;     
        border-radius: 0;
        padding: 15px;
        float: left;
        width: 100%;
        margin: 0;
      
    }
    span.downloadlink
    {
        white-space: normal; color: #23527c;
    }
    span.filesize
    {
        float: right;
    }

    div.row-collection
    {
        padding-top: 10px;
        border-top: 1px solid lightgray; 
        margin-top: 10px;
    }
    div.row-collection:first-child
    {
        padding-top: 0px;
        border-top: 0px; 
        margin-top:0px;
       
    }
    div.row-detail
    {
        padding-top: 10px;
        font-size: small;
    }
    
    #product-discussion h3 {
        color: #2673b0;
        margin-bottom: 20px;
        margin-top: 0;
    }
</style>


    <link href="/theme/react/assets/css/get-it.css" type="text/css" rel="stylesheet"/>

    <!-- facebook -->
    <div id="fb-root"></div>
    <?php if (Zend_Auth::getInstance()->hasIdentity()) {
        ?>
    <div id="report-product-<?= $this->product->project_id ?>" class="modal report-product" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <form id="product-report" class="full-width partialjson" action="/report/product/"
                      data-target="#report-product-<?= $this->product->project_id ?>-message">
                    <input type="hidden" name="p" value="<?= $this->product->project_id ?>">
                    <div id="report-product-<?= $this->product->project_id ?>-message">
                        <p>Do you really want to report this product?</p>
                        <div class="modal-footer">
                            <button type="submit" class="small">
                                <span class="glyphicon glyphicon-share-alt"></span> Yes
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div id="report-product-fraud-<?= $this->product->project_id ?>" class="modal report-product-fraud" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <form id="product-report-fraud" class="full-width partialjsonfraud" action="/report/productfraud/"
                      data-target="#report-product-fraud-<?= $this->product->project_id ?>-message" >
                    <input type="hidden" name="p" value="<?= $this->product->project_id ?>">
                    <div id="report-product-fraud-<?= $this->product->project_id ?>-message" class="message" style="padding: 20px">
                        <div>Please specify why this product is misused (min 5 chars):
                           <textarea class="" id="report-text" name="t" cols="50" rows="3"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="small">
                                <span class="glyphicon glyphicon-share-alt"></span> Report
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


     <div id="report-product-clone-<?= $this->product->project_id ?>" class="modal report-product-clone" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                                <h2 class="modal-title">This product is based on:</h2>
                </div>
                <form id="product-report-clone" class="full-width partialjson" action="/report/productclone/"
                      data-target="#report-product-clone-<?= $this->product->project_id ?>-message">
                    <input type="hidden" name="p" value="<?= $this->product->project_id ?>">
                    <div id="report-product-clone-<?= $this->product->project_id ?>-message" class="message" style="padding: 20px">
                        <div>
                            <label class="form-label">Original product ID on opendesktop:  </label><br/>
                            <input name="pc" onkeyup="this.value=this.value.replace(/[^\d]/,'')"/><br/><br/>
                            <label class="form-label">External link to original product: </label><br/>
                            <input name="l" style="width: 440px;" />
                            <br/><br/>
                            <label class="form-label">Additional message: </label>
                            <br/>
                           <textarea class="" id="report-text" name="t"  rows="3" style="width: 440px;"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="small">
                                <span class="glyphicon glyphicon-share-alt"></span> add credits
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <?php } ?>




    <?php if (Zend_Auth::getInstance()->hasIdentity()) {
        ?>
    <div id="like-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <div class="modal-body">
                 <form class="full-width " action="/" method="post">
                            <input type="hidden" name="p" value="<?= $this->product->project_id ?>"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>
                            <input type="hidden" name="pm" value="<?=$this->product->member_id?>" id="productcreator"/>
                </form>
                </div>
            </div>
        </div>
    </div>

    <?php
    } else { ?>

    <div id="like-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
           <div class="modal-content" style="min-height: 100px; ">
               <span style="text-align: center; display: block; padding-top: 30px">Please login. <br/><a href="<?=$loginUrl?>">Login</a></span>
           </div>
         </div>
    </div>

    <?php } ?>

    <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
    <div id="review-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <div class="modal-body">
                 <form class="full-width product-add-comment-review" action="/productcomment/addreplyreview/" method="post" >
                            <input type="hidden" name="p" value="<?= $this->product->project_id ?>"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>
                            <input type="hidden" name="v" value="1" id="voteup"/>
                            <input type="hidden" name="pm" value="<?=$this->product->member_id?>" id="productcreator"/>
                            <input type="hidden" name="otxt" value="<?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?>" id="otxt"/>
                            <input type="hidden" name="userrate" value="<?=$this->ratingOfUser==null?-1:$this->ratingOfUser['user_like']?>" id="userrate"/>
                            <textarea name="msg" class="full-width" id="commenttext"><?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?></textarea>
                            <button type="submit" class="small pull-right">Rate Now</button>
                </form>
                </div>
            </div>
        </div>
    </div>

    <div id="score-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <form class="full-width product-add-comment-review-new" action="/productcomment/addreplyreviewnew/" method="post" id="reviewform">
               <div class="modal-body">
                 
                            <input type="hidden" name="p" value="<?= $this->product->project_id ?>"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>                            
                            <input type="hidden" name="pm" value="<?=$this->product->member_id?>" id="productcreator"/>
                            <input type="hidden" name="otxt" value="<?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?>" id="otxt"/>
                            
                            <input type="hidden" name="userscore" value="<?=$this->ratingOfUser==null?-1:$this->ratingOfUser['score']?>" id="userscore"/>
                            <input type="hidden" name="s" value="<?=$this->ratingOfUser==null?-1:$this->ratingOfUser['score']?>" id="userscorevalue"/>
                            <textarea name="msg" class="full-width" id="commenttext"><?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?></textarea>
                                   
                </div>
                <div class="modal-footer">
                            <button type="button" class="small" id="modal-btn-cancel" style="margin-right:20px ">Cancel</button>                             
                            <button type="submit" class="small pull-right" id="modal-btn-onsubmit">Rate Now</button>
                </div>
                </form>
            </div>
        </div>
    </div>

    <?php } else {?>
        <div id="review-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
               <div class="modal-content" style="min-height: 150px; ">
                   <span style="text-align: center; display: block; padding-top: 30px">
                    Please login.
                    <br/>
                    <a href="<?=$loginUrl?>" rel="nofollow"> Login </a>
                   <?php /*
                    Only registered members with an active supporting can vote<br/>to limit spam and fraud voting.<br/>
                    <a href="/support">Become a supporter</a>
                    <br/><br/>You can still 'Like' a product, but that doesn't affect its score.
                        */
                    ?>
                    </span>
               </div>
             </div>
        </div>

        <div id="score-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
               <div class="modal-content" style="min-height: 150px; ">
                   <span style="text-align: center; display: block; padding-top: 30px">
                    Please login.
                    <br/>
                    <a href="<?=$loginUrl?>" rel="nofollow"> Login </a>                   
                    </span>
               </div>
             </div>
        </div>

    <?php } ?>


    <link href="/theme/flatui/css/product-page.css" type="text/css" rel="stylesheet"/>

    <main id="product-page-content">
        <div id="product-page-view" class="disply-flex">
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12 sidebar-left" style="">
                <?php  echo $this->render('explore/partials/filter.phtml'); ?>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12" id="product-main">
                <div class="flex-row imgsmall" id="product-main-img-container">
                    <div class="product-main-img flex-item-24" id="product-main-img">
                        <div id="product-title-div" class="product-title-div">
                            <div  class="product-title">
                            <div class="product-logo-container">
                                  <img class="logo" src="<?= $helpImage->Image($this->product->image_small,
                                      array('width' => 85, 'height' => 85, 'crop' => 'crop')); ?>"/>
                                </div>
                                <div id="product-header-info-container">

                                    <div id="product-header-title">
                                    <?php if (false === empty($this->product->link_1)): ?><a
                                        href="<?php echo $this->product->link_1; ?>"
                                        target="_NEW"
                                        title="<?php echo $this->product->link_1; ?>"
                                        rel="nofollow"
                                        > <?= $this->product->title; ?> <span class="fa fa-external-link"></span></a>
                                    <?php else : ?>
                                        <?= $this->product->title; ?>
                                    <?php endif; ?>

                                    <?php
                                                if($this->product->featured=='1'){
                                        ?>
                                            <span class=" label label-info right" style="font-size: 13px;padding: .2em .6em .3em;"> Featured</span>
                                    <?php }?>

                                    <?php if($this->isProjectOriginal($this->product->project_id)){?>
                                    <span class=" label label-info right" style="font-size: 13px;padding: .2em .6em .3em;"> Original</span>
                                    <?php }?>

                                    </div>


                                    <p class="product_category">
                                    <?php
                                    echo '<a href="/browse/cat/' . $this->product->project_category_id . '/order/latest">' . $this->product->cat_title . ' </a>';
                                    ?>

                                    <?php
                                    echo '<span class="topics">';

                                    $tagsuser = $tagmodel->getTagsUser($this->product->project_id, Default_Model_Tags::TAG_TYPE_PROJECT);
                                    echo '<span class="topicslink">';
                                    if(false === empty($tagsuser))
                                    {
                                        foreach (explode(',',$tagsuser) as $tag) {
                                    ?>
                                    <a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a>
                                     <?php
                                        }
                                     }
                                     echo '</span><!--end of topicslink-->';
                                     if($isowner){
                                            $this->headLink()->appendStylesheet('/theme/flatui/css/select2.min.css');
                                            $this->headLink()->appendStylesheet('/theme/flatui/css/select2.custmized.css');
                                            $this->inlineScript()->appendFile('/theme/flatui/js/lib/select2.min.js');
                                        ?>
                                        <span class="tagsuserselectpanel" style="display: none; ">
                                            <select
                                                    id="tagsuserselect"
                                                    name="tagsuser"
                                                    multiple="true"
                                                    class="taggingSelect2"
                                                    data-pid="<?php echo $this->product->project_id?>"
                                                    >
                                                <option value=""></option>
                                                <?php
                                                $element_value =$tagsuser;
                                                $value = empty($element_value) ? array() : explode(',',$element_value);
                                                foreach ($value as $v) {
                                                    echo '<option value="'.$v.'" selected="selected">'.$v.'</option>';
                                                }
                                                ?>
                                            </select>
                                        </span>

                                        <button class="btn-link topic-tags-btn"  type="button" >Manage tags</button>
                                        <span class="topic-tags-saved"><i class="fa fa-check"></i> Saved </span>
                                    <?php
                                            $this->inlineScript()->appendScript(
                                                '    $(document).ready(function(){
                                                        TagingProductDetail.setup();
                                                    });
                                                ');
                                         }
                                    echo '</span>';
                                     ?>

                                </div>
                            </div>

                            <div class="product-title-right" >


                                <div class="projectdtailHeart">
                                        <div id="container-follow<?=$this->product->project_id?>" class="container-pling">
                                        <?php
                                            echo $this->partial(
                                                '/product/partials/projectlike.phtml',
                                                array(
                                                    "authMember"  => $identity,
                                                    "project_id" => $this->product->project_id
                                                )
                                            );
                                        ?>
                                        </div>
                                </div>

                                 <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName ){  ?>
                                <div class="projectdetailRating" style="clear: right">
                                        <?php echo $this->render('partials/sidebarRating.phtml'); ?>
                                </div>
                                <?php } ?>
                                
                                <div class="projectdetailRating" style="clear: right">
                                        <?php echo $this->render('partials/sidebarScore.phtml'); ?>
                                </div>


                            </div>
                        </div>

                        <div style="padding-left: 25px;">   
                            <?php
                                    if($this->product->is_gitlab_project && $this->product->use_gitlab_project_readme && null != $this->gitlab_project['readme_url']) {
                                    ?>
                                    <article>
                                        <b>Description:</b> <br/><br/>
                                        <?=$this->readme ?><br/><br/>
                                    </article>
                                    <?php
                                        } else {
                                    ?>
                                    <article>
                                        <b>Description:</b> <br/><br/>
                                        <?=$this->product->description ?>
                                     </article>
                                  <?php  }?>
                        </div>

                        <?php /* replace carousel part with info description
                        <div id="carouselContainer" class="carouselContainer">
                            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">

                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <?php // media embed code
                                      $cnt = 1;
                                    if ((null != $this->product->embed_code) && trim($this->product->embed_code)!=''): ?>
                                         <li data-target="#myCarousel" data-slide-to="<?php echo $cnt ?>"
                                                class="active"></li>
                                    <?php
                                      $cnt = 2;
                                    endif; ?>

                                    <?php
                                    $this->galleryPictures = $tableCollection->getGalleryPictureSources($this->product->project_id);
                                    if (count($this->galleryPictures) > 0) {
                                        foreach ($this->galleryPictures as $picture): ?>
                                            <li data-target="#myCarousel" data-slide-to="<?php echo $cnt ?>"
                                                class="<?php if (!$this->product->ppload_collection_id && $cnt == 1) {
                                                    echo 'active';
                                                } ?>"></li>
                                            <?php
                                            $cnt++;
                                        endforeach;
                                    }
                                    ?>
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">

                                    <?php // media embed code
                                      $cnt = 1;
                                    if ((null != $this->product->embed_code) && (trim($this->product->embed_code)!='')): ?>
                                        <div class="item active" style="text-align:center">
                                                <?= $this->product->embed_code ?>
                                        </div>
                                    <?php
                                      $cnt = 2;
                                    endif; ?>

                                    <?php

                                    foreach ($this->galleryPictures as $picture): ?>
                                        <div class="item <?php if (!$this->product->ppload_collection_id && $cnt == 1) {
                                            echo 'active';
                                        } ?>">
                                            <img src="<?php echo $helpImage->Image($picture, array('height' => '600')); ?>"/>
                                        </div>
                                        <?php
                                        $cnt++;
                                    endforeach; ?>
                                </div><!-- End Carousel Inner -->

                                <!-- Controls -->
                                <?php if (count($this->galleryPictures) > 1 || (count($this->galleryPictures) ==1&&(null != $this->product->embed_code) && (trim($this->product->embed_code)!=''))) { ?>
                                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </a>
                                <?php } ?> 
                            </div><!-- End Carousel -->
                        </div>
                    */?>

                    </div>
                </div>

                

                <div class="flex-item-24" id="product-tabs-container">
                    <!-- TABS -->
                    <div id="product-tabs" class="pling-nav-tabs">
                        <ul class="nav nav-tabs ">
                            <?php /*
                            <li class="active"><a href="#about-panel" data-toggle="tab">Info</a></li>
                            */?>
                        <?php if(count($this->collection_projects)>0){ ?>
                            <li class="active"><a href="#products-panel" data-toggle="tab">Products <?php echo '('.count($this->collection_projects).')';  ?></a></li>
                        <?php } ?>
                        <?php if(count($this->updates)>0){ ?>
                            <li><a href="#updates-panel" data-toggle="tab">Changelogs <?php echo '('.count($this->updates).')';  ?></a></li>
                        <?php } ?>


                        <?php /*if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName ){  ?>
                        <li><a href="#ratings-panel" data-toggle="tab">Ratings & Reviews <?php echo '('.$cntRatingsActive.')';  ?></a></li>
                       <?php } */?>
                        
                        <li><a href="#ratings-panel2" data-toggle="tab">Ratings & Reviews <?php echo '('.$cntRatingsActive.')';  ?></a></li>   

                         <?php if(count($this->likes)>0){ ?>
                            <li><a href="#likes-panel" data-toggle="tab">Fans <?php echo '('.count($this->likes).')';  ?></a></li>
                        <?php } ?>
                        <?php if(count($this->projectplings)>0){ ?>
                            <li><a href="#plings-panel" data-toggle="tab">Plings <?php echo '('.count($this->projectplings).')';  ?></a></li>
                        <?php } ?>
                        </ul>
                    </div>
                    <!-- /TABS -->

                    <!-- PANELS -->

                    <div class="tab-content row collection-panels" id="product-panels">

                        <!-- ABOUT -->
                        <?php /*
                        <div class="tab-pane active" id="about-panel">                            
                            <div id="product-about" class="col-lg-9 col-md-9 col-sm-9 col-xs-12">

                                <div>
                                    <?php
                                        if($this->product->is_gitlab_project && $this->product->use_gitlab_project_readme && null != $this->gitlab_project['readme_url']) {
                                    ?>
                                    <article>
                                        <b>Description:</b> <br/><br/>
                                        <?=$this->readme ?><br/><br/>
                                    </article>
                                    <?php
                                        } else {
                                    ?>
                                    <article>
                                        <b>Description:</b> <br/><br/>
                                        <?=$this->product->description ?>
                                        <br/><br/>
                                        <?php if($this->isProjectEbook($this->product->project_id)){?>
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookSubject($this->product->project_id);
                                            
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Subjects:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>

                                        
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookAuthor($this->product->project_id);
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Author/s:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>
                                        
                                        
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookEditor($this->product->project_id);
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Editor/s:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>

                                        
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookIllustrator($this->product->project_id);
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Illustrator/s:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>

                                        
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookTranslator($this->product->project_id);
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Tranlator/s:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>

                                        
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookShelf($this->product->project_id);
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Bookshelf:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>

                                        
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookLanguage($this->product->project_id);
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Language:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>
                                        
                                        
                                            <?php
                                            $tagsuser = $tagmodel->getTagsEbookType($this->product->project_id);
                                            if(false === empty($tagsuser))
                                            {
                                                echo '<b>Type:</b> <br/><span class="topics"><span class="topicslink"><ul style="margin-top: 5px;">';
                                                foreach ($tagsuser as $tag) {
                                            ?>
                                            <li><a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a></li>
                                            <?php
                                                }
                                                echo '</ul></span></span><!--end of topicslink-->';
                                            } ?>

                                        <?php }?>
                                        
                                    </article>
                                    
                                    <?php
                                        }
                                    ?>
                                    


                                        <?php
                                        if (count($this->updates) > 0) {
                                            $this->productUpdate = $this->updates[0];
                                            ?>
                                            <article class="lastchangelog">
                                            <b>Last changelog:</b>

                                            <?= $this->render('product/partials/productUpdatesV1.phtml'); ?>
                                            </article>
                                        <?php } ?>


                                    <!-- comments -->
                                    <div id="product-discussion">
                                        <?php
                                        $modelComments = new Default_Model_ProjectComments();
                                        $offset = $this->paramPageId;
                                        $testComments = $modelComments->getCommentTreeForProject($this->product->project_id);
                                        $testComments->setItemCountPerPage(25);
                                        $testComments->setCurrentPageNumber($offset);
                                        $this->comments = $testComments;
                                        echo $this->render('product/partials/productCommentsUX1.phtml');
                                        ?>
                                    </div>
                                    <!-- /comments -->
                                </div>

                            </div>

                            <?php if ($viewClaimBox) {
                                echo $this->partial(
                                    $viewClaimBox,
                                    array(
                                        "member"  => $this->member,
                                        "product" => $this->product
                                    )
                                );
                            }
                            ?>


                        </div>
                        <!-- /ABOUT -->                        
                        */?>

                        <!-- collectionProducts -->
                        <?php
                        if (count($this->collection_projects) > 0) { ?>
                        <div class="tab-pane active" id="products-panel">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                
                                <article>
                                    <div id="collectionProductsContainer">
                                    <?php
                                           echo $this->render('collection/partials/collectionProjects.phtml');
                                      ?>
                                      </div>
                                </article>
                                
                                <?php /*
                                    if (count($this->updates) > 0) {
                                        $this->productUpdate = $this->updates[0];
                                        ?>
                                        <article class="lastchangelog">
                                        <b>Last changelog:</b>

                                        <?= $this->render('collection/partials/productUpdatesV1.phtml'); ?>
                                        </article>
                                    <?php } */?>


                                    <!-- comments -->
                                    <div id="product-discussion">
                                        <?php
                                        $modelComments = new Default_Model_ProjectComments();
                                        $offset = $this->paramPageId;
                                        $testComments = $modelComments->getCommentTreeForProject($this->product->project_id);
                                        $testComments->setItemCountPerPage(25);
                                        $testComments->setCurrentPageNumber($offset);
                                        $this->comments = $testComments;
                                        echo $this->render('collection/partials/productCommentsUX1.phtml');
                                        ?>
                                    </div>
                                    <!-- /comments -->
                                
                            </div>
                            
                            
                                
                        </div>
                        <?php } ?>

                        <!-- MEDIA -->
                        <div class="tab-pane" id="media-panel">
                            <?php if (null != ($this->product->embed_code)): ?>
                                <?= $this->product->embed_code ?>
                            <?php endif; ?>
                        </div>
                        <!-- /MEDIA -->

                        <!-- updates panel -->
                        <?php  if (count($this->updates) > 0) { ?>
                        <div class="tab-pane" id="updates-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                            <article>
                                <?php
                                    foreach ($this->updates as $this->productUpdate) {
                                       echo $this->render('product/partials/productUpdatesV1.phtml');
                                    }
                                  ?>
                            </article>
                            </div>
                        </div>
                        <?php } ?>

                       <!-- ratings panel -->
                        <?php /* if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) { ?>
                        <div class="tab-pane" id="ratings-panel">
                            <div id="ratings-panel-wrapper" class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <article>
                                <div id="productRatingContainer">
                                <?php
                                       echo $this->render('product/partials/productRating.phtml');
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>
                       <?php } */?>


                        <!-- ratings panel2 -->
                        
                        <div class="tab-pane" id="ratings-panel2">
                            <div id="ratings-panel-wrapper2" class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <article>
                                <div id="productRatingContainer2">
                                <?php
                                       echo $this->render('product/partials/productRating2.phtml');
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>

                        <!-- likes panel -->
                        <?php  if (count($this->likes) > 0) { ?>
                        <div class="tab-pane" id="likes-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <article>
                                <div id="productLikesContainer">
                                <?php
                                       echo $this->render('product/partials/productLikes.phtml');
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>
                        <?php } ?>

                        <!-- plings panel -->
                        <?php  if (count($this->projectplings) > 0) { ?>
                        <div class="tab-pane" id="plings-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <article>
                                <div id="productPlingsContainer">
                                <?php
                                       echo $this->render('product/partials/productPlings.phtml');
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                    <!-- /PANELS -->
                </div>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 flex-right" id="product-maker">
                <div>
                    <div class="project-share-new col-lg-12 col-md-12 col-sm-12 col-xs-12">                        
                        <?php if (empty($this->product->claimable)) { ?>
                            <div class="prod-widget-box prod-user right ">
                                <div class="sidebar-content">
                                    <div class="product-maker-sidebar">
                                        <div class="product-maker-thumbnail relative">
                                            <a href="<?php echo $helpMemberUrl->buildMemberUrl($this->product->username); ?>"
                                               title="<?= $this->product->username ?>"  class="tooltipuserleft" data-tooltip-content="#tooltip_content" data-user="<?=$this->product->member_id?>">
                                               <?php
                                                    if($this->isSupporter($this->product->member_id)) {
                                                        $isSupporterActive = $this->isSupporterActive($this->product->member_id);
                                                ?>
                                                    <span class="supporter-badge <?=($isSupporterActive?'':'inactive')?>" >S</span>
                                                <?php } ?>
                                                <img src="<?= $helpImage->Image($this->product->profile_image_url,
                                                    array('width' => 80, 'height' => 80)) ?>"
                                                     alt="product-maker" width="15" height="15"
                                                     class="sidebar-profile-image">
                                            </a>
                                        </div>
                                        <div class="product-maker-summary">
                                            <h5>
                                                <a href="<?php echo $helpMemberUrl->buildMemberUrl($this->product->username); ?>" class="tooltipuserleft" data-tooltip-content="#tooltip_content" data-user="<?=$this->product->member_id?>">
                                                    <?= $this->product->username; ?>
                                                </a>
                                            </h5>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>

                        <div>
                            <?php
                            $this->moreProducts = $tableProject->fetchMoreCollections($this->product, 6);
                            $this->moreProductsTitle = 'More ' . $this->product->cat_title . ' from ' . $this->product->username;

                            if (count($this->moreProducts) > 0) {
                            echo $this->render('collection/partials/productMoreProductsWidgetV1.phtml');
                            } ?>
                        </div>
                        
                        <div>
                            <?php
                            $this->moreProducts = $tableProject->fetchMoreCollectionsOfOtherUsr($this->product, 6);
                            $this->moreProductsTitle = 'Other ' . $this->product->cat_title;

                            if (count($this->moreProducts) > 0) {
                            echo $this->render('collection/partials/productMoreProductsWidgetV1.phtml');
                            } ?>
                        </div>
                        <!-- /MORE PRODUCTS -->


                        <?php echo $this->render('partials/sidebarCcLicense.phtml'); ?>

                        <?php echo $this->render('collection/partials/details.phtml'); ?>                                                

                      <?php echo $this->render('collection/partials/tags.phtml'); ?>



                    </div>
                </div>

            </div>
        </div>
         <div class="tooltip_templates" style="display: none">
            <span id="tooltip_content">
                <i class="fa fa-spinner"></i>
            </span>
        </div>
    </main>

    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>


<script type="application/javascript">
    // tool tips
    $('body').on('mouseenter', '.product-thumbnail, .supporter-thumbnail', function () {
        $(this).popover('show');
    });

    $('body').on('mouseleave', '.product-thumbnail, .supporter-thumbnail', function () {
        $(this).popover('hide');
    });
</script>


<script type="text/javascript">
  var product = <?php echo $productJson ?>;
  var xdgTypeJson = <?php echo $xdgTypeJson ?>;
</script>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
            InitActiveHashTab.setup();
            PartialJson.setup();
            PartialJsonFraud.setup();
            ProductDetailCarousel.setup();
            PartialCommentReviewForm.setup();
            PartialCommentReviewFormNew.setup();
            PartialsButtonHeartDetail.setup();
            PartialsButtonPlingProject.setup();
            TooltipUser.setup("tooltipuserleft","left");
            AppimagequestionOnClick.setup();
            Opendownloadfile.setup();
        });
    ');
