<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

if ($this->error) {
    echo $this->error_text;
} else {
    ?>
    <div style="text-align: center;">
        <form action="<?= $this->form_url ?>" target="PPDGFrame">
            <input id="type" type="hidden" name="expType" value="light">
            <input id="paykey" type="hidden" name="paykey" value="<?= $this->paypalkey ?>">
            <input type="submit" id="submitBtn" value="Pay with PayPal">
        </form>
    </div>
    <script>
        var dgFlow = new PAYPAL.apps.DGFlow({trigger: 'submitBtn'});
        $("#submitBtn").click();
    </script>
<?php } ?>