<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<?php
$helperHumanTiming = new Default_View_Helper_HumanTiming();
$helperImage = new Default_View_Helper_Image();
?><div class="comments-list"><a name="comments_block"></a>
        <?php
        $comment = $this->comment[0];
        $age = $helperHumanTiming->humanTiming($comment['comment_created_at']);
        ?>
        <div class="media">
            <p class="pull-right history">
                <small><?= $age['age'] ?> <span class="light"><?= $age['unit'] ?> ago</span></small>
            </p>
            <a class="media-left">
                <img src="<?= $helperImage->Image($comment['profile_image_url'], array('width' => 40, 'height' => 40)) ?>" width="40" height="40">
            </a>
            <div class="media-body">
                <h4 class="media-heading user_name"><?= $comment['username'] ?></h4>
                <div class="small"><?= \Application\Model\Service\HtmlPurifyService::purify($comment['comment_text']) ?></div>
            </div>
        </div>
</div>
