<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperPrintDate = new Default_View_Helper_PrintDate();
$createTime = $helperPrintDate->printDate($this->created_at);
$updateTime = $helperPrintDate->printDate($this->changed_at);

$helperBuildProductUrl = new Default_View_Helper_BuildProductUrl();
$helperFetchSubcategoriesForProduct = new Default_View_Helper_FetchCategoriesForProductAsString();
?>
<div class="product-item grid-item">
    <a href="<?= $helperBuildProductUrl->buildProductUrl($this->project_id, ''); ?>">
        <figure>
            <img src="<?php echo $this->Image($this->image_small, array('width' => 167, 'height' => 167)); ?>" class="explore-product-image"/>
        </figure>
        <div class="details">
            <h3>
                <a href="<?= $helperBuildProductUrl->buildProductUrl($this->project_id, ''); ?>">
                    <?php echo $this->title; ?> <?php echo $this->version; ?>
                </a>
            </h3>
            <?php if (empty($this->claimable)) { ?>
                <span>By <b><?php echo $this->username; ?></b></span>
            <?php } ?>
            <span>In <b><?php echo $helperFetchSubcategoriesForProduct->fetchCategoriesForProductAsString($this->project_id) ?></b>
            </span>
            <!-- RATING -->
            <?php
            $this->widgetRating = new stdClass();
            $this->widgetRating->project_id = $this->project_id;
            $this->widgetRating->laplace_score = $this->laplace_score;
            $this->widgetRating->count_likes = $this->count_likes;
            $this->widgetRating->count_dislikes = $this->count_dislikes;
            echo $this->render('partials/widgetRating.phtml'); ?>
            <!-- /RATING -->
            <div class="progress">
                <div class="bar no-goal">
                </div>
            </div>
            <span><?= $updateTime == null ? '' : 'updated: ' . $updateTime ?> </span>
            <span><?= $createTime == null ? '' : 'added: ' . $createTime ?> </span>
        </div>
    </a>
</div