<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperPrintDate = new Default_View_Helper_PrintDate();
$updateTime = $helperPrintDate->printDate($this->product->project_changed_at);
$helperBuildProductUrl = new Default_View_Helper_BuildProductUrl();
$helperFetchSubcategoriesForProduct = new Default_View_Helper_FetchCategoriesForProductAsString();
$helperImage = new Default_View_Helper_Image();
?>
<div class="explore-product col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
        <div class="rownum">
            <?= intval($this->rownum)?>.
        </div>        
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 explore-product-imgcolumn">
        <figure>
            <a href="<?= $helperBuildProductUrl->buildProductUrl($this->product->project_id, ''); ?>">
                <div class="text-center">
                <img src="<?php echo $helperImage->Image($this->product->image_small, array('width' => 167, 'height' => 167)); ?>" class="explore-product-image"/>
                </div>
            </a>
        </figure>
    </div>
    <div class="explore-product-details col-lg-7 col-md-7 col-sm-7 col-xs-7">
        <h3>
            <a href="<?= $helperBuildProductUrl->buildProductUrl($this->product->project_id, ''); ?>"><?php echo $this->product->title; ?> <span style="font-size: smaller; padding-left: 20px"><?php echo $this->product->version ?> </span></a>
        </h3>
       
        <b style="display: block; margin-bottom: 5px"><?php echo $helperFetchSubcategoriesForProduct->fetchCategoriesForProductAsString($this->product->project_id) ?></b>
         <?php 
          $helperPackageTypes = new Default_View_Helper_FetchProjectPackageTypes();
          $type = $helperPackageTypes->FetchProjectPackageTypes($this->product->project_id);
          if(!empty($type)){
            ?>
                <?=$type ?>
            <?php } ?>
        <br/><br/>
        <div class="productInfo">
       <?php
                $count_plingers = $this->product->count_plingers;
                $count_comments = $this->product->count_comments;
                echo ($count_plingers>0 ? '<span class="cntSupporters">'.$count_plingers.' supporter':'').($count_plingers>1?'s':'').($count_plingers>0?'</span>':'') ;
                echo ($count_comments>0 ? '<span class="cntComments">'.$count_comments.' comment':'').($count_comments>1?'s':'').($count_comments>0?'</span>':'') ;
                ?>
        </div>            
    </div>
    <div class="explore-product-plings col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <!-- RATING -->
        <?php
        $this->widgetRating = new stdClass();
        $this->widgetRating->project_id = $this->product->project_id;
        $this->widgetRating->laplace_score = $this->product->laplace_score;
        $this->widgetRating->count_likes = $this->product->count_likes;
        $this->widgetRating->count_dislikes = $this->product->count_dislikes;
        echo $this->render('partials/widgetRating.phtml'); ?>
        <!-- /RATING -->
        <div class="progress">
            <div class="bar no-goal">
            </div>
        </div>
         
        <div class="collected">
          
             <span><?php echo $updateTime ?></span>
        </div>
        
    </div>
</div><!-- END .explore-product -->