<ul class="x-suggested-amounts">
	<li class="amount-item">                                     
  <div class="item-text">
  	<div style="width: 100%;text-align: right; padding-right: 40px">
	    <span class="unit-wrapper">
	      <span class="unit">$</span>
	    </span>
	    <span class="amount"><?=$this->tier?> </span>                                        
	</div>
  </div>                                    
 </li>
</ul>