<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<style>
    .jtable-toolbar-item-add-record {
        display: none !important;
    }
</style>
<div class="messages">
    <?php foreach (Zend_Controller_Action_HelperBroker::getStaticHelper('flashMessenger')
                       ->getCurrentMessages() as $message) : ?>
        <p><?php echo $this->escape($message); ?></p>
    <?php endforeach; ?>
</div>
<div id="TableContainer"></div>
<div id="dialog-form" title="Object Details"></div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#TableContainer').jtable({
            jqueryuiTheme: true,
            paging: true,
            title: 'Table of reports',
            sorting: true, //Enable sorting
            defaultSorting: 'created_at DESC', //Set default sorting
            actions: {
                listAction: '/backend/reportproducts/list',
                createAction: '/backend/reportproducts/create',
                updateAction: '/backend/reportproducts/update',
                deleteAction: '/backend/reportproducts/delete'
            },
            fields: {
                report_id: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                project_id: {
                    title: 'Project ID',
                    width: '10%',
                    display: function (data) {
                        if (data.record.project_id) {
                            return data.record.project_id + ' <a href="/p/' + data.record.project_id + '/" class="btn btn-info btn-xs pull-right" role="button" style="color: white" target="_blank">show</a>';
                        }
                    }
                },
                reported_by: {
                    title: 'Reported by',
                    width: '10%',
                    display: function (data) {
                        if (data.record.reported_by) {
                            return data.record.reported_by
                                + ' <a role="button" title="show member info" class="btn btn-info btn-xs member-info pull-right" style="color:white;"  data-record="' + data.record.reported_by + '"><span>info</span></a>'
                                ;
                        }
                    }
                },
                is_deleted: {
                    title: 'Deleted',
                    width: '5%'
                },
                created_at: {
                    title: 'Created',
                    width: '10%',
                    type: 'date',
                    create: false,
                    edit: false
                },
                counter: {
                    title: 'total count reported',
                    width: '10%',
                    create: false,
                    edit: false
                },
                hide: {
                    title: '',
                    width: '1%',
                    sorting: false,
                    create: false,
                    edit: false,
                    list: true,
                    display: function (data) {
                        if (data.record.status) {
                            if (data.record.status > 40) {
                                btn_title = 'deactivate';
                            } else {
                                btn_title = 'activate';
                            }
                            return '<a role="button" title="' + btn_title + ' this product" class="btn btn-warning btn-xs toggle-status pull-right" style="color:white;"  data-record="' + data.record.project_id + '"><span>' + btn_title + '</span></a>'
                                ;
                        }
                    }
                }

            }
        });

        $('#TableContainer').jtable('load');

        $("#dialog-form").dialog({
            autoOpen: false,
            //height: 350,
            width: 600,
            modal: true,
            buttons: {
                Close: function () {
                    $(this).dialog("close");
                }
            }
        });

        $('body').on("click", 'a.member-info', function (event) {
            event.preventDefault();
            event.stopImmediatePropagation();

            var elementRecord = $(this).data("record");

            jQuery.ajax({
                data: {'member_id': elementRecord},
                url: '/backend/user/memberinfo/',
                type: 'post',
                error: function () {
                    alert("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
                    return false;
                },
                success: function (results) {
                    $('#dialog-form').html(results.ViewRecord).dialog('open');
                    return false;
                }
            });

            return false;
        });

       $('body').on("click", 'a.toggle-status', function (event) {
            event.preventDefault();
            event.stopImmediatePropagation();

            var elementRecord = $(this).data("record");

            jQuery.ajax({
                data: {'c': elementRecord},
                url: '/backend/reportproducts/status/',
                type: 'post',
                error: function () {
                    alert("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
                    return false;
                },
                success: function (results) {
                    $('#TableContainer').jtable('reload');
                    return false;
                }
            });

            return false;
        });

    });
</script>