<?php
        if ($this->storeabout) {
            ?>
            <div class="prod-widget-box right catabout" id="storecontent">
                <?php include $this->storeabout; ?>
            </div>
            <?php
        }
        ?>

        <?php
        if ($this->catabout) {
            ?>
            <div class="prod-widget-box right catabout" id="catcontent">
                <?php include $this->catabout; ?>
            </div>
            <?php
        }
        ?>