<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$isAdmin = $this->isAdmin;
$catId = $this->project_category_id;
$section = $this->section;
$isSupporter = $this->isSupporter;
$support = $this->supportData;
$supporters = $this->supporters;

$filter = new Application\Model\Service\UrlEncrypt();
$thisurl = "/";
if (isset($_GET['url'])) {
    $thisurl = $_GET['url'];
} else {
    $http_scheme = $this->plugin('serverUrl')->getScheme();
    $host = $this->plugin('serverUrl')->setUseProxy(true)->getHost();
    $thisurl = $http_scheme . '://' . $host . $_SERVER["REQUEST_URI"];
}


$url_login = SERVER_BASE_PATH . "/login/redirect/" . $filter->encryptForUrl($thisurl);

?>

    <style>
        .amount_predefined input {
            opacity: .95;
            margin-top: -8px;
            color: #000;
            font-size: 18px;
            width: 50%;
            margin: 0;
            margin-top: 0px;
            margin-top: 0;
            border: 0;
            border-bottom-color: currentcolor;
            border-bottom-style: none;
            border-bottom-width: 0px;
            border-bottom: 1px solid #d0d0d0;
            padding: 0;
            box-shadow: none;
            background: none;
        }

        .amount_predefined {
            padding-left: 4px;
        }

    </style>

<?php
$baseurlStore = $this->baseurl_store;
?>
    <div class="prod-widget-box prod-user right ">
        <div class="sidebar-content" style="text-align: center;">
            <div class="product-maker-sidebar">
                <h4>Become a Supporter</h4>

                <?php
                if ($isSupporter) {
                    ?>
                    <span
                        style="padding-bottom: 10px;font-size: small;">Thank you very much for supporting <?= $section['name'] ?>
                        <?php
                        if ($isAdmin) {
                            ?>
                            <a style="font-style: italic;"
                               href="<?= $baseurlStore . '/section?id=' . $section['section_id'] ?>"> * </a>
                            <?php
                        }
                        ?>
            with $<?= $support['tier'] ?> per month.</span><br><br>
                    <?php
                }
                ?>

                <div>
                    <form action="<?= $baseurlStore ?>/support-predefined" method="POST" id="support_form_predefined">
                        <input type="hidden" name="section_id" value="<?= $section['section_id'] ?>"/>
                        <input type="hidden" name="project_id" value="<?= $this->project_id ?>"/>
                        <input type="hidden" name="amount_predefined" id="amount-1" value="1"/>
                        <div>
                        <span style="display:inline-block; padding-bottom:10px;">
                            Become a 1 year supporter for $1/month
                        </span>
                        </div>

                        <div class="supportDiv">
                            <button id="add_support" type="submit" class="btn btn-primary btn-lg active btn-block"
                                    role="button" aria-pressed="true">Support
                            </button>
                        </div>
                    </form>
                </div>
                <div style="margin-top: 20px;">
            
                <span style="padding-bottom: 10px;font-size: small;">
                    <?= $this->project_title ?> is part of <?= $section['name'] ?>, which is supported by the following people:
                </span>
                    <div class="row" style="margin-top: 10px;margin-bottom: 10px;">
                        <?php
                        $i = 0;
                        if (count($supporters) >= 1) {
                            foreach ($supporters as $user) {
                                if ($i++ > 6) {
                                    break;
                                }
                                ?>
                                <a href="<?php echo $this->buildMemberUrl($user['username']); ?>"
                                   class="tooltipuserleft" data-tooltip-content="#tooltip_content"
                                   data-user="<?= $user['member_id'] ?>">
                                    <img height="25" width="25" src="<?php echo $this->Image(
                                        $user['profile_image_url'], array(
                                        'width' => '25',
                                        'height' => '25',
                                        'crop' => 2,
                                    )
                                    ); ?>" class="supporterx"/>
                                </a>
                                <?php
                            }
                        } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {

            $(".custom_amount").click(function () {
                $('#amount-5').prop("checked", true);
            });

            $("#add_support").click(function (e) {
                e.preventDefault();

                $radioVal = $('input[name=amount_predefined]:checked', '#support_form_predefined').val()
                if ($radioVal == 'free') {
                    $amount = $(".custom_amount").val();

                    if ($amount && $amount.length > 0 && $amount > 10.01) {
                        $("#support_form_predefined").submit();
                        return true;
                    } else {
                        alert('Please enter a free amount > 10.01');
                        return false;
                    }
                } else {
                    $("#support_form_predefined").submit();
                    return true;
                }
            });

        });
    </script>

<?php

//}