version: '3'
services:
  web:
    build:
      context: .
      args:
        BUILD_ENV: development
    ports:
      - '80:80'
    volumes:
      - .:/usr/src/ocs-webserver
      - ./.docker_init/configs/application.dev.ini:/usr/src/ocs-webserver/application/configs/application.local.ini
      - ./.docker_init/httpdocs/.htaccess:/usr/src/ocs-webserver/httpdocs/.htaccess
      - ./.docker_init/httpdocs/images_sys/store_kde:/usr/src/ocs-webserver/httpdocs/images_sys/store_kde
      - ./.docker_init/httpdocs/images_sys/store_opendesktop:/usr/src/ocs-webserver/httpdocs/images_sys/store_opendesktop
      - ./.docker_init/httpdocs/images_sys/superstore:/usr/src/ocs-webserver/httpdocs/images_sys/superstore
#      - ./.docker_init/templates:/usr/src/ocs-webserver/data/stores/templates
    expose:
      - '80'
    depends_on:
      - sessions
      - cache
      - sqldb
  sessions:
    image: 'memcached:1.5'
    expose:
      - '11211'
  cache:
    image: 'memcached:1.5'
    expose:
      - '11211'
  sqldb:
    image: mariadb
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${OCS_WS_MYSQL_ROOT_PWD:-root}
    volumes:
      - ./.docker_init/seed/:/docker-entrypoint-initdb.d
