<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->tab = 'downloadhistory';
$helpProductUrl = new Default_View_Helper_BuildProductUrl();
$helpDate = new Default_View_Helper_PrintDate();
?>
<main class="user-admin-page">
    <?php echo $this->render('user/partials/userHeader_top.phtml'); ?>  
    <section class="body-wrap">
        <section class="wrapper product-page">
            <!-- PAGE BODY -->
            <section class="my-products-page">
                <!-- NAVIGATION -->
                <?php echo $this->render('user/partials/userHeader.phtml'); ?>
                <!-- /NAVIGATION -->
             
              <div class="my-products-heading">
                   <h1 class="page-title left"><?= $this->translate('Download History') ?></h1>                   
               </div>


                <div class="my-downloadshistory-list">
                    <div class="row header">
                        <div class="col-lg-3">                        
                        </div>
                        
                       <div class="col-lg-1">                        
                           Category
                       </div>
                         <div class="col-lg-2">                        
                           Filename
                       </div>
                       <div class="col-lg-2">                        
                           Download timestamp
                       </div>
                       <div class="col-lg-2">                        
                           Last download
                       </div>
                       <div class="col-lg-1">                        
                           
                       </div>
                        <div class="col-lg-1">
                            <span class="glyphicon glyphicon-heart" style="color:red"></span>
                        </div>
                    </div>
                    
                        <?php echo $this->partialLoop('user/partials/loopDownloadHistory.phtml', $this->downloadhistory); ?>
                   
                </div>
            </section>

            <!-- /PAGE BODY -->

        </section>

    </section>

</main>
