<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->tab = 'downloadhistory';
$identity = Zend_Auth::getInstance()->getStorage()->read();
$this->issupport = $this->isSupporter($this->member->member_id);
//Rating for ACTIVE SUPPORTERS only

$pageCount = $this->downloadhistory->getTotalItemCount()/$this->downloadhistory->getItemCountPerPage();
?>
<main class="user-admin-page">
    <?php echo $this->render('user/partials/userHeader_top.phtml'); ?>  
    <section class="body-wrap">
        <section class="wrapper product-page">
            <!-- PAGE BODY -->
            <section class="my-products-page">
                <!-- NAVIGATION -->
                <?php echo $this->render('user/partials/userHeader.phtml'); ?>
                <!-- /NAVIGATION -->
             
              <div class="my-products-heading">
                   <h1 class="page-title left"><?= $this->translate('Download History') ?></h1>                   
               </div>


                <div class="my-downloadshistory-list" id="my-downloadshistory-list">

                <div class="row">
                    <div class="col-lg-7">
                    <small class="pull-right">
                        <div class="row" style="margin:0;padding: 0;text-align: right;"><?=$this->downloadhistory->getTotalItemCount()?> Downloads</div>
                        <?php if ($pageCount > 1) echo $this->paginationControl($this->downloadhistory, 'Sliding', '/partials/paginationControlBootstrap.phtml',
                            array('params' => array(), 'dom_target' => 'div#my-downloadshistory-list')); ?></small>                    
                    </div>
                </div>

                   <div class="row">
                       <div class="col-lg-4">
                       </div>
                       <div class="col-lg-1">
                        Downloaded at
                       </div>
                       <div class="col-lg-2">
                           Action
                       </div>
                   </div>
                    <?php  
                        $this->result = array();                                                
                        foreach ($this->downloadhistory as $element) {
                            $this->result[$element['project_id']][] = $element;
                        }                       
                        foreach($this->result as $this->projectfiles){                                                            
                            $i = 0;
                            foreach($this->projectfiles as $file){                                                                                            
                                echo $this->partial('user/partials/loopDownloadHistory.phtml',  array(
                                        "file"  => (object)$file,
                                        "isSupporter" =>$this->isSupporter,
                                        "member_id" =>$this->member->member_id,
                                        "counter" => $i++
                                    ));                                                                                                  
                            }
                        }
                    ?>                                                               
                </div>
            </section>

            <!-- /PAGE BODY -->

        </section>

    </section>

</main>


  <?php if (Zend_Auth::getInstance()->hasIdentity() /*&& $this->issupport */ ) { ?>
    <div id="review-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <div class="modal-body">
                 <form class="full-width product-add-comment-review" action="/productcomment/addreplyreview/" method="post">
                            <input type="hidden" name="p" id="form_p"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>
                            <input type="hidden" name="v" value="1" id="voteup"/>                                                        
                            <textarea name="msg" class="full-width" id="commenttext"></textarea>
                            <button type="submit" class="small pull-right">Rate Now</button>
                </form>
                </div>
            </div>
        </div>
    </div>    
<?php }?>

<?php
$this->inlineScript()->appendScript(
    '    $(document).ready(function(){            
            PartialsReviewDownloadHistory.setup();
             PartialCommentReviewForm.setup();
             PartialsButton.setup();
        });
    ');
