<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->tab = 'payout';
$this->countDownloadsOverall = 0;

$modelDownload = new Default_Model_StatDownload();
$this->downloads = $modelDownload->getUserDownloads($this->member->member_id);

$this->countDownloadsOverall = count($this->downloads);
?>
<main class="user-admin-page">
    <?php echo $this->render('user/partials/userHeader_top.phtml'); ?>
    <section class="body-wrap">
        <section class="wrapper product-page">
            <!-- PAGE BODY -->
            <section class="my-products-page">
                <!-- NAVIGATION -->
                <?php echo $this->render('user/partials/userHeader.phtml'); ?>
                <!-- /NAVIGATION -->
                <div class="my-products-heading">
                    <h1 class="page-title left"><?= $this->translate('My plings') ?></h1>
                </div>
                <div class="my-products-list" id="my-payout-list">
                    <?php
                    if ($this->countDownloadsOverall > 0) {
                        echo $this->render('user/partials/loopPayout.phtml');
                    } else {
                        echo '<div class="well well-sm" role="alert">You have no downloads.</div>';
                    }
                     ?>
                </div>
            </section>
            <!-- /PAGE BODY -->
        </section>
    </section>
</main>
