<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->tab = 'plings';
$this->countDownloadsOverall = 0;

#$modelDownload = new Default_Model_StatDownload();
#$this->downloads = $modelDownload->getUserDownloads($this->member->member_id);
#$this->countDownloadsOverall = count($this->downloads);
?>
<main class="user-admin-page">
    <?php echo $this->render('user/partials/userHeader_top.phtml'); ?>
    <section class="body-wrap">
        <section class="wrapper product-page">
            <!-- PAGE BODY -->
            <section class="my-products-page">
                <!-- NAVIGATION -->
                <?php echo $this->render('user/partials/userHeader.phtml'); ?>
                <!-- /NAVIGATION -->
                <div class="my-products-heading">
                    <h1 class="page-title left"><?= $this->translate('Payout') ?></h1>
                <?php
                    $member = $this->view_member;
                    if($member->pling_excluded == 1) {
                        echo "<br><br><br><h1 style='color: red; '>This account has been excluded from receiving plings, due to various misuses.</h1>";
                    }
                ?>
                </div>
                <section>
                <?php
                    $member = $this->view_member;
                    if($member->paypal_valid_status > 100) {
                        $status = $this->paypal_valid_status;
                        if($status->color == 'red') {
                            echo '<div class="alert alert-danger" role="alert">'.$status->description.'</div>';
                        }
                        if($status->color == 'yellow') {
                            echo '<div class="alert alert-warning" role="alert">'.$status->description.'</div>';
                        }
                        if($status->color == 'blue') {
                            echo '<div class="alert alert-info" role="alert">'.$status->description.'</div>';
                        }
                        if($status->color == 'green') {
                            echo '<div class="alert alert-success" role="alert">'.$status->description.'</div>';
                        }
                    }
                ?>
                </section>
                
                <?php
                    if($member->pling_excluded == 0 || (Zend_Auth::getInstance()->hasIdentity() AND Zend_Auth::getInstance()->getIdentity()->roleName == 'admin')) {        
                ?>  
                <div class="my-products-list" id="my-payout-list">
                    <div id="tabs">
                        <ul>
                          <li><a href="/member/<?= $this->member->member_id ?>/plinglistajax/2019">2019</a></li>
                          <li><a href="/member/<?= $this->member->member_id ?>/plinglistajax/2018">2018</a></li>
                        </ul>
                        <div id="tabs-1">
                          <h2>Content heading 1</h2>
                          <p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>
                        </div>
                        <div id="tabs-2">
                          <h2>Content heading 2</h2>
                          <p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
                        </div>
                    </div>
                    
                    
                    <?php
                    //if ($this->countDownloadsOverall > 0) {
                    echo $this->render('user/partials/loopPlings.phtml');
                    //} else {
                    //    echo '<div class="well well-sm" role="alert">You have no downloads and no plings.</div>';
                    //}
                    ?>
                </div>
                <?php
                    }
                ?>
            </section>
            <!-- /PAGE BODY -->
        </section>
    </section>
</main>
