<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->tab = 'plings';
$this->countDownloadsOverall = 0;

#$modelDownload = new Default_Model_StatDownload();
#$this->downloads = $modelDownload->getUserDownloads($this->member->member_id);
#$this->countDownloadsOverall = count($this->downloads);

$member = $this->view_member;
?>
<?php
    if($member->pling_excluded == 0 || (Zend_Auth::getInstance()->hasIdentity() AND Zend_Auth::getInstance()->getIdentity()->roleName == 'admin')) {        
?>  
<div class="my-products-list" id="my-payout-list">

    <?php
    //if ($this->countDownloadsOverall > 0) {
    echo $this->render('user/partials/loopAffiliatesForMonth.phtml');
    //} else {
    //    echo '<div class="well well-sm" role="alert">You have no downloads and no plings.</div>';
    //}
    ?>
</div>
<?php
    }
?>
<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>    