<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->headLink()->appendStylesheet('/theme/flatui/css/chosen.css');
$this->inlineScript()->appendFile('/theme/flatui/js/lib/chosen.jquery.min.js');
$this->inlineScript()->appendScript('
                                    $(document).ready(function(){
                                        $("select.chosen").chosen({
                                        width: "100%", 
                                        max_selected_options: "5",
                                        disable_search: "false",
                                        disable_search_threshold: "5"
                                        });
                                    });
                                '); ?>
<div class="form-group">
    <div class="col-sm-12 margin-top-15">
        <?php if ($this->element->getOption('required')) { ?>
            <div class="small grey bold-font pull-left margin-right-5">*</div>
        <?php } ?>
        <label class="form-label" for="<?= $this->element->getName() ?>">Tags</label>
    </div>
    <div class="col-sm-12">
        <select
                id="<?= $this->element->getName() ?>"
                name="<?= $this->element->getName() ?>[]"
                data-placeholder="Choose max 5 Tags..."
                multiple="multiple"
                class="chosen">
            <option value=""></option>
            <?php
            $modelTagGroup = new Default_Model_TagGroup();
            $groups = $modelTagGroup->fetchGroupHierarchy();
            //$value = array_map('strval', explode(',',$this->element->getValue()));
            $element_value = $this->element->getValue();
            $value = empty($element_value) ? array() : explode(',', $element_value);
            foreach ($groups as $label => $opt): ?>
                <optgroup label="<?php echo $label; ?>">
                    <?php foreach ($opt as $id => $name):
                        $opt = '';
                        if (in_array($name, $value)) {
                            $opt .= ' selected="selected"';
                        } ?>
                        <option <?= $opt ?> value="<?php echo $name; ?>"><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </optgroup>
            <?php endforeach; ?>
        </select>
        <?php if ($this->element->getMessages()) {
            $errorHtml = '';
            foreach ($this->element->getMessages() as $currentError) {
                $errorHtml .= '<label id="' . $this->escape($this->element->getName()) . '-error" class="error" for="' . $this->escape($this->element->getName()) . '"><small>' . $currentError . '</small></label>';
            }
            ?>
            <?php echo $errorHtml ?>
        <?php } ?>
    </div>
</div>