<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="form-group">
    <div class="col-sm-12 margin-top-15">
        <?php if ($this->element->getOption('required')) { ?>
            <div class="small grey bold-font pull-left margin-right-5">*</div>
        <?php } ?>
        <label class="form-label" for="<?= $this->escape($this->element->getName()) ?>">
            Link to Source/Code *(needed for plings depending on product category). Link to original if your product is unmodified
            and based on someone elses work. If it is modified, you need to link to a repository with FULLY EXTRACTED source code,
            NOT an archive. If Link is not valid, product can be excluded or removed.
        </label>
    </div>
    <div class="col-sm-12">
        <input placeholder="https://github.com/github-tools/github"
               id="<?= $this->element->getName() ?>"
               class="form-control"
               type="text"
               pattern="https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)"
               maxlength="200"
               aria-required="false"
               aria-invalid="false"
               data-rule-minlength="10"
               data-rule-maxlength="200"
               data-msg-minlength="At least 10 chars"
               data-msg-maxlength="At most 200 chars"
               value="<?= $this->element->getValue() ?>"
               name="<?= $this->element->getName() ?>"/>
        <?php if ($this->element->getMessages()) {
            $errorHtml = '';
            foreach ($this->element->getMessages() as $currentError) {
                $errorHtml .= '<label id="' . $this->escape($this->element->getName()) . '-error" class="error" for="' . $this->escape($this->element->getName()) . '"><small>' . $currentError . '</small></label>';
            }
            ?>
            <?php echo $errorHtml ?>
        <?php } ?>
    </div>
</div>