<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="form-group">
    <div class="col-sm-12 margin-top-15">
        <?php if ($this->element->getOption('required')) { ?>
            <div class="small grey bold-font pull-left margin-right-5">*</div>
        <?php } ?>
        <label class="form-label" for="<?= $this->escape($this->element->getName()) ?>">Product Name (4 letters min.)</label>
    </div>
    <div class="col-sm-12">
        <input id="<?= $this->escape($this->element->getName()) ?>"
               class="required form-control"
               type="text"
               maxlength="60"
               value="<?= $this->escape($this->element->getValue()) ?>"
               name="<?= $this->escape($this->element->getName()) ?>"/>
        <?php if ($this->element->getMessages()) {
            $errorHtml = '';
            foreach ($this->element->getMessages() as $currentError) {
                $errorHtml .= '<label id="' . $this->escape($this->element->getName()) . '-error" class="error" for="' . $this->escape($this->element->getName()) . '"><small>' . $currentError . '</small></label>';
            }
            ?>
            <?php echo $errorHtml ?>
        <?php } ?>
    </div>
</div>