<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="form-group">
    <div class="col-sm-12 margin-top-15">
        <?php if ($this->element->isRequired()) { ?>
            <div class="small grey bold-font pull-left margin-right-5">*</div>
        <?php } ?>
        <?php echo $this->formLabel($this->element->getName(), $this->element->getLabel(), array('class' => 'form-label')) ?>
    </div>
    <div class="col-sm-12">
        <?php echo $this->{$this->element->helper}(
            $this->element->getName(),
            $this->element->getValue(),
            $this->element->getAttribs()
        ) ?>
        <?php if ($this->element->getMessages()) {
            $errorHtml = '';
            foreach ($this->element->getMessages() as $currentError) {
                $errorHtml .= '<span class="help-block text-danger"><small>' . $currentError . '</small></span>';
            }
            ?>
            <?php echo $errorHtml ?>
        <?php } ?>
    </div>
</div>