<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperSearchCategories = new Default_View_Helper_ListCategories();
$categories = $helperSearchCategories->listCategories();
$helperTagProductCounter = new Default_View_Helper_CategoryProductCount();
$helperFetchTotalProductsCount = new Default_View_Helper_FetchTotalProductsCount();
$helperBuildExploreUrl = new Default_View_Helper_BuildExploreUrl();
?>
<main id="browse-page">

    <section class="head-wrap">

        <section class="wrapper">

            <div class="page-title">
                <div class="center">
                    <div><h1>Browse</h1></div>
                </div>
                <hr/>
            </div>

            <div class="row">

                <div class="banner col-lg-5 col-md-5 col-sm-6 col-xs-8">

                    <div class="top">

                        <div class="large"><?= $helperFetchTotalProductsCount->fetchTotalProductsCount() ?></div>
                        <div clas="small">Products</div>

                    </div>

                    <div class="bottom">

                        <a class="btn btn-native" href="/register">Register</a> to add your product

                    </div>

                </div>

            </div>

        </section>

    </section>

    <section class="body-wrap" id="cat-list">

        <section class="wrapper">

            <div class="row">
                <!-- Main Cat -->
                <div>
                    <div>
                        <!-- SubCat -->
                        <div class="scroll-pane">
                            <div class="sub-categories">

                                <?php
                                $lastSubMenueElement = 0;
                                $startSubmenue = 0;
                                $parentCategory = 0;
                                $lastMainCat = 0;
                                foreach ($categories as $key => $element) {

                                    $element['product_counter'] = (int)$element['product_counter'];

                                    $element['product_counter'] = $helperTagProductCounter->categoryProductCount($element['project_category_id']);

                                    $depth = (int)$element['depth'];

                                    if ($depth == 2) {
                                        echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 cat-cont">
                                <div class="category ' . $this->translate($element['title']) . '" >
                                    <a class="title" href="' . $helperBuildExploreUrl->buildExploreUrl($parentCategory, $element['project_category_id']) . '/">'
                                            . $this->translate($element['title']) . '<span class="label label-default">' . $element['product_counter'] . '</span>
                                    </a></div></div>';
                                    } else if ($depth == 1) {
                                        echo '</div></div><!-- /SubCat -->';
                                        echo '</div></div><!-- /MainCat -->';

                                        echo '<!-- MainCat --><div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 cat-cont">
                                <div class="category ' . $this->translate($element['title']) . '" >
                                    <a class="title" href="' . $helperBuildExploreUrl->buildExploreUrl($element['project_category_id']) . '">'
                                            . $this->translate($element['title']) . '<span class="label label-default">' . $element['product_counter'] . '</span>
                                    </a>';

                                        echo '<!-- SubCat --><div class="scroll-pane"><div class="sub-categories">';
                                    }

                                }
                                ?>
                            </div>

        </section>

    </section>

</main>

<script>
    $(document).ready(function () {
        var BrowseCategoriesPage = (function () {

            return {

                setup: function () {

                    $(window).load(function () {

                        $('#cat-list').find('.container').each(function () {

                            var $container = $(this).find('.row');

                            $container.masonry({
                                itemSelector: '.item'
                            });

                        });

                    });

                }
            }

        })();


        BrowseCategoriesPage.setup();
    });
</script>