<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$isProdncoll = false;
if ($this->tab == 'add' || $this->tab == 'products' || $this->tab == 'addcollection' || $this->tab == 'collections') {
    $isProdncoll = true;
}
?>
<div class="pling-nav-tabs">
    <ul class="nav nav-tabs">

        <li class="header-menu-left-item <?php echo $isProdncoll ? 'active' : ''; ?>">
            <a href="<?php echo $this->buildMemberUrl($this->member->username, 'products'); ?>"> <span
                    class="glyphicon glyphicon-th-list"></span>
                <?= $this->translate('Products/Listing') ?>
            </a>
        </li>


        <?php /*if ($this->isAdmin) { ?>
    <li class="header-menu-left-item <?php echo $this->tab == 'payout' ? 'active' : ''; ?>">
        <a href="<?php echo $this->buildMemberUrl($this->member->username, 'payoutold'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('Payout-Old') ?>
        </a>
    </li>
    <?php } */ ?>

        <li class="header-menu-left-item <?php echo $this->tab == 'payoutsection' ? 'active' : ''; ?>">
            <a href="<?php echo $this->buildMemberUrl($this->member->username, 'payout'); ?>">
                <span class="glyphicon glyphicon-usd"></span>
                <?= $this->translate('Payout') ?>
            </a>
        </li>

        <?php /*
    <?php if ($this->isAdmin) { ?>
    <li class="header-menu-left-item <?php echo $this->tab == 'payouthistory' ? 'active' : ''; ?>">
        <a href="<?php echo $this->buildMemberUrl($this->member->username, 'payouthistoryold'); ?>">                                   
            <span class="payouthistory-icon" aria-hidden="true"></span>
            <?= $this->translate('Payout-History-Old') ?>
        </a>
    </li>
    <?php } ?>
     * 
     */ ?>
        <li class="header-menu-left-item <?php echo $this->tab == 'payouthistory2' ? 'active' : ''; ?>">
            <a href="<?php echo $this->buildMemberUrl($this->member->username, 'payouthistory'); ?>">
                <span class="payouthistory-icon" aria-hidden="true"></span>
                <?= $this->translate('Payout-History') ?>
            </a>
        </li>

        <?php if ($this->currentUser()->isAdmin()) {
            echo '<span style="font-style: italic;">';
            ?>

            <?php if ($this->isSupporter($this->member->member_id)) { ?>
                <!--
        <li class="header-menu-left-item <?php echo $this->tab == 'support' ? 'active' : ''; ?>">           
             <a href="<?php echo $this->buildMemberUrl($this->member->username, 'support'); ?>">        
                <span class="glyphicon glyphicon-usd"></span>
                <?= $this->translate('Support') ?>
            </a>
        </li>
        -->
            <?php } ?>
         
        <?php echo '</span>'; } ?>

        <li class="header-menu-left-item <?php echo $this->tab == 'funding' ? 'active' : ''; ?>">
            <a href="<?php echo $this->buildMemberUrl($this->member->username, 'funding'); ?>">
                <span class="glyphicon glyphicon-usd"></span>
                <?= $this->translate('Funding') ?>
            </a>
        </li>


        <li class="<?php echo $this->tab == 'downloadhistory' ? 'active' : ''; ?>">
            <a href="<?php echo $this->buildMemberUrl($this->member->username, 'downloadhistory'); ?>">
                <span class="glyphicon glyphicon-star"></span>
                <?= $this->translate('Downloads') ?>
            </a>
        </li>

        <li class="<?php echo $this->tab == 'likes' ? 'active' : ''; ?>">
            <a href="<?php echo $this->buildMemberUrl($this->member->username, 'likes'); ?>">
                <i class="fa fa-heart" aria-hidden="true"></i>
                <?= $this->translate('Fan of') ?>
            </a>
        </li>

        <li class="<?php echo $this->tab == 'activities' ? 'active' : ''; ?>">
            <a href="<?php echo $this->buildMemberUrl($this->member->username, 'activities'); ?>">
                <span class="glyphicon glyphicon-align-justify"></span>
                <?= $this->translate('Activities') ?>
            </a>
        </li>

        <?php /*
    <li class="header-menu-left-item <?php echo $this->tab == 'profiles' ? 'active' : ''; ?>">
        <a href="<?php echo $this->buildBaseUrl('settings/profile'); ?>">
            <span class="glyphicon glyphicon-user"></span>
            <?= $this->translate('Profile') ?>
        </a>
    </li>
    
    
    <li class="header-menu-left-item <?php echo $this->tab == 'settings' ? 'active' : ''; ?>">
        <a href="<?php echo $this->buildBaseUrl('settings'); ?>">
            <span class="glyphicon glyphicon-cog"></span>
            <?= $this->translate('Settings') ?>
        </a>
    </li>
    

  

   <li class="header-menu-left-item <?php echo $this->tab == 'supporterbox' ? 'active' : ''; ?>">
        <a href="<?php echo $this->buildBaserUrl('supporterbox'); ?>/<?=$identity->member_id?>">            
            <i class="fa fa-user"></i>
            <?= $this->translate('Supporter box') ?>
        </a>
    </li>
    <li class="header-menu-left-item <?php echo $this->tab == 'earnings' ? 'active' : ''; ?>">
        <a href="<?php echo $this->buildMemberUrl($this->member->member_id, 'income'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('My Income') ?>
        </a>
    </li>
 
    <li class="header-menu-left-item <?php echo $this->tab == 'payment' ? 'active' : ''; ?>">
        <a href="<?php echo $this->buildMemberUrl($this->member->member_id, 'payments'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('My Payments') ?>
        </a>
    </li>
    */ ?>

    </ul>
</div>