<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

?>
<link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/css/template.css">
<link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/css/validationEngine.jquery.css">
<script src="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/js/jquery.validationEngine.min.js"></script>
<script src="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/languages/jquery.validationEngine-en.js"></script>
<style>
    .highlight {
        background-color: #fefff3;
    }
</style>


<div id="TableContainer"></div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#TableContainer').jtable({
            jqueryuiTheme: true,
            paging: true,
            title: 'Table of GHNS-Excluded Projects',
            actions: {
                listAction: '/backend/ghnsexcluded/list'
            },
            fields: {
                project_id: {
                    title: 'Project Id',
                    key: true,
                    create: false,
                    edit: false,
                    list: true,
                    width: '2%'
                },
                title: {
                    title: 'Proj. Title',
                    key: false,
                    create: false,
                    edit: false,
                    list: true,
                    width: '25%'
                },
                exclude_member_id: {
                    title: 'Excluded from',
                    key: false,
                    create: false,
                    edit: false,
                    list: false,
                    width: '2%'
                },
                 exclude_member_name: {
                    title: 'Excluded from',
                    key: false,
                    create: false,
                    edit: false,
                    list: true,
                    width: '5%'
                },
                exclude_time: {
                    title: 'Excluded at',
                    width: '5%',
                    type: 'datetime',
                    create: false,
                    edit: false,
                    list: true
                }
            }
        });
        
        $('#TableContainer').jtable('load');

    });
</script>