<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$collection_cat_id = Zend_Registry::get('config')->settings->client->default->collection_cat_id;
$ranking_cat_id = Zend_Registry::get('config')->settings->client->default->ranking_cat_id;
?>
<div class="form-group">
  <div class="col-sm-12 margin-top-15">
      <?php if ($this->element->isRequired()) { ?>
        <div class="small grey bold-font pull-left margin-right-5">*</div>
      <?php } ?>
    <label class="form-label" for="<?= $this->escape($this->element->getName()) ?>">What type is your product?</label>
  </div>
  <div id="wrapper_form_cat" class="col-sm-5">
    <select class="required form-control product_select_cat"
           id="<?= $this->escape($this->element->getName()) ?>"
           name="<?= $this->escape($this->element->getName()) ?>"
           value="<?= $this->escape($this->element->getValue()) ?>"
           >>
        <option value="<?= $collection_cat_id ?>">Collection</option>
        <option value="<?= $ranking_cat_id ?>">Ranking</option>
        
    </select>
    <div id="wrapper_cat_id">
    </div>
      <?php if ($this->element->getMessages()) {
          $errorHtml = '';
          foreach ($this->element->getMessages() as $currentError) {
              $errorHtml .= '<label id="<?=$this->escape($this->element->getName())?>-error" class="error" for="<?=$this->escape($this->element->getName())?>">' . $currentError . '</label>';
          }
          ?>
          <?php echo $errorHtml ?>
      <?php } ?>
  </div>
  <div id="wrapper_sub_cat"></div>
</div>