<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="field relative">
    <?php if ($this->element->isRequired()) { ?>
        <div class="mandatory absolute small grey bold-font">*</div>
    <?php } ?>
    <?php echo $this->formLabel($this->element->getName(),
        $this->element->getLabel()) ?>
    <?php
    //    echo $this->{$this->element->helper}(
    //        $this->element->getName(),
    //        $this->element->getValue(),
    //        $this->element->getAttribs()
    //    );
    echo $this->content;
    ?>
    <?php if ($this->element->getMessages()) { ?>
        <div class="field-missing-container absolute clearfix">
            <div class="field-missing-left"></div>
            <div class="field-missing"><?php echo $this->formErrors($this->element->getMessages()) ?></div>
        </div><!-- /.field-missing-container -->
    <?php } ?>
</div>
<?php /*
<div class="<?php echo $this->class ?>">
    <?php echo $this->formLabel($this->element->getName(),
        $this->element->getLabel()) ?>
    <?php echo $this->{$this->element->helper}(
        $this->element->getName(),
        $this->element->getValue(),
        $this->element->getAttribs()
    ) ?>
    <?php echo $this->formErrors($this->element->getMessages()) ?>
    <div class="hint"><?php echo $this->element->getDescription() ?></div>
</div> */ ?>