<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Created: 31.05.2017
 */
$modelInfo = new Default_Model_Info();
$countActiveMembers = $modelInfo->countTotalActiveMembers();
?>
<link href="/theme/flatui/css/support.css" rel="stylesheet">
<style type="text/css">
    li.amount-item
    {
       border-bottom: 0px !important;
    }
  
    ul.suggested-amounts.less-margin
    {
       margin: 10px !important;
       padding-left: 0px;
    }
    .tabs .row
    {
        border-bottom: dotted thin #E7E7E7 !important;
        padding: 16px 0 7px;
        padding:0px;
        margin-left: 20px;
        margin-right: 20px;
      
    }

    .tabs .row:first-child
    {
        margin:0px;
        margin-right: -15px;
        margin-left: -15px;
        border-bottom: 0px !important;
    }
    .tabs .row:last-child
    {
        padding:20px;
    }



</style>
<main>
    <section class="wrapper" id="products-wrapper">
        <form class="donation-form" id="new_donation" action="/support/pay" accept-charset="UTF-8" data-remote="true" method="post">  
                <input type="hidden" id="currency-symbol" value="$">
                <input type="hidden" name="provider" value="paypal" id="provider">
        <div class="container-fluid">
            <div class="row">
                <div class="sidebar-left col-md-2"></div>
                
   
                <div class="content col-md-8">
                    <h2>Become a Supporter</h2>
                    <p>Your donation supports <b> <?=$countActiveMembers?></b> creators on opendesktop.org.
                    </p> 
                                                                          
                    <div class="tabs donation-widget ">

                            <div class="row disply-flex">
                                    <div class="col-lg-6">        
                                            <div class="tabs-header non-selectable basic-color-background">
                                              <div class="header-content">
                                                <span class="display-amount">
                                                  <span class="step-1 active">Choose monthly tier</span>
                                                </span>
                                              </div>
                                            </div>                                                  
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="tabs-header non-selectable basic-color-background">
                                          <div class="header-content">
                                            <span class="display-amount">
                                              <span class="step-1 active">Choose yearly tier</span>
                                            </span>
                                          </div>
                                        </div>                                               
                                    </div>
                            </div> <!--end of row-->
                            <div class="row disply-flex">
                                <div class="col-lg-6">  
                               <?php
                                    echo $this->partial('/support/partials/option.phtml',
                                        $this->payment_options['Option1']
                                    );
                                ?>
                                </div>
                                <div class="col-lg-6">  
                                    <?php
                                    echo $this->partial('/support/partials/option.phtml',
                                        $this->payment_options['Option5']
                                    );
                                ?>                                    
                                </div>
                            </div> <!--end of row-->

                            <div class="row disply-flex">
                                <div class="col-lg-6">  
                               <?php
                                    echo $this->partial('/support/partials/option.phtml',
                                        $this->payment_options['Option2']
                                    );
                                ?>
                                </div>
                                <div class="col-lg-6">  
                                    <?php
                                    echo $this->partial('/support/partials/option.phtml',
                                        $this->payment_options['Option6']
                                    );
                                ?>                                    
                                </div>
                            </div> <!--end of row-->
                            
                            <div class="row disply-flex">
                                <div class="col-lg-6">  
                               <?php
                                    echo $this->partial('/support/partials/option.phtml',
                                        $this->payment_options['Option3']
                                    );
                                ?>
                                </div>
                                <div class="col-lg-6">  
                                    <ul class="suggested-amounts less-margin">
                                    <li class="amount-item last">
                                          <label class="mdl-radio mdl-js-radio is-upgraded" for="custom_amount_item" data-upgraded=",MaterialRadio">
                                            <input class="suggested-amount mdl-radio__button" id="custom_amount_item" type="radio" value="Option7" name="amount_predefined">
                                            <span class="mdl-radio__label">
                                              <span class="item-text">
                                                <span class="unit-wrapper">
                                                  <span class="unit">$</span>
                                                </span>
                                                <span class="amount">
                                                  <input id="custom_amount" min="16" step="any" inputmode="numeric" type="number" name="amount_handish">
                                                </span>
                                                <span class="desc">Enter a free amount > $15</span>
                                              </span>
                                            </span>
                                          <span class="mdl-radio__outer-circle"></span><span class="mdl-radio__inner-circle"></span></label>
                                        </li>
                                    </ul>
                                                                   
                                </div>
                            </div> <!--end of row-->

                            <div class="row disply-flex">
                                <div class="col-lg-6">  
                               <?php
                                    echo $this->partial('/support/partials/option.phtml',
                                        $this->payment_options['Option4']
                                    );
                                ?>
                                </div>
                                <div class="col-lg-6">  
                                                                   
                                </div>
                            </div> <!--end of row-->
            
                        <div class="row disply-flex">
                              <div class="col-lg-12">  
                                <div class="tabs-footer">
                                    <?php if (Zend_Auth::getInstance()->hasIdentity()) {?>
                                  <button type="submit" class="dw-btn mdl-button mdl-js-button mdl-js-ripple-effect step-3 basic-color-background" data-upgraded=",MaterialButton,MaterialRipple">
                                    <span class="donate" id="linkButton">
                                      <span class="amount">
                                        <span isolate="">Donate via PayPal</span>
                                      </span>
                                    </span>
                                    </button>
                                     <?php }else{
                                        echo "Please login to donate";
                                    }?>
                                </div>
                                    </div>
                        </div> <!--end of row-->
                    </div> <!--end of tabs-->
                    
                    
                </div> <!--end of content-->
                <div class="sidebar-right col-md-2"></div>
                
            </div>
            
        </div>
         </form>
    </section>
</main>

<script>
    $(document).ready(function(){
        $("#custom_amount").click(function(){
            $('.mdl-radio__button').removeAttr('checked');
            $('#custom_amount_item').prop("checked", true);            
        });

        $('#plingListOpen').click(function(){
            $('#plingList').trigger( "click" );       
        });

    });
</script>