<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Created: 31.05.2017
 */
?>
<main id="explore-content">
    <section class="wrapper" id="products-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="sidebar-left col-md-2"></div>
                <div class="content col-md-8">
                    <h2><?= $this->paymentMessage ?></h2>
                    <p>Your Donation was cancelled. Please try again.</p>
                    <p><a href="/support">Back</a></p>
                </div>
                <div class="sidebar-right col-md-2"></div>
            </div>
            <section class="explore-footer text-center">
                
            </section>
        </div>
    </section>
</main>