<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<!--Script and CSS includes for YUI dependencies on this page-->
<link rel="stylesheet" type="text/css" href="/tools/yui_2.9.0/build/datatable/assets/skins/sam/datatable.css"/>
<link rel="stylesheet" type="text/css" href="/tools/yui_2.9.0/build/datatable/assets/skins/sam/datatable-skin.css"/>
<link rel="stylesheet" type="text/css" href="/tools/yui_2.9.0/build/button/assets/skins/sam/button.css"/>
<link rel="stylesheet" type="text/css" href="/tools/yui_2.9.0/build/paginator/assets/skins/sam/paginator.css"/>
<link rel="stylesheet" type="text/css" href="/tools/yui_2.9.0/build/menu/assets/skins/sam/menu.css"/>
<link rel="stylesheet" type="text/css" href="/tools/yui_2.9.0/build/tabview/assets/skins/sam/tabview.css"/>
<script type="text/javascript" src="/tools/yui_2.9.0/build/yahoo/yahoo-debug.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/event/event.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/dom/dom.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/connection/connection-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/json/json-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/utilities/utilities.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/container/container_core.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/container/container.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/menu/menu.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/element/element-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/datasource/datasource-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/datatable/datatable-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/button/button-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/paginator/paginator-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/event-delegate/event-delegate-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/autocomplete/autocomplete-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/tabview/tabview-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/swf/swf-min.js"></script>
<script type="text/javascript" src="/tools/yui_2.9.0/build/charts/charts-min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        YAHOO.namespace("pling");
    });
</script>

