<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>ocs-webserver :: Backend</title>
    <script type="text/javascript" src="/js/libs/mootools-core.js"></script>
    <script type="text/javascript" src="/js/libs/mootools-more.js"></script>
    <script type="text/javascript" src="/js/libs/mootools-more-1.4.0.1.js"></script>
</head>
<body>
<div id="parent">

    <?php $auth = Zend_Auth::getInstance(); ?>

    <?php if ($auth->hasIdentity()): ?>

        <div id="mainarea" class="ui-corner-all">
            <?php if ($this->pageTitle): ?><h3><?= $this->escape($this->pageTitle); ?></h3><?php endif; ?>
            <?php echo $this->layout()->content; ?>
        </div>
    <?php else: ?>
        <div id="loginArea" class="ui-corner-all">
            <?php echo $this->layout()->content; ?>
        </div>
    <?php endif; ?>
    <div id="footer" style="clear: both;" class=""><span>&copy;
            <?php echo $_SERVER['SERVER_NAME']?></span><span>|</span><span>Zend FW Version: <?php echo Zend_Version::VERSION; ?></span></div>
</div>
</body>
</html>

