<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperUserRole = new Backend_View_Helper_UserRole();
$userRoleName = $helperUserRole->userRole();
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>ocs-webserver :: Backend</title>

    <!-- Loading Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="/theme/backend/css/bootstrap/bootstrap-formhelpers.css" rel="stylesheet">
    <link href="/theme/backend/css/backend.css" rel="stylesheet" type="text/css"/>
    <link href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" media="screen"/>
    <link href="/theme/backend/js/jtable/themes/jqueryui/jtable_jqueryui.min.css" rel="stylesheet" type="text/css" media="screen"/>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <script type="text/javascript" src="/theme/backend/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/theme/backend/js/jtable/jquery.jtable.min.js"></script>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script type="text/javascript" src="/theme/backend/js/backendFunctions.js"></script>
    <script type="text/javascript" src="/theme/backend/js/jquery.qtip-1.0.0-rc3.min.js"></script>

    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/css/template.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/css/validationEngine.jquery.css">
    <script src="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/js/jquery.validationEngine.min.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.validationengine/2.6.4/languages/jquery.validationEngine-en.js"></script>

    <script src="/tools/elfinder/js/elfinder.min.js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="/tools/elfinder/css/elfinder.min.css" type="text/css" media="screen" charset="utf-8"/>
    <link rel="stylesheet" href="/tools/elfinder/css/theme.css" type="text/css" media="screen" charset="utf-8"/>

    <link rel="stylesheet" href="/tools/fancybox2.1.4/jquery.fancybox.css" type="text/css" media="screen" charset="utf-8"/>
    <script src="/tools/fancybox2.1.4/jquery.fancybox.js" type="text/javascript" charset="utf-8"></script>
    
    <link rel="stylesheet" href="/theme/backend/css/jtreetable/jquery.treetable.css" type="text/css" media="screen" charset="utf-8"/>
    <script src="/theme/backend/js/jtreetable/jquery.treetable.js" type="text/javascript" charset="utf-8"></script>

    <?= $this->partial('yui.phtml'); ?>
    <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_STAFF == $userRoleName) : ?>
        <script src="/theme/backend/js/backend_nav_staff.js" type="text/javascript" charset="utf-8"></script>
    <?php endif; ?>
    <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) : ?>
        <script src="/theme/backend/js/backend_nav_admin.js" type="text/javascript" charset="utf-8"></script>
    <?php endif; ?>
    <style>
        body {

        }

        #mainarea {

        }
    </style>
</head>
<body>
<div id="parent">
    <?php $auth = Zend_Auth::getInstance(); ?>

    <?php if ($auth->hasIdentity()): ?>
        <div id="mainarea" class="ui-corner-all">
            <?php if ($this->pageTitle): ?><h3><?= $this->escape($this->pageTitle); ?></h3><?php endif; ?>
            <?php echo $this->layout()->content; ?>
        </div>
    <?php else: ?>
        <div id="loginArea" class="ui-corner-all">
            <?php echo $this->layout()->content; ?>
        </div>
    <?php endif; ?>
    <div id="footer" style="clear: both;" class=""><span>&copy;
            <?=$_SERVER['SERVER_NAME']?></span><span>|</span><span>Zend FW Version: <?php echo Zend_Version::VERSION; ?></span></div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        $("#logout, #portal").hover(
            function () {
                $(this).addClass("ui-state-hover");
            },
            function () {
                $(this).removeClass("ui-state-hover");
            }
        );

    });
</script>

</body>
</html>

