<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

?>

<?php

$response = array('username'=>$this->username);

?>

<main class="startpage-portal" style="margin-top:40px; width:100%;height:100%">
      <div id="main-content-portal"></div>               
</main>

<script type="text/javascript">        
        var data = <?php echo Zend_Json::encode($response)?>;
</script>
<script src="/theme/react/bundle/portal-index-bundle.js" type="text/javascript"></script>
