<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$modelCategory = new Default_Model_ProjectCategory();
$this->categories = $modelCategory->fetchTreeForView();
$jsonTree = json_encode($this->categories);
?>
<div class="pling-nav-tabs">
    <ul class="nav nav-tabs ">
        <li class="active"><a class="newuserprojectTab" href="#d3-line" data-toggle="tab">New Members & Projects </a></li>
         <li><a class="newproductsweeklyTab" href="#newproductsweeklyTab" data-toggle="tab">New Products weekly</a></li>

        <li><a class="downloadsDomainTab" href="#downloadsDomainTab" data-toggle="tab">Downloads Domain</a></li>
        <li><a class="downloadsdailyTab" href="#downloadsdailyTab" data-toggle="tab">Downloads&Payouts daily</a></li>

        <li><a class="topDownloadsPerDayTab" href="#topDownloadsPerDayTab" data-toggle="tab">Product/Day</a></li>
        <li><a class="topDownloadsPerMonthTab" href="#topDownloadsPerMonthTab" data-toggle="tab">Product/Month</a></li>
        <li><a class="payoutTab" href="#payoutTab" data-toggle="tab">Payout Member</a></li>
        <li><a class="payoutNewcomerTab" href="#payoutNewcomerTab" data-toggle="tab">Payout Newcomer</a></li>
        <li><a class="payoutNewloserTab" href="#payoutNewloserTab" data-toggle="tab">Payout Newloser</a></li>
        <li><a class="payoutMonthDiffTab" href="#payoutMonthDiffTab" data-toggle="tab">Payout Month Diff</a></li>
        <li><a class="payoutCategoryMonthlyTab" href="#payoutCategoryMonthlyTab" data-toggle="tab">Payout Categories</a></li>
        <li><a class="payoutCategoryTab" href="#payoutCategoryTab" data-toggle="tab">Payout Category monthly</a></li>              

    </ul>
    <div class="tab-content row">
        <div id="d3-line" class="tab-pane active ">
            <div style="width: 100%; padding: 20px">

                <div id='d3linelableinline' class="d3linepath"></div>

                

            </div>
        </div>

        <div id="downloadsdailyTab" class="tab-pane">
            <span style="float: left">#number of months back</span>
            <select id="numofmonthback" style="float: left">
                <option>2</option>
                <option selected>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
                <option>11</option>
                <option>12</option>
            </select>
            <div id="downloadsdailyTabContainer" class="d3linepath"></div>
        </div>

      
        <div id="downloadsDomainTab" class="tab-pane ">
            <div style="display: block; clear: both">
                Begin:<input name="filterDownloadsDomainDateBegin" id="filterDownloadsDomainDateBegin" value="<?php echo date("Y-m-j") ?>" />
                End:<input name="filterDownloadsDomainDateEnd" id="filterDownloadsDomainDateEnd" value="<?php echo date("Y-m-j") ?>" />
                <button class="filterDownloadsDomainDate">go!</button>
            </div>
            <div id="downloadsDomainTabContainer" style="display: block;clear: left"></div>
        </div>

        <div id="topDownloadsPerDayTab" class="tab-pane ">
            <div style="display: block; clear: both">
                <input name="filterTopDownloadsDate" id="filterTopDownloadsDate" value="<?php echo date("Y-m-j") ?>"/>
                <button class="filterTopDownloadsDate">go!</button>
                <button class="filterTopDownloadsDateClear">clear!</button>

            </div>
            <div id="topDownloadsPerDayTabContainer" style="display: block;clear: left"></div>
        </div> 

        <div id="topDownloadsPerMonthTab" class="tab-pane ">
            <div style="display: block; clear: both" class="filter">
                <input name="filterTopDownloadsMonth" id="filterTopDownloadsMonth" value="<?php echo date("Ym") ?>" />                
                <script type="text/javascript">
                    
                </script>                                
            </div>
            <div id="topDownloadsPerMonthTabContainer" style="display: block;clear: left"></div>
        </div> 

        <div id="payoutTab" class="tab-pane">
            <div style="width: 1500px; display: block;float: left">
                    <div id="payoutyear" style="display: block; float: left; padding-right: 20px" class="d3linepath"></div>         
                        <div id="pie" style="clear:left;padding:50px; display:block;  "></div>
             

            </div>

            <div>    
                        
                    
                         <div style="display: block; float: left; clear:left" id="detailContainer"></div>         
                        
                
            </div>
            
            
            

        </div>

        <div id="payoutNewcomerTab" class="tab-pane">
            <div id="payoutNewcomerTabContainer"></div>
        </div>

        <div id="payoutNewloserTab" class="tab-pane">
            <div id="payoutNewloserTabContainer"></div>
        </div>

        <div id="payoutMonthDiffTab" class="tab-pane">
            <div id="payoutMonthDiffTabContainer"></div>
        </div>

        <div id="payoutCategoryMonthlyTab" class="tab-pane">
            <div id="pieCategoryMonthly" style="padding:50px; "></div>
        </div>

          <div id="payoutCategoryTab" class="tab-pane">
            <div style="display: block; clear: both" class="filter">
                <button id="clearChartPanel">clear</button>
            </div>
               
            <div id="payoutCategoryLineChart"  style="max-width: 1000px; height: 100%; display: block; float: right; ">
                    
            </div>
        </div>
        <div id="newproductsweeklyTab" class="tab-pane">
            <div id="newproductsweekly" style="padding:50px; ">TEST</div>
        </div>
        

    </div>
</div> <!--end of tab-->


<div id="dataFilter" style="display: none">
<div id="category-tree-container"></div>
</div>
<script type="application/javascript">
  var catTree = <?= $jsonTree ?>;  
  var backendView = true;
</script>
<script type="application/javascript" src="/theme/react/cat-tree.js"></script>



