<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/


$modelCategory = new Default_Model_ProjectCategory();
$this->categories = $modelCategory->fetchTreeForView();
$jsonTree = json_encode($this->categories);
$this->tab = 'payout-category-monthly';
echo $this->render('statistics/headerTabs.phtml'); 
?>
<h3>Statistics: Payout Category Monthly</h3>

<div id="payoutCategoryTab" class="tab-pane">
            <div style="display: block; clear: both" class="filter">
                <button id="clearChartPanel">clear</button>
                <div id="category-tree-container" style="float: left"></div>   
            </div>
               
            <div id="payoutCategoryLineChart"  style="max-width: 1000px; height: 100%; display: block; float: left; ">
                    
            </div>
        </div>
<script type="application/javascript">
  var catTree = <?= $jsonTree ?>;  
  var backendView = true;  
</script>
<script type="application/javascript" src="/theme/react/cat-tree.js"></script>
<script type="text/javascript">
    $(document).ready(function () {     
        window.selectedTab = '#payoutCategoryTab';
        window.selectedCatid = 0;
        window.selectedCatTitle = '';
    });    
</script>