<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<h3>Statistics: Payout Member</h3>
<div id="payoutTab" class="tab-pane">
            <div style="width: 1500px; display: block;float: left">
                    <div id="payoutyear" style="display: block; float: left; padding-right: 20px" class="d3linepath"></div>         
                        <div id="pie" style="clear:left;padding:50px; display:block;  "></div>             

            </div>

            <div>    
             <div style="display: block; float: left; clear:left" id="detailContainer"></div>                                                 
            </div>                                    
        </div>
<script type="text/javascript">
	$(document).ready(function () {		
        $.getScript("/theme/flatui/js/stati/payoutyear.js");
        $.getScript("/theme/flatui/js/stati/memberPayout.js");
	});
</script>