<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
<?php
    echo $this->headTitle();
    echo $this->headMeta();
    echo $this->headLink();
    echo $this->headStyle();
    echo $this->headScript(); ?>
    <link rel="stylesheet" href="/theme/portal/css/style.css">
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>