<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="panel-heading">
    <h4 class="panel-title">
        <a data-toggle="collapse" href="#delete-collapse" data-parent="#accordion" id="delete-trigger">
            <span class="glyphicon glyphicon-trash"></span>
            <?= $this->translate('Delete account') ?>
            <span class="absolute glyphicon glyphicon-chevron-down"></span>
        </a>
    </h4>
</div>

<div class="panel-collapse collapse" id="delete-collapse">
    <div class="panel-body">
        <form class="standard-form well partial" action=""
              method="" data-target="#form-delete"
              data-trigger="#delete-trigger">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <p><?= $this->translate('Once you delete your account, there is no going back. Please be certain.') ?></p>
                </div>
            </div>
            <hr>
            <div class="row">
                <a href="#modalDeleteUser" data-toggle="modal" role="btn"
                   class="btn btn-danger pull-right margin-right-5"
                   tabindex="30"><?= $this->translate('Delete your account') ?></a>
            </div>
        </form>
        <!-- /.standard-form -->
    </div>
    <!-- /.section-body -->
</div>
<div id="modalDeleteUser" class="modal hide fade" aria-hidden="true" style="display: none;">
    <div class="modal-dialog content-modal">
        <div class="modal-content">
            <!-- dialog contents -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="center"><?= $this->translate('Delete Confirmation') ?></h3>
            </div>
            <div class="modal-body"><?= $this->translate('Do you really want to delete your account?') ?></div>
            <!-- dialog buttons -->
            <div class="modal-footer">
                <a href="/settings/delete/" role="button" class="btn btn-primary"><?= $this->translate('YES') ?></a>
                <a href="#" role="button" class="btn btn-primary" data-dismiss="modal"
                   aria-hidden="true"><?= $this->translate('NO') ?></a>
            </div>
        </div>
    </div>
</div>