<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>

<div class="panel-collapse " id="newsletter-collapse">

    <div class="panel-body">
        <form class="standard-form partial well" action="<?= $this->newsletterform->getAttribute('action'); ?>"
              method="<?= $this->newsletterform->getAttribute('method'); ?>" data-target="#form-newsletter"
              data-trigger="#newsletter-trigger">
            <p class="italic">
                <?= $this->translate('You get the Newsletter with new products. You can turn the Newsletter On or Off below:') ?>
            </p>

            <div class="field clearfix">
                <div class="left purple newsletter-label"><?= $this->translate('NEWSLETTER') ?></div>
                <div class="left">
                    <?php echo $this->formElement($this->newsletterform->get('newsletter')); ?>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="box pull-left margin-left-15"  style="padding-left: 15px;"><?= $this->formResult($this->newsletterform, $this->save); ?></div>
                <button type="submit" class="btn btn-native pull-right"
                        tabindex="23"><?= $this->translate('Save &amp; Update') ?></button>
            </div>
        </form>
        <!-- /.standard-form -->
    </div>
    <!-- /.section-body -->

</div>