<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$form = $this->passwordform;
$form->get('passwordOld')->setAttributes(array(   
  'tabindex' => 15
  ));
$form->get('password1')->setAttributes(array(   
'tabindex' => 16
));
$form->get('password2')->setAttributes(array(   
'tabindex' => 17
));
?>


<div class="panel-collapse " id="password-collapse">
    <div class="panel-body">
        <form class="standard-form well partial" action="<?= $this->passwordform->getAttribute('action'); ?>"
              method="<?= $this->passwordform->getAttribute('method'); ?>" data-target="#form-password"
              data-trigger="#password-trigger">
            <div class="row">
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">       
                    <span class="mandatory small grey bold-font">*</span>             
                    <?php echo $this->formLabel($form->get('passwordOld')); ?>
                    <?php echo $this->formElement($form->get('passwordOld')); ?>
                    <?php echo $this->formElementErrors($form->get('passwordOld')); ?>  
                </div>
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                    <span class="mandatory small grey bold-font">*</span>             
                    <?php echo $this->formLabel($form->get('password1')); ?>
                    <?php echo $this->formElement($form->get('password1')); ?>
                    <?php echo $this->formElementErrors($form->get('password1')); ?>                      
                </div>
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                <span class="mandatory small grey bold-font">*</span>             
                    <?php echo $this->formLabel($form->get('password2')); ?>
                    <?php echo $this->formElement($form->get('password2')); ?>
                    <?php echo $this->formElementErrors($form->get('password2')); ?>                      
                </div>
            </div>
            <!-- /.row-fluid -->
            <hr>
            <div class="row">
                <div
                    class="box pull-left margin-left-15"  style="padding-left: 15px;">
                    <?= $this->formResult($this->passwordform, $this->save); ?></div>
                <button type="submit" class="btn btn-native pull-right"
                        tabindex="18"><?= $this->translate('Save &amp; Update') ?></button>
            </div>
        </form>
    </div>
</div>