<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="panel-collapse " id="payments-collapse">
    <div class="panel-body">
        <form class="standard-form well partial" action="<?= $this->paymentform->getAttribute('action'); ?>"
              method="<?= $this->paymentform->getAttribute('method'); ?>" data-target="#form-payment"
              data-trigger="#payments-trigger">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <?php
                        $member = $this->member;
                        if($member && $member->paypal_valid_status > 100) {
                            $status = $this->paypal_valid_status;
                            if($status->color == 'red') {
                                echo '<div class="alert alert-danger" role="alert">'.$status->description.'</div>';
                            }
                            if($status->color == 'yellow') {
                                echo '<div class="alert alert-warning" role="alert">'.$status->description.'</div>';
                            }
                            if($status->color == 'blue') {
                                echo '<div class="alert alert-info" role="alert">'.$status->description.'</div>';
                            }
                            if($status->color == 'green') {
                                echo '<div class="alert alert-success" role="alert">'.$status->description.'</div>';
                            }
                        }
                    ?>
                    <p class="italic">
                        <?= $this->translate('Here are the settings for receiving payouts. Please provide a valid paypal address to participate in the payout program.') ?>
                    </p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formLabel($this->paymentform->get('paypal_mail')); ?>
                        <?php echo $this->formElement($this->paymentform->get('paypal_mail')); ?>
                        <?php echo $this->formElementErrors($this->paymentform->get('paypal_mail')); ?>                  
                    </div>                    
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <label for="wallet_address">Bitcoin: Your Public Wallet Address</label><br/>Coming in the future</div>
            </div>
            <?php /*
            <br/>
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <?= $this->paymentform->wallet_address->setAttrib('tabindex', 25)->setAttrib('pattern', '^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$') ?>
                </div>
            </div>
             * 
             */ ?>
            <?php /* 
            <div class="row margin-top-15">
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <?= $this->paymentform->dwolla_id->setAttrib('tabindex', 25) ?>
                </div>
            </div>
            */
            ?>

            <hr>
            <div class="row">   
                <div class="box pull-left margin-left-15"  style="padding-left: 15px;">
                    <?php echo $this->formResult($this->paymentform, $this->save); ?>
                </div>             
                <button type="submit" class="btn btn-native pull-right"
                        tabindex="25"><?= $this->translate('Save &amp; Update') ?></button>
            </div>
        </form>
        <!-- /.standard-form -->
    </div>
    <!-- /.section-body -->
</div>
