<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$form = $this->pictureformbg;
$form->get('profile_picture_background_upload')
     ->setAttributes(array('class'=>'product-picture'
                           ,'onchange' =>'ImagePreview.previewImageMember(this, \'profile-picture-background-preview\');'
        ));
$form->get('profile_image_url_bg')->setAttributes(array('data-target'=>'#profile-picture-bg-preview'));
$form->get('submit')->setAttributes(array('class'=>'btn btn-native pull-right', 'tabindex' => 14));
?>
<style>
.image-preview .delete_img {
    position: absolute;
    top: 37px;
    right: 67px;
    z-index: 100;
    color: #9a2b1f;
    cursor: pointer;
}
</style>

<!--partialajaxbg-->
<div class="panel-collapse " id="picture-bg-collapse">
    <div class="panel-body">
        <form class="standard-form partialajaxbg well" action="<?= $form->getAttribute('action'); ?>"
              method="<?= $form->getAttribute('method'); ?>" data-target="#form-picture-background"
              data-trigger="#picture-background-trigger" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4 center">
                <?= $this->formLabel($form->get('profile_picture_background_upload')); ?>
                    <div>
                        <div class="bordered box image-preview" style="overflow: hidden;">
                            <span class="glyphicon glyphicon-trash delete_img delete_bg_img"></span>
                            <img src="/theme/flatui/img/sample-profile-image-2.jpg"
                                alt="profile-image"
                                id="profile-picture-background-preview"
                                height="200"
                                width="200">
                        </div>
                        <!-- hack hack hack -->
                        <a class="btn btn-purple" id="add-profile-picture-background" onclick="$('input#profile_picture_background_upload').click();"
                        tabindex="13">
                            ADD PICTURE
                        </a>
                       
                        <?= $this->formElement($form->get('profile_picture_background_upload')); ?>
                        <?= $this->formElementErrors($form->get('profile_picture_background_upload')); ?>
                        <?= $this->formElement($form->get('profile_image_url_bg')); ?>
                    </div>
                                                     
                </div>
                <!-- /.span4 -->
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                    <div class="image-info">
                        <p>
                            <em class="icon info-icon"></em>
                        </p>
                      
                        <p class="italic">
                            <?= $this->translate('You can use <br><span class="purple">JPG, PNG, GIF</span> formats') ?>
                        </p>
                    </div>
                </div>
                <!-- /.span4 -->
            </div>
            <!-- /.row-fluid -->
            <hr>
            <div class="row">
                <div class="box pull-left margin-left-15"  style="padding-left: 15px;">
                    <?php echo $this->formResult($this->pictureformbg, $this->save, true, 'Changes saved. Some picture elements will be updated at next login.'); ?>
                </div>
                <button type="submit" class="btn btn-native pull-right"
                        tabindex="14"><?= $this->translate('Save &amp; Update') ?></button>
            </div>
        </form>
        <!-- /.standard-form -->
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        ImagePreview.initProfilePictureBackground();
        PartialFormsAjaxMemberBg.setup();
        
        //init delete bg pic
        $('body').on('click', '.delete_bg_img', function (event) {
            event.stopPropagation();
            jQuery.ajax({
                data: '',
                url: '/settings/deletepicturebackground',
                type: 'GET',
                error: function () {
                    return false;
                },
                success: function (results) {
                    $('#profile-picture-background-preview').attr('src', '/img/default.png');
                    return false;
                }
            });
        });
    });
</script>