<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="messages">
    <?php foreach (Zend_Controller_Action_HelperBroker::getStaticHelper('flashMessenger')
                       ->getCurrentMessages() as $message) : ?>
        <p><?php echo $this->escape($message); ?></p>
    <?php endforeach; ?>
</div>
<div class="filtering">
    <form>
        First Name: <input type="text" name="filter_firstname" id="filter_firstname"/>
        Last Name: <input type="text" name="filter_lastname" id="filter_lastname"/>
        Username: <input type="text" name="filter_username" id="filter_username"/>
        e-mail: <input type="text" name="filter_mail" id="filter_mail"/>
        <button type="submit" id="LoadRecordsButton"><?= $this->translate('Load records'); ?></button>
        <button type="reset" id="RemoveFilterButton"><?= $this->translate('Remove filter'); ?></button>
    </form>
</div>
<div id="TableContainer"></div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#TableContainer').jtable({
            jqueryuiTheme: true,
            paging: true,
            sorting: true,
            defaultSorting: 'mail asc',
            title: 'Table of user',
            actions: {
                listAction: '/backend/user/list',
                createAction: '/backend/user/create',
                updateAction: '/backend/user/update',
                deleteAction: '/backend/user/delete'
            },
            fields: {
                member_id: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                uuid: {
                    title: 'UUID',
                    width: '10%',
                    list: false,
                    create: false
                },
                password: {
                    title: 'Password',
                    list: false,
                    edit: false,
                    create: false,
                    type: 'password'
                },
                roleId: {
                    title: 'Role',
                    width: '5%',
                    sorting: false //This column is not sortable!
                },
                type: {
                    title: 'Type',
                    width: '5%',
                    sorting: false //This column is not sortable!
                },
                firstname: {
                    title: 'firstname',
                    width: '5%'
                },
                lastname: {
                    title: 'lastname',
                    width: '5%'
                },
                street: {
                    title: 'street',
                    list: false
                },
                zip: {
                    title: 'zip',
                    list: false
                },
                city: {
                    title: 'city',
                    list: false
                },
                phone: {
                    title: 'phone',
                    list: false
                },
                mail: {
                    title: 'mail',
                    width: '5%',
                    list: true
                },
                lastonline: {
                    title: 'lastonline',
                    type: 'date',
                    list: false
                },
                is_deleted: {
                    title: 'Deleted',
                    width: '5%',
                    list: true
                },
                verificationVal: {
                    title: 'Verification Value',
                    list: false
                },
                mail_checked: {
                    title: 'mail_checked',
                    list: false
                },
                created_at: {
                    title: 'Created',
                    width: '10%',
                    type: 'date',
                    create: false,
                    edit: false
                },
                changed_at: {
                    title: 'Changed',
                    width: '10%',
                    type: 'date',
                    create: false,
                    edit: false
                },
                deleted_at: {
                    title: 'Deleted',
                    width: '10%',
                    type: 'date',
                    create: false,
                    edit: false
                },
                biography: {
                    title: 'biography',
                    type: 'textarea',
                    list: false
                },
                avatar: {
                    title: 'avatar',
                    list: false
                },
                username: {
                    title: 'username',
                    width: '5%',
                    list: true
                },
                agb: {
                    title: 'agb',
                    list: false
                },
                country: {
                    title: 'country',
                    list: false
                },
                newsletter: {
                    title: 'newsletter',
                    list: false
                },
                is_active: {
                    title: 'Active',
                    width: '5%',
                    list: true,
                    sorting: false //This column is not sortable!
                },
                paypal_mail: {
                    title: 'paypal_mail',
                    width: '5%',
                    list: true
                },
                main_project_id: {
                    title: 'main_project_id',
                    list: false
                },
                profile_image_url: {
                    title: 'profile_image_url',
                    list: false
                },
                login_method: {
                    title: 'login_method',
                    list: false
                },
                social_username: {
                    title: 'social_username',
                    list: false
                },
                social_user_id: {
                    title: 'social_user_id',
                    list: false
                },
                gravatar_email: {
                    title: 'gravatar_email',
                    list: false
                },
                profile_img_src: {
                    title: 'profile_img_src',
                    list: false
                },
                facebook_username: {
                    title: 'facebook_username',
                    list: false
                },
                twitter_username: {
                    title: 'twitter_username',
                    list: false
                },
                link_facebook: {
                    title: 'link_facebook',
                    list: false
                },
                link_twitter: {
                    title: 'link_twitter',
                    list: false
                },
                link_website: {
                    title: 'link_website',
                    list: false
                },
                link_google: {
                    title: 'link_google',
                    list: false
                },
                validated_at: {
                    title: 'validated_at',
                    type: 'date',
                    create: false,
                    edit: false,
                    list: false
                },
                validated: {
                    title: 'validated',
                    list: false
                }
            }
        });

        //Re-load records when user click 'load records' button.
        $('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#TableContainer').jtable('load', {
                filter_firstname: $('#filter_firstname').val(),
                filter_lastname: $('#filter_lastname').val(),
                filter_username: $('#filter_username').val(),
                filter_mail: $('#filter_mail').val()
            });
        });

        //Re-load records when user click 'remove filter' button.
        $('#RemoveFilterButton').click(function (e) {
            e.preventDefault();
            $('#TableContainer').jtable('load', {
                filter_firstname: null,
                filter_lastname: null,
                filter_username: null,
                filter_mail: null
            });
        });

        $('#TableContainer').jtable('load');
    });
</script>