<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?><!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->render('partials/htmlheader.phtml'); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="alternate" type="application/rss+xml" title="Latest Products" href="/content.rdf"/>

    <link rel="stylesheet" type="text/css" href="/theme/flatui/js/lib/tooltipster/dist/css/tooltipster.bundle.min.css" />
    <link rel="stylesheet" type="text/css" href="/theme/flatui/js/lib/tooltipster/dist/css/plugins/tooltipster/sideTip/themes/tooltipster-sideTip-light.min.css" />
    <link rel="stylesheet" type="text/css" href="/theme/flatui/css/tooltipster-light-customized.css" />

    <!-- Loading Bootstrap -->
    <link rel="stylesheet" href="/theme/flatui/css/bootstrap/bootstrap.min.css" type="text/css"  crossorigin="anonymous">
    <link rel="stylesheet" href="/tools/fancybox2.1.4/jquery.fancybox.css?v=2.1.4" type="text/css" media="screen" />
    <link rel="stylesheet" href="/theme/flatui/css/fontawsome/font-awesome.min.css"  crossorigin="anonymous">

    <!-- custom styles -->
    <link href="/theme/flatui/css/flex-layout.css" rel="stylesheet">
    <link href="/theme/flatui/css/style.css" rel="stylesheet">
    <link href="/theme/flatui/css/stylesheet.css?<?= APPLICATION_VERSION ?>" rel="stylesheet">

    <link href="/theme/flatui/css/jquery.step.css" rel="stylesheet">


    <link rel="SHORTCUT ICON" href="<?=$this->template['favicon']?>"/>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
    <script src="/theme/flatui/js/lib/html5shiv.js"></script>
    <![endif]-->

    <script src="/theme/flatui/js/lib/jquery-3.2.1.min.js" ></script>
    <script src="/theme/flatui/js/lib/bootstrap.min.js" ></script>
    <script type="text/javascript" src="/theme/flatui/js/lib/tooltipster/dist/js/tooltipster.bundle.min.js"></script>
<?php
/*
    <script type="text/javascript" src="/theme/react/lib/react/react.js"></script>
    <script type="text/javascript" src="/theme/react/lib/react-dom/react-dom.js"></script>
    */?>

   <script type="text/javascript" src="/theme/react/lib/react/react.production.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/react-dom/react-dom.production.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/redux/redux.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/redux/react-redux.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/mdl/material.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/timeago/timeago.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/md5/md5.js"></script>
   
</head>
<body id="od-body">

<?php echo $this->render('partials/header/metaheader.phtml');?>
<?php
    if(!$this->noheader) echo $this->render('partials/header/header.phtml');
 ?>
<?php echo $this->render('partials/flashMessage.phtml'); ?>
<?php echo $this->layout()->content; ?>
<?php echo $this->render('partials/footer/template.phtml'); ?>


<div id="overlays" class="" tabindex="-1" role="dialog"><?php if (isset($this->overlay)) {
        echo $this->overlay;
    } ?></div>
<div id="modal-dialog" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-body"></div>
    <div id="error"></div>
</div>

<div id="generic-dialog" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content container" style="width: 600px;">
            <div class="modal-header row">
                <div class="modal-header-text col-md-11">Put the headline here</div>
                <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer hidden">
                <button type="button" class="btn btn-native" data-dismiss="modal" style="padding: 5px 10px;">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php echo $this->render('partials/genericModalConfirmation.phtml'); ?>

<!-- Load JS here for greater good =============================-->
<?php /*
<script src="/theme/flatui/js/lib/angular.min.js"></script>
<script src="/theme/flatui/js/lib/bootstrap-colorpicker-module.js"></script>
<script src="/theme/flatui/js/lib/jquery.rss.js"></script>
<script src="/theme/flatui/js/lib/jquery.fancytree-all.min.js"></script>
<script src="/theme/flatui/js/lib/masonry.pkgd.min.js"></script>
<script src="/theme/backend/js/jquery.cookie.js"></script>
*/
?>
<script src="/theme/flatui/js/lib/jquery.colorbox-min.js"></script>
<script src="/theme/flatui/js/lib/jquery.placeholder.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.jscrollpane.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.zclip.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.mousewheel.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.crypt.js"></script>
<script src="/theme/flatui/js/lib/bootstrap-dialog.min.js"></script>

<script src="/theme/flatui/js/lib/jquery.form.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.validate.min.js"></script>
<script src="/theme/flatui/js/lib/additional-methods.min.js"></script>
<script src="/tools/md5.js"></script>
<script src="/theme/flatui/js/lib/jquery.steps.min.js"></script>
<script src="/theme/flatui/js/lib/jquery-ui.min.js"></script>
<script src="/theme/flatui/js/lib/moment.min.js"></script>
<script type="text/javascript" src="/tools/fancybox2.1.4/jquery.fancybox.pack.js?v=2.1.4"></script>
<script src="/theme/flatui/js/script.min.js?<?= APPLICATION_VERSION ?>"></script>

<?php
echo $this->render('partials/propagateLogin.phtml');
echo $this->render('partials/propagateLogout.phtml');
?>

<?=$this->inlineScript() ?>

<?php if (APPLICATION_ENV != 'development') { ?>
    <?php
    $googleid ='UA-78422931-1';
    $domainconfig = Zend_Registry::isRegistered('store_config') ? Zend_Registry::get('store_config') : null;
    if($domainconfig)
    {
        $googleid = $domainconfig->google_id;
    }
    ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<?php echo $googleid ?>', 'auto', {'allowLinker': true});
        ga('require', 'linker');
        ga('linker:autoLink', ['<?php echo $_SERVER["SERVER_NAME"] ?>'] );
        ga('send', 'pageview');

    </script>


    <!-- Piwik -->
    <?php
    $piwikid ='1';
    if($domainconfig)
    {
        $piwikid = $domainconfig->piwik_id;
    }
    ?>
    <script type="text/javascript">
      var _paq = _paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//piwik.opendesktop.org/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', '<?= $piwikid ?>']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Piwik Code -->
<?php } ?>
<?php
 echo $this->render('partials/profiler.phtml')
?>
<?php
$session = new Zend_Session_Namespace();
$apiv4 = Zend_Registry::get("config")->settings->server->ip->api->v4;
$apiv6 = Zend_Registry::get("config")->settings->server->ip->api->v6;
if (false == $session->stat_valid) : ?>
    <script src="/tools/fpjs2/fp2.compressed.js" ></script>
    <script type="text/javascript">OcsStats.readStats('<?php echo $apiv4; ?>','<?php echo $apiv6; ?>');</script>
<?php endif; ?>
</body>
</html>
