<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->render('partials/htmlheader.phtml'); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="alternate" type="application/rss+xml" title="Latest Products" href="/content.rdf"/>

    <!-- Loading Bootstrap -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/tools/fancybox2.1.4/jquery.fancybox.css?v=2.1.4" type="text/css" media="screen" />    

    <!-- custom styles -->
    <link href="/theme/flatui/css/style.css" rel="stylesheet">
    <link href="/theme/flatui/css/stylesheet.css?<?= APPLICATION_VERSION ?>" rel="stylesheet">

    <!-- third party -->
    <link href="/theme/flatui/css/bootstrap/colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet">
    <link href="/theme/flatui/css/colorbox.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="/theme/flatui/css/ui.fancytree.min.css" rel="stylesheet" type="text/css">
    <link href="/theme/flatui/css/jquery.step.css" rel="stylesheet">
    <link rel="stylesheet" href="/theme/flatui/css/bootstrap/bootstrap-dialog.min.css" type="text/css" media="screen"/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

    <link rel="SHORTCUT ICON" href="<?=$this->template['favicon']?>"/>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
    <script src="/theme/flatui/js/lib/html5shiv.js"></script>
    <![endif]-->

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js"></script>
</head>
<body>
<?php echo $this->render('partials/header/template.phtml'); ?>
<?php echo $this->render('partials/flashMessage.phtml'); ?>
<?php echo $this->layout()->content; ?>
<?php echo $this->render('partials/footer/template.phtml'); ?>

<div id="overlays" class="" tabindex="-1" role="dialog"><?php if (isset($this->overlay)) {
        echo $this->overlay;
    } ?></div>
<div id="modal-dialog" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-body"></div>
    <div id="error"></div>
</div>

<div id="generic-dialog" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header row">
                <div class="modal-header-text col-md-11">Put the headline here</div>
                <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-native" data-dismiss="modal" style="padding: 5px 10px;">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php echo $this->render('partials/genericModalConfirmation.phtml'); ?>

<!-- Load JS here for greater good =============================-->

<script src="/theme/flatui/js/lib/jquery.crypt.js"></script>
<script src="/theme/flatui/js/lib/bootstrap-colorpicker-module.js"></script>
<script src="/theme/flatui/js/lib/bootstrap-dialog.min.js"></script>
<script src="/theme/flatui/js/lib/masonry.pkgd.min.js"></script>

<script src="//code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.colorbox-min.js"></script>
<script src="/theme/flatui/js/lib/jquery.placeholder.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.form.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.mousewheel.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.jscrollpane.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.zclip.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.fancytree-all.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.validate.min.js"></script>
<script src="/theme/flatui/js/lib/additional-methods.min.js"></script>
<script src="/theme/flatui/js/lib/jquery.steps.min.js"></script>

<script src="/tools/md5.js"></script>
<script type="text/javascript" src="/tools/fancybox2.1.4/jquery.fancybox.pack.js?v=2.1.4"></script>

<script src="/theme/flatui/js/script.js?<?= APPLICATION_VERSION ?>"></script>

<?=$this->inlineScript() ?>
<?php if (APPLICATION_ENV != 'development') { ?>
    <?php
    $googleid ='UA-78422931-1';
    $domainconfig = Zend_Registry::isRegistered('store_config') ? Zend_Registry::get('store_config') : null;
    if($domainconfig)
    {
        $googleid = $domainconfig['google_id'];
    }
    ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<?php echo $googleid ?>', 'auto', {'allowLinker': true});
        ga('require', 'linker');
        ga('linker:autoLink', ['<?php echo $_SERVER["SERVER_NAME"] ?>'] );
        ga('send', 'pageview');

    </script>
<?php } ?>
</body>
</html>