<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?><!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->render('partials/htmlheader.phtml'); ?>

    <link rel="SHORTCUT ICON" href="<?=$this->template['favicon']?>"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="alternate" type="application/rss+xml" title="Latest Products" href="/content.rdf"/>

    <!-- Loading Bootstrap -->
    <link rel="stylesheet" href="/theme/flatui/css/bootstrap/bootstrap.min.css" type="text/css"  crossorigin="anonymous">
    <link rel="stylesheet" href="/tools/fancybox2.1.4/jquery.fancybox.css?v=2.1.4" type="text/css" media="screen" />
    <link rel="stylesheet" type="text/css" href="/theme/flatui/js/lib/tooltipster/dist/css/tooltipster.bundle.min.css" />
    <link rel="stylesheet" type="text/css" href="/theme/flatui/js/lib/tooltipster/dist/css/plugins/tooltipster/sideTip/themes/tooltipster-sideTip-light.min.css" />
    <link rel="stylesheet" type="text/css" href="/theme/flatui/css/tooltipster-light-customized.css" />
    <!-- custom styles -->
    <link href="/theme/flatui/css/style.css" rel="stylesheet">
    <link href="/theme/flatui/css/stylesheet.css?<?= APPLICATION_VERSION ?>" rel="stylesheet">
    <link href="/theme/flatui/css/explore_index.css" rel="stylesheet">
    <link href="/theme/flatui/css/startpage.css" rel="stylesheet">
    <link href="/theme/react/assets/css/metaheader.css?<?= APPLICATION_VERSION ?>" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="/theme/react/assets/css/home-main-container.css"/>
    <!-- third party -->
    <link href="/theme/flatui/css/fontawsome/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous">
    <script src="/theme/flatui/js/lib/jquery-3.2.1.min.js" ></script>
    <script type="text/javascript" src="/theme/flatui/js/lib/tooltipster/dist/js/tooltipster.bundle.min.js"></script>

    <script type="text/javascript" src="/theme/react/lib/react/react.production.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/react-dom/react-dom.production.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/theme/flatui/js/lib/cookieconsent/cookieconsent.min.css" />            
    <script type="text/javascript" src="/theme/flatui/js/lib/cookieconsent/cookieconsent.min.js"></script>

    <script>
    window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#000"
        },
        "button": {
          "background": "#f1d600"
        }
      },
      "content": {
        "message": "This website uses cookies to ensure certain functionality of our web offerings.",
        "dismiss": "OK",
        "link": "Learn more",
        "href": "/terms/cookies"
      }
    })});
   </script>

</head>
<body id="od-body">
<?php echo $this->render('partials/header/metaheader.phtml');?>
<?php echo $this->render('partials/flashMessage.phtml'); ?>
<?php echo $this->layout()->content; ?>
<?php echo $this->render('partials/footer/template.phtml'); ?>

<div id="modal-dialog" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-body"></div>
    <div id="error"></div>
</div>

<script src="/theme/flatui/js/lib/bootstrap.min.js" crossorigin="anonymous"></script>
<script src="/theme/flatui/js/lib/moment.min.js"></script>
<script src="/tools/md5.js"></script>
<script src="/theme/flatui/js/script.js?<?= APPLICATION_VERSION ?>"></script>
<script type="text/javascript" src="/tools/fancybox2.1.4/jquery.fancybox.pack.js?v=2.1.4"></script>

<?php
echo $this->render('partials/propagateLogin.phtml');
echo $this->render('partials/propagateLogout.phtml');
?>

<?=$this->inlineScript() ?>

<?php if (APPLICATION_ENV != 'development') { ?>
    <?php
    $googleid ='UA-78422931-1';
    $domainconfig = Zend_Registry::isRegistered('store_config') ? Zend_Registry::get('store_config') : null;
    if($domainconfig)
    {
        $googleid = $domainconfig->google_id;
    }
    ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<?php echo $googleid ?>', 'auto', {'allowLinker': true});
        ga('require', 'linker');
        ga('linker:autoLink', ['<?php echo $_SERVER["SERVER_NAME"] ?>'] );
        ga('send', 'pageview');

    </script>


    <!-- Piwik -->
    <?php
    $piwikid ='1';
    if($domainconfig)
    {
        $piwikid = $domainconfig->piwik_id;
    }
    ?>
    <script type="text/javascript">
      var _paq = _paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//piwik.opendesktop.org/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', '<?= $piwikid ?>']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Piwik Code -->
<?php } ?>
<?php
 echo $this->render('partials/profiler.phtml')
?>

<?php
$session = new Zend_Session_Namespace();
$fp = $session->client_fp;
if (empty($fp)) : ?>
    <script src="/tools/fpjs2/fp2.js" ></script>
    <script type="text/javascript">
        var options={};window.requestIdleCallback?requestIdleCallback(function(){Fingerprint2.get(options,function(a){var b=a.map(function(a){return a.value}),c=Fingerprint2.x64hash128(b.join(""),31);$.post("/l/fp",{fp:c})})}):setTimeout(function(){Fingerprint2.get(options,function(a){var b=a.map(function(a){return a.value}),c=Fingerprint2.x64hash128(b.join(""),31);$.post("/l/fp",{fp:c})})},500);
    </script>
<?php endif; ?>
</body>
</html>
