<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <?= $this->render('partials/htmlheader.phtml'); ?>
</head>
<body id="od-body">
<?php echo $this->render('partials/header/template.phtml'); ?>

<div id="main">
    <?= $this->layout()->content; ?>
</div>

<?php echo $this->render('partials/footer/template.phtml'); ?>

<?php if (APPLICATION_ENV != 'development') { ?>
    <?php
    $googleid ='UA-78422931-1';
    $domainconfig = Zend_Registry::isRegistered('store_config') ? Zend_Registry::get('store_config') : null;
    if($domainconfig)
    {
        $googleid = $domainconfig->google_id;
    }
    ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<?php echo $googleid ?>', 'auto');
        ga('send', 'pageview');

    </script>

    <!-- Piwik -->
    <?php
    $piwikid ='1';
    if($domainconfig)
    {
        $piwikid = $domainconfig->piwik_id;
    }
    ?>
    <script type="text/javascript">
      var _paq = _paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//piwik.opendesktop.org/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', '<?= $piwikid ?>']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Piwik Code -->
<?php } ?>

<?php
$session = new Zend_Session_Namespace();
$apiv4 = Zend_Registry::get("config")->settings->server->ip->api->v4;
$apiv6 = Zend_Registry::get("config")->settings->server->ip->api->v6;
if (false == $session->stat_valid) : ?>
    <script src="/theme/flatui/js/script.js?<?= APPLICATION_VERSION ?>"></script>
    <script src="/tools/fpjs2/fp2.compressed.js" ></script>
    <script type="text/javascript">OcsStats.readStats('<?php echo $apiv4; ?>','<?php echo $apiv6; ?>');</script>
<?php endif; ?>
</body>
</html>
