<main id="product-page-content">
    <div id="product-page-view" class="disply-flex">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 center-block">

<?php /*            <h2><?= $this->message ?></h2> */ ?>
            <div class="cover"><h1>Webservice currently unavailable <small>Error 500</small></h1>
                <p class="lead">An unexpected condition was encountered.<br/>Our service team has been dispatched to bring it back
                    online.</p></div>

            <?php if (!empty($this->display_exceptions)) : ?>
                <?php if (isset($this->exception)
                    && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
                    <hr/>

                    <h2>Additional information:</h2>
                    <h3><?= get_class($this->exception) ?></h3>
                    <dl>
                        <dt>File:</dt>
                        <dd>
                            <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
                        </dd>
                        <dt>Message:</dt>
                        <dd>
                            <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
                        </dd>
                        <dt>Stack trace:</dt>
                        <dd>
                            <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                        </dd>
                    </dl>

                    <?php if ($ex = $this->exception->getPrevious()) : ?>
                        <hr/>

                        <h2>Previous exceptions:</h2>
                        <ul class="list-unstyled">
                            <?php $icount = 0 ?>
                            <?php while ($ex) : ?>
                                <li>
                                    <h3><?= get_class($ex) ?></h3>
                                    <dl>
                                        <dt>File:</dt>
                                        <dd>
                                            <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
                                        </dd>
                                        <dt>Message:</dt>
                                        <dd>
                                            <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
                                        </dd>
                                        <dt>Stack trace:</dt>
                                        <dd>
                                            <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
                                        </dd>
                                    </dl>
                                </li>
                                <?php
                                $ex = $ex->getPrevious();
                                if (++$icount >= 50) {
                                    echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
                                    break;
                                }
                                ?>
                            <?php endwhile ?>
                        </ul>
                    <?php endif ?>
                <?php else : ?>
                    <h3>No Exception available</h3>
                <?php endif ?>
            <?php endif ?>

        </div>
    </div>
</main>