<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

if ($this->noPopup == true) {
    $cssPopup = '';
} else {
    $cssPopup = 'popup';
} ?>
<div class="<?= $cssPopup ?>">
    <button type="button" class="close popup-close" data-dismiss="modal" aria-hidden="true">×</button>
    <div class="container page-container login-container">
        <div class="login-popup row-fluid">
            <div class="login-popup-form">
                <h3 class="report-heading lightblue"><?= $this->translate('Log in to your account') ?></h3>
                <hr>
                <div id="error" class="center text-error">
                    <?php if ($this->error && isset($this->errorText)): ?>
                        <p class="errors errorText">
                            <?= $this->translate($this->errorText) ?>
                        </p>
                    <?php endif; ?>
                </div>
                <div class="login-form-container">
                    <form class="standard-form form-wrapper-01"
                          action="<?= $this->form->getAction(); ?>"
                          method="<?= $this->form->getMethod(); ?>">
                        <?= $this->form->redirect ?>
                        <?= $this->form->dologin ?>
                        <?= $this->form->mail ?>
                        <?= $this->form->password ?>
                        <?= $this->form->remember_me ?>
                        <?= $this->form->login ?>
                    </form>
                    <p class="login-form-links"><a class="scroll"
                                                   href="/register/"><?= $this->translate('Register now') ?></a>&nbsp;&nbsp;|&nbsp;&nbsp;<a
                            class="scroll partial"
                            data-target="#modal-dialog"
                            href="/index/forget/"><?= $this->translate('Forgot password') . '?' ?></a></p>
                </div>
                <hr/>
                <div class="social">
                </div>
            </div>
        </div>
    </div>
</div>