<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$users = $this->newUsers($limit = 216,'created_at','DESC');
$buildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$url_param_redirect = isset($this->redirect) ? 'redirect/'.$this->redirect : null;
$this->headMeta()->setName('robots', 'noindex, nofollow');
$imageHelper = new Default_View_Helper_Image();

  $regs="";
  $ip = $_SERVER[REMOTE_ADDR];

?>


<script language="javascript">
 function test(data) {
     console.log('ip: ' + data);
     console.log('ip: ' + data['address']);
 }
 
</script>
<script src="https://ipv6.test-ipv6.ams.vr.org/ip/?callback=test" type="text/javascript"></script>


  <link href="/theme/flatui/css/bootstrap/social-buttons.css" rel="stylesheet" type="text/css">
  <style>
    .btn-github {
      border: 1px solid;
      border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
    }
  </style>
	<!-- new code -->
    <main id="reg-page">

        <section class="wrapper" id="register-wrap">
            <div id="register" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
                <div id="register-box" class="col-lg-8 col-md-8 col-sm-8 col-xs-8">

                    <?= $this->render('authorization/partials/loginForm.phtml') ?>

                </div>
                <!-- END #register-box -->
                <div id="social-register" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <h3></h3>

                    <div id="social-login-elements">
                        <div class="bottom margin-top-15">
                            <a href="/login/ocs/<?= $url_param_redirect ?>" class="btn btn-block btn-social btn-github" rel="nofollow">
                                <span class="glyphicon glyphicon-log-in"></span>
                                <span class="small" style="padding-left:2px;">openDesktop ID</span>
                            </a>
                        </div>

                        <div class="bottom margin-top-15">
                            <div id="show-login-description" class="small light lightgrey">New user?</div>
                            <div class="login2">
                                <a href="/register/" id="show-login-form" class="btn btn-native btn-min-width" rel="nofollow">
                                    <i class="icon-white icon-lock"></i>
                                    Register
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
        </section>

        <section id="thumbs">
            <?php foreach ($users as $key => $user) { ?>
                <div class="thumb">
                    <a href="<?php echo $buildMemberUrl->buildMemberUrl($user['username']); ?>"
                       title="<?= $user['profile_image_url'] ?>">
                        <span></span>
                        <img src="<?php echo $imageHelper->Image($user['profile_image_url'], array('width' => 110, 'height' => 110, 'crop' => 2)); ?>"/>
                    </a>
                </div>
            <?php } ?>
        </section>

    </main>
    <!-- /new code -->
<script>
    var PartialJsonLogin = (function () {
        return {
            setup: function () {
                $('body').on("submit", 'form.partialjson', function (event) {
                    event.preventDefault();
                    event.stopImmediatePropagation();

                    var target = $(this).attr("data-target");
                    var trigger = $(this).attr("data-trigger");
                    var loadState = $(this).attr('data-load-state');

                    $(target).find(loadState).prop('disabled', true);
                    $(target).find(loadState).find('i').removeClass('hidden');

                    jQuery.ajax({
                        data: $(this).serialize(),
                        url: this.action,
                        type: this.method,
                        dataType: "json",
                        error: function () {
                            $(target).empty().html("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
                            $(target).find(loadState).prop('disabled', false);
                            $(target).find(loadState).find('i').addClass('hidden');
                        },
                        success: function (data, textStatus) {
                            $(target).find(loadState).prop('disabled', false);
                            $(target).find(loadState).find('i').addClass('hidden');

                            if (data.redirect) {
                                // data.redirect contains the string URL to redirect to
                                window.location.href = data.redirect;
                                return;
                            }
                            if (target) {
                                // data.message contains the HTML for the replacement form
                                $(target).empty().html(data.message);
                            }
                            if (trigger) {
                                $(target).find(trigger).trigger('click');
                            }
                        }
                    });

                    return false;
                });
            }
        }
    })();
    
</script>


<?php
$session = new Zend_Session_Namespace();
$fp = $session->client_fp;
if (empty($fp)) : ?>
    <script src="/tools/fpjs2/fp2.js" ></script>
    <script type="text/javascript">
        var options={};window.requestIdleCallback?requestIdleCallback(function(){Fingerprint2.get(options,function(a){var b=a.map(function(a){return a.value}),c=Fingerprint2.x64hash128(b.join(""),31);$.post("/l/fp",{fp:c})})}):setTimeout(function(){Fingerprint2.get(options,function(a){var b=a.map(function(a){return a.value}),c=Fingerprint2.x64hash128(b.join(""),31);$.post("/l/fp",{fp:c})})},500);
    </script>
<?php endif; ?>


<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
            PartialJsonLogin.setup();
        });
    ');
