<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperNewUsers = new Default_View_Helper_NewUsers();
$users = $helperNewUsers->newUsers($limit = 216,'created_at','DESC');
$buildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$this->headMeta()->setName('robots', 'noindex, nofollow');
?>

<script language="javascript">
    
function test(data) {
    $(document).ready(function(){
        $('#ipv4').val(data['ip']);
    });

}

function test6(data) {
    $(document).ready(function(){
        $('#ipv6').val(data['ip']);
    });

}
 
</script>

<script type="application/javascript" src="https://ipify6.pling.com?format=jsonp&callback=test6"></script>
<script type="application/javascript" src="https://ipify4.pling.com?format=jsonp&callback=test"></script>


	<!-- new code -->
    <main id="reg-page">

        <section class="wrapper" id="register-wrap">
            <div id="register" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
                <div id="register-box" class="col-lg-8 col-md-8 col-sm-8 col-xs-8">

                    <?= $this->render('authorization/partials/registerForm.phtml') ?>

                </div>
                <!-- END #register-box -->
                <div id="social-register" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <h3></h3>

                    <div id="social-login-elements">
                        <?php /*
                        <div class="register-facebook">
                            <p class="small center light greylight">Register with</p>
                            <a  href="/login/github/" class="btn btn-block btn-social btn-github" rel="nofollow">
                                <span class="fa fa-github"></span>
                                <span class="small">Github</span>
                            </a>
                        </div>
                        */ ?>
                        <div class="bottom margin-top-15">
                            <div id="show-login-description" class="small light lightgrey">Already have an account?</div>
                            <div class="login2">
                                <a href="/login/" id="show-login-form" class="btn btn-native btn-min-width" rel="nofollow">
                                    <i class="icon-white icon-lock"></i>
                                    Login
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="thumbs">

        	<?php foreach ($users as $key => $user) { ?>

                <div class="thumb">
                    <a href="<?php echo $buildMemberUrl->buildMemberUrl($user['username']); ?>">
                        <span></span>
                        <img src="<?php echo $helperImage->Image($user['profile_image_url'],array('width' => 110, 'height' => 110, 'crop' => 2)); ?>"/>
                    </a>
                </div>

            <?php } ?>
        

        </section>

    </main>
    <!-- /new code -->

<script>
$('document').ready(function(){

    var ValidateAjax = {
        isClean: {},
        initialize: function (formid, endpoint) {
            end_url = endpoint;
            form_id = '#'+formid;

            $(form_id +' input[id=username],input[id=mail]').
            blur(function () {
                var formElementID = $(this).attr('id');
                var formElementValue = $(this).val();
                ValidateAjax.doValidate(formElementID, formElementValue);
                return false;
            });
            $(form_id).on('submit', function(e){
                var target = $(this).attr("data-target");
                var loadState = $(this).attr('data-load-state');

                $(target).find(loadState).prop('disabled', true);
                $(target).find(loadState).find('i').removeClass('hidden');

                var validateValues = ValidateAjax.isClean;
                for (var k in validateValues){
                    if (validateValues.hasOwnProperty(k)) {
                        if (!validateValues[k]) {
                            e.preventDefault();
                            return false;
                        }
                    }
                }
                return true;
            });
        },

        doValidate: function (id, value) {
            $.fn.capitalize = function () {
                $.each(this, function () {
                    var caps = this.value;
                    caps = caps.charAt(0).toUpperCase() + caps.slice(1);
                    this.value = caps;
                });
                return this;
            };
            
            var url = end_url;
            var data = {'name' : id, 'value': value};
            $.post(url, data, function (response) {
                $('#'+id).parent().find('.form-control-feedback').remove();
                $('#'+id).parent().removeClass('has-error');
                
                if (!response['status']) {
                    ValidateAjax.isClean[id] = false;
                    $('#login').attr("disabled","disabled");
                    
                    $('#'+id).parent().addClass('has-error');
                    if (response[id]) {
                        $('#'+id).parent().append('<i class="glyphicon glyphicon-remove form-control-feedback"></i>');
                        $('#'+id).parent().find('.errors').remove();
                        
                        $msgArray = response[id];
                        $msgString = "";
                        $msgString += '<ul class="errors" style="text-align: left;">';
                        if(id == 'mail') {
                            $msgString += '<li class="errors">Email is invalid or already taken</li>';
                        } else {
                            $.each($msgArray, function( key, value ) {
                                if(key == 'regexNotMatch') {
                                    $msgString += '<li class="errors">Username may only contain lower case alphanumeric characters or single hyphens, and cannot begin or end with a hyphen</li>';
                                } else {
                                    $msgString += '<li class="errors">' + value + '</li>';
                                }
                            });
                            
                        }
                        $msgString += '</ul>';
                            $('#'+id).parent().append($msgString);
                        if($msgString == '<ul class="errors" style="text-align: left;"></ul>') {
                            $('#'+id).parent().append('<ul class="errors" style="text-align: left;"><li class="errors">This '+id+' is already taken</li></ul>');
                        }
                    }
                } else {
                    ValidateAjax.isClean[id] = true;
                    $('#login').removeAttr("disabled");
                    $('#'+id).parent().addClass('has-success');
                    $('#'+id).parent().append('<i class="glyphicon glyphicon-ok form-control-feedback"></i>');
                    $('#'+id).parent().find('.errors').remove();
                    $('#'+id).parent().append('<ul class="errors" style="visibility: hidden;"><li></li></ul>');
                }
            },'json');

        },
        getHTML: function (errArray) {
            var o = '<ul class="errors">';
            $.each(errArray,function(key,value){
                o += '<li>'+ value+'</li>';
            });
            o+='</ul>';

            return o;
        }
    };

    ValidateAjax.initialize('<?= $this->formRegister->getAttrib('id') ?>', '/register/validate');
});
</script>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
            // PartialJson.setup();
        });
    ');
