<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<link rel="stylesheet" href="/tools/elfinder/css/elfinder.min.css" type="text/css" media="screen" charset="utf-8"/>
<link rel="stylesheet" href="/tools/elfinder/css/theme.css" type="text/css" media="screen" charset="utf-8"/>
<script src="/tools/elfinder/js/elfinder.min.js" type="text/javascript" charset="utf-8"></script>

<div id="fileBrowser"></div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        $('#fileBrowser').elfinder({
            //lang: 'de',             // language (OPTIONAL)
            url: '/tools/elfinder/php/connector.php'  // connector URL (REQUIRED)
        });
    });
</script>