<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$modelCategory = new Default_Model_ProjectCategory();
$this->categories = $modelCategory->fetchTreeForView(25);
$jsonTree = json_encode($this->categories);
?>
<?= $this->partial('yui.phtml'); ?>
<link href="/theme/flatui/js/lib/jquerymonthpicker/MonthPicker.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="/theme/flatui/js/lib/d3pie.min.js"></script>

<script type="text/javascript" src="/theme/react/lib/react/react.js"></script>
<script type="text/javascript" src="/theme/react/lib/react-dom/react-dom.js"></script>
<script type="text/javascript" src="/theme/react/lib/redux/redux.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/redux/react-redux.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/mdl/material.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/timeago/timeago.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/md5/md5.js"></script>
<script src="/theme/flatui/js/lib/jquerymonthpicker/MonthPicker.js"></script>

<div class="pling-nav-tabs">
    <ul class="nav nav-tabs ">
        <li class="active"><a class="newuserprojectTab" href="#d3-line" data-toggle="tab">New Members & Projects </a></li>
        <li><a class="downloadsDomainTab" href="#downloadsDomainTab" data-toggle="tab">Downloads Domain</a></li>
        <li><a class="downloadsdailyTab" href="#downloadsdailyTab" data-toggle="tab">Downloads&Payouts daily</a></li>
        <!-- <li ><a class="downloadsundpayoutsdailyTab" href="#downloadsundpayoutsdailyTab" data-toggle="tab">Downloads vs Payouts daily</a></li> -->

        <li><a class="topDownloadsPerDayTab" href="#topDownloadsPerDayTab" data-toggle="tab">Product/Day</a></li>
        <li><a class="topDownloadsPerMonthTab" href="#topDownloadsPerMonthTab" data-toggle="tab">Product/Month</a></li>
        <li><a class="payoutTab" href="#payoutTab" data-toggle="tab">Payout Member</a></li>
        <li><a class="payoutNewcomerTab" href="#payoutNewcomerTab" data-toggle="tab">Payout Newcomer</a></li>
        <li><a class="payoutNewloserTab" href="#payoutNewloserTab" data-toggle="tab">Payout Newloser</a></li>
        <li><a class="payoutMonthDiffTab" href="#payoutMonthDiffTab" data-toggle="tab">Payout Month Diff</a></li>
        <li><a class="payoutCategoryMonthlyTab" href="#payoutCategoryMonthlyTab" data-toggle="tab">Payout Categories</a></li>
        <li><a class="payoutCategoryTab" href="#payoutCategoryTab" data-toggle="tab">Payout Category monthly</a></li>


    </ul>
    <div class="tab-content row">
        <div id="d3-line" class="tab-pane active ">
            <div style="width: 100%; padding: 20px">

                <div id='d3linelableinline' class="d3linepath"></div>

                

            </div>
        </div>

        <div id="downloadsdailyTab" class="tab-pane">
            <span style="float: left">#number of months back</span>
            <select id="numofmonthback" style="float: left">
                <option>2</option>
                <option selected>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
                <option>11</option>
                <option>12</option>
            </select>
            <div id="downloadsdailyTabContainer" class="d3linepath"></div>
        </div>

        <!--
           <div id="downloadsundpayoutsdailyTab" class="tab-pane ">
                <div id="downloadsundpayoutsdailyTabContainer"></div>
          </div>
        -->

        <div id="downloadsDomainTab" class="tab-pane ">
            <div style="display: block; clear: both">
                Begin:<input name="filterDownloadsDomainDateBegin" id="filterDownloadsDomainDateBegin" value="<?php echo date("Y-m-j") ?>" />
                End:<input name="filterDownloadsDomainDateEnd" id="filterDownloadsDomainDateEnd" value="<?php echo date("Y-m-j") ?>" />
                <button class="filterDownloadsDomainDate">go!</button>
            </div>
            <div id="downloadsDomainTabContainer" style="display: block;clear: left"></div>
        </div>

        <div id="topDownloadsPerDayTab" class="tab-pane ">
            <div style="display: block; clear: both">
                <input name="filterTopDownloadsDate" id="filterTopDownloadsDate" value="<?php echo date("Y-m-j") ?>"/>
                <button class="filterTopDownloadsDate">go!</button>
                <button class="filterTopDownloadsDateClear">clear!</button>

            </div>
            <div id="topDownloadsPerDayTabContainer" style="display: block;clear: left"></div>
        </div> 

        <div id="topDownloadsPerMonthTab" class="tab-pane ">
            <div style="display: block; clear: both" class="filter">
                <input name="filterTopDownloadsMonth" id="filterTopDownloadsMonth" value="<?php echo date("Ym") ?>" />                
                <script type="text/javascript">
                    $('#filterTopDownloadsMonth').MonthPicker({ StartYear: 2018, ShowIcon: true,MonthFormat:'yymm',OnAfterChooseMonth: function() { 
                                window.selectedMonth = $(this).val();
                        }  });
                </script>                                
            </div>
            <div id="topDownloadsPerMonthTabContainer" style="display: block;clear: left"></div>
        </div> 

        <div id="payoutTab" class="tab-pane ">

            <div id="payoutyear" style="display: block; float: left; padding-right: 20px" class="d3linepath"></div>
            <div id="pie" style="clear:left;padding:50px; display:block;  "></div>
            <div style="display: block; float: left; clear:left" id="detailContainer"></div>

        </div>

        <div id="payoutNewcomerTab" class="tab-pane">
            <div id="payoutNewcomerTabContainer"></div>
        </div>

        <div id="payoutNewloserTab" class="tab-pane">
            <div id="payoutNewloserTabContainer"></div>
        </div>

        <div id="payoutMonthDiffTab" class="tab-pane">
            <div id="payoutMonthDiffTabContainer"></div>
        </div>

        <div id="payoutCategoryMonthlyTab" class="tab-pane">
            <div id="pieCategoryMonthly" style="padding:50px; "></div>
        </div>

          <div id="payoutCategoryTab" class="tab-pane">
            <div style="display: block; clear: both" class="filter">
                <button id="clearChartPanel">clear</button>
            </div>
               
            <div id="payoutCategoryLineChart"  style="max-width: 1000px; height: 100%; display: block; float: right; ">
                    
            </div>
        </div>

    </div>
</div> <!--end of tab-->

<div id="dataFilter" style="display: none">
 <div id="category-tree-container"></div>
 </div>

<script type="application/javascript">
  var catTree = <?= $jsonTree ?>;  
  var backendView = true;
</script>
<script type="application/javascript" src="/theme/react/cat-tree.js"></script>

<script type="text/javascript">
var indicator = '<span class="glyphicon glyphicon-refresh spinning" style="position: relative; left: 0;top: 0px;"></span>';
    function createMonthFilter(selectid, triggerEvent) {
        let html = '<select id="' + selectid + '" style="float: left;">';
        for (i = 1; i < 10; i++) {
            let oneMonthsAgo = moment().subtract(i, 'months');
            if (i == 1) {
                html = html + '<option selected>' + oneMonthsAgo.format('YYYYMM') + '</option>';
            } else {
                html = html + '<option>' + oneMonthsAgo.format('YYYYMM') + '</option>';
            }
        }
        html = html + '</select>';
        return html;
    }

    function createMonthFilterWithCurrent(selectid, triggerEvent) {
        let html = '<select id="' + selectid + '" style="float: left;">';
        for (i = 0; i < 10; i++) {
            let oneMonthsAgo = moment().subtract(i, 'months');
            if (i == 0) {
                html = html + '<option selected>' + oneMonthsAgo.format('YYYYMM') + '</option>';
            } else {
                html = html + '<option>' + oneMonthsAgo.format('YYYYMM') + '</option>';
            }
        }
        html = html + '</select>';
        return html;
    }

    $.ajaxSetup({
        // Disable caching of AJAX responses
        // Used when debugging
        cache: false
    });

    $.getScript("/theme/flatui/js/stati/newUserProject.js");
    $(".newuserprojectTab").click(function () {
        $.getScript("/theme/flatui/js/stati/newUserProject.js");
    });


    $(".downloadsdailyTab").click(function () {
        $('#downloadsdailyTabContainer').empty();
        $.getScript("/theme/flatui/js/stati/downloadsdaily.js");
    });
    $('#numofmonthback').change(function () {
        $.getScript("/theme/flatui/js/stati/downloadsdaily.js");
    });


    $('button.filterDownloadsDomainDate').click(function () {
        loadDownloadsDomain();
    });

    function loadDownloadsDomain() {
        $('#downloadsDomainTabContainer').empty();
        let dateBegin = $("#filterDownloadsDomainDateBegin").val();
        let dateEnd = $("#filterDownloadsDomainDateEnd").val();
        $.getJSON("/backend/index/getdownloadsdomain?dateBegin=" + dateBegin + "&dateEnd=" + dateEnd, function (response) {
            let data = response.results;
            let table = "<table class='tablestati'><thead><tr><td class='number'>CNT</td><td>Domain</td><td class='number'>IS_OWN?</td></tr></thead>";
            $.each(data, function (index, value) {
                table = table + '<tr>'
                    + '<td class="number">' + value.cnt + '</td>'
                    + '<td >' + value.referer_domain + '</td>'
                    + '<td class="number">' + value.is_from_own_domain + '</td>'
                    + '</tr>';
            });
            table = table + "</table>";
            $('#downloadsDomainTabContainer').append(table);
        });
    }

    $(".downloadsDomainTab").click(function () {
        loadDownloadsDomain();
    });


    // topdownloadsperdate

    $('button.filterTopDownloadsDate').click(function () {
        loadTopdownloadsperday();
    });
    $('button.filterTopDownloadsDateClear').click(function () {
        $('#topDownloadsPerDayTabContainer').empty();
    });

    function loadTopdownloadsperday() {
        let date = $("#filterTopDownloadsDate").val();
        $.getJSON("/backend/index/gettopdownloadsperdate?date=" + date, function (response) {
            let data = response.results;
            let table = "<table class='tablestati'><thead><tr><td colspan='7'>" + date + "</td></tr><tr><td>ProjectID</td><td>Username</td><td class='number'>CNT</td><td>Title</td><td>Category</td><td>created_at</td></tr></thead>";
            $.each(data, function (index, value) {
                table = table + '<tr>'
                    + '<td><a target="_blank" href="https://opendesktop.org/p/' + value.project_id + '">'
                    + value.project_id + '</a></td>'
                    + '<td>' + value.username + '</td>'
                    + '<td class="number">' + value.cnt + '</td>'
                    + '<td>' + value.ptitle + '</td>'
                    + '<td>' + value.ctitle + '</td>'
                    + '<td>' + value.pcreated_at + '</td>'
                    + '</tr>';
            });
            table = table + "</table>";
            $('#topDownloadsPerDayTabContainer').append(table);
        });
    } 

    function loadTopdownloadspermonth() {
        
        console.log(window.selectedMonth);
        
        $('#topDownloadsPerMonthTabContainer').empty();
        $('#topDownloadsPerMonthTabContainer').append(indicator);
        $.getJSON("/backend/index/gettopdownloadspermonth?month=" + window.selectedMonth+'&catid='+window.selectedCatid, function (
            response) {
            let data = response.results;
            let table = "<table class='tablestati'><thead><tr><td colspan='7'>" + window.selectedMonth+'_'+window.selectedCatTitle + "</td></tr><tr><td>ProjectID</td><td>Username</td><td class='number'>CNT</td><td>Title</td><td>Category</td><td>created_at</td></tr></thead>";
            $.each(data, function (index, value) {
                table = table + '<tr>'
                    + '<td><a target="_blank" href="https://opendesktop.org/p/' + value.project_id + '">'
                    + value.project_id + '</a></td>'
                    + '<td>' + value.username + '</td>'
                    + '<td class="number">' + value.cnt + '</td>'
                    + '<td>' + value.ptitle + '</td>'
                    + '<td>' + value.ctitle + '</td>'
                    + '<td>' + value.pcreated_at + '</td>'
                    + '</tr>';
            });
            table = table + "</table>";
            $('#topDownloadsPerMonthTabContainer').empty();
            $('#topDownloadsPerMonthTabContainer').append(table);
        });
    } 

    $(".topDownloadsPerDayTab").click(function () {
        $('#topDownloadsPerDayTabContainer').empty();
        loadTopdownloadsperday();
    });

    $('#payoutTab').prepend(createMonthFilter('selectmonth'));
    $('#selectmonth').change(function () {
        $.getScript("/theme/flatui/js/stati/memberPayout.js");
    });
    $(".payoutTab").click(function () {
        $('#detailContainer').empty();
        $.getScript("/theme/flatui/js/stati/payoutyear.js");
        $.getScript("/theme/flatui/js/stati/memberPayout.js");
    });

    // payout Category Monthly tab begin
    $('#payoutCategoryMonthlyTab').prepend(createMonthFilter('selectmonthCategoryMonthly'));
    $(".payoutCategoryMonthlyTab").click(function () {
        $.getScript("/theme/flatui/js/stati/payoutCategoryMonthly.js");
    });
    $('#selectmonthCategoryMonthly').change(function () {
        $('.payoutCategoryMonthlyTab').trigger('click');
    });
    // payout Category Monthly tab end


    $('#payoutNewcomerTab').prepend(createMonthFilter('selectmonthNewcomer'));
    $('#selectmonthNewcomer').change(function () {
        $(".payoutNewcomerTab").trigger('click');
    });
    $(".payoutNewcomerTab").click(function () {
        $('#payoutNewcomerTabContainer').empty();
        let yyyymm = $("#selectmonthNewcomer option:selected").text();
        $.getJSON("/backend/index/newcomer?yyyymm=" + yyyymm, function (response) {
            let data = response.results;
            let table = "<table class='tablestati'>";
            $.each(data, function (index, value) {
                table = table + '<tr><td><a target="_blank" href="https://opendesktop.org/member/' + value.member_id + '">' + value.member_id + '</a></td><td>' + value.username + '</td><td>' + value.paypal_mail + '</td><td class="number">' + value.amount + '</td></tr>';
            });
            table = table + "</table>";
            $('#payoutNewcomerTabContainer').html(table);
        });
    });

    $('#payoutNewloserTab').prepend(createMonthFilter('selectmonthNewloser'));
    $('#selectmonthNewloser').change(function () {
        $(".payoutNewloserTab").trigger('click');
    });
    $(".payoutNewloserTab").click(function () {
        $('#payoutNewloserTabContainer').empty();
        let yyyymm = $("#selectmonthNewloser option:selected").text();
        $.getJSON("/backend/index/newloser?yyyymm=" + yyyymm, function (response) {
            let data = response.results;
            let table = "<table class='tablestati'>";
            $.each(data, function (index, value) {
                table = table + '<tr><td><a target="_blank" href="https://opendesktop.org/member/' + value.member_id + '">' + value.member_id + '</a></td><td>' + value.username + '</td><td>' + value.paypal_mail + '</td><td class="number">' + value.amount + '</td></tr>';
            });
            table = table + "</table>";
            $('#payoutNewloserTabContainer').html(table);
        });
    });


    $('#payoutMonthDiffTab').prepend(createMonthFilter('selectmonthMonthDiff'));
    $('#selectmonthMonthDiff').change(function () {
        $(".payoutMonthDiffTab").trigger('click');
    });
    $(".payoutMonthDiffTab").click(function () {
        $('#payoutMonthDiffTabContainer').empty();
        let yyyymm = $("#selectmonthMonthDiff option:selected").text();
        $.getJSON("/backend/index/monthdiff?yyyymm=" + yyyymm, function (response) {
            let data = response.results;
            let table = "<table class='tablestati'>";
            table = table + '<thead><tr><td>Member</td><td>Username</td><td class="number">Diff</td><td>month</td><td class="number">amount</td><td>last month</td><td  class="number">amount </td></tr></thead>';
            $.each(data, function (index, value) {
                table = table + '<tr><td><a target="_blank" href="https://opendesktop.org/member/' + value.member_id + '">' + value.member_id + '</a></td><td>' + value.username + '</td><td class="number">' + value.am_diff + '</td>'
                    + '<td>' + value.ym_akt + '</td><td class="number">' + value.am_akt + '</td>'
                    + '<td>' + value.ym_let + '</td><td class="number">' + value.am_let + '</td>'
                ;
            });
            table = table + "</table>";
            $('#payoutMonthDiffTabContainer').html(table);
        });
    });
</script>


<script type="text/javascript">
    var parseTime = d3.timeParse("%Y%m"); 
    window.selectedCatid = 0;
    window.selectedTab = '';
    window.selectedMonth;

    $(document).ready(function () { 

            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                var target = $(e.target).attr("href");
                console.log(target);
                if('#topDownloadsPerMonthTab' == target || '#payoutCategoryTab' ==target)
                {
                    var cattree = $('#category-tree-container');
                    $(target).find('.filter').append(cattree);                   
                } 
                window.selectedTab = target;
                window.selectedCatid = 0;
                window.selectedCatTitle = '';
                
            });

            $('body').on('click', '#category-tree a', function (event) {
                event.preventDefault();
                event.stopPropagation();            
                var start = this.href.indexOf("cat");
                var catid;
                var title;
                if(start<0) {
                    catid = 0;
                    title = 'All';
                }else
                {
                    catid = this.href.substring(start+4, (this.href.length-1));  
                    title = $(this).text();
                }
                window.selectedCatid = catid;
                window.selectedCatTitle = title;
                if(window.selectedTab=='#payoutCategoryTab')
                {
                    if($('#payoutCategoryLineChart').find('#payoutCategoryLineChart'+catid).length==0)
                    {
                        $('#payoutCategoryLineChart').append('<div class="chart-wrapper" id="payoutCategoryLineChart'+catid+'"> loading ... </div>');
                        $.getScript("/theme/flatui/js/stati/payoutCategory.js");
                    }
                }
                if(window.selectedTab=='#topDownloadsPerMonthTab')
                {                    
                    window.selectedMonth = $('#filterTopDownloadsMonth').val();
                    loadTopdownloadspermonth();
                }
            });

            $('#clearChartPanel').on('click',function(){
                 $("#payoutCategoryLineChart").empty();
            });


           

    });
   



</script>


<script src="/theme/flatui/js/lib/multiline.js"></script>


