<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<!DOCTYPE html>
<html>
<head>
    <title>Download/Install</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link href="tools/spectre/spectre.css" rel="stylesheet" type="text/css"/>
    <link href="tools/spectre/spectre-icons.css" rel="stylesheet" type="text/css"/>
    <link href="tools/spectre/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <style>
        
        
        
    </style>
    
</head>
<body>
    <main id="ads-page">
        
        <div class="columns" style="background-color: #f8f9fa;">
            <div class="col-8 col-md-12 col-xs-12 col-sm-12 column">
                <div class="toast toast-success" style="margin-bottom: 10px;">
                    <?php if($this->link_type == 'download') { ?>
                    Prepare download successful. Please click the "Download" button to download.
                    <?php } else { ?>
                    Prepare download successful. Please click the "Install" button to download.
                    <?php } ?>
                    
                </div>
                <section class="empty">
                    <div class="empty-icon">
                        <i class="icon icon-link"></i>
                    </div>
                    <h1 class="empty-title"><?= $this->project_title ?></h1>
                    <div class="empty-action">
                        
                        <?php
                        if ($_SERVER['REQUEST_METHOD'] == 'POST') { 
                            //echo '<a href="'.$this->url.'">Please click here</a>';
                            echo '<script>top.location.href = "'.$this->url.'"; parent.jQuery.fancybox.close();</script>';

                        } else {
                        ?>
                        <form id="Form1" name="Form1" action="" method="POST">    

                         <?php if($this->link_type == 'download') { ?>
                         <button type="submit" value="Continue Download" class="btn btn-success btn-lg"><i class="icon icon-time"></i> Download (<?= $this->file_size_human ?>)</button>
                         <?php } else { ?>
                         <button type="submit" value="Continue Installation" class="btn btn-success btn-lg"><i class="icon icon-time"></i> Installation</button>
                         <br><br><p>*Needs <a href="https://www.opendesktop.org/p/1136805/" target="_NEW">ocs-url</a> or <a href="https://www.opendesktop.org/p/1175480/" target="_NEW">ocs-store</a> to install things</p>
                         <?php } ?>
                         
                         <?php
                        }
                         ?>

                        </form>   
                        
                        
                    </div>
                    <center style="margin: 10px 0 0;">
                        <!--
                        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="MYAVVME9CMX28">
                        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" name="submit" alt="PayPal - The safer, easier way to pay online!" border="0">
                        <img alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1" border="0">
                        </form>
                        -->
                        <p style="font-size: 12px; line-height: 18px;">
                            <?php 
                                    $identity = Zend_Auth::getInstance()->getIdentity();
                                    if(null == $identity || (null != $identity && !$this->isSupporter($identity->member_id))) {                                                  
                            ?>
                            Please consider to become a <a href="/support" target="_TOP">supporter</a> to help the site grow.
                            <?php   } else if((null != $identity && $this->isSupporter($identity->member_id))) { ?>
                            Thank you for your support!
                            <?php   }?>                            
                            
                        </p>
                    </center>
                </section>
            </div>
        </div>
    </main>

</body>
</html>



