<?php

/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */
?>


<?php

if (($this->page == 1) && ($this->nopage == 0)) {
    echo '<div class="product-list">';
}

$this->nr = ($this->page - 1) * $this->pageLimit + 1;
echo $this->partialLoop('partials/mostplingedcreators.phtml', $this->users);

if (($this->page == 1) && ($this->nopage == 0)) {
    echo '</div>';
}

if (($this->totalcount > $this->pageLimit) && ($this->page == 1) && ($this->nopage == 0)) {
    $pagehtml = $this->printPaging($this->totalcount, $this->pageLimit, $this->page, '');
    echo $pagehtml;
}
?>

