<?php
/**
 *   ocs-webserver
 *
 *   Copyright 2016 by pling GmbH.
 *
 *     This file is part of ocs-webserver.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Application\View\Helper;

return [
    'invokables' => [
        BuildSearchBaseUrl::class,
        BuildProductUrl::class,
        BuildMemberUrl::class,
        BuildExploreUrl::class,
        BuildCollectionUrl::class,
        Image::class,
        AddDefaultScheme::class,
        BuildBaseUrl::class,
        Truncate::class,
        HeadMeta::class,
        FetchScoreColor::class,
        HumanTiming::class,
        HumanFilesize::class,
        PrintDate::class,
        PrintDateSince::class,
        Bbcode2html::class,
        FacebookLink::class,
        TwitterLink::class,
        BuildSearchUrl::class,
        BuildSearchTagUrl::class,
        FormResult::class,
        Escape::class,
        CalcDonation::class,
        CalcDonationText::class,
        CalcDonationTextBoth::class,
        CalcDonationYearlyText::class,
        UserIsOwner::class,
        IsProjectActive::class,
        BuildDownloadLink::class,
        PrintPaging::class,
    ],
    'factories'  => [
        ConfigHelper::class                      => Factory\ConfigHelperFactory::class,
        CurrentUser::class                       => Factory\CurrentUserFactory::class,
        CurrentStore::class                      => Factory\CurrentStoreFactory::class,
        UrlEncrypt::class                        => Factory\UrlEncryptFactory::class,
        UrlDecrypt::class                        => Factory\UrlDecryptFactory::class,
        FetchStoresForCatTreeJson::class         => Factory\FetchStoresForCatTreeJsonFactory::class,
        FetchMetaheaderMenuJson::class           => Factory\FetchMetaheaderMenuJsonFactory::class,
        ReadCategoryData::class                  => Factory\ReadCategoryDataFactory::class,
        NewUsers::class                          => Factory\NewUsersFactory::class,
        IsSupporter::class                       => Factory\IsSupporterFactory::class,
        IsProjectOriginal::class                 => Factory\IsProjectOriginalFactory::class,
        IsProjectFeatured::class                 => Factory\IsProjectFeaturedFactory::class,
        IsProjectMod::class                      => Factory\IsProjectModFactory::class,
        CatXdgType::class                        => Factory\CatXdgTypeFactory::class,
        FetchHeartsForProject::class             => Factory\FetchHeartsForProjectFactory::class,
        UserFollowsProject::class                => Factory\UserFollowsProjectFactory::class,
        FetchCategoriesForProductAsString::class => Factory\FetchCategoriesForProductAsStringFactory::class,
        FetchCategoryIdForProduct::class         => Factory\FetchCategoryIdForProductFactory::class,
        IsSupporterActive::class                 => Factory\IsSupporterActiveFactory::class,
        ListCategories::class                    => Factory\ListCategoriesFactory::class,
        ProjectFiles::class                      => Factory\ProjectFilesFactory::class,
        ProjectUpdates::class                    => Factory\ProjectUpdatesFactory::class,
        FetchTagsCategoryForProject::class       => Factory\FetchTagsCategoryForProjectFactory::class,
        FetchTagsUserForProject::class           => Factory\FetchTagsUserForProjectFactory::class,
        FetchScore::class                        => Factory\FetchScoreFactory::class,
        FetchRate::class                         => Factory\FetchRateFactory::class,
        IsProjectEbook::class                    => Factory\IsProjectEbookFactory::class,
        CatTitle::class                          => Factory\CatTitleFactory::class,
        ProjectDetailCounts::class               => Factory\ProjectDetailCountsFactory::class,
        FetchReportsSpamCnt::class               => Factory\FetchReportsSpamCntFactory::class,
        FetchReportsMisuseCnt::class             => Factory\FetchReportsMisuseCntFactory::class,
        FetchLicenseTags::class                  => Factory\FetchLicenseTagsFactory::class,
        ReadSectionData::class                   => Factory\ReadSectionDataFactory::class,
        Params::class                            => Factory\ParamsFactory::class,
        FetchMemberSettingItem::class            => Factory\FetchMemberSettingItemFactory::class,
        IsProjectClone::class                    => Factory\IsProjectCloneFactory::class,
        MemberSettingItem::class                 => Factory\MemberSettingItemFactory::class,
        FetchHeaderData::class                   => Factory\FetchHeaderDataFactory::class,
    ],
    'aliases'    => [
        'Image'                             => Image::class,
        'image'                             => Image::class,
        'configHelp'                        => ConfigHelper::class,
        'currentUser'                       => CurrentUser::class,
        'currentStore'                      => CurrentStore::class,
        'buildSearchBaseUrl'                => BuildSearchBaseUrl::class,
        'buildProductUrl'                   => BuildProductUrl::class,
        'buildCollectionUrl'                => BuildCollectionUrl::class,
        'buildMemberUrl'                    => BuildMemberUrl::class,
        'urlEncrypt'                        => UrlEncrypt::class,
        'urlDecrypt'                        => UrlDecrypt::class,
        'fetchStoresForCatTreeJson'         => FetchStoresForCatTreeJson::class,
        'fetchMetaheaderMenuJson'           => FetchMetaheaderMenuJson::class,
        'readCategoryData'                  => ReadCategoryData::class,
        'newUsers'                          => NewUsers::class,
        'truncate'                          => Truncate::class,
        'isSupporter'                       => IsSupporter::class,
        'headMeta'                          => HeadMeta::class,
        'catXdgType'                        => CatXdgType::class,
        'addDefaultScheme'                  => AddDefaultScheme::class,
        'isProjectOriginal'                 => IsProjectOriginal::class,
        'isProjectFeatured'                 => IsProjectFeatured::class,
        'isProjectMod'                      => IsProjectMod::class,
        'fetchHeartsForProject'             => FetchHeartsForProject::class,
        'userFollowsProject'                => UserFollowsProject::class,
        'fetchScoreColor'                   => FetchScoreColor::class,
        'humanTiming'                       => HumanTiming::class,
        'humanFilesize'                     => HumanFilesize::class,
        'printDate'                         => PrintDate::class,
        'printDateSince'                    => PrintDateSince::class,
        'fetchCategoriesForProductAsString' => FetchCategoriesForProductAsString::class,
        'fetchCategoryIdForProduct'         => FetchCategoryIdForProduct::class,
        'isSupporterActive'                 => IsSupporterActive::class,
        'bbcode2html'                       => Bbcode2html::class,
        'facebookLink'                      => FacebookLink::class,
        'twitterLink'                       => TwitterLink::class,
        'listCategories'                    => ListCategories::class,
        'projectFiles'                      => ProjectFiles::class,
        'projectUpdates'                    => ProjectUpdates::class,
        'fetchTagsCategoryForProject'       => FetchTagsCategoryForProject::class,
        'fetchTagsUserForProject'           => FetchTagsUserForProject::class,
        'fetchScore'                        => FetchScore::class,
        'fetchRate'                         => FetchRate::class,
        'isProjectEbook'                    => IsProjectEbook::class,
        'catTitle'                          => CatTitle::class,
        'buildSearchUrl'                    => BuildSearchUrl::class,
        'buildSearchTagUrl'                 => BuildSearchTagUrl::class,
        'projectDetailCounts'               => ProjectDetailCounts::class,
        'fetchReportsSpamCnt'               => FetchReportsSpamCnt::class,
        'fetchReportsMisuseCnt'             => FetchReportsMisuseCnt::class,
        'buildBaseUrl'                      => BuildBaseUrl::class,
        'formResult'                        => FormResult::class,
        'escape'                            => Escape::class,
        'fetchLicenseTags'                  => FetchLicenseTags::class,
        'calcDonation'                      => CalcDonation::class,
        'calcDonationText'                  => CalcDonationText::class,
        'calcDonationTextBoth'              => CalcDonationTextBoth::class,
        'calcDonationYearlyText'            => CalcDonationYearlyText::class,
        'userIsOwner'                       => UserIsOwner::class,
        'isProjectActive'                   => IsProjectActive::class,
        'buildDownloadLink'                 => BuildDownloadLink::class,
        'printPaging'                       => PrintPaging::class,
        'readSectionData'                   => ReadSectionData::class,
        'params'                            => Params::class,
        'fetchMemberSettingItem'            => FetchMemberSettingItem::class,
        'isProjectClone'                    => IsProjectClone::class,
        'memberSettingItem'                 => MemberSettingItem::class,
        'fetchHeaderData'                   => FetchHeaderData::class,
    ],
];