<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$tableProject = new Default_Model_Project();
$this->product_views = $tableProject->fetchProjectViews($this->product->project_id);
 $helperUserRole = new Backend_View_Helper_UserRole();
$userRoleName = $helperUserRole->userRole();

$tableTags = new Default_Model_Tags();
$tagsArray = $tableTags->getTagsArray($this->product->project_id, $tableTags::TAG_TYPE_PROJECT, $tableTags::TAG_GHNS_EXCLUDED_GROUPID);
$isGhnsExcluded = false;
if(isset($tagsArray) && (count($tagsArray) == 1)) {
    $isGhnsExcluded = true;
}

$filesTable = new Default_Model_DbTable_PploadFiles();
$countDownloadsToday = $filesTable->fetchCountDownloadsTodayForProject($this->product->ppload_collection_id);
$countDownloadsTodayUk = $filesTable->fetchCountDownloadsTodayForProjectNew($this->product->ppload_collection_id);

$mediaViewsTable = new Default_Model_DbTable_MediaViews();
$countMediaViewsToday = $mediaViewsTable->fetchCountViewsTodayForProject($this->product->project_id);
$countMediaViewsAlltime = $mediaViewsTable->fetchCountViewsForProjectAllTime($this->product->project_id);

$countPageviews = $this->projectDetailCounts($this->product->project_id);
$countPageviewsTotal = 0;
$countPageviewsToday = $countPageviews[0]['count_views'];
if(sizeof($countPageviews)==2) $countPageviewsTotal = $countPageviews[1]['count_views'];



// $heute = date("Y-m-d H:i:s");
$today = (new DateTime())->modify('-1 day');
$filterDownloadToday = $today->format("Y-m-d H:i:s");
?>
<style>
    .font-italic{
        font-style: italic;
    }
    .font-italic span{
        font-style: italic;
    }
</style>
<div class="prod-widget-box right details">
    <span class="title"> Details </span>

    <div class="row">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">license</span>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <span class="value">
            <?= $this->product->project_license_title; ?> </span>
        </div>
    </div>

    <div class="row">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">version</span>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <span class="value">
            <?= Default_Model_HtmlPurify::purify($this->product->project_version); ?> </span>
        </div>
    </div>

    <?php if ($this->product->project_changed_at) { ?>
        <div class="row">
            <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">updated</span>
            <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $this->printDate($this->product->project_changed_at) ?></span>
        </div>
    <?php } ?>

    <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) : ?>
        <div class="row font-italic">
            <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">major updated</span>
            <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $this->printDate($this->product->project_major_updated_at) ?></span>
        </div>
    <?php endif; ?>

    <div class="row">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">added</span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $this->printDate($this->product->project_created_at) ?></span>
    </div>

    <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) : ?>
    <div class="row font-italic">
        <span class=" col-lg-6 col-md-6 col-sm-6 col-xs-6">downloads 24h old</span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <div id="downloadscntdb"><?= $countDownloadsToday ?></div></span>
    </div>
    <?php endif; ?>
    
    <div class="row">
        <span class=" col-lg-6 col-md-6 col-sm-6 col-xs-6">downloads 24h</span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <div id="downloadscntdb2"><?= $countDownloadsTodayUk ?></div></span>
    </div>
    
    <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) : ?>

    <div class="row font-italic">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">mediaviews 24h </span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $countMediaViewsToday ?></span>
    </div>
    
    <div class="row font-italic">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">mediaviews total </span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $countMediaViewsAlltime ?></span>
    </div>

    <?php endif; ?>    
    
    <div class="row">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">pageviews 24h </span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $countPageviewsToday ?></span>
    </div>

    
    <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) : ?>

    <div class="row font-italic">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">pageviews total </span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $countPageviewsTotal ?></span>
    </div>

    <div class="row font-italic">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">spam reports</span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $this->fetchReportsSpamCnt($this->product->project_id) ?></span>
    </div>

    <div class="row font-italic">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">misuse reports</span>
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6 value"> <?= $this->fetchReportsMisuseCnt($this->product->project_id)?></span>
    </div>
     <?php endif; ?>
        <div class="row" style="padding-top: 5px">
            <div class="col-lg-12">
                <div class="small " id="product-actions">

                      <span style="padding-right: 20px;">
                            <?php if (Zend_Auth::getInstance()->hasIdentity()) {  ?>
                                <a data-toggle="modal" data-target="#report-product-fraud-<?= $this->product->project_id ?>" role="button"
                                   href="#report-product-fraud-<?= $this->product->project_id ?>">
                                    <span class="glyphicon glyphicon-alert"></span> Report Misuse
                                </a>
                            <?php }else{ ?>
                                    <a data-toggle="modal" data-target="#like-product-modal" role="button">
                                                  <span class="glyphicon glyphicon-alert"></span> Report Misuse
                                    </a>
                            <?php } ?>
                    </span>



                    <?php if (Zend_Auth::getInstance()->hasIdentity()) {  ?>
                           <a data-toggle="modal" data-target="#report-product-<?= $this->product->project_id ?>" role="button"
                           href="#report-product-<?= $this->product->project_id ?>">
                            <span class="glyphicon glyphicon-alert"></span> Report SPAM
                        </a>
                    <?php }else{ ?>
                            <a data-toggle="modal" data-target="#like-product-modal" role="button">
                                   <span class="glyphicon glyphicon-alert"></span> Report SPAM
                            </a>
                    <?php } ?>



                </div>
            </div>
        </div>


    <?php if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) : ?>
        <span class="page-views font-italic">
            <a target="_NEW" href="http://cp1.hive01.com/content/show.php?content=<?= $this->product->project_source_pk ?>">link to hive</a>
        </span>
        <span class="page-views font-italic">
            <a id="delete-this" href="/backend/project/delete?project_id=<?= $this->product->project_id ?>">delete product</a>
        </span>

        <div style="clear: both" class="small">(remember the cache) after you change some value below and refresh the page you may encounter some differences to your changes</div>
        <span class="page-views font-italic">
            <input type="checkbox" id="spam-checked-checkbox" <?php echo $this->product->spam_checked == 1 ? ' checked=\'checked\' ' : ''; ?> />  spam checked
        </span>
        <span class="page-views font-italic">
          <input type="checkbox" id="feature-this-checkbox" <?php echo $this->product->featured == 1 ? ' checked=\'checked\' ' : ''; ?> />  featured
        </span>
        <span class="page-views font-italic" style="color: red;">
            <input type="checkbox" id="ghns_excluded-this-checkbox" <?php echo $isGhnsExcluded == 1 ? ' checked=\'checked\' ' : ''; ?> />  ghns-excluded
        </span>
        <span class="page-views font-italic" style="color: red;">
            <input type="checkbox" id="pling-excluded-checkbox" <?php echo $this->product->pling_excluded == 1 ? ' checked=\'checked\' ' : ''; ?> />  pling-excluded
        </span>

        <script>
            $('#delete-this').on('click', function (event) {
                event.stopPropagation();
                var result = confirm("Delete Product?");
                if (result) {
                    var target = $(this).attr('href');
                    $.ajax({
                        url: target,
                        success: function (results) {
                            alert('Product deleted successfully');
                        },
                        error: function () {
                            alert('Service is temporarily unavailable.');
                        }
                    });
                }

                return false;
            });

            $('#spam-checked-checkbox').on('click', function (event) {
                event.stopPropagation();
                var feature = 0;
                if (this.checked) {
                    feature = 1;
                } else {
                    feature = 0;
                }

                var target = "/backend/project/dospamchecked?project_id=<?= $this->product->project_id ?>&checked=" + feature;
                $.ajax({
                    url: target,
                    success: function (results) {
                        if (0 == results.spam_checked) {
                            $('#spam-checked-checkbox').prop("checked", false);
                        } else {
                            $('#spam-checked-checkbox').prop("checked", true);

                        }

                    },
                    error: function () {
                        alert('Service is temporarily unavailable.');
                    }
                });

                return false;

            });

            $('#feature-this-checkbox').on('click', function (event) {
                event.stopPropagation();
                var feature = 1;
                if (this.checked) {
                    feature = 1;
                } else {
                    feature = 0;
                }

                var target = "/backend/project/dofeature?project_id=<?= $this->product->project_id ?>&featured=" + feature;
                $.ajax({
                    url: target,
                    success: function (results) {
                        if (feature == 0) {
                            alert('Project remove featured successfully');
                            $('#feature-this-checkbox').prop("checked", false);

                        } else {
                            alert('Project set featured successfully');
                            $('#feature-this-checkbox').prop("checked", true);

                        }

                    },
                    error: function () {
                        alert('Service is temporarily unavailable.');
                    }
                });

                return false;

            });




            $('#pling-excluded-checkbox').on('click', function (event) {
                event.stopPropagation();
                var status = 0;
                if (this.checked) {
                    status = 1;
                } else {
                    status = 0;
                }

                var target = "/backend/project/doexclude?project_id=<?= $this->product->project_id ?>&pling_excluded=" + status;
                $.ajax({
                    url: target,
                    success: function (results) {
                        if (status == 0) {
                            alert('Project was successfully included for plinging');
                            $('#pling-excluded-checkbox').prop("checked", false);

                        } else {
                            alert('Project was successfully excluded for plinging');
                            $('#pling-excluded-checkbox').prop("checked", true);

                        }

                    },
                    error: function () {
                        alert('Service is temporarily unavailable.');
                    }
                });

                return false;
            });
        </script>

        <span class="page-views"><input style="width: 40px;" type="text" id="project_category_id"
                                        value="<?php echo $this->product->project_category_id; ?>"> <button id="change_cat"
                                                                                                            data-href="/backend/project/changecat?project_id=<?= $this->product->project_id ?>&project_category_id=">change category</button></span>
        <script>
            $('#change_cat').on('click', function (event) {

                event.stopPropagation();
                var target = $(this).attr('data-href');
                var newCat = $('#project_category_id').val();

                $.ajax({
                    url: target + newCat,
                    success: function (results) {
                        alert('Project updated successfully');
                        location.reload();
                    },
                    error: function () {
                        alert('Service is temporarily unavailable.');
                    }
                });

                return false;
            });
        </script>

    <?php elseif (Default_Model_DbTable_MemberRole::ROLE_NAME_MODERATOR == $userRoleName) : ?>

        <span class="page-views " style="color: red;">
            
             <input type="checkbox" id="ghns_excluded-this-checkbox" <?php echo $isGhnsExcluded == 1 ? ' checked=\'checked\' ' : ''; ?> />  ghns-excluded
        </span>

       
    <?php endif; ?>
 
</div>

<?php
if(Default_Model_DbTable_MemberRole::ROLE_NAME_MODERATOR == $userRoleName ||
    Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName
    ){
            $this->inlineScript()->appendScript(
                '    $(document).ready(function(){
                        GhnsExcludedClick.setup('.$this->product->project_id.');
                    });
                ');
}
