<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$tableProject = new Default_Model_Project();
$helperUserRole = new Backend_View_Helper_UserRole();
$userRoleName = $helperUserRole->userRole();

$tableTags = new Default_Model_Tags();

$authorTags = $tableTags->getTagsEbookAuthor($this->product->project_id);



?>
<div class="prod-widget-box right details">
    <span class="title"> eBook Details </span>

    <div class="row">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">Author</span>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <span class="value">
                <?php
                if(!empty($authorTags)) {
                    echo "<ul>";
                    foreach ($authorTags as $author) {
                        echo "<li>";
                        echo $author;
                        echo "</li>";
                    }
                    echo "</ul>";
                }
                ?>
            </span>
        </div>
    </div>

    <div class="row">
        <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">Editor</span>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <span class="value">
            </span>
        </div>
    </div>
</div>