<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperImage = new Default_View_Helper_Image();
?>

<?php  foreach ($this->galleryPictures as $picture): ?>
            <a rel="gallery1" class="fancybox" href="<?php echo $helperImage->Image($picture, array('width' => '1024', 'height' => '682')); ?>">
                <img src="<?php echo $helperImage->Image($picture, array('width' => '140', 'height' => '85')); ?>" width="140" height="85"/>
            </a>
<?php endforeach;?>


<script type="text/javascript">
    $(document).ready(function() {
    $(".fancybox").fancybox({
    	
        openEffect  : 'none',
        closeEffect : 'none'
        

    });
    });
</script>
   