<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperMember = new Default_View_Helper_BuildMemberUrl();
$helperBase = new Default_View_Helper_BuildBaseUrl();

?>

<div class="my-products-heading">
    <h1 class="page-title left"><?= $this->translate('Products/Collections') ?></h1>
</div>

<div class="pling-nav-tabs">
    <ul class="nav nav-tabs">

        <li class="<?php echo $this->tab == 'products' ? 'active' : ''; ?>">
            <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'products'); ?>">
                <span class="glyphicon glyphicon-th-list"></span>
                <?= $this->translate('Products') ?>
            </a>
        </li>

        <li class="<?php echo $this->tab == 'collections' ? 'active' : ''; ?>">
            <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'collections'); ?>">
                <span class="glyphicon glyphicon-th-list"></span>
                <?= $this->translate('Collections') ?>
            </a>
        </li>
        <li class="header-menu-left-item <?php echo $this->tab == 'add' ? 'active' : ''; ?>">
            <?php if ($this->mode == 'edit') : ?>
                <a href="<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri() ?>">
                    <span class="glyphicon glyphicon-pencil"></span>
                    <?= $this->translate('Edit Product') ?>
                </a>
            <?php else : ?>
                <a href="<?php echo Zend_Registry::get('config')->settings->client->default->baseurl_store . '/product/add'; ?>">
                    <span class="glyphicon glyphicon-plus"></span>
                    <?= $this->translate('Add Product') ?>
                </a>
            <?php endif ?>
        </li>
        <li class="header-menu-left-item <?php echo $this->tab == 'addcollection' ? 'active' : ''; ?>">
            <?php if ($this->mode == 'editcollection') : ?>
                <a href="<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri() ?>">
                    <span class="glyphicon glyphicon-pencil"></span>
                    <?= $this->translate('Edit Collection') ?>
                </a>
            <?php else : ?>
                <a href="<?php echo Zend_Registry::get('config')->settings->client->default->baseurl_store . '/collection/add'; ?>">
                    <span class="glyphicon glyphicon-plus"></span>
                    <?= $this->translate('Add Collection') ?>
                </a>
            <?php endif ?>
        </li>

    </ul>
</div>