<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperHumanTiming = new Default_View_Helper_HumanTiming();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperUserIsOwner = new Default_View_Helper_UserIsOwner();
$helperImage = new Default_View_Helper_Image();
$comment = $this->comment;
$marginLeft = $this->marginLeft;
$age = $helperHumanTiming->humanTiming($comment['comment_created_at']);
?><div class="comment-row" style="margin-left: <?php echo $marginLeft?>px;">
    <div class="comment well background-white">
        <div class="row">
            <div class="col-md-9 col-lg-9 col-sm-9 col-xs-9">
                            <span class="name">
                               by <a href="<?= $helperBuildMemberUrl->buildUrl($comment['member_id']) ?>"><?php echo $comment['username']; ?></a></span>
                on: <span class="small lightgrey"> <?= $age['age'] ?> <span class="light"><?= $age['unit'] ?> ago</span> </span>
            </div>
            <div class="col-md-3 col-lg-3 col-sm-3 col-xs-3">
                <figure class="well relative row" style="width:150px;padding:0;margin-bottom: 0;">
                    <div class="col-md-5 col-lg-5 col-sm-5 col-xs-5 product-maker-thumbnail relative">
                        <a title="<?= $comment['username'] ?>" href="<?= $helperBuildMemberUrl->buildUrl($comment['member_id']) ?>">
                            <div class="profile-image-overlay-4 absolute"></div>
                            <img width="40"
                                 height="40"
                                 alt="<?= $comment['username'] ?>"
                                 src="<?= $helperImage->Image($comment['profile_image_url'], array('width' => 40, 'height' => 40)) ?>">
                        </a>
                    </div>
                    <div class="col-md-7 col-lg-7 col-sm-7 col-xs-7 product-maker-summary">
                        <h6>
                            <a href="<?= $helperBuildMemberUrl->buildUrl($comment['member_id']) ?>" class="small"><?= $comment['username'] ?></a>
                        </h6>
                    </div>
                </figure>
            </div>
        </div>
        <div class="comment-content">
            <div class="popover-content">
                <p><?= $comment['comment_text'] ?></p>
            </div>
            <?php if (Zend_Auth::getInstance()->hasIdentity()) {
                $identity = Zend_Auth::getInstance()->getStorage()->read();
                ?>
                <a class="btn btn-native small show-maker-reply" style="padding: 4px;">Reply to this</a>
                <div class="popover-content maker-comment-container maker-form well" style="display:none;">
                    <div class="row">
                        <div class="col-md-11 col-lg-11 col-sm-11 col-xs-11">
                            <figure class="supporter-thumbnail relative">
                                <a href="<?= $helperBuildMemberUrl->buildUrl($identity->member_id) ?>"
                                   title="<?= $identity->username ?>">
                                    <img height="40" width="40" src="<?= $helperImage->Image($identity->profile_image_url,array('width' => 40, 'height' => 40, 'crop' => 2)); ?>"
                                         alt="<?= $identity->username ?>">
                                </a>
                            </figure>
                        </div>
                        <div class="col-md-1 col-lg-1 col-sm-1 col-xs-1">
                            <span class="glyphicon glyphicon-remove pull-right"></span>
                        </div>
                    </div>

                    <div class="maker-comment comment-content">
                        <div class="popover-content">
                            <form class="full-width" action="/productcomment/addreply/">
                                <input type="hidden" name="i" value="<?= $comment['comment_id'] ?>">
                                <input type="hidden" name="p" value="<?= $comment['comment_target_id'] ?>">
                                <input type="hidden" name="m" value="<?= $identity->member_id ?>">
                                <textarea name="msg" class="full-width"></textarea>
                                <input type="submit"
                                       class="btn btn-native small"
                                       style="padding:5px;margin-top:5px;"
                                value="Send"/>
                            </form>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
