<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperAddDefaultScheme = new Default_View_Helper_AddDefaultScheme();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
?>
<div id="project-maker" class="sidebar-section">
    <h4 id="user-heading"
        class="small upcase sidebar-heading"><?php echo $this->translate('projects.show.maker'); ?></h4>

    <div id="project-user" class="clearfix">
        <div id="user-image" class="alignleft">
            <div class="image-overlay-128">
                <a href="<?php echo $helperBuildMemberUrl->buildMemberUrl($this->member->member_id); ?>"><img
                        src="/images/system/user-profile-image-overlay-white-128-bg.png"></a>
            </div>
            <a href="<?php echo $helperBuildMemberUrl->buildMemberUrl($this->member->member_id); ?>"><img
                    src="<?php echo $helperImage->Image($this->member->profile_image_url,array('width' => 128, 'height' => 128, 'crop' => 2)); ?>" alt="sample avatar" width="128"></a>
        </div>
        <div id="user-details" class="alignleft">
            <h3 id="user-title"><a
                    href="<?php echo $helperBuildMemberUrl->buildMemberUrl($this->member->member_id); ?>"><?php echo $this->member->username; ?></a>
            </h3>

            <div id="user-url"><a
                    href="<?php echo $helperAddDefaultScheme->addDefaultScheme($this->member->link_website); ?>"
                    class="lightgrey small light"><?php echo $this->member->link_website; ?></a></div>
            <div id="user-social">
                <a href="<?php echo $this->member->link_facebook; ?>" id="facebook-small">facebook</a>
                <a href="<?php echo $this->member->twitter_code; ?>" id="twitter-small">twitter</a>
                <a href="<?php echo $this->member->google_code; ?>" id="g-plus-small">google plus</a>
            </div>
        </div>
    </div>
</div><!-- END #project-maker -->

<hr class="sidebar-divider">

<?php echo $this->render('partials/sidebarRelatedProducts.phtml', array('relatedProjects' => $this->relatedProducts)); ?>

<hr class="sidebar-divider">

<?php echo $this->render('partials/sidebarPlingButton.phtml', $this->project); ?>

<hr class="sidebar-divider">