<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperHumanTiming = new Default_View_Helper_HumanTiming();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperUserIsOwner = new Default_View_Helper_UserIsOwner();
$countSupporter = count($this->supporter->toArray());
$helperImage = new Default_View_Helper_Image();
?>

<div id="comments">
    <h3>Recent Donations</h3>
    <?php
    if ($countSupporter == 0) {
        ?>
        <div>Be the first to donate</div>
        <?php
    } else {
        foreach ($this->plings as $comment):
            $age = $helperHumanTiming->humanTiming($comment['create_time']);
            ?>
            <div class="comment-row">
                <div class="comment">
                    <figure class="supporter-thumbnail relative">
                        <a href="<?= $helperBuildMemberUrl->buildMemberUrl($comment['member_id']) ?>"
                           title="<?= $comment['username'] ?>">
                            <img src="<?= $helperImage->Image($comment['profile_image_url'],array('width' => 100, 'height' => 100, 'crop' => 2)); ?>" alt="<?= $comment['username'] ?>">
                        </a>
                    </figure>
                    <div class="comment-content">
                        <div class="popover-title">
                            <span class="name">
                                <a href="<?= $helperBuildMemberUrl->buildMemberUrl($comment['member_id']) ?>"><?php echo $comment['username'] ?></a></span>
                            <?php
                            if (!$comment['amount'] == 0) {
                                ?>
                                <span class="amount"> donated $<?php echo $comment['amount'] ?></span>
                                <?php
                            }
                            ?>
                            <span class="small lightgrey"> <?= $age['age'] ?> <span class="light"><?= $age['unit'] ?>
                                    ago</span> </span>
                        </div>
                        <div class="popover-content">
                            <p><?= $comment['comment_text'] ?></p>
                        </div>
                     </div>
                </div>
            </div>
            <?php
        endforeach;
    } ?>
</div><!-- /.comment-content -->