<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
           
<style type="text/css">
    
    #plings-panel .u-wrap {
    float: left;
    padding: .3em;
    border: .35em solid #dee0e0;
    border-radius: 5px;
    height: 14em;
    margin-bottom: 1em;
    background: #fff;
    width: 115px;
    height: 200px;
    margin-right: 10px;
    -webkit-transition: all .2s ease-out;
    -moz-transition: all .2s ease-out;
    -ms-transition: all .2s ease-out;
    -o-transition: all .2s ease-out;
}

#plings-panel .u-wrap figure img {
    width: 100%;
    border: 1px solid #dbdbdb;
    -webkit-border-radius: 999px;
    -moz-border-radius: 999px;
    border-radius: 999px;
    -webkit-background-clip: padding-box;
    -moz-background-clip: padding;
    background-clip: padding-box;
}

#plings-panel .u-wrap h3 {
    font-size: 13px;
    font-weight: 700;
    word-wrap: break-word;
    line-height: 20px;
    height: 20px;
    padding: 0;
    margin: 0;
}
</style>                                                            
 <?php 
        foreach ($this->projectplings as $user) {                                  
    ?>
        <div class="user " >
            <div class="u-wrap">
                <a  href="<?php echo $this->buildMemberUrl($user['member_id']); ?>" class="tooltipuser"  data-tooltip-content="#tooltip_content" role="button" data-user="<?=$user['member_id'] ?>">
                    <figure >
                        <img src="<?php echo $this->Image($user['profile_image_url'], array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
                    </figure>
                    <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo Default_Model_HtmlPurify::purify($user['username']); ?></h3>                                                   
                </a>
                 <span class="small"><i class="fa fa-check myfav" aria-hidden="true"></i> <?= $this->printDate($user['created_at'])?></span>
            </div>
        </div>
<?php } ?>
<div class="clearboth"></div> 


