<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$options = array(1 => 'ugh', 2=>'really bad',3=>'bad',4=>'soso',5=>'average', 6=>'okay',7=>'good', 8=>'great', 9=>'excellent',10=>'the best');
$scoreColor = new Default_View_Helper_FetchScoreColor();
?>

<style type="text/css">
	.userimg {
    border-radius: 50%;
    border: 1px solid #ccc;
    width: 40px;
    height: 40px;}
</style>
<?php  
$tmp=null;
foreach ($this->ratings as $this->productRating) {
		if($this->productRating['user_like']>1)
		{
			$tmp = $this->productRating;
		}
	    if($this->productRating['rating_active']==0 || $this->productRating['user_like']>1) continue;	   			
	?>

<div class="productRating-rows <?=$this->productRating['rating_active']==0?'productRating-rows-inactive':'productRating-rows-active'?>  <?=$this->productRating['user_like']==1?'clsUpvotes':'clsDownvotes' ?> "  >
	<div class="product-heading product-update-heading">
	<a href="<?php echo $this->buildMemberUrl($this->productRating['username']); ?>" >	
	<img class="userimg"  
					src="<?= $this->Image(($this->productRating['profile_image_url']==null)?'hive/user-pics/nopic.png':$this->productRating['profile_image_url'],
	                                                array('width' => 40, 'height' => 40)) ?>"
	                                                 alt="product-maker" 
	                                                />
    </a>
	<span>	
		<a href="<?php echo $this->buildMemberUrl($this->productRating['username']); ?>" style="font-weight: bold;">
		<?=$this->productRating['username'] ?> 
		</a>
	</span>
	  <span class="small light lightgrey product-update-date"> 
	  	<?=$this->printDate($this->productRating['created_at']) ?> 
	  </span>
	  <span>
		<span class="score label" style="background-color:<?=$this->fetchScoreColor($this->productRating['score'])?>; ">
			<?=$this->productRating['score'] ?>
		</span>
		<span style="font-size: small;padding-left: 5px;"><?php echo ' '.$options[$this->productRating['score']]?></span>
	  </span>
	</div>
	<div style="padding-left: 45px; padding-bottom: 15px;">			
		<?=$this->productRating['comment_text'] ?> 
	</div>
</div>
<?php } ?>

<?php if($tmp){?>

	<div class="productRating-rows">
		<div class="product-heading product-update-heading">
		<a href="<?php echo $this->buildMemberUrl($this->productRating['username']); ?>" >	
		<img class="userimg"  
						src="<?= $this->Image('hive/user-pics/nopic.png',
		                                                array('width' => 40, 'height' => 40)) ?>"
		                                                 alt="product-maker" 
		                                                />
	    </a>
		<span>	
		<a href="<?php echo $this->buildMemberUrl($this->productRating['username']); ?>" style="font-weight: bold;">
		<?=$this->productRating['username'] ?> 
		</a>
		</span>
		  <span class="small light lightgrey product-update-date"> 
		  	<?=$this->printDate($this->productRating['created_at']) ?> 
		  </span>
		  <span>
			<span class="score label" style="background-color:<?=$this->fetchScoreColor(5)?>; ">
				Count:<?php echo $tmp['user_like']+$tmp['user_dislike']; ?> Rating: <?=number_format($this->fetchScore($tmp['user_like'],$tmp['user_dislike']),2)?>
			</span>		
		  </span>
		</div>	
	</div>

<?php }else{?>

<div class="productRating-rows">
	<div class="product-heading product-update-heading">
	<a href="<?php echo $this->buildMemberUrl($this->productRating['username']); ?>" >	
	<img class="userimg"  
					src="<?= $this->Image('hive/user-pics/nopic.png',
	                                                array('width' => 40, 'height' => 40)) ?>"
	                                                 alt="product-maker" 
	                                                />
    </a>
	
	  <span>
		<span class="score label" style="background-color:<?=$this->fetchScoreColor(5)?>; ">
			Count: 2 Rating: 5.00
		</span>		
	  </span>
	</div>	
</div>
<?php } ?>


