<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperHumanTiming = new Default_View_Helper_HumanTiming();
$date = $helperHumanTiming->humanTiming($this->productUpdate['changed_at']);
$helpBBCode = new Default_View_Helper_Bbcode2html();
?>
<a name="anker_<?= $this->productUpdate['project_update_id'] ?>"></a>
<h3 class="product-heading product-update-heading" style="float: left; width: 100%">
    <?= $this->productUpdate['title'] ?><span class="small light lightgrey product-update-date"
                             style="padding-left: 10px;"> <?= $date['age'] ?> <?= $date['unit'] ?> ago</span>
</h3>

<p><?= $helpBBCode->Bbcode2html($this->productUpdate['text']) ?></p>
