<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>

<button id="showRatingAll" class="pull-right">Show all Reviews</button>
<button id="showRatingActive" class="pull-right">Show Active Reviews</button>
<button id="showRatingUpvotes" class="pull-right">Show only Upvotes</button>
<button id="showRatingDownvotes" class="pull-right">Show only Downvotes</button>
<?php  foreach ($this->ratings as $this->productRating) {
	?>
<div class="productRating-rows <?=$this->productRating['rating_active']==0?'productRating-rows-inactive':'productRating-rows-active'?>  <?=$this->productRating['user_like']==1?'clsUpvotes':'clsDownvotes' ?> "  >
	<h3 class="product-heading product-update-heading" >
	<a href="<?php echo $this->buildMemberUrl($this->productRating['member_id']); ?>">
	<img class="userimg"  
					src="<?= $this->Image($this->productRating['profile_image_url'],
	                                                array('width' => 40, 'height' => 40)) ?>"
	                                                 alt="product-maker" 
	                                                />
    </a>
	<span>	
		<a href="<?php echo $this->buildMemberUrl($this->productRating['member_id']); ?>">
		<?=$this->productRating['username'] ?> 
		</a>
	</span>
	  <span class="small light lightgrey product-update-date"> <?=$this->printDate($this->productRating['created_at']) ?> </span>
	  <span> <?php 
	  	
	  	if($this->productRating['member_id']==0 ){
	  	     // import from Hive sum vote
	  	     if($this->productRating['user_dislike']>0) echo '<span class="glyphicon glyphicon-thumbs-down o-thumbs-down"> </span>'.$this->productRating['user_dislike'];
	  	     if($this->productRating['user_like']>0) echo '<span class="glyphicon glyphicon-thumbs-up o-thumbs-up"> </span>'.$this->productRating['user_like'];
	  	     
	  	}else{
	  		if($this->productRating['user_like']==1 ){
	  		     echo '<span class="glyphicon glyphicon-thumbs-up o-thumbs-up"> </span>';
	  		}else{
	  		     echo '<span class="glyphicon glyphicon-thumbs-down o-thumbs-down"> </span>';		
	  		} 	
	  	}

	  ?> </span>
	</h3>
	<span style="padding-left: 45px">	
		<?=$this->productRating['comment_text'] ?> 
	</span>
</div>
<?php } ?>

<?php
$this->inlineScript()->appendScript(
    '    $(document).ready(function(){            
            productRatingToggle.setup();
        });
    ');
