<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

 // product detail pling single project button	
$plings = new Default_Model_DbTable_ProjectPlings();			 			
$cntplings = count($plings->getPlings($this->project_id));
$isPlinged = false;
$member_id = null;
$isSupporter = false;
if($this->authMember){
	$member_id = $this->authMember->member_id;
	$tmp = $plings->getPling($this->project_id,$member_id);
      if($tmp)
      {
            $isPlinged = true;
      }
      $isSupporter = $this->isSupporter($member_id);
}

$heartatt = '';    	
$urlUserFollows = $this->buildProductUrl($this->project_id, 'plingproject');

$heartatt = $heartatt. 'role="button" data-fragment=""  '
	      .' data-target="#container-pling'.$this->project_id.'"'
	      .' data-href="'.$urlUserFollows.'"'
                         .' data-issupporter="'.$isSupporter.'"'                         
	      .' data-auth="'.$member_id.'"';
$out ='<div role="button" class="partialbuttonplingproject" '.$heartatt.' style="display:flex; align-items: center; justify-content: center;">';
 $out = $out. '<span class="plingtext small "  ><span class="plingnum"> '.$cntplings.'</span> Plings  </span>';
 if ($isPlinged){     
      $out = $out.'<span class="plingcircle active">p</span>';           
 }else{                  
      $out = $out.'<span class="plingcircle ">p</span>';     
 }


 $out = $out.'</div>';
echo $out;
?>


<style type="text/css">
      div.projectdtailHeart{
            float: right;           
            z-index: 100;
            margin-right: 5px;
            
          
           
        }
         .container-pling{
              position: relative;              
            }
        
         .partialbuttonplingproject
        {
          text-align: center;

        }

        span.plingcircle{
            width: 30px;
            height: 30px;
            background-color: #fff;
            border: 3px solid #C8C8C8;
            border-radius: 50%;
           
            font-size: 17px;
            text-align: center;
            color: #C8C8C8;
            font-weight: bold;
            transform: rotate(345deg);
            display: block;
            float: right;
          
        }
        span.active{
            border: 3px solid #EE6E09;
             color: #EE6E09;
        }

        span.plingtext{
        
          padding-right: 15px;
        }

</style>
