<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

 // product detail pling single project button  
$plings = new Default_Model_DbTable_ProjectPlings();            
$cntplings = count($plings->getPlings($this->project_id));
$isPlinged = false;
$member_id = null;
$isSupporter = false;
if($this->authMember){
  $member_id = $this->authMember->member_id;
  $tmp = $plings->getPling($this->project_id,$member_id);
      if($tmp)
      {
            $isPlinged = true;
      }
      $isSupporter = $this->isSupporter($member_id);
}

$heartatt = '';     
$urlUserFollows = $this->buildProductUrl($this->project_id, 'plingproject');

$heartatt = $heartatt. 'role="button" data-fragment=""  '
        .' data-target="#container-pling'.$this->project_id.'"'
        .' data-href="'.$urlUserFollows.'"'
                         .' data-issupporter="'.$isSupporter.'"'                         
        .' data-auth="'.$member_id.'"';
$out ='<div role="button" class="partialbuttonplingproject" '.$heartatt.' style="display:block; float:right">';
 $out = $out. '<span class="plingtext  "  ><span class="plingnum"> '.$cntplings.'</span> Plings  </span>';
 if ($isPlinged){             
      $out = $out.'<img id="plingbtn" data-src="/images/system/pling-btn-active.png" src="/images/system/pling-btn-active.png"/>';       
 }else{                  
      $out = $out.'<img id="plingbtn" data-src="/images/system/pling-btn-normal.png"  src="/images/system/pling-btn-normal.png"/>';       
 }

$out = $out.'</div>';

$soll = $this->getCurrentMonthPlings($this->project_id);
$sollhtml = ' <div class="amountsoll" style="width:50px; text-align:right;padding-right:5px;">'.$soll.'</div>';

$out = $out.'<div style="display:flex;clear:both">'.$sollhtml.'<div class="plingbar" style="flex:1;padding-top:4px">                         
                          <div class="progress" style="height: 12px; width: 200px;padding:2px;background-color: transparent; box-shadow: none;">
                          <div class="progress-bar" style="background-color: #b8c8b8;width: 100%;"> </div> 
                          </div></div></div>';


echo $out;
?>

<style type="text/css">
      div.projectdtailHeart{
            float: right;           
            z-index: 100;                                 
        }
     
        span.plingtext{        
          padding-right: 15px;
        }
</style>
