<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<h3><?= $this->translate('COMMENTS') ?></h3>
<?php
if (count($this->comments) == 0) { ?>
    <div class="sidebar-empty">
        <?php echo "No comments yet";//echo $this->translate('product.no_comments'); ?>
    </div>
<?php } else { ?>
    <div id="comments-carousel" class="sidebar-content carousel slide">

        <div class="comments carousel-inner">
            <?php echo $this->partialLoop('product/partials/comment.phtml', $this->comments); ?>
        </div>
        <div class="comment-carousel-controls <?php if (count($this->comments) <= 1) {
            echo 'disabled';
        } ?>">
            <a href="#comments-carousel" data-slide="prev">
                <div class="comment-carousel-control left">&lsaquo;</div>
            </a>
            <a href="#comments-carousel" data-slide="next">
                <div class="comment-carousel-control right">&rsaquo;</div>
            </a>
        </div>

    </div><!-- /.sidebar-content -->
    <?php $this->inlineScript()->appendScript("
       $(document).ready(function(){
            $('.carousel').each(function(){
                $(this).carousel({
                    interval: false
                });
            });
        });"); ?>

<?php } ?>