<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<h3>XGDURL</h3>
OpenDesktop now supports XDG-URL to make installation of resources easy.
<br>
To enable XDG-URL on your system, simply install the xdgurl tool from here: 
<br>
<a target="_blank" href="https://www.linux-apps.com/p/1136805/">https://www.linux-apps.com/p/1136805/</a>
<br>
<br>


<h3>BROWSER</h3>
After xdgurl is installed, just click the "Install" button on any supported fileformat.
<br>
In Firefox a program selection window opens the first time you click on an Install button: Choose "xdgurl" as custom URL handler and tick "remember the file association".
<br>
If you don't get the program selection window or you are using another browser, please set the xdgurl program as custom URL handler for xdg:// scheme in the browser's settings.
