<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
class Default_Form_Element_Email extends Default_Form_Element_Html5
{

    public function __construct($spec, $options = null)
    {
        if (is_array($options)) {
            $options['type'] = Default_Form_Element_Html5::FIELD_EMAIL;
        } elseif ($options instanceof Zend_Config) {
            $options->type = Default_Form_Element_Html5::FIELD_EMAIL;
        } else {
            $options = array('type' => Default_Form_Element_Html5::FIELD_EMAIL);
        }

        parent::__construct($spec, $options); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        $this->addValidator('EmailAddress');
        $this->addFilter('StringTrim');
        parent::init();
    }

}