<ul class="suggested-amounts less-margin">
<li class="amount-item <?=(isset($this->islast) ? 'last':'')?>">
  <label class="mdl-radio mdl-js-radio is-upgraded" for="sam-15" data-upgraded=",MaterialRadio" style="padding:0px">
     <div style="display: block; float: left">
      <input class="suggested-amount mdl-radio__button" <?=$this->checked?> id="sam-15" type="radio" value="<?=$this->value?>" name="amount_predefined">
    </div>
    <div class="mdl-radio__label">
      <div class="item-text">
        <span class="unit-wrapper">
          <span class="unit">$</span>
        </span>
        <span class="amount"><?=$this->amount?> </span>
        <span class="extrasmall"><?=$this->text?></span>
      </div>
    </div>
  </label>
</li>
</ul>