<main id="resend-page">
    <section id="form-warp" class="wrapper">
        <div style="height: 50px;"></div>
        <div class="panel panel-default" style="width: 75%; margin: auto;">
            <div class="panel-heading">
                <h3 class="panel-title">Your mail address is not validated.</h3>
            </div>
            <div class="panel-body">
                Please check your mail account or click the button below to request a new validation mail.<br>
                <form style="margin-top: 15px;" method="post" action="/verify/resend">
                    <?=Default_Model_CsrfProtection::getFormCsrf(); ?>
                    <button class="btn btn-native btn-min-width" type="submit">Resend</button>
                </form>
            </div>
        </div>
        <div style="height: 50px;"></div>
    </section>
</main>