<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.opendesktop.org')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:type', 'website')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:title', 'opendesktop.org')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:site_name','www.opendesktop.org')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:image','https://www.opendesktop.org/images/system/opendesktop-logo.png')->setAutoEscape(false);


$modelInfo = new Default_Model_Info();
$host = $_SERVER['SERVER_NAME'];
$getAuthUser = new Default_View_Helper_GetAuthUser();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();

$auth = Zend_Auth::getInstance();
$member = $getAuthUser->getAuthUser();
$this->member = $member;
?>
<link href="/theme/flatui/css/style-index-common.css" rel="stylesheet">
<main id="explore-content">
    <section class="wrapper-kde-store" id="intro-kde-store" >
        <section class="container" style="height:100%; width: 100%;">                               
            <div class="row">   

                <aside class="col-lg-2 col-md-4 col-sm-6 col-xs-12 aside" >
                     <?php  echo $this->render('settings/index.phtml'); ?>
                </aside>               
                
            </div> <!--row -->
        </section>
    </section>
</main>
