<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->headTitle($this->headTitle, 'SET');
$this->doctype(Laminas\View\Helper\Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', $_SERVER['HTTP_HOST'])->setAutoEscape(false);
$this->headMeta()->appendProperty('og:type', 'website')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:title', $_SERVER['HTTP_HOST'])->setAutoEscape(false);
$this->headMeta()->appendProperty('og:site_name',$_SERVER['HTTP_HOST'])->setAutoEscape(false);
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:image','https://www.pling.com/theme/react/assets/img/logo-pling.png')->setAutoEscape(false);


$this->headLink()
        ->prependStylesheet($this->basePath('/theme/flatui/css/home.css'))
       ;            
        
?>

<main id="explore-content" class="startpage-store">
  <div class="GridFlex">
    <div class="GridFlex-cell sidebar-left">
            <?php  echo $this->render('/application/explore/partials/filter.phtml'); ?>
    </div>

    <div class="GridFlex-cell content" id="main-content">
      <div class="contentcontainer">         
                        
       <div class="row text-center">
        <div class="refertext" style="display: block;margin: 0 auto;padding-bottom: 20px">
            Welcome to pling.com! For general Linux jump to jump to 
          <a href="http://www.pling.com/s/Linux" title="pling.com">/s/Linux </a>or pick one of the subgroups from the top or sidebar.
        </div>
       </div>
        

        <div class="row"  id="featureProductsContainer">
          <?php
          
          if ($this->featureProducts) {echo $this->render('partials/featured-products.phtml');}
          
          ?>
        </div>
    
        <div class="row">
          <div id="carousel-module-container"></div>
        </div>

        <div class="row blockpadding disply-flex" >
         <?php
                  echo $this->partial('/application/home/partials/product_group.phtml', array(
                          "title"  => "Applications",
                          "products" => $this->productsApps,
                          "catIDs" =>"233"
                      )
                  );

                     echo $this->partial('/application/home/partials/product_group.phtml', array(
                             "title"  => "App Add-Ons",
                             "products" => $this->productsAddons,
                             "catIDs" =>"152"
                         )
                     );                    
         ?>
        </div>

        <div class="row blockpadding disply-flex">
        <?php

            echo $this->partial('/application/home/partials/product_group.phtml', array(
              "title"  => "KDE Plasma",
              "products" => $this->productsThemesPlasma,
              "catIDs" =>"365"
              )
            );
            echo $this->partial('/application/home/partials/product_group.phtml', array(
                    "title"  => "GTK/Gnome",
                    "products" => $this->productsThemesGTK,
                    "catIDs" =>"366"
                )
            );
        ?>
        </div>

        <div class="row blockpadding disply-flex">
        <?php
                    echo $this->partial('/application/home/partials/product_group.phtml', array(
                            "title"  => "Window Managers",
                            "products" => $this->productsWindowmanager,
                            "catIDs" =>"147"
                        )
                    );

                    echo $this->partial('/application/home/partials/product_group.phtml', array(
                            "title"  => "Icons, Cursors",
                            "products" => $this->productsIconsCursors,
                            "catIDs" =>"386,107"
                        )
                    );
        ?>
        </div>

        <div class="row blockpadding disply-flex">
        <?php
                echo $this->partial('/application/home/partials/product_group.phtml', array(
                        "title"  => "Phone ",
                        "products" => $this->productsPhone,
                        "catIDs" =>"491"
                    )
                );


                    echo $this->partial('/application/home/partials/product_group.phtml', array(
                            "title"  => "Distros",
                            "products" => $this->productsDistors,
                            "catIDs" =>"404"

                        )
                    );
        ?>
        </div>   

        <div class="row blockpadding disply-flex">
          <?php
                  echo $this->partial('/application/home/partials/product_group.phtml', array(
                          "title"  => "Top Listings",
                          "products" => $this->productsCollections,
                          "catIDs" =>"567"
                      )
                  );

                  echo $this->partial('/application/home/partials/product_group_store.phtml', array(
                          "title"  => "Artwork",
                          "products" => $this->productsArtwork,
                          "stores" =>"Artwork"
                      )
                  );   


                         
        ?>
        </div>
        
        <div class="row blockpadding disply-flex">
        <?php
                echo $this->partial('/application/home/partials/product_group.phtml', array(
                        "title"  => "Wallpapers ",
                        "products" => $this->productsWallpapers,
                        "catIDs" =>"295"
                    )
                );


                    echo $this->partial('/application/home/partials/product_group.phtml', array(
                            "title"  => "Wallpapers (Original)",
                            "products" => $this->productsWallpapersOriginal,
                            "catIDs" =>"295"

                        )
                    );
        ?>
        </div> 


        <div class="row blockpadding disply-flex" id="productgroup1">
          <?php
                    echo $this->partial('/application/home/partials/product_group_store.phtml', array(
                            "title"  => "Music,Videos",
                            "products" => $this->productsVideos,
                            "stores" =>"Music,Videos"
                        )
                    );
                    echo $this->partial('/application/home/partials/product_group_store.phtml', array(
                            "title"  => "Books,Comics",
                            "products" => $this->productsBooksComics,
                            "stores" =>"Books,Comics"
                        )
                    );  
                    

                         
        ?>
        </div>

                                 
      </div>
    </div>
    <div class="GridFlex-cell sidebar-right">
            <aside  id="explore-sidebar" >

            <?php
                $this->show_git = true;
                $this->is_startpage = true;                
                include __DIR__.'/../explore/partials/common_rightsidebar.phtml';
               // echo $this->render('/application/home/partials/common_rightsidebar.phtml');
            ?>


            </aside>
            <!--<div id="right-sidebar-container"></div>-->
    </div>
  </div>
  <div class="tooltip_templates" style="display:none">
      <span id="tooltip_content">
          <i class="fa fa-spinner"></i>
      </span>
  </div>
</main>

<script type="application/javascript">
    $(document).ready(function () {
        $('body').on('click', '.ajaxPartialFeatureProduct', function (event) {
            event.preventDefault();
            $(this).off();
            var target = '#featureProductsContainer';
            if($(this).hasClass( "disabled" )) return false;
            var url = $(this).attr("href");
            $(target).load(url, function (response, status, xhr) {
                if (status == "error") {
                    $(target).empty().html('Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.');
                }
            });
            return false;
        });
    });

  var page = "opendesktop";
  var hpVersion = 2;
  var data = <?php echo $this->carouselData?>;                                
</script>
<script src="/theme/react/bundle/carousel-bundle.js" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/carousel.css"/>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
                TooltipUser.setup("tooltipuser","right");
                TooltipUser.setup("tooltipuserleft","left");
                TooltipUserPlings.setup("tooltipuserplings","right");
            });
        ');
