<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="messages">
    <?php foreach (Zend_Controller_Action_HelperBroker::getStaticHelper('flashMessenger')
                       ->getCurrentMessages() as $message) : ?>
        <p><?php echo $this->escape($message); ?></p>
    <?php endforeach; ?>
</div>
<?php
$lastMonth = date("Ym", strtotime("first day of previous month"));
?>

<div class="filtering">
    <form>
        Month: 
            <select name="filter_yearmonth" id="filter_yearmonth">
                <option value="201704" <?php if($lastMonth == '201704') echo 'selected=1'; ?> >2017 April</option>
                <option value="201705" <?php if($lastMonth == '201705') echo 'selected=1'; ?> >2017 Mai</option>
                <option value="201706" <?php if($lastMonth == '201706') echo 'selected=1'; ?> >2017 June</option>
                <option value="201707" <?php if($lastMonth == '201707') echo 'selected=1'; ?> >2017 July</option>
                <option value="201708" <?php if($lastMonth == '201708') echo 'selected=1'; ?> >2017 August</option>
            </select>
        Member Id: <input type="text" name="filter_member_id" id="filter_member_id"/>
        PayPal-Mail: <input type="text" name="filter_paypal_mail" id="filter_paypal_mail"/>
        e-mail: <input type="text" name="filter_mail" id="filter_mail"/>
        <button type="submit" id="LoadRecordsButton"><?= $this->translate('Load records'); ?></button>
        <button type="reset" id="RemoveFilterButton"><?= $this->translate('Remove filter'); ?></button>
    </form>
</div>
<div id="TableContainer"></div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#TableContainer').jtable({
            jqueryuiTheme: true,
            paging: true,
            sorting: true,
            defaultSorting: 'amount asc',
            title: 'Table of member payouts',
            actions: {
                listAction: '/backend/memberpayout/list',
                //createAction: '/backend/memberpayout/create',
                updateAction: '/backend/memberpayout/update',
                //deleteAction: '/backend/memberpayout/delete'
            },
            fields: {
                id: {
                    title: 'Id',
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                yearmonth: {
                    title: 'YearMonth',
                    width: '10%',
                    list: true,
                    create: false,
                    edit: false
                },
                member_id: {
                    title: 'Member Id',
                    list: true,
                    edit: false,
                    create: false
                },
                mail: {
                    title: 'Mail',
                    width: '5%',
                    list: true,
                    edit: false,
                    create: false
                },
                paypal_mail: {
                    title: 'PayPal Mail',
                    width: '5%',
                    list: true,
                    edit: false,
                    create: false
                },
                num_downloads: {
                    title: '#DL',
                    width: '5%',
                    list: true,
                    edit: false,
                    create: false
                },
                amount: {
                    title: 'Amount',
                    width: '5%',
                    list: true,
                    edit: false,
                    create: false
                },
                status: {
                    title: 'status',
                    width: '5%',
                    options: {'': '', '0': 'Not done yet', '1': 'Pending', '100' : 'Paid okay', '500': 'Denied', '900' : 'Error'},
                    optionsSorting: 'id',
                    list: true,
                    edit: true
                },
            },
            recordsLoaded: function (event, data) {
                for (var i in data.records) {
                    if (data.records[i].status == 100) {
                        $('#TableContainer').find(".jtable tbody tr:eq(" + i + ")").css("cssText", "background-color:green !important; color:white !important;");
                    }
                    if (data.records[i].status == 1) {
                        $('#TableContainer').find(".jtable tbody tr:eq(" + i + ")").css("cssText", "background-color:yellow !important; color:black !important;");
                    }
                    if (data.records[i].status > 100) {
                        $('#TableContainer').find(".jtable tbody tr:eq(" + i + ")").css("cssText", "background-color:red !important; color:white !important;");
                    }
                }
            },
            recordUpdated: function (event, data) {
                if (data.record) {
                    $('#YourTableContainer').jtable('load');
                }
            }
        });

        //Re-load records when user click 'load records' button.
        $('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#TableContainer').jtable('load', {
                filter_yearmonth: $('#filter_yearmonth').val(),
                filter_member_id: $('#filter_member_id').val(),
                filter_paypal_mail: $('#filter_paypal_mail').val(),
                filter_mail: $('#filter_mail').val()
            });
        });

        //Re-load records when user click 'remove filter' button.
        $('#RemoveFilterButton').click(function (e) {
            e.preventDefault();
            $('#TableContainer').jtable('load', {
                filter_yearmonth: null,
                filter_member_id: null,
                filter_paypal_mail: null,
                filter_mail: null
            });
        });

        $('#TableContainer').jtable('load');
        
        
    });
</script>