<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->headTitle($this->headTitle);

$this->tab = 'settings';

?>
<main class="user-admin-page">
    <?php include __DIR__.'/partials/userHeader_settings_top.phtml';?>
    <section class="body-wrap">
        <section class="wrapper product-page">
            <!-- PAGE BODY -->
            <section class="my-products-page">
                <!-- NAVIGATION -->
                <?php include __DIR__.'/partials/userHeader_settings.phtml';?>                
                <!-- /NAVIGATION -->

                <!-- PAGE BODY -->
                <section class="settings-page">
                    <h1 class="page-title"><?= $this->translate('Settings') ?></h1>
                    <br/>

                    <div class="pling-nav-tabs">
                        <ul class="nav nav-tabs ">
                           

                            <li class="active">
                                <a href="#form-email-panel" data-toggle="tab">
                                    <span class="glyphicon glyphicon-envelope"></span>
                                    <?= $this->translate('Emails') ?>
                                </a>
                            </li>

                            <li>
                                <a href="#form-payment-panel" data-toggle="tab">
                                    <span class="glyphicon glyphicon-usd"></span>
                                    <?= $this->translate('Payout Options') ?>
                                </a>
                            </li>

                            <li>
                                <a href="#form-github-panel" data-toggle="tab">
                                    <svg aria-hidden="true" class="octicon octicon-mark-github" height="12" version="1.1"
                                         viewBox="0 0 16 16" width="15">
                                        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                                    </svg>
                                    <span class="githublabel"><?= $this->translate('Github Developer Account') ?></span>
                                </a>
                            </li>

                           

                            <li>
                                <a href="#form-password-panel" data-toggle="tab">
                                    <span class="glyphicon glyphicon-lock"></span>
                                    <?= $this->translate('Password') ?>
                                </a>
                            </li>

                            <li>
                                <a href="#form-newsletter-panel" data-toggle="tab">
                                    <span class="glyphicon glyphicon-inbox"></span>
                                    <?= $this->translate('Newsletter') ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content row settings-main ">                        
                        <div class="tab-pane active" id="form-email-panel">
                            <section class="panel container" id="form-email">
                                <?php include __DIR__.'/partials/email.phtml';?>                                 
                            </section>
                        </div>

                        <div class="tab-pane " id="form-payment-panel">
                            <section class="panel container" id="form-payment">
                                <?php include __DIR__.'/partials/payment.phtml';?>                                  
                            </section>
                        </div>
                        
                        <div class="tab-pane " id="form-github-panel">
                            <section class="panel container" id="form-github">
                                 <?php include __DIR__.'/partials/github.phtml';?>                                   
                            </section>
                        </div>

                        <div class="tab-pane " id="form-password-panel">
                            <section class="panel container" id="form-password">
                                <?php include __DIR__.'/partials/password.phtml';?>                               
                            </section>
                        </div>

                        <div class="tab-pane " id="form-newsletter-panel">
                            <section class="panel container" id="form-newsletter">
                                <?php include __DIR__.'/partials/newsletter.phtml';?>                                  
                            </section>
                        </div>

                    </div>
                </section>
                <!-- /PAGE BODY -->
            </section>
            <!-- /PAGE BODY -->
        </section>
    </section>
</main>
<script>
    $(document).ready(function () {
        if (document.location.hash) {
            var hash = $(document.location.hash);
            $('a[href="' + document.location.hash + '"]').trigger("click");
        }
    });
</script>

<?php $this->inlineScript()->appendScript('
    $(document).ready(function(){
        ImagePreview.setup();
        PartialForms.setup();
        });
');
