<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Created: 31.05.2017
 */

?>

<link href="/theme/backend/lib/jquery-ui/themes/smoothness/jquery-ui.min.css" rel="stylesheet">
<link href="/theme/backend/lib/jtable/themes/jqueryui/jtable_jqueryui.min.css" rel="stylesheet">
<script src="/theme/backend/lib/jquery-ui/jquery-ui.min.js"></script>
<script src="/theme/backend/lib/jtable/jquery.jtable.min.js"></script>

<style type="text/css">
        img.pimage{
            float: left;            
            width: 100%;
            border: 1px solid #dbdbdb;
            border-radius: 999px;
            width: 45px;
            height: 45px;
        }
       
        div.jtable-main-container table.jtable tbody > tr > td{
            vertical-align: top;
            border-left:0px;
            border-right:0px;
            font-size: small;
        }
        div.jtable-main-container table.jtable{
            border: 0px;
        }
        div.jtable-main-container table.jtable th{
            border: 0px;
            background: none;
            font-weight: bold;
        }
        
        #products-wrapper{
            padding-bottom: 20px;
        }


        #explore-content .ui-state-default
        {
            background: none;
            border: 0px;

        }


        #explore-content div.jtable-main-container table.jtable .rating{
            width:80px; 
            margin-left:140px;
            padding-top:20px;
        }
        #explore-content div.jtable-main-container table.jtable .tooltipuser{
            color: #2673b0;
            cursor: pointer;
        }
        
        a.profileimagelink{
            cursor: pointer;
        }
        

       

</style>
<main id="explore-content">

    
  <section class="wrapper" id="products-wrapper" >

    <div id="TableContainer"></div>    
    </section>

</main>
<div class="tooltip_templates" style="display: none">
    <span id="tooltip_content">
        <i class="fa fa-spinner"></i>
    </span>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        $("#dialog-form").dialog({
            autoOpen: false,
            //height: 350,
            width: 600,
            modal: true,
            buttons: {
                Close: function () {
                    $(this).dialog("close");
                }
            }
        });


        $('#TableContainer').jtable({
            jqueryuiTheme: true,
            paging: true,
            sorting: true,                     
            actions: {
                listAction: '/backend/letteravatar/list'
            },
            fields: {
                   member_id: {
                                     title: 'member_id',
                                     key: true,
                                     create: false,
                                     edit: false,
                                     list: true  ,
                                     display: function (data) {
                                               
                                                    var html =   ' <a href="/member/' + data.record.member_id + '/" target="_blank">'+data.record.member_id+'</a>' ;                                                              
                                                    return html;
                                               
                                            }                 
                                 },
                    username: {
                                     title: 'username',                                 
                                     create: false,
                                     edit: false,
                                     list: true                   
                                 },
                    is_auto_generated: {
                                     title: 'is_auto_generated',                                 
                                     create: false,
                                     edit: false,
                                     list: true                   
                                 },
                    profile_image_url: {
                        title: 'Profile Image',                         
                        create: false,
                        edit: false,
                        list: true,     
                         width: '10%',                                   
                        display: function (data) {
                            if (data.record.profile_image_url) {
                                var html =   ' <a class="profileimagelink" data-memberid="'+data.record.member_id+'" ><img  class="pimage" src='+data.record.profile_image_url+' /></a>' ;                                                              
                                return html;
                            }
                        }
                    }
            }
        });


                
        $('#TableContainer').jtable('load',{jtPageSize:10});
    });
</script>

     