<?php

/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Created: 16.12.2016
 **/
class OAuthController extends Zend_Controller_Action
{

    /**
     * @inheritDoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->_helper->layout()->disableLayout();
        $this->_helper->viewRenderer->setNoRender(true);
    }

    public function loginAction()
    {
        //TODO: Filter param provider

        $authAdapter = Default_Model_OAuth::factory($this->getParam('provider'));
        $authAdapter->authStart($this->getParam('redirect'));
    }

    public function githubAction()
    {
        $authAdapter = Default_Model_OAuth::factory('github');

        $access_token = $authAdapter->authFinish($this->getAllParams());

        if (false == $authAdapter->isConnected()) {
            $this->_helper->flashMessenger->addMessage('<p class="text-danger center">An error occurred while trying authenticate you. Please try later or try our local login or register.</p>');
            $this->forward('index', 'explore', 'default');
        }

        $authAdapter->authenticate();
        $authAdapter->storeAccessToken($access_token);

        $this->forward('products', 'user');
    }

}