<?php
header('content-type: image/png');
require APPLICATION_LIB . "/Local/LoginCookie.php";

if (isset($_GET['k'])) {
    $key = $_GET['k'];
    $id = Local_LoginCookie::readJwt($key);
    if ($id) {
        $cookie_lifetime = (int)Zend_Registry::get('config')->resources->session->remember_me_seconds;
        /** @var Zend_Cache_Core $cache */
        $cache = Zend_Registry::get('cache');
        if ($data = $cache->load($id)) {
            $cookie_domain = Local_Tools_ParseDomain::get_domain($_SERVER['HTTP_HOST']);
            $cookie_params = session_get_cookie_params();
            setcookie($data['domain'], $data['id'], time() + $cookie_lifetime, $cookie_params['path'], $cookie_domain, $cookie_params['secure'], true);
            if (false == empty($data['remember_me'])) {
                $cookie_name = Zend_Registry::get('config')->settings->session->remember_me->name;
                setcookie($cookie_name, serialize($data['remember_me']), time() + $cookie_lifetime, $cookie_params['path'], $cookie_domain, $cookie_params['secure'], true);
            }
            $cache->remove($id);
        }
    }
}

$imagePath = APPLICATION_PATH . "/../httpdocs/img/default.png";
$image = file_get_contents($imagePath);
echo $image;