<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
use Application\Model\Entity\ProjectCategory;
$this->headTitle($this->headTitle);
/** @var \Laminas\View\Helper\ServerUrl $serverUrlPlugin */
$serverUrlPlugin = $this->plugin('serverUrl')->setUseProxy(true);
$og_server = $serverUrlPlugin->getScheme() . '://' . $serverUrlPlugin->getHost() . $_SERVER['REQUEST_URI'];

$modelCategory = $this->projectCategoryRepository;
if($this->cat_id) {
    $this->dataCategory = $modelCategory->findById($this->cat_id);
} else {
    $this->dataCategory = new ProjectCategory();
}

$catTitle = '';
if($this->dataCategory->project_category_id)
{
  $catTitle = $this->dataCategory->title;
}

if($this->filters['order'] == 'latest'){
  $og_title = 'Browse '.$catTitle.' Latest | '.$og_server;
}else if($this->filters['order'] == 'top'){
  $og_title = 'Browse '.$catTitle.' Top | '.$og_server;
}else{
  $og_title='Browse '.$catTitle.' | '.$og_server;
}
$og_description = $og_title .'| A community for free and open source software and libre content';
$og_image = 'https://' . $_SERVER['HTTP_HOST'] .$this->templateConfigData['logo'];
$this->doctype(\Laminas\View\Helper\Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:url', $og_server);
$this->headMeta()->appendProperty('og:title', $og_title);
$this->headMeta()->appendProperty('og:site_name',$og_server);
$this->headMeta()->appendProperty('og:description',$og_description);
$this->headMeta()->appendProperty('og:image',$og_image);

$this->headLink()->appendStylesheet('/theme/flatui/css/explore_index.css');


if($this->inputFilterOriginal ==1)
{
    $checkedOriginal = ' checked';
}else
{
   $checkedOriginal = '';
}

$this->filter_mode = 'filter_favourites';
$filters = array();
$filters = $this->filters;
$filters['fav']='1';
?>

<style>
  .purple{
    color:#8e44ad;
  }

  @media (max-width:720px){

    body > .panel.panel-default.pull-left {
      max-width: 100%;
      overflow-y: hidden;
    }

    #explore-content .GridFlex .content {
      padding-right: 15px;
      min-width: 400px;
    }

    #explore-content .GridFlex .sidebar-right {
      width: 400px;
      flex: none !important;
      margin: 0 auto;
    }

    #explore-content .GridFlex .content .explore-products {
      padding: 0 !important;
    }

    .explore-products .product-list .explore-product {
      position: relative;
      padding-left: 20px;
      padding-right: 50px;
    }

    .explore-products .product-list .explore-product > .col-xs-1 {
      position: absolute;
      top: 10px;
      left: 10px;
      padding: 0;
    }

    .explore-products .product-list .explore-product .explore-product-imgcolumn {
      width: 20%;
    }

    .explore-products .product-list .explore-product .explore-product-details {
      width: 80%;
    }

    .explore-products .product-list .explore-product .explore-product-plings {
      position: absolute;
      top: 10px;
      right: 0;
      width: 50px;
    }

    .explore-products .product-list .explore-product .explore-product-plings .rating {
      width: 100%;
    }

    .pling-nav-tabs ul.nav-tabs>li:last-child {
      float: right;
      padding: 10px;
      font-size: 12px;
    }

    #explore-content .sidebar-right-info .prod-widget-box {
      width: 100%;
    }

  }

  @media (max-width:611px){
    #explore-content .GridFlex .content {
      padding-right: 0;
      min-width: 100%;
    }

    #explore-content .GridFlex .sidebar-left {
      flex: none !important;
      width: 100%;
    }

    #explore-content .GridFlex .sidebar-right {
      flex: none !important;
      width: 100%;
      padding: 0;
    }
  }

  .filter_browse_tag_group {
      margin-right: 5px;
  }

</style>

<main id="explore-content">
    <section class="wrapper" id="products-wrapper">
    <span class="glyphicon  togglesidebar" id="btnTogglesidebar" ></span>
    <div class="GridFlex">
      <div class="GridFlex-cell sidebar-left" >
          <?php  $time_start = microtime(true);echo $this->render('partials/filter.phtml'); $time_elapsed = microtime(true) - $time_start; ?>
          <?php if($this->ocs_user AND $this->ocs_user->roleName == 'admin') {
             echo '<div class="alert alert-warning font-italic" role="alert"><strong>Rendering Time: </strong>'.$time_elapsed.' s</div>';
          }?>
      </div>
      <div class="GridFlex-cell content">
        <section class="explore-products" id="explore-products">

            <div class="pling-nav-tabs">
              <ul class="nav nav-tabs pling-nav-tabs" id="sort">
                  <li class="active">
                      <a><div id="fav_icon"></div><span><?= $this->translate('My Favourites') ?></span></a>
                  </li>                 
              </ul>
            </div>

              <div class="product-list">
                  <?php
                  if (count($this->products) == 0) {
                      echo '<div class="empty">No Favourites.</div>';
                  } else {
                       $time_start = microtime(true);
                       echo $this->render('partials/products-fav.phtml');
                       $time_elapsed = microtime(true) - $time_start;
                  }
                  ?>
                  <?php if($this->ocs_user AND $this->ocs_user->roleName == 'admin') {
                      echo '<div class="explore-product col-lg-12 col-md-12 col-sm-12 col-xs-12 font-italic">';
                      echo '<div class="alert alert-warning" role="alert"><strong>Rendering Time: </strong>'.$time_elapsed.' s</div>';
                      echo '</div>';
                  }?>
              </div>


              <section class="explore-footer">
                  <?php echo $this->paginationControl($this->products, 'Sliding',
                      'partials/paginationControl.phtml',
                      array('params' => $filters, 'dom_target' => 'section.explore-products', 'request' => $this->request, 'totalcount' => $this->totalcount, 'pageLimit' => $this->pageLimit, 'page' => $this->page)); ?>
              </section>
          </section>
      </div>

<?php
$time_start = microtime(true);
$asidehide = '';
            if(!$this->catabout && count($this->comments)==0  && count($topprods)==0 )
            {
                $asidehide = 'hide';
            }
            $this->show_git = false;
?>
      <div class="GridFlex-cell sidebar-right">
          <aside  id="explore-sidebar <?=$asidehide?>" >
             <?php
                echo $this->render('partials/common_rightsidebar.phtml');
            ?>

            <div  class="row sidebar-right-info" >
              <?php
              if (count($topprods) > 0) {
                  ?>
                  <span class="commentTitle"> Popularity <span class="small light"> (based on plings, downloads, etc.)</span></span>

                  <div class="prod-widget-box right bgwhite" id="mostdownloaded">
                      <?php
                      $this->rownum = 1;
                      foreach ($topprods as $this->product) {
                          echo $this->render('partials/productTop.phtml');
                          $this->rownum++;
                      }
                      ?>
                  </div>
              <?php } ?>

            </div>
        </aside>
          <?php
          $time_elapsed = microtime(true) - $time_start;
          if($this->ocs_user AND $this->ocs_user->roleName == 'admin') {
              echo '<div class="alert alert-warning font-italic" role="alert"><strong>Rendering Time: </strong>'.$time_elapsed.' s</div>';
          }?>
      </div>
    </div>
    </section>

    <div class="tooltip_templates" style="display: none">
    <span id="tooltip_content">
        <i class="fa fa-spinner"></i>
    </span>
</div>
</main>


<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
            TooltipUser.setup("tooltipuserleft","left");
            TooltipUser.setup("tooltipuser","right");            
            FilterBrowseTagGroupFn.setup();    
            PartialsButton.setup();        
        });
    ');
