<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->headTitle($this->headTitle);

$catTitle = '';
if($this->cat_id) {
  $catTitle = $this->cat_title;
} 
$store_config = $GLOBALS['ocs_store']->config;
$host = $store_config->host;
$site_name = $store_config->name;
/** @var \Laminas\View\Helper\ServerUrl $serverUrlPlugin */
$serverUrlPlugin = $this->plugin('serverUrl')->setUseProxy(true);
$og_server = $serverUrlPlugin->getScheme() . '://' . $serverUrlPlugin->getHost() . $_SERVER['REQUEST_URI'];

if($this->filters['order'] == 'latest'){
  $og_title = 'Browse '.$catTitle.' Latest | '.$og_server;
}else if($this->filters['order'] == 'top'){
  $og_title = 'Browse '.$catTitle.' Top | '.$og_server;
}else{
  $og_title='Browse '.$catTitle.' | '.$og_server;
}
$og_description = $og_title .' | A community for free and open source software and libre content';
$this->templateConfigData = $GLOBALS['ocs_store']->template;
$og_image = 'https://' . $_SERVER['HTTP_HOST'] .$this->templateConfigData['header-logo']['image-src'];
$this->doctype(\Laminas\View\Helper\Doctype::XHTML1_RDFA);

foreach ($this->headMeta as $key => $value) {
    $this->headMeta()->appendProperty($key, $value)->setAutoEscape(false);
}

$this->headMeta()->appendProperty('og:type', 'website')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:url', $og_server)->setAutoEscape(false);
$this->headMeta()->appendProperty('og:title', $og_title)->setAutoEscape(false);
$this->headMeta()->appendProperty('og:description',$og_description)->setAutoEscape(false);
$this->headMeta()->appendProperty('og:image',$og_image)->setAutoEscape(false);
$this->headMeta()->appendProperty('og:site_name',$og_server)->setAutoEscape(false);

$this->headLink()->appendStylesheet('/theme/flatui/css/explore_index.css');

$myParams = array();
if(strrpos($_SERVER['REQUEST_URI'],'/s/')===false) {
    //echo('Is not a Store');
} else {
    //echo('Is a Store');
    $myParams['store_id'] = $GLOBALS['ocs_store']->config->name;
}

?>

    <!-- PRODUCT MEDIA SLIDER CSS -->
        
    <div id="app-container"></div>

    <script type="text/javascript">
      var productBrowseData = <?php echo json_encode($this->productBrowseData)?>;
    </script>

    <script type="text/javascript" src="/theme/react/lib/jszip/jszip.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/epub/epub.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/bookblock/js/modernizr.custom.js"></script>
    <script type="text/javascript" src="/theme/react/lib/bookblock/js/jquerypp.custom.js"></script>
    <script type="text/javascript" src="/theme/react/lib/bookblock/js/jquery.bookblock.min.js"></script>
    <script type="text/javascript" src="/theme/react/bundle/app-main-bundle.js"></script>

    <?php $this->inlineScript()->appendScript(
        '    $(document).ready(function(){
                TooltipUser.setup("tooltipuserleft","left");
                TooltipUser.setup("tooltipuser","right");            
                FilterBrowseTagGroupFn.setup();
            });
        ');
