<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

// Sorry autoloader doesn't work for me
require_once(APPLICATION_PATH . '/modules/backend/models/ClientFileConfig.php');

class Backend_Model_ClientFileConfigTest extends PHPUnit_Framework_TestCase
{

    protected function setUp()
    {
        require_once APPLICATION_LIB . '/Local/Application.php';

        // Create application, bootstrap, and run
        $this->bootstrap = new Local_Application(
            APPLICATION_ENV,
            Zend_Registry::get('configuration'),
            Zend_Registry::get('cache')
        );

        $this->bootstrap->bootstrap('autoload');

        parent::setUp(); // TODO: Change the autogenerated stub

        /** @var Zend_Config $config */
        $config = new Zend_Config($this->bootstrap->getOptions(), true);
        $config->settings->client->config->path = TEST_PATH . '/_files/configs/';
        Zend_Registry::set('config', $config);
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testInitConfigReader()
    {
        $clientConfigReader = new Backend_Model_ClientFileConfig(null);
        $this->assertNull($clientConfigReader->getConfig());
    }

    public function testSetClientName()
    {
        $clientConfigReader = new Backend_Model_ClientFileConfig('test');
        $this->assertEquals('test', $clientConfigReader->getClientName());
    }

    public function testLoadClientConfig()
    {
        $clientConfigReader = new Backend_Model_ClientFileConfig(null);
        $clientConfigReader->loadClientConfig('test');
        $this->assertEquals('pling.it', $clientConfigReader->getConfig()['head']['browser_title']);
    }

    public function testGetForm()
    {
        $clientConfigReader = new Backend_Model_ClientFileConfig(null);
        $clientConfigReader->loadClientConfig('test');
        $form = $clientConfigReader->getForm();
        $this->assertInstanceOf('Zend_Form', $form);
    }

}
