<?php
header("Content-type: text/css");
if (isset($_GET['k'])) {
    $key = $_GET['k'];
    $id = Library\LoginCookie::readJwt($key);
    if ($id) {
//        $cookie_lifetime = (int)$GLOBALS['ocs_config']->resources->session->remember_me_seconds;
        $cookie_lifetime = $this->getEvent()->getApplication()->getServiceManager()->get('config')['session_config']['options']['remember_me_seconds'];
        /** @var Zend_Cache_Core $cache */
        $cache = Zend_Registry::get('cache');
        if ($data = $cache->load($id)) {
            $cookie_domain = \Library\Tools\ParseDomain::get_domain($_SERVER['HTTP_HOST']);
            $cookie_params = session_get_cookie_params();
            setcookie($data['domain'], $data['id'], time() + $cookie_lifetime, $cookie_params['path'], $cookie_domain, $cookie_params['secure'], true);
            if (false == empty($data['remember_me'])) {
                $cookie_name = $GLOBALS['ocs_config']->settings->session->remember_me->name;
                setcookie($cookie_name, serialize($data['remember_me']), time() + $cookie_lifetime, $cookie_params['path'], $cookie_domain, $cookie_params['secure'], true);
            }
            $cache->remove($id);
        }
    }
}
include APPLICATION_PATH . "/../../httpdocs/theme/flatui/css/empty.css";