<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Created: 31.05.2017
 */
$modelInfo= new Default_Model_Info();
$filter = new Local_Filter_Url_Encrypt();
$thisurl = "/";
if(isset($_GET['url'])) {
    $thisurl = $_GET['url'];
}else
{
   $thisurl= Zend_Controller_Front::getInstance()->getRequest()->getScheme() . '://' . Zend_Controller_Front::getInstance()->getRequest()->getHttpHost().$_SERVER["REQUEST_URI"];
}


$url_login = "/login/redirect/".$filter->filter($thisurl);

$sumPayment = 0;

if($this->amount_predefined == "free") {
    $sumPayment = $this->support_amount;
} else {
    $sumPayment = $this->amount_predefined;
}



?>
<link href="/theme/flatui/css/support.css" rel="stylesheet">


<style>
    .amount input {
        opacity: .95;
        margin-top: -8px;
        color: #000;
        font-size: 24px;
        width: 50%;
        margin: 0;
            margin-top: 0px;
        margin-top: 0;
        border: 0;
            border-bottom-color: currentcolor;
            border-bottom-style: none;
            border-bottom-width: 0px;
        border-bottom: 1px solid #d0d0d0;
        padding: 0;
        box-shadow: none;
        background-color: #fff;
    }
    
    .unit-wrapper {
        position: absolute;
        display: inline-block;
    }
    
    .unit-wrapper .unit {
        color: #231f20;
        opacity: .6;
        font-size: 13px;
        position: absolute;
        top: 5px;
        right: 3px;
        line-height: 10px;
    }
    
    .item-text {
        padding-left: 15px;
    }
    
    .disabled {
        cursor: not-allowed !important;
        background-color: #959595 !important;
        box-shadow: 0 2px 0 0 #404040 !important;
    }
    
    .hiddden {
        display: none !important;
    }
    
</style>

<main>
    <section class="wrapper" id="products-wrapper">
        <form class="donation-form" id="new_donation" action="<?= $this->urlPay ?>" accept-charset="UTF-8" data-remote="true" method="post">  
                <input type="hidden" id="currency-symbol" value="$">
                <input type="hidden" name="provider" value="paypal" id="provider">
        <div class="container-fluid">
            <div class="row">
                <div class="sidebar-left col-md-2"></div>
                
   
                <div class="content col-md-8">
                    <h2>Become a Supporter</h2>
                    <p>Help sustain any of the sections and the creators providing content for it (see <a href="/faq-pling">Pling FAQ</a> and <a href="/funding">Public Funding</a>).</p>
                    </p>
                    
                    
                    
                        
                        <div class="row disply-flex">
                            <div class="col-lg-12 col-md-12" style="border-top: dotted thin #E7E7E7 !important;padding-top: 35px;">  
                                
                                <div class="tabs-footer">
                                    <input type="hidden" name="amount_predefined-<?= $this->section_predefined ?>" value="">
                                    <?php 
                                        if($this->amount_predefined == "free") {
                                            echo "<input type='hidden' name='amount_handish-<?= $this->section_predefined ?>' value='<?= $this->support_amount ?>'>";
                                            echo "<input type='hidden' name='amount_predefined-". $this->section_predefined ."' value='Option7'>";
                                        } else {
                                            echo "<input type='hidden' name='amount_predefined-". $this->section_predefined ."' value='Option5'>";
                                        }
                                    ?>
                                    <input type="hidden" name="" value="">
                                    
                                    You support SECTION_NAME with $<span id="sum"><?= $sumPayment ?></span>/Month
                                    - Pay 
                                    <select name="paymentFrequenz">
                                        <option value="Y">Yearly</option>
                                        <option value="M">Monthly</option>
                                    </select>
                                    <div>
                                        <span class="extrasmall"><?=$this->calcDonationTextBoth($sumPayment)?></span>
                                    </div>

                                    
                                </div>
                            </div>
                        </div> <!--end of row-->
            
                        <div class="row disply-flex">
                              <div class="col-lg-12 col-md-12">  
                                <div class="tabs-footer">
                                    <?php if (Zend_Auth::getInstance()->hasIdentity()) {?>
                                    <button disabled="true" type="submit" id="submit" class="disabled dw-btn mdl-button mdl-js-button mdl-js-ripple-effect step-3 basic-color-background" data-upgraded=",MaterialButton,MaterialRipple">
                                    <span class="donate" id="linkButton">
                                      <span class="amount">
                                        <span isolate="">Donate via PayPal</span>
                                      </span>
                                    </span>
                                    </button>
                                     <?php }else{
                                        echo "<a href='".$url_login."'>Please login to donate</a>";
                                    }?>
                                </div>
                                    </div>
                        </div> <!--end of row-->
                    </div> <!--end of tabs-->
                    
                    
                </div> <!--end of content-->
                <div class="sidebar-right col-md-2"></div>
                
            </div>
            
        </div>
         </form>
    </section>
</main>

<script>
    
</script>