<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$licenseListHelper = new Default_View_Helper_FetchLicenseTags();
?>
<div class="form-group">
  <div class="col-sm-12 margin-top-15">
      <?php if ($this->element->isRequired()) { ?>
        <div class="small grey bold-font pull-left margin-right-5">*</div>
      <?php } ?>
    <label class="form-label" for="<?= $this->escape($this->element->getName()) ?>">License *a valid License needed for plings</label>
  </div>
  <div class="col-sm-4">
    <select class="form-control product_select_license"
            id="<?= $this->escape($this->element->getName()) ?>"
            name="<?= $this->escape($this->element->getName()) ?>">
        <option value=""></option>
        <?php
        // force $value to array so we can compare multiple values to multiple
        // options; also ensure it's a string for comparison purposes.
        $value = array_map('strval', (array)$this->element->getValue());
        $tagList = $licenseListHelper->fetchList();
        foreach ($tagList as $opt_value => $opt_label) {
            // selected?
            $opt = '';
            if (in_array((string)$opt_value, $value)) {
                $opt .= ' selected="selected"';
            }
            ?>
          <option <?= $opt ?> value="<?= $opt_value ?>"><?= $opt_label ?></option><?php
        }
        ?>
    </select>
      <?php if ($this->element->getMessages()) {
          $errorHtml = '';
          foreach ($this->element->getMessages() as $currentError) {
              $errorHtml .= '<label id="<?=$this->escape($this->element->getName())?>-error" class="error" for="<?=$this->escape($this->element->getName())?>">' . $currentError . '</label>';
          }
          ?>
          <?php echo $errorHtml ?>
      <?php } ?>
  </div>
</div>