<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$css_error = "";
if ($this->element->getMessages()) {
    $css_error = " bg-danger";
}
?>
<div class="form-group">
    <div class="col-sm-12 margin-top-15<?=$css_error?>">
        <div class="small grey bold-font pull-left margin-right-5">*</div>
        <label class="form-label" for="<?= $this->escape($this->element->getName()) ?>">Gallery Pictures (5MB, max. 5 pictures)</label>
    </div>
    <div class="col-sm-12<?=$css_error?>">
        <?php
        echo $this->content;
        ?>
    </div>
</div>