<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<?php if($this->step ==0) {?>
	<h3>Number of all not yet importetd projects: <?= $this->coutAll ?></h3>
	
	
	<form action="/backend/hive">
	<input type="hidden" name="step" value="10">
	<button>Go to next step</button>
	</form>
	
	<br/><br/><br/><br/>
	<p>Info: <?= $this->info ?></p>


<?php } else if($this->step ==10) {?>


	<h3>Step 1 - Hive-Categories: </h3>
	
	<form action="/backend/hive">
	<input type="hidden" name="step" value="20">
	<input type="text" name="cat_ids" value="" size="100">
	<button>Next</button>
	</form>
	
	
	<br/><br/><br/><br/>
	<p><a href="/backend/hive">Back to Start</a></p>
	<p>Info: <?= $this->info ?></p>
<?php } else if($this->step ==20) {?>


	<h3>Step 2 - Overview Import: </h3>
	
	<p><b>- Hive-Categories: <?= $this->cat_ids?></b></p>
	
	<ul>
	
	<?php 
		$catArray = $this->categories;
		foreach ($catArray as $cat) {
			echo '<li>Hive-Cat-Id: '.$cat['id'].' - '.$cat['desc'].' - Ocs-Cat-Id: '.$cat['ocs_cat_id'].'</li>';
		}
	?>
	</ul>
	 
	<form action="/backend/hive">
	<input type="hidden" name="step" value="30">
	<input type="hidden" name="cat_ids" value="<?= $this->cat_ids ?>">
	<p><input type="checkbox" name="import_previews"> Import Gallery-Pics?</p>
	<p><input type="checkbox" name="import_files"> Import Files?</p>
	
	<button>Start Import</button>
	</form>
	
	
	<br/><br/><br/><br/>
	<p><a href="/backend/hive">Back to Start</a></p>
	<p>Info: <?= $this->info ?></p>

<?php } else if($this->step ==30) {?>


	<h3>Step 3 - Import...</h3>
	<h4><span id="info_text"></span></h4>
	<p><span id="info"></span></p>
	<br/><br/><br/><br/>
	<p>Info: <?= $this->info ?></p>
	
	
	<script type="text/javascript">
		catIds = '<?= $this->cat_ids ?>';
		catList = catIds.split(',');
		startImport(catList,0,5,0,2000);
	
		
		var importCounter = 0;
		var errorCounter = 0;
		function startImport(cat_ids, index, limit, sum_now, sum_all) {
			if(index>=cat_ids.length) {
				$('#info_text').html('<b>Import Done! Imported ' + importCounter + ' projects. <p><a href="/backend/hive">Back to Start</a></p></b>');
				return false;
			}
			cat_id = cat_ids[index];
			
			if(null != cat_id) {
				
		        var url_string = '/backend/hive/start-import-all-ajax?cat_id='+cat_id+'&limit='+limit+'&import_files=<?= $this->import_files ?>&import_previews=<?= $this->import_previews ?>';
		
		        jQuery.ajax({
		            url: url_string,
		            type: 'get',
		            error: function () {
		            	errorCounter++;
		            	if(errorCounter<100) {
		            		startImport(cat_ids,index,limit, sum_now, sum_all);
		            	} else {
		            		//alert("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
		            		index++;
		                	startImport(cat_ids,index,limit, 0, sum_all);
		            	}
		                return false;
		            },
		            success: function (results) {
			            
		            	sum_now =  sum_now + limit;
		            	
		            	
		                is_done = results['IsImportDone'];
		                newOffset = results['offset'];
		                newLimit = results['limit'];
		                counter = results['ImportCounter'];
		                totalCounter = results['TotalCounter'];
		                importCounter = importCounter + counter;

		                if(sum_all == 0) {
				            sum_all = totalCounter;
			            }
		                
		                //$('#info_text').html('<b>' + results['ImportCounter'] + ' projects with ' + results['ImportFileCounter'] + ' files imported!</b>');
		            	$('#info_text').html('<b>Imported ' + importCounter + ' projects. ' + totalCounter + ' projects left.</b>');
		                if(is_done && counter>0 && sum_now<sum_all) {
		                	
		                	//abortTimer();
		                	//alert('Done');
		                	$('#info').html(results['Message']);
		                	//startImport(0,25);
		                	startImport(cat_ids,index,limit, sum_now, sum_all);
		                	
		                } else {
		                	index++;
		                	startImport(cat_ids,index,limit, 0, sum_all);
		                }
		                return false;
		            }
		        });
			}
		}
	</script>	
	
<?php } else if($this->step ==1) {?>


	<h3>Step 1: Hive-Category</h3>
	
	<form action="/backend/hive">
	<input type="hidden" name="step" value="2">
	<p>Please select hive category:</p>
	<select id="cat_id" name="cat_id" style="height: 25px;">
		<option></option>
	<?php 
		$catArray = $this->categories;
		foreach ($catArray as $cat) {
			echo '<option value="'.$cat['id'].'">'.$cat['desc'].'</option>';
		}
	?>
	</select>
	<button>Next</button>
	</form>
	<br/><br/>
	<span id="info_text"></span>
	
	<br/><br/><br/><br/>
	<p><a href="/backend/hive">Back to Start</a></p>
	<p>Info: <?= $this->info ?></p>
	<script type="text/javascript">
	    $('body').on("change", 'select', function (event) {
	        event.preventDefault();
	        event.stopImmediatePropagation();
	
	        var url_string = '/backend/hive/count?cat_id=' + $('#cat_id').val();
	
	        jQuery.ajax({
	            url: url_string,
	            type: 'get',
	            error: function () {
	                alert("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
	                return false;
	            },
	            success: function (results) {
	                $('#info_text').html('<b>' + results['TotalRecordCount'] + ' projects</b>');
	                return false;
	            }
	        });
	
	        return false;
	    });
	
	</script>
<?php } else if($this->step ==2) {?>


	<h3>Step 2 - OCS-Category: </h3>
	
	<form action="/backend/hive">
	<input type="hidden" name="step" value="3">
	<input type="hidden" name="cat_id" value="<?= $this->cat_id ?>">
	<p>Please select the target ocs category for hive-category <?= $this->cat_desc ?></p>
	<select name="ocs_cat_id" style="height: 25px;">
	<?php 
		$catArray = $this->categories;
		foreach ($catArray as $cat) {
			echo '<option value="'.$cat['id'].'">'.$cat['desc'].'</option>';
		}
	?>
	</select>
	<button>Next</button>
	</form>
	
	
	<br/><br/><br/><br/>
	<p><a href="/backend/hive">Back to Start</a></p>
	<p>Info: <?= $this->info ?></p>
<?php } else if($this->step ==3) {?>


	<h3>Step 3 - Summary</h3>
	
	<p><b>- Hive-Category: <?= $this->cat_desc ?> (id = <?= $this->cat_id ?>)</b></p>
	<p><b>- OCS-Category: <?= $this->ocs_cat_desc ?> (id = <?= $this->ocs_cat_id ?>)</b></p>
	<p><b>- We will import files from <?= $this->count?> Hive-Projects</b></p>
	
	<form action="/backend/hive">
	<input type="hidden" name="step" value="4">
	<input type="hidden" name="cat_id" value="<?= $this->cat_id ?>">
	<input type="hidden" name="ocs_cat_id" value="<?= $this->ocs_cat_id ?>">
	
	<p><input type="checkbox" name="import_previews"> Import Gallery-Pics?</p>
	<p><input type="checkbox" name="import_files"> Import Files?</p>
	
	<button>Start Import</button>
	</form>
	
	
	<br/><br/><br/><br/>
	<p><a href="/backend/hive">Back to Start</a></p>
	<p>Info: <?= $this->info ?></p>
<?php } else if($this->step ==4) {?>


	<h3>Step 4 - Import...</h3>
	<h4><span id="info_text"></span></h4>
	<p><span id="info"></span></p>
	<br/><br/><br/><br/>
	<p>Info: <?= $this->info ?></p>
	
	
	<script type="text/javascript">
		startImport(0,25);
		var importCounter = 0;
		var errorCounter = 0;
		function startImport(offset, limit) {
			
	        var url_string = '/backend/hive/start-import-ajax?cat_id=<?= $this->cat_id ?>&ocs_cat_id=<?= $this->ocs_cat_id ?>&import_files=<?= $this->import_files ?>&import_previews=<?= $this->import_previews ?>&limit='+limit+'&offset='+offset;
	
	        jQuery.ajax({
	            url: url_string,
	            type: 'get',
	            error: function () {
	                //alert("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
	                //$('#info_text').html('<b>Status: ERROR ' + results['Message'] + '</b>');
	                //abortTimer();
	            	errorCounter++;
	            	if(errorCounter<100) {
	            		startImport(0,25);
	            	} else {
	            		alert("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
	            	}
	                return false;
	            },
	            success: function (results) {
	            	
	                is_done = results['IsImportDone'];
	                newOffset = results['offset'];
	                newLimit = results['limit'];
	                counter = results['ImportCounter'];
	                totalCounter = results['TotalCounter'];
	                importCounter = importCounter + counter;
	                //$('#info_text').html('<b>' + results['ImportCounter'] + ' projects with ' + results['ImportFileCounter'] + ' files imported!</b>');
	            	$('#info_text').html('<b>Imported ' + importCounter + ' projects. ' + totalCounter + ' projects left.</b>');
	                if(is_done && counter>0) {
	                	
	                	//abortTimer();
	                	//alert('Done');
	                	$('#info').html(results['Message']);
	                	startImport(0,25);
	                } else if(is_done && counter==0) {
	                	$('#info_text').html('<b>Import Done! Imported ' + importCounter + ' projects. <p><a href="/backend/hive">Back to Start</a></p></b>');
	                }
	                return false;
	            }
	        });
		}

        // set timeout
        //var tid = setTimeout(getStatus, 2000);
        function getStatus() {
          // do some stuff...
        	var url_string = '/backend/hive/import-status-ajax';
        	var is_done = false;
            jQuery.ajax({
                url: url_string,
                type: 'get',
                error: function () {
                    alert("<span class='error'>Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.</span>");
                    abortTimer();
                    $('#info_text').html('<b>Status: ERROR ' + results['Message'] + '</b>');
                    return false;
                },
                success: function (results) {
                    $('#info_text').html('<b>Status: import project ' + results['ImportCounter'] + ' of ' + results['ProjectCounter'] + ' projects</b>');
                    is_done = results['IsImportDone'];
                }
            });

            if(is_done) {
            	abortTimer();
            } else {
            	tid = setTimeout(getStatus, 2000); // repeat myself
            }
        	
        }
        function abortTimer() { // to be called when you want to stop the timer
          clearTimeout(tid);
        }

        
	</script>
	
<?php }?>

