<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperImage = new Default_View_Helper_Image();
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
$this->tab = 'settings';
?>
<main class="user-admin-page">

    <section class="head-wrap">

        <!-- HEADER -->

        <section class="wrapper about-me-header">

            <figure>
                <img src="<?php echo $helperImage->Image($this->member->profile_image_url,array('width' => 110, 'height' => 110, 'crop' => 2)); ?>" alt="profile-image" width="110" height="110">
            </figure>

            <div class="user-menu well">

                <div class="pull-left">
                    <div class="intro">
                        <div class="large">Hi
                            <span class="lightblue"><?php echo $this->member->username; ?></span><?= $this->translate(', welcome to your personal start page!') ?>
                        </div>
                        <div class="small lightgrey">
                            <a href="<?php echo $helpMemberUrl->buildMemberUrl($this->member->member_id); ?>"><?= $this->translate('Click here to go to your About Me page.') ?></a>
                        </div>
                    </div>
                </div>

            </div>

        </section>

        <!-- /HEADER -->

    </section>

    <section class="body-wrap">

        <section class="wrapper product-page">

            <!-- PAGE BODY -->

            <section class="my-products-page">

                <!-- NAVIGATION -->

                <?php echo $this->render('user/partials/userHeader.phtml'); ?>

                <!-- /NAVIGATION -->

                <!-- PAGE BODY -->
                <section class="settings-page">

                    <h1 class="page-title"><?= $this->translate('Settings') ?></h1>
                    <hr/>
                    <div class="row settings-options">
                        <!-- main setting panel -->
                        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 settings-main panel-group" id="accordion">
                            <!-- edit profile -->
                            <section class="panel panel-default" id="form-profile">
                                <?php echo $this->render('settings/partials/profile.phtml'); ?>
                            </section>
                            <!-- /edit profile -->
                            <!-- edit emails -->
                            <section class="panel panel-default" id="form-email">
                                <?php echo $this->render('settings/partials/email.phtml'); ?>
                            </section>
                            <!-- /edit emails -->
                            <!-- edit payments -->
                            <section class="panel panel-default" id="form-payment">
                                <?php echo $this->render('settings/partials/payment.phtml'); ?>
                            </section>
                            <!-- /edit payments -->
                            <!-- edit github -->
                            <section class="panel panel-default" id="form-github">
                                <?php echo $this->render('settings/partials/github.phtml'); ?>
                            </section>
                            <!-- /edit github -->
                            <!-- edit connceted accounts -->
                            <section class="panel panel-default" id="form-connected-accounts">
                                <?php echo $this->render('settings/partials/accounts.phtml'); ?>
                            </section>
                            <!-- /edit connected accounts -->
                            <!-- edit avatar -->
                            <section class="panel panel-default" id="form-picture">
                                <?php echo $this->render('settings/partials/picture.phtml'); ?>
                            </section>
                            <!-- /edit avatar -->
                            <!-- edit password -->
                            <section class="panel panel-default" id="form-password">
                                <?php echo $this->render('settings/partials/password.phtml'); ?>
                            </section>
                            <!-- /edit password -->
                            <!-- edit website -->
                            <section class="panel panel-default" id="form-website">
                                <?php echo $this->render('settings/partials/website.phtml'); ?>
                            </section>
                            <!-- /edit website -->
                            <!-- edit newsletter -->
                            <section class="panel panel-default" id="form-newsletter">
                                <?php echo $this->render('settings/partials/newsletter.phtml'); ?>
                            </section>
                            <!-- /edit newsletter -->
                            <!-- delete account
                            <section class="panel panel-default panel-danger" id="form-delete-account">
                                <?php //echo $this->partial('settings/partials/delete.phtml'); ?>
                            </section>
                             /delete account -->

                        </div>
                        <!-- /settings main -->
                    </div>

                </section>
                <!-- /PAGE BODY -->

            </section>

            <!-- /PAGE BODY -->

        </section>

    </section>

</main>
<script type="application/javascript">
    var SettingsExpand = (function () {
        return {
            setup: function () {
                $('.panel-heading').on('click', function () {

                    var this_panel = $(this).parents('.panel');
                    var this_panel_body = this_panel.find('.panel-collapse');

                    if (this_panel_body.hasClass('in')) {
                        $(this).removeClass('active');
                    } else {
                        $(this).addClass('active');
                    }

                });
            }
        };
    })();

    var InputAvatar = (function () {
        return {
            setup: function () {
                $('body').on("change", 'input.avatar', function (event) {
                    event.preventDefault();
                    var username = this.value;
                    var dataHref = $(this).attr("data-href");
                    var target = $(this).attr("data-target");
                    var dataFunc = $(this).attr("data-func");
                    var dataSrc = $(this).data('src');

                    if (dataFunc) {
                        var funcCall = dataFunc + '(\'' + username + '\')';
                        username = eval(funcCall);
                    }

                    var imageSrc = dataHref.replace('{username}', username);
                    $(target).attr('src', imageSrc);
                    $('#profile_img_src').val(dataSrc);

                    return false;
                });
                $('body').on("change", 'input#profile_picture_upload', function (event) {
                    event.preventDefault();
                    $('#profile_img_src').val('local');
                });
            }
        }
    })();

    SettingsExpand.setup();
    InputAvatar.setup();
    
</script>


<script>
    $(document).ready(function(){
        if(document.location.hash) {
            $myform = $(document.location.hash);
            var this_panel = $myform.parents('.panel');
            this_panel.addClass('in');
            var this_header = this_panel.find('.panel-heading');
            this_header.addClass('active');
            var this_body = this_panel.find(document.location.hash);
            this_body.addClass('in');
        }
    });

</script>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
            ImagePreview.setup();
            PartialForms.setup();
        });
    ');
