<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperImage = new Default_View_Helper_Image();
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
$this->tab = 'supporterbox';
$totalcnt = $this->supporters->getTotalItemCount();
?>
<main class="user-admin-page">
    <?php echo $this->render('user/partials/userHeader_top.phtml'); ?>
    <section class="body-wrap">
        <section class="wrapper product-page">
            <!-- PAGE BODY -->
            <section class="my-products-page">
                <!-- NAVIGATION -->
                <?php echo $this->render('user/partials/userHeader.phtml'); ?>
                <!-- /NAVIGATION -->

                 <section class="supporterboxsection">
                        
                            <h1 class="page-title">
                             supporter box
                            </h1>

                        <div style="width: 600px; height: 800px">
                            <div class="supporter-box-container">
                                <div class="supporter-box-top">
                                    
                                        <div class="title">
                                            <a target="_blank" href="<?php echo $this->buildMemberUrl($this->member->username); ?>"
                                               title="<?php echo $this->member->username; ?>"><?php echo $this->member->username; ?></a>
                                        </div>
                                        <figure>
                                            <a target="_blank" href="<?php echo $this->buildMemberUrl($this->member->username); ?>"
                                               title="<?php echo $this->member->username; ?>">
                                                <img
                                                    class="profileimage"                                                    
                                                    src="<?php echo $helperImage->Image($this->member->profile_image_url, array('width' => 80, 'height' => 80)); ?>"
                                                    alt="<?php echo $this->member->username; ?>"/>
                                            </a>
                                        </figure>
                          
                                      
                                    </div>
                                  
                           
                                <div class="supporter-box-body">
                                    <div class="info">
                                        <em class="icon pling-icon-gold"></em>
                                        <span>opendesktop.org</span>
                                        <span><?php                                         
                                        echo $totalcnt; ?> Supporters</span>
                                    </div>
                                    <div class="supporters">
                                        <?php
                                        if ( $totalcnt== 0) {
                                            echo $this->translate('supporterbox.beFirstSupporter');
                                        } else {
                                            $helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
                                            foreach ($this->supporters as $supporter) { ?>
                                                <figure>
                                                    <a target="_blank"
                                                       href="<?php echo $helperBuildMemberUrl->buildMemberUrl($supporter['username']); ?>"
                                                       title="<?php echo $supporter['username']; ?>">
                                                        <img src="<?php echo $supporter['profile_image_url']; ?>"
                                                             alt="<?php echo $supporter['username']; ?>">
                                                    </a>
                                                </figure>
                                            <?php }
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                 </section>
                <!-- /PAGE BODY -->
            </section>
            <!-- /PAGE BODY -->
        </section>
    </section>
</main>

<style type="text/css">
    .supporter-box-container .supporter-box-top figure a {
        overflow:visible;
    }
    .profileimage{
        border: 1px solid #dbdbdb;
        border-radius: 999px;
    }

    .supporter-box-container .supporter-box-top figure{
        border:0px;
    }
   .supporter-box-container .supporters img{
        border: 1px solid #dbdbdb;
        border-radius: 999px;

    }
</style>


<?php $this->inlineScript()->appendScript('
    $(document).ready(function(){
    
        });
');
