<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$users = $this->newUsers($limit = 216,'created_at','DESC');
$this->inlineScript()->appendFile('/theme/flatui/js/lib/bootstrap-validator.min.js');
?>
<style>
    main#reg-page section#register-wrap {
        z-index: 1000;
    }

    div.checkbox input[type="checkbox"] {
        margin-top: -0.2em;
    }

    div.checkbox input[type="checkbox"]:checked {
        background-color: gray;
    }

    @media (max-width: 767px) {
        main#reg-page section#register-wrap {
            position: absolute;
            top: 150px;
            margin: 0;
            width: 90%;
            left: 5%;
        }

        main#reg-page section#register-wrap button#login {
            margin-top: 8px;
            width: 100%;
        }

        main#reg-page section#register-wrap #register #register-box {
            width: 100%;
        }

        main#reg-page section#register-wrap #register #social-register {
            float: right;
            width: 100%;
            padding: 0;
        }

        main#reg-page section#register-wrap #register #social-register #social-login-elements {
            margin: 0;
        }
    }

    /* style for form errors */
    form ul {
        list-style-type: none;
        padding: 0px;
        margin: 0px 5px;
    }

    form ul li {
        color: red;
    }

    .form-group {
        position: relative;
    }

</style>

    <!-- new code -->
    <main id="reg-page">

        <section class="wrapper" id="register-wrap">
            <div id="register" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
                <div id="register-box" class="col-lg-8 col-md-8 col-sm-8 col-xs-8">

                    <div id="login-form-box" class="well" style="width:100%;">
                        <h3><?= $this->translate('Please type in your new password.') ?></h3>

                        <div id="help-block" class="help-block">
                            <?= $this->translate('') ?>
                        </div>
                        <div id="error" class="center text-error help-block">
                            <?php if ($this->error && isset($this->errorText)): ?>
                                <p class="errors">
                                    <?= $this->translate($this->errorText) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                        <form id="passwordForm" class="standard-form row-fluid center" action="<?=$this->action?>" method="post" role="form" data-toggle="validator">
                            <?php
                            if ($this->error) {
                                $this->form->mail->class = $this->form->mail->class . ' has-error';
                            }
                            ?>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('new_password')); ?>
                                <?= $this->formElement($form->get('new_password')); ?>
                                <?= $this->formElementErrors($form->get('new_password')); ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('confirm_new_password')); ?>
                                <?= $this->formElement($form->get('confirm_new_password')); ?>
                                <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
                            </div>
                            <?= $this->formElement($form->get('csrf')) ?>
                            <?= $this->formElementErrors($form->get('csrf')); ?>

                            <button name="change_it" id="change_it" type="submit" class="btn btn-min-width btn-native">Change Password <i id="load-state" class="fa fa-spinner fa-pulse hidden" aria-hidden="true"></i></button>

                        </form>

                    </div>

                </div>
                <!-- END #login-box -->
                <div id="social-register" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <h3></h3>

                    <div class="bottom">
                        <div id="show-login-description" class="small light lightgrey">Already have an account?</div>
                        <div class="login2">
                            <a href="<?=$this->url('application_login')?>"
                               id="show-login-form"
                               class="btn btn-native btn-min-width" rel="nofollow">
                                <i class="icon-white icon-lock"></i>
                                Login
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="thumbs">
            <?php foreach ($users as $key => $user) { ?>
                <div class="thumb">
                    <a href="<?php //echo $buildMemberUrl->buildMemberUrl($user['username']); ?>"
                       title="<?= $user->profile_image_url ?>">
                        <span></span>
                        <img src="<?php echo $this->Image($user->profile_image_url, array('width' => 110, 'height' => 110, 'crop' => 2)); ?>" />
                    </a>
                </div>
            <?php } ?>
        </section>

    </main>
    <!-- /new code -->