<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$users = $this->newUsers($limit = 216,'created_at','DESC');
?>

    <!-- new code -->
    <main id="reg-page">

        <section class="wrapper" id="register-wrap">
            <div id="register" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
                <div id="register-box" class="col-lg-8 col-md-8 col-sm-8 col-xs-8">

                    <div id="login-form-box" class="well" style="width: 100%">
                        <h3>Forgot your password?</h3>

                        <div id="help-block" class="help-block">
                            Please provide the email of the account you like to recover and instructions how to reset your password will be emailed to you:    </div>
                        <div id="error" class="center text-error help-block">
                        </div>
                        <form class="standard-form row-fluid center" action="/password/request" method="post">

                            <div class="form-group has-feedback">
                                <input name="mail" id="mail" value="" placeholder="Email" type="email" required style="width: 100%;"></div>
                            <button name="send" id="send" type="submit" class="btn btn-min-width btn-native">Request password reset</button>
                        </form>

                    </div>

                </div>
                <!-- END #login-box -->
                <div id="social-register" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <h3></h3>

                    <div class="bottom">
                        <div id="show-login-description" class="small light lightgrey">Already have an account?</div>
                        <div class="login2">
                            <a href="<?=$this->url('application_login')?>"
                               id="show-login-form"
                               class="btn btn-native btn-min-width" rel="nofollow">
                                <i class="icon-white icon-lock"></i>
                                Login
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="thumbs">
            <?php foreach ($users as $key => $user) { ?>
                <div class="thumb">
                    <a href="<?php //echo $buildMemberUrl->buildMemberUrl($user['username']); ?>"
                       title="<?= $user->profile_image_url ?>">
                        <span></span>
                        <img src="<?php echo $this->Image($user->profile_image_url, array('width' => 110, 'height' => 110, 'crop' => 2)); ?>" />
                    </a>
                </div>
            <?php } ?>
        </section>

    </main>
    <!-- /new code -->