<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */

    use Laminas\Uri\Uri;
    use Laminas\View\Helper\Doctype;

    $this->headTitle($this->headTitle, 'SET');
    $uri = $_SERVER['REQUEST_URI'];
    $redirect = new Uri($_SERVER['REQUEST_URI']);
    $redirect->setHost(null)->setScheme(null);      
    $description_meta = strip_tags($this->product->description);
    
    $this->doctype(Doctype::XHTML1_RDFA);

    $this->headMeta()->setName('description', $this->truncate($description_meta, 200, '...', false, true))->setAutoEscape(false);
    $this->headMeta()->setName('title', $this->truncate($this->product->title, 200, '...', false, true))->setAutoEscape(false);
    $this->headMeta()
        ->appendProperty('og:url', $this->buildProductUrl($this->product->project_id, '', null, true))
        ->setAutoEscape(false);
    $this->headMeta()->appendProperty('og:type', 'website')->setAutoEscape(false);
    $this->headMeta()->appendProperty('og:title', $this->product->title)->setAutoEscape(false);
    $this->headMeta()
        ->appendProperty('og:description', $this->truncate($description_meta, 200, '...', false, true))
        ->setAutoEscape(false);
    $this->headMeta()
        ->appendProperty('og:image', $this->Image($this->product->image_small, array('width' => 400, 'height' => 400)))
        ->setAutoEscape(false);
    
    $jsonTree = json_encode($this->categories);      
?>
    
    <style>
        #media-slider .carousel-control {
            /* Firefox */
            height: -moz-calc(100% - 75px) !important;
            /* WebKit */
            height: -webkit-calc(100% - 75px) !important;
            /* Opera */
            height: -o-calc(100% - 75px) !important;
            /* Standard */
            height: calc(100% - 75px) !important;
        }

        .is-mobile .video-react-video {
            height: 100% !important;
        }

    </style>

    <div id="product-view-container"></div>

    <script type="text/javascript">       

        var productViewData = <?php echo json_encode($this->productViewData); ?>;   
       
        <?php
            $productViewData = json_encode($this->productViewData);            
            $productViewDataEncoded = base64_encode($productViewData);
            echo "var productViewDataEncoded = '{$productViewDataEncoded}';";

            $catIdExists = isset($this->product) ?$this->product->project_category_id : "null";
            echo "var categoryId = {$catIdExists};";            
            $store_config = $GLOBALS['ocs_store']->config;
            $is_show_real_domain_as_url = $store_config->is_show_real_domain_as_url;
            echo "var is_show_real_domain_as_url = $is_show_real_domain_as_url;";
            echo "var cat_tree_filter = '$this->filter_mode';";
            echo "var tag_group_filter = null;";                                   
        ?>
            // cat tree vars   
        var catTree = <?= json_encode($this->categories) ?>;
        var tagCloud = productViewData.categoriesTopTags;
            
        function b64_to_utf8( str ) {
        return decodeURIComponent(escape(window.atob( str )));
        }
    </script>
    
    <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
    <script type="text/javascript" src="/theme/react/lib/swiper/swiper.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/jszip/jszip.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/epub/epub.min.js"></script>
    <script type="text/javascript" src="/theme/react/lib/bookblock/js/modernizr.custom.js"></script>
    <script type="text/javascript" src="/theme/react/lib/bookblock/js/jquerypp.custom.js"></script>
    <script type="text/javascript" src="/theme/react/lib/bookblock/js/jquery.bookblock.min.js"></script>
    <script type="text/javascript" src="/theme/react/bundle/product-view-bundle.js"></script>
    