<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$color = $this->fetchScoreColor($this->score/10);
$ss = explode(".", number_format($this->score/10,1));
$r = $this->r;
$strokeDasharray = 2*3.14159*$r;
$strokeDashoffset = 2*3.14159*$r*(1-$this->score/100);

?>
<div class="bmIcXH" style="width:<?=$r+2?>px; height:<?=$r+2?>px">
    <svg xmlns="http://www.w3.org/2000/svg" width="<?=$r+2?>" height="<?=$r+2?>" viewBox="0 0 <?=$r*2?> <?=$r*2?>" class="donMiK">
        <circle fill="#fff" cx="50%" cy="50%" r="<?=$r?>"></circle>
        <circle stroke="#eceded" fill="transparent" cx="50%" cy="50%" r="<?=$r?>" stroke-width="14"></circle>
        <circle fill="transparent" cx="50%" cy="50%" r="<?=$r?>" 
                stroke-dasharray="<?=$strokeDasharray?>" 
                stroke-dashoffset="<?=$strokeDashoffset?>" 
                stroke-width="14" 
                stroke = "<?php echo $color;?>"
                class="cnGKWN"></circle>
    </svg>
    <div class="kaLHBk">
        <div class="kkSWyw" style="color:<?php echo $color?>; font-size:<?=($this->fontSize?$this->fontSize:2.4).'em'?>">
<span><?=$ss[0]?></span><?php if((int)$ss[0]<10):?><span class="jdsHLZ">.<?=$ss[1]?></span><?php endif;?>
        </div>
    </div>
</div>
  