<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

if ($this->pageCount): ?>
<span class="glyphicon glyphicon-refresh spinning" style="display: none"></span> 
     <div>
         <ul class="pagination">
             <!-- Previous page link -->
             <?php if (isset($this->previous)):                                          
                ?>
                 <li>
                     <a class="paginationPartial" href="<?php echo $this->url($this->route, array('action'=>$this->action,'username'=>$this->username,'page' => $this->previous),true) ?>">
                         <<
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <<
                     </a>
                 </li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current):                                                           
                    if($this->action)
                    {                                                                  
                        $url = $this->url($this->route,array('action'=>$this->action,'username'=>$this->username,'page'=>$page),true);                                            
                    }else{
                        $url = $this->url($this->route,array('username'=>$this->username,'page'=>$page),true);                                            
                    }                    
                    ?>
                     <li>
                         <a  class="paginationPartial" href="<?php echo $url ?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="active">
                         <a href="#"><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)):                                       
                ?>
                 <li>
                     <a class="paginationPartial" href="<?php echo $this->url($this->route, array('action'=>$this->action,'username'=>$this->username,'page'=>$this->next),true) ?>">
                         >>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         >>
                     </a>
                 </li>
             <?php endif; ?>
         </ul>
     </div>
 <?php endif; ?>

 <script type="application/javascript">
    $(document).ready(function () {
        var target = '<?=$this->dom_target?>';          
        $(target).off('click', 'ul.pagination a.paginationPartial').on('click', 'ul.pagination a.paginationPartial',function(event) {
                event.preventDefault();                         
                var url = $(this).attr("href")+ ' ' + target + ' > *';  
                 
                $('html, body').scrollTop($(target).offset().top);                   
                $(target).find('.glyphicon.glyphicon-refresh.spinning').show();
                $(target).load(url, function (response, status, xhr) {
                    if (status == "error") {
                        $(target).empty().html('Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.');
                    }                  
                });          
                return false;
           });                    
    });
</script>