<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
    $i = 0;
    foreach ($this->collection_projects as $project): 
        $project=(object)$project;
        $i++;
?>
<div class="row smaller " style="padding-bottom: 10px;border-bottom: 1px solid lightgray;margin-top: 10px;" >
        <div class="col-lg-1 col-md-1">
            <figure>
                <?= $i ?>.
            </figure>   
        </div> 
        <div class="col-lg-5 col-md-5">
            <figure>
                <img src="<?php echo $this->Image($project->image_small, array('width' => 80, 'height' => 80)); ?>" class="downloadhistory-image" />
            </figure>   
            <div>
                <a href="<?= $this->buildProductUrl($project->project_id) ?>"><?=$project->title?></a>
                
            </div>
        </div>      
                    
        <div class="col-lg-2 col-md-2">  
            <!--
            <div class="rating text-center" >               
                <?php                
                        $this->widgetRating = new stdClass();
                        $this->widgetRating->project_id =$project->project_id;
                        $this->widgetRating->laplace_score = null;
                        $this->widgetRating->count_likes =$project->count_likes; 
                        $this->widgetRating->count_dislikes =$project->count_dislikes;
                        echo $this->render('partials/widgetRating.phtml'); 
                ?>          
            </div>            
            -->
        </div>

        <div class="col-lg-3" >                                                                    
            <!--
                    <?=$this->printDate($project->created_at)?>
            -->
        </div>

      </div>

 <?php endforeach; ?>

 