<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
    

<?php 
        foreach ($this->projectplings as $user) {                                  
    ?>
            <div class="u-wrap">                
                   
                    <a href="<?php echo $this->buildMemberUrl($user['username']); ?>" class="tooltipuser"  data-tooltip-content="#tooltip_content" role="button" data-user="<?=$user['member_id'] ?>">
                    <img src="<?php echo $this->Image($user['profile_image_url'], array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
                    </a>                   
                    <div class="username"><?php echo Default_Model_HtmlPurify::purify($user['username']); ?></div>                                                                   
                
                <div class="bottom-title">
                    <img src="/images/system/pling-btn-active.png" style="width: 20px; height: 20px" /> <?= $this->printDate($user['created_at'])?>
                </div>
            </div>
        
<?php } ?>
