<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/


?>
<main id="plings-page">   
    <section class="body-wrap" id="cat-list">
        <section class="wrapper">
        	<div class="row title">
        	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	        	<span class="label lable-default left">
	        		
	        	</span>
        		<span class="label lable-default right" >
        			Pling Factor
        		</span>
        	</div>
        	</div>            
            <?php
            $categories = $this->listCategories();
            foreach ($categories as $key => $element) {                                	                                    
                $depth = (int)$element['depth'];
                $cls = 'depth'.$depth;
                $countSubCat = (int)$element['rgt'] - (int)$element['lft'] - 1;
                $plingFactor='';
                if($countSubCat==0){
                	$plingFactor = '<span class="right factor">'. $element['dl_pling_factor'].'</span>';                                       
                }
                echo '<div class="row">'; 
                echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 '.$cls.'">' . $this->translate($element['title']) 
                      . $plingFactor.'</div>';                                                                                
                echo '</div>';
            }
            ?>
                          
            </div>
        </section>
    </section>
</main>
