<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.opendesktop.org');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'opendesktop.org');
$this->headMeta()->appendProperty('og:site_name','www.opendesktop.org');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.opendesktop.org/images/system/opendesktop-logo.png');

$modelInfo = new Default_Model_Info();
$this->comments = $modelInfo->getLatestComments(10);
//$this->users = $modelInfo->getNewActiveMembers(18);
//$this->supporters = $modelInfo->getNewActiveSupporters(9);
//$this->plingproducts = $modelInfo->getNewActivePlingProduct(9);
$this->productsThemesGTK = $modelInfo->getLastProductsForHostStores(5,"366,363,273,267,138,125,131,153,154,414,133");
$this->productsThemesPlasma = $modelInfo->getLastProductsForHostStores(5,"365,119,123,266,114,118,349,417,101,100,111,422,423,446,417");
$this->productsWindowmanager = $modelInfo->getLastProductsForHostStores(5,"117,267,139,143,142,140,141,144");
$this->productsIconsCursors= $modelInfo->getLastProductsForHostStores(5,"386,107");
$this->productsScreenshots= $modelInfo->getLastProductsForHostStores(5,"225,445");
$this->productsApps = $modelInfo->getLastProductsForHostStores(5,233);
$this->productsAddons = $modelInfo->getLastProductsForHostStores(5,"152");
$this->productsWallpapersOriginal = $modelInfo->getLastProductsForHostStores(5,"295,158",null,true);
$this->productsWallpapers = $modelInfo->getLastProductsForHostStores(5,"295,158",null,false);
$this->countSupporters = $modelInfo->getCountActiveSupporters();

$featuredProducts = $modelInfo->getFeaturedProductsForHostStores(100);
if ($featuredProducts->getTotalItemCount()) {
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $offset = (int)$request->getParam('page');
    $irandom = rand(1,$featuredProducts->getTotalItemCount());
    $featuredProducts->setItemCountPerPage(1);
    $featuredProducts->setCurrentPageNumber($irandom);
    $this->featureProducts = $featuredProducts;
}

$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$helpPrintDate = new Default_View_Helper_PrintDate();


$response = array(
    "comments" => Zend_Json::encode($this->comments),
    "productsThemesGTK" => Zend_Json::encode($this->productsThemesGTK),
    "productsThemesPlasma" => Zend_Json::encode($this->productsThemesPlasma),
    "productsWindowmanager" => Zend_Json::encode($this->productsWindowmanager),
    "productsIconsCursors" => Zend_Json::encode($this->productsIconsCursors),
    "productsScreenshots" => Zend_Json::encode($this->productsScreenshots),
    "productsApps" => Zend_Json::encode($this->productsApps),
    "productsAddons" => Zend_Json::encode($this->productsAddons),
    "productsWallpapersOriginal" => Zend_Json::encode($this->productsWallpapersOriginal),
    "productsWallpapers" => Zend_Json::encode($this->productsWallpapers),
    "featureProducts" => Zend_Json::encode($this->featureProducts)
);

?>

testest
<div id="explore-content"></div>
<script type="text/javascript">
  var data =<?php echo Zend_Json::encode($response)?>;
</script>
<script src="/theme/react/opendesktop-home.js" ></script>
