<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

  $modelInfo = new Default_Model_Info();
  $host = $_SERVER['SERVER_NAME'];
  $package_type = $this->package_type;

  if(strpos ( $host , ".cc" ) > 0 || strpos ( $host , ".local" ) > 0) {
    $this->LatestProducts = $modelInfo->getLastProductsForHostStores(7,"33,112",$package_type);
    $this->topGames = $modelInfo->getTopProductsForHostStores(7,"112",$package_type);
    $this->topApps = $modelInfo->getTopProductsForHostStores(7,"33",$package_type);
  } else {
    $this->LatestProducts = $modelInfo->getLastProductsForHostStores(7,"6,234,239,243,244,245,388,391,392,450,481,492",$package_type);
    $this->topGames = $modelInfo->getTopProductsForHostStores(7,"6",$package_type);
    $this->topApps = $modelInfo->getTopProductsForHostStores(7,"234,239,243,244,245,388,391,392,450,481,492",$package_type);
  }

?>

<main id="explore-content"></main>
<script type="text/javascript">

  <?php
    $js_latestProducts = json_encode($this->LatestProducts);
    $js_topGames = json_encode($this->topGames);
    $js_topApps = json_encode($this->topApps);
  ?>

  var products = {
    LatestProducts:<?php echo $js_latestProducts ?>,
    TopGames:<?php echo $js_topGames ?>,
    TopApps:<?php echo $js_topApps ?>
  };
  var filters = {};
  var view = "home";
  console.log(products);
</script>
