<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.pling.com');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'pling.com');
$this->headMeta()->appendProperty('og:site_name','www.pling.com');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.pling.com/theme/react/assets/img/logo-pling.png');

$modelInfo = new Default_Model_Info();
$this->comments = $modelInfo->getLatestComments(10);

$this->productsCollections = $modelInfo->getLastProductsForHostStores(5,"567");

$this->productsThemesGTK = $modelInfo->getLastProductsForHostStores(5,"366,363,273,267,138,125,131,153,154,414,133");
$this->productsThemesPlasma = $modelInfo->getLastProductsForHostStores(5,"365,119,123,266,114,118,349,417,101,100,111,422,423,446,417");
$this->productsWindowmanager = $modelInfo->getLastProductsForHostStores(5,"117,267,139,143,142,140,141,144");
$this->productsIconsCursors= $modelInfo->getLastProductsForHostStores(5,"386,107");
//$this->productsScreenshots= $modelInfo->getLastProductsForHostStores(5,"225,445");
$this->productsApps = $modelInfo->getLastProductsForHostStores(5,233);
$this->productsAddons = $modelInfo->getLastProductsForHostStores(5,"152");
$this->productsWallpapersOriginal = $modelInfo->getLastProductsForHostStores(5,"295",null,true);
$this->productsWallpapers = $modelInfo->getLastProductsForHostStores(5,"295",null,false);

$this->productsArtwork = $modelInfo->getLastProductsForHostStores(5,"158");
$this->productsVideos = $modelInfo->getLastProductsForHostStores(5,"586");
$this->productsComics = $modelInfo->getLastProductsForHostStores(5,"39");
$this->productsPhone = $modelInfo->getLastProductsForHostStores(5,"491");
$this->productsDistors = $modelInfo->getLastProductsForHostStores(5,"404");

$this->countSupporters = $modelInfo->getCountAllSupporters();

$this->featureProducts = $modelInfo->getRandFeaturedProduct();
$this->type='Featured';

$json_productsPlinged = $modelInfo->getJsonNewActivePlingProduct(15);


$response = array(
  'productsThemesGTK' => array('title' =>'Supporters Favourites','catIds' =>'','products' => $json_productsPlinged),
);


$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$helpPrintDate = new Default_View_Helper_PrintDate();
?>

<style>

  @media (max-width:611px){

    body > .panel.panel-default.pull-left {
      max-width: 100%;
      overflow-y: hidden;
    }


    .sidebar-left {
        background-color: #e4e4e4;
    }

    .GridFlex-cell.sidebar-left {
      width: 100%;
      flex: none !important;
      border: 0;
      border-bottom: 1px solid #ccd4d8;
    }

    #explore-content.startpage-store .GridFlex-cell.content {
      padding: 0;
      min-width: 100% !important;
      padding: 0 5px;
      padding-right: 5px !important;
    }

    #featureProductsContainer .feature_container {
      width: 100% !important;
    }

    #featureProductsContainer {
      height: auto !important;
      margin-bottom: 15px;
    }

    #featureProductsContainer .feature_container {
        width: 100%;
        display: block;
        margin: 0 auto;
    }

    #featureProductsContainer .feature_container .main_container {
      float: left;
      width: 100%;
    }

    #featureProductsContainer .feature_container .feature_title {
      width: 100%;
      display: block;
      float: left;
      text-align: center;
      height: 25px;
      line-height: 30px;
    }

    #featureProductsContainer .feature_container .main_container .label_featured {
      float: right;
      position: absolute;
      top: 30px;
      right: 0;
      height: 25px;
      line-height: 25px;
      border-radius: 0 5px 0 5px;
    }

    #featureProductsContainer .feature_container .main_container .feature_image {
      width: 100%;
      margin: 0;
      max-width: 100%;
    }

    #featureProductsContainer .feature_container .main_container .feature_image img {
      margin: 0 auto;
      display: table;
      max-width: 100%;
      width: 100%;
      height: auto;
    }

    #featureProductsContainer .feature_container .main_container .feature_text {
      width: 100%;
      float: left;
      padding: 15px;
    }

    #featureProductsContainer .feature_container .main_container .feature_text .feature_category {
      width: 80%;
    }

    #featureProductsContainer .feature_container .main_container .feature_text .feature_rating {
      padding-right: 0;
      padding-top: 0;
    }

    .prod-widget-box {
      padding: 0;
      width: 100% !important;
    }

    #explore-content .GridFlex .sidebar-right {
        width: 100% !important;
        flex: none !important;
    }

    #explore-content .sidebar-right-info {
      padding-left: 10px;
    }

    .commentstore {
      padding: 5px;
    }

  }


.product-carousel-header
{
  padding-left: 20px;
}

#carousel-module-container
{
  padding-bottom: 20px;
}
</style>


<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/carousel.css"/>
<main id="explore-content" class="startpage-store">
  <div class="GridFlex">
    <div class="GridFlex-cell sidebar-left">
            <?php  echo $this->render('explore/partials/filter.phtml'); ?>
    </div>

    <div class="GridFlex-cell content" id="main-content">
      <div class="contentcontainer">         
                        
       <div class="row">
        <div class="refertext" style="width: 800px;display: block;margin: 0 auto;padding-bottom: 20px">
          Welcome to pling.com. For Linux related content jump to 
          <a href="http://www.pling.com/s/Linux" title="pling.com">/s/Linux </a>or pick one of the substores from the sidebar.
        </div>
       </div>
        

        <div class="row"  id="featureProductsContainer">
          <?php
          if ($this->featureProducts) {echo $this->render('home/partials/featured-products.phtml');}
          ?>
        </div>

        <div class="row">
            <div id="carousel-module-container"></div>                                                                                                              
        </div>



        <div class="row" id="productgroup1">
        <?php
                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "Comics",
                            "products" => $this->productsComics,
                            "catIDs" =>"39"
                        )
                    );  
                    
                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "Videos",
                            "products" => $this->productsVideos,
                            "catIDs" =>"586"
                        )
                    );

                         
        ?>
        </div>


        <div class="row blockpadding">
        <?php

                  echo $this->partial('/home/partials/product_group.phtml', array(
                          "title"  => "Artwork",
                          "products" => $this->productsArtwork,
                          "catIDs" =>"158"
                      )
                  );   

                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "Collections/Rankings",
                            "products" => $this->productsCollections,
                            "catIDs" =>"567"
                        )
                    );

                         
        ?>
        </div>

        <div class="row blockpadding">
        <?php
                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "GTK/Gnome",
                            "products" => $this->productsThemesGTK,
                            "catIDs" =>"366"
                        )
                    );

                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "KDE Plasma",
                            "products" => $this->productsThemesPlasma,
                            "catIDs" =>"365"
                        )
                    );
        ?>
        </div>

        <div class="row blockpadding">
        <?php
                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "Window Managers",
                            "products" => $this->productsWindowmanager,
                            "catIDs" =>"147"
                        )
                    );

                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "Icons, Cursors",
                            "products" => $this->productsIconsCursors,
                            "catIDs" =>"386,107"
                        )
                    );
        ?>
        </div>

        <div class="row blockpadding" >
         <?php
                     echo $this->partial('/home/partials/product_group.phtml', array(
                             "title"  => "App Add-Ons",
                             "products" => $this->productsAddons,
                             "catIDs" =>"152"
                         )
                     );

                     echo $this->partial('/home/partials/product_group.phtml', array(
                             "title"  => "Applications",
                             "products" => $this->productsApps,
                             "catIDs" =>"233"
                         )
                     );

         ?>
        </div>
        <div class="row blockpadding">
        <?php
                echo $this->partial('/home/partials/product_group.phtml', array(
                        "title"  => "Wallpapers ",
                        "products" => $this->productsWallpapers,
                        "catIDs" =>"295"
                    )
                );


                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "Wallpapers (Original)",
                            "products" => $this->productsWallpapersOriginal,
                            "catIDs" =>"295"

                        )
                    );
        ?>
        </div> 

        <div class="row blockpadding">
        <?php
                echo $this->partial('/home/partials/product_group.phtml', array(
                        "title"  => "Phone ",
                        "products" => $this->productsPhone,
                        "catIDs" =>"491"
                    )
                );


                    echo $this->partial('/home/partials/product_group.phtml', array(
                            "title"  => "Distros",
                            "products" => $this->productsDistors,
                            "catIDs" =>"404"

                        )
                    );
        ?>
        </div>                            
      </div>
    </div>
    <div class="GridFlex-cell sidebar-right">
            <aside  id="explore-sidebar" >

            <?php
                $this->show_git = true;
                $this->is_startpage = true;
                echo $this->render('/home/partials/common_rightsidebar.phtml');
            ?>


            </aside>
    </div>
  </div>
  <div class="tooltip_templates" style="display:none">
      <span id="tooltip_content">
          <i class="fa fa-spinner"></i>
      </span>
  </div>
</main>

<script type="application/javascript">
    $(document).ready(function () {
        $('body').on('click', '.ajaxPartialFeatureProduct', function (event) {
            event.preventDefault();
            $(this).off();
            var target = '#featureProductsContainer';
            if($(this).hasClass( "disabled" )) return false;
            var url = $(this).attr("href");
            $(target).load(url, function (response, status, xhr) {
                if (status == "error") {
                    $(target).empty().html('Service is temporarily unavailable. Our engineers are working quickly to resolve this issue. <br/>Find out why you may have encountered this error.');
                }
            });
            return false;
        });
    });


  var page = "opendesktop";
  var hpVersion = 2;
  var data = <?php echo Zend_Json::encode($response)?>;                                
</script>
<script src="/theme/react/carousel.js" type="text/javascript"></script>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
                TooltipUser.setup("tooltipuser","right");
                TooltipUser.setup("tooltipuserleft","left");
                TooltipUserPlings.setup("tooltipuserplings","right");
            });
        ');
