<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.opendesktop.org');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'opendesktop.org');
$this->headMeta()->appendProperty('og:site_name','www.opendesktop.org');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.opendesktop.org/images/system/opendesktop-logo.png');

$modelInfo = new Default_Model_Info();
$productsThemesPlasma = $modelInfo->getLastProductsForHostStores(5,33);
foreach ($productsThemesPlasma as &$p) {
  $p['image_small'] = $this->Image($p['image_small'], array('width' => 200, 'height' => 200));
}
/*'products' => array('title' =>'KDE Plasma','catIds' =>'365','products' => $productsThemesPlasma),*/
$response = array(
  'comments' => $modelInfo->getLatestComments(5),
  'products' => $productsThemesPlasma
);

?>
<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/home-main-container.css"/>

<div class="tooltip_templates" style="display:none">
      <span id="tooltip_content">
          <i class="fa fa-spinner"></i>
      </span>
</div>

<main class="startpage-store">
      <div id="main-content"></div>
      <script type="text/javascript">
        var page = "opendesktop";
        var hpVersion = 2;
        var data = <?php echo Zend_Json::encode($response)?>;
      </script>
      <script src="/theme/react/bundle/home-main-container-bundle.js" type="text/javascript"></script>
</main>
