<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.appimagehub.com');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'appimagehub.com');
$this->headMeta()->appendProperty('og:site_name','www.appimagehub.com');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.appimagehub.com/images_sys/superstore/appimagehub-logo-4.png');


$modelInfo = new Default_Model_Info();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$helpPrintDate = new Default_View_Helper_PrintDate();

$host = $_SERVER['SERVER_NAME'];

$modelProject = new Default_Model_Project();
$totalProjects = $modelProject->fetchTotalProjectsCount(true);

if(strpos ( $host , ".cc" ) > 0 || strpos ( $host , ".local" ) > 0) {
    //$products1 = $modelInfo->getJsonLastProductsForHostStores(15,"105,98,57,53,52,48,295,158");    
    //$products2 = $modelInfo->getJsonLastProductsForHostStores(15,"104");
    
    $products1 = $modelInfo->getJsonLastProductsForHostStores(15);
    $products2 = $modelInfo->getJsonLastProductsForHostStores(15,"105,104,98,57,53,52,48,295,158");    

    $response = array(
        'products1' => array('title' =>'Latest','catIds' =>'104,105,98','products' => $products2)
    );

  } else {
    //$products1 = $modelInfo->getJsonLastProductsForHostStores(15,"391,392,544,526,492,542,450,388,481");    
    //$products2 = $modelInfo->getJsonLastProductsForHostStores(15,"6");

    $products1 = $modelInfo->getJsonLastProductsForHostStores(15);
    $products2 = $modelInfo->getJsonLastProductsForHostStores(15,"391,392,544,526,492,542,450,388,481,6");    

    //'products1' => array('title' =>'Apps','catIds' =>'391,392','products' => $products1),
    //'products2' => array('title' =>'Games','catIds' =>'6','products' => $products2),    

    $response = array(
        'products1' => array('title' =>'Latest','catIds' =>'391,392,6','products' => $products2)
    );
  }
  
  $helperBuildBaseUrl = new Default_View_Helper_BuildBaseUrl();
  $basrUrl = $helperBuildBaseUrl->buildBaseUrl();

  $modelCategories = new Default_Model_ProjectCategory();
  $cat_tree = $modelCategories->fetchTreeForView();

?>

<main id="explore-content"></main>
<script type="text/javascript">
  var filters = {};
  var view = "home";
  var hpVersion = 2;
  var page = "appimages";
  var data = <?php echo Zend_Json::encode($response)?>;
  var totalProjects = <?php echo $totalProjects ?>;
  var baseUrl = <?php echo Zend_Json::encode($basrUrl)?>;
  var catTree = <?php echo Zend_Json::encode($cat_tree)?>;
</script>

<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/carousel.css"/>
<div id="carousel-module-container" class="app-images-hub"></div>

<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/category-blocks.css"/>
<div id="category-blocks-container" class="app-images-hub"></div>
<script type="text/javascript" src="/theme/react/bundle/category-blocks-bundle.js"></script>