<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.appimagehub.com');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'appimagehub.com');
$this->headMeta()->appendProperty('og:site_name','www.appimagehub.com');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.appimagehub.com/images_sys/superstore/appimagehub-logo-4.png');


$modelInfo = new Default_Model_Info();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$helpPrintDate = new Default_View_Helper_PrintDate();

$productsPlinged = $modelInfo->getJsonNewActivePlingProduct(15);
$productsThemesGTK = $modelInfo->getJsonLastProductsForHostStores(15,"366,363,273,267,138,125,131,153,154,414,133");
$productsThemesPlasma = $modelInfo->getJsonLastProductsForHostStores(15,"365,119,123,266,114,118,349,417,101,100,111,422,423,446,417");
$productsWindowmanager = $modelInfo->getJsonLastProductsForHostStores(15,"117,267,139,143,142,140,141,144");
$productsIconsCursors= $modelInfo->getJsonLastProductsForHostStores(15,"386,107");
$productsScreenshots= $modelInfo->getJsonLastProductsForHostStores(15,"225,445");
$productsApps = $modelInfo->getJsonLastProductsForHostStores(15,233);
$productsAddons = $modelInfo->getJsonLastProductsForHostStores(15,"152");
$productsWallpapersOriginal = $modelInfo->getJsonLastProductsForHostStores(15,"295,158",null,true);
$productsWallpapers = $modelInfo->getJsonLastProductsForHostStores(15,"295,158",null,false);
$this->countSupporters = $modelInfo->getCountAllSupporters();

$featuredProducts = $modelInfo->getFeaturedProductsForHostStores(100);
if ($featuredProducts->getTotalItemCount()) {
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $offset = (int)$request->getParam('page');
    $irandom = rand(1,$featuredProducts->getTotalItemCount());
    $featuredProducts->setItemCountPerPage(1);
    $featuredProducts->setCurrentPageNumber($irandom);
    $this->featureProducts = $featuredProducts;
}



$item;
foreach ($this->featureProducts as $i) {
   $item = $i;
   break;
}
$helpCategories = new Default_View_Helper_FetchCategoriesForProductAsString();
$imagehelper = new Default_View_Helper_Image();
$feature = array(
    'project_id' => $item['project_id'],
    'member_id' =>  $item['member_id'],
    'username' =>  $item['username'],
    'profile_image_url' =>  $imagehelper->Image($item['profile_image_url'],array('width' => 300, 'height' => 230, 'crop' => 1)),
    'featured' =>  $item['featured'],
    'description' =>  $item['description'],
    'title' =>  $item['title'],
    'category' =>  $helpCategories->fetchCategoriesForProductAsString($item['project_id']),
    'image_small' =>  $item['image_small'],
    'laplace_score' =>  $item['laplace_score'],
    'count_likes' =>  $item['count_likes'],
    'count_dislikes' =>  $item['count_dislikes'],
    'changed_at' =>  $item['changed_at'],
    'created_at' =>  $item['created_at'],
    'count_comments' =>  $item['count_comments']
);

$response = array(
  'productsPlinged' => array('title' =>'Plinged','catIds' =>'','products' => $productsPlinged),

  'productsThemesGTK' => array('title' =>'GTK/Gnome','catIds' =>'366','products' => $productsThemesGTK),
  'productsThemesPlasma' => array('title' =>'KDE Plasma','catIds' =>'365','products' => $productsThemesPlasma),

  'productsWindowmanager' =>array('title' =>'Window Managers','catIds' =>'147','products' => $productsWindowmanager),
  'productsIconsCursors' =>array('title' =>'Icons, Cursors','catIds' =>'386,107','products' => $productsIconsCursors),


  'productsApps' =>array('title' =>'Applications','catIds' =>'233','products' => $productsApps),
  'productsAddons' =>array('title' =>'App Add-Ons','catIds' =>'152','products' => $productsAddons),
  'productsWallpapersOriginal' =>array('title' =>'Artwork, Wallpapers (Original)','catIds' =>'158,295','products' => $productsWallpapersOriginal),
  'productsWallpapers' =>array('title' =>'Artwork, Wallpapers','catIds' =>'158,295','products' => $productsWallpapers),

  'productsScreenshots' =>array('title' =>'Concepts, Screenshots','catIds' =>'445,225','products' => $productsScreenshots),
  "featureProducts" => Zend_Json::encode($feature)
);

  $modelInfo = new Default_Model_Info();
  $host = $_SERVER['SERVER_NAME'];
  $tags = $this->tag_filter;

  if(strpos ( $host , ".cc" ) > 0 || strpos ( $host , ".local" ) > 0) {
    $this->LatestProducts = $modelInfo->getLastProductsForHostStores(7,"33,112",$tags);
    $this->topGames = $modelInfo->getTopProductsForHostStores(7,"112",$tags);
    $this->topApps = $modelInfo->getTopProductsForHostStores(7,"33",$tags);
  } else {
    $this->LatestProducts = $modelInfo->getLastProductsForHostStores(15,"6,234,239,243,244,245,388,391,392,450,481,492",$tags);
    $this->topGames = $modelInfo->getTopProductsForHostStores(15,"6",$tags);
    $this->topApps = $modelInfo->getTopProductsForHostStores(15,"234,239,243,244,245,388,391,392,450,481,492",$tags);
  }
  $modelProject = new Default_Model_Project();
  $totalProjects = $modelProject->fetchTotalProjectsCount(true);
?>

<main id="explore-content"></main>
<script type="text/javascript">

  <?php
    $js_latestProducts = json_encode($this->LatestProducts);
    $js_topGames = json_encode($this->topGames);
    $js_topApps = json_encode($this->topApps);
  ?>

  var products = {
    LatestProducts:<?php echo $js_latestProducts ?>,
    TopGames:<?php echo $js_topGames ?>,
    TopApps:<?php echo $js_topApps ?>,
    TotalProjects:<?php echo $totalProjects ?>
  };
  var filters = {};
  var view = "home";
  var hpVersion = 2;
  var data = <?php echo Zend_Json::encode($response)?>;
  console.log(products);
</script>
<div id="carousel-module-container">
</div>
<script src="/theme/react/carousel.js" type="text/javascript"></script>
