<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.opendesktop.org');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'opendesktop.org');
$this->headMeta()->appendProperty('og:site_name','www.opendesktop.org');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.opendesktop.org/images/system/opendesktop-logo.png');

$modelInfo = new Default_Model_Info();

$productsThemesGTK = $modelInfo->getJsonLastProductsForHostStores(15,"104");
$productsThemesPlasma = $modelInfo->getJsonLastProductsForHostStores(15,"365,119,123,266,114,118,349,417,101,100,111,422,423,446,417");
$productsWindowmanager = $modelInfo->getJsonLastProductsForHostStores(15,"117,267,139,143,142,140,141,144");
$productsIconsCursors= $modelInfo->getJsonLastProductsForHostStores(15,"386,107");
$productsScreenshots= $modelInfo->getJsonLastProductsForHostStores(15,"225,445");
$productsApps = $modelInfo->getJsonLastProductsForHostStores(15,233);
$productsAddons = $modelInfo->getJsonLastProductsForHostStores(15,"152");
$productsWallpapersOriginal = $modelInfo->getJsonLastProductsForHostStores(15,"295,158",null,true);
$productsWallpapers = $modelInfo->getJsonLastProductsForHostStores(15,"295,158",null,false);
$this->countSupporters = $modelInfo->getCountAllSupporters();
$featuredProducts = $modelInfo->getFeaturedProductsForHostStores(100);
if ($featuredProducts->getTotalItemCount()) {
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $offset = (int)$request->getParam('page');
    $irandom = rand(1,$featuredProducts->getTotalItemCount());
    $featuredProducts->setItemCountPerPage(1);
    $featuredProducts->setCurrentPageNumber($irandom);
    $this->featureProducts = $featuredProducts;
}

$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$helpPrintDate = new Default_View_Helper_PrintDate();

$item;
foreach ($this->featureProducts as $i) {
   $item = $i;
   break;
}
$helpCategories = new Default_View_Helper_FetchCategoriesForProductAsString();
$imagehelper = new Default_View_Helper_Image();
$feature = array(
    'project_id' => $item['project_id'],
    'member_id' =>  $item['member_id'],
    'username' =>  $item['username'],
    'profile_image_url' =>  $imagehelper->Image($item['profile_image_url'],array('width' => 300, 'height' => 230, 'crop' => 1)),
    'featured' =>  $item['featured'],
    'description' =>  $item['description'],
    'title' =>  $item['title'],
    'category' =>  $helpCategories->fetchCategoriesForProductAsString($item['project_id']),
    'image_small' =>  $item['image_small'],
    'laplace_score' =>  $item['laplace_score'],
    'count_likes' =>  $item['count_likes'],
    'count_dislikes' =>  $item['count_dislikes'],
    'changed_at' =>  $item['changed_at'],
    'created_at' =>  $item['created_at'],
    'count_comments' =>  $item['count_comments']
);

$response = array(
  'productsThemesGTK' => array('title' =>'GTK/Gnome','catIds' =>'104','products' => $productsThemesGTK),
  'productsThemesPlasma' => array('title' =>'KDE Plasma','catIds' =>'365','products' => $productsThemesPlasma),

  'productsWindowmanager' =>array('title' =>'Window Managers','catIds' =>'147','products' => $productsWindowmanager),
  'productsIconsCursors' =>array('title' =>'Icons, Cursors','catIds' =>'386,107','products' => $productsIconsCursors),

  'productsWallpapers' =>array('title' =>'Artwork, Wallpapers','catIds' =>'158,295','products' => $productsWallpapers),
  'productsWallpapersOriginal' =>array('title' =>'Artwork, Wallpapers (Original)','catIds' =>'158,295','products' => $productsWallpapersOriginal),

  'productsAddons' =>array('title' =>'App Add-Ons','catIds' =>'152','products' => $productsAddons),
  'productsApps' =>array('title' =>'Applications','catIds' =>'233','products' => $productsApps),

  'productsScreenshots' =>array('title' =>'Concepts, Screenshots','catIds' =>'445,225','products' => $productsScreenshots),
  "featureProducts" => Zend_Json::encode($feature)
);

?>
<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/homepage.css"/>
<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/carousel.css"/>

<main id="explore-content" class="startpage-store">

    <div class="sidebar-left">
      <?php  echo $this->render('explore/partials/filter.phtml'); ?>
    </div>

    <div class="content">
      <div id="main-content"></div>
      <script type="text/javascript">
        var page = "opendesktop";
        var hpVersion = 2;
        var data = <?php echo Zend_Json::encode($response)?>;
      </script>
      <script src="/theme/react/opendesktop-home.js" type="text/javascript"></script>
      <div id="carousel-module-container">
      </div>
      <script src="/theme/react/bundle/carousel-bundle.js" type="text/javascript"></script>
    </div>

    <div class="sidebar-right">
      <aside  id="explore-sidebar" >
        <?php
            $this->show_git = false;
            echo $this->render('/home/partials/common_rightsidebar.phtml');
        ?>
        <div>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Responsive New Displayblock -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-1150932386931372"
                 data-ad-slot="1024407251"
                 data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
      </aside>
    </div>

  <div class="tooltip_templates" style="display:none">
      <span id="tooltip_content">
          <i class="fa fa-spinner"></i>
      </span>
  </div>

</main>
