<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.appimagehub.com');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'appimagehub.com');
$this->headMeta()->appendProperty('og:site_name','www.appimagehub.com');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.appimagehub.com/images_sys/superstore/appimagehub-logo-4.png');


$modelInfo = new Default_Model_Info();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$helpPrintDate = new Default_View_Helper_PrintDate();

$host = $_SERVER['SERVER_NAME'];

$modelProject = new Default_Model_Project();
$totalProjects = $modelProject->fetchTotalProjectsCount(true);

if(strpos ( $host , ".cc" ) > 0 || strpos ( $host , ".local" ) > 0) {
    $products1 = $modelInfo->getJsonLastProductsForHostStores(15,"104");
    $products2 = $modelInfo->getJsonLastProductsForHostStores(15,"105");
    $products3 = $modelInfo->getJsonLastProductsForHostStores(15,"98");
    $products4= $modelInfo->getJsonLastProductsForHostStores(15,"57");
    $products5= $modelInfo->getJsonLastProductsForHostStores(15,"53");
    $products6 = $modelInfo->getJsonLastProductsForHostStores(15,"52");
    $products7 = $modelInfo->getJsonLastProductsForHostStores(15,"48");
    $products8 = $modelInfo->getJsonLastProductsForHostStores(15,"295,158");
    $products9 = $modelInfo->getJsonLastProductsForHostStores(15,"295,158");
    $products10 = $modelInfo->getJsonLastProductsForHostStores(15,"295,158");

    $response = array(
        'products1' => array('title' =>'Audio','catIds' =>'104','products' => $products1),
        'products2' => array('title' =>'Education','catIds' =>'105','products' => $products2),
        'products3' => array('title' =>'Games','catIds' =>'98','products' => $products3),
        'products4' => array('title' =>'Graphics','catIds' =>'57','products' => $products4),
        'products5' => array('title' =>'Internet','catIds' =>'53','products' => $products5),
        'products6' => array('title' =>'IoT','catIds' =>'52','products' => $products6),
        'products7' => array('title' =>'Office','catIds' =>'48','products' => $products7),
        'products8' => array('title' =>'Programming','catIds' =>'104','products' => $products8),
        'products9' => array('title' =>'System & Tools','catIds' =>'104','products' => $products9),
        'products10' => array('title' =>'Video','catIds' =>'104','products' => $products10),
    );

  } else {
    $products1 = $modelInfo->getJsonLastProductsForHostStores(15,"392");
    $products2 = $modelInfo->getJsonLastProductsForHostStores(15,"544");
    $products3 = $modelInfo->getJsonLastProductsForHostStores(15,"6");
    $products4= $modelInfo->getJsonLastProductsForHostStores(15,"526");
    $products5= $modelInfo->getJsonLastProductsForHostStores(15,"492");
    $products6 = $modelInfo->getJsonLastProductsForHostStores(15,"542");
    $products7 = $modelInfo->getJsonLastProductsForHostStores(15,"450");
    $products8 = $modelInfo->getJsonLastProductsForHostStores(15,"388");
    $products9 = $modelInfo->getJsonLastProductsForHostStores(15,"391");
    $products10 = $modelInfo->getJsonLastProductsForHostStores(15,"481");

    $response = array(
        'products1' => array('title' =>'Audio','catIds' =>'392','products' => $products1),
        'products2' => array('title' =>'Education','catIds' =>'544','products' => $products2),
        'products3' => array('title' =>'Games','catIds' =>'6','products' => $products3),
        'products4' => array('title' =>'Graphics','catIds' =>'526','products' => $products4),
        'products5' => array('title' =>'Internet','catIds' =>'492','products' => $products5),
        'products6' => array('title' =>'IoT','catIds' =>'542','products' => $products6),
        'products7' => array('title' =>'Office','catIds' =>'450','products' => $products7),
        'products8' => array('title' =>'Programming','catIds' =>'388','products' => $products8),
        'products9' => array('title' =>'System & Tools','catIds' =>'391','products' => $products9),
        'products10' => array('title' =>'Video','catIds' =>'481','products' => $products10),
    );
  }
  $helperBuildBaseUrl = new Default_View_Helper_BuildBaseUrl();
  $basrUrl = $helperBuildBaseUrl->buildBaseUrl();
?>

<main id="explore-content"></main>
<script type="text/javascript">
  var filters = {};
  var view = "home";
  var hpVersion = 2;
  var page = "appimages";
  var data = <?php echo Zend_Json::encode($response)?>;
  var totalProjects = <?php echo $totalProjects ?>;
  var baseUrl = <?php echo Zend_Json::encode($basrUrl)?>;
  console.log(data);
</script>
<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/carousel.css"/>
<div id="carousel-module-container" class="app-images-hub"></div>

