<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->headTitle($_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->appendProperty('og:url', 'www.opendesktop.org');
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', 'opendesktop.org');
$this->headMeta()->appendProperty('og:site_name','www.opendesktop.org');
$this->headMeta()->appendProperty('og:description','A community where developers and artists share applications, themes and other content');
$this->headMeta()->appendProperty('og:image','https://www.opendesktop.org/images/system/opendesktop-logo.png');

$modelInfo = new Default_Model_Info();
$this->comments = $modelInfo->getLatestComments(10);
//$this->users = $modelInfo->getNewActiveMembers(18);
//$this->supporters = $modelInfo->getNewActiveSupporters(9);
//$this->plingproducts = $modelInfo->getNewActivePlingProduct(9);
$this->productsThemesGTK = $modelInfo->getLastProductsForHostStores(5,"366,363,273,267,138,125,131,153,154,414,133");
$this->productsThemesPlasma = $modelInfo->getLastProductsForHostStores(5,"365,119,123,266,114,118,349,417,101,100,111,422,423,446,417");
$this->productsWindowmanager = $modelInfo->getLastProductsForHostStores(5,"117,267,139,143,142,140,141,144");
$this->productsIconsCursors= $modelInfo->getLastProductsForHostStores(5,"386,107");
$this->productsScreenshots= $modelInfo->getLastProductsForHostStores(5,"225,445");
$this->productsApps = $modelInfo->getLastProductsForHostStores(5,233);
$this->productsAddons = $modelInfo->getLastProductsForHostStores(5,"152");
$this->productsWallpapersOriginal = $modelInfo->getLastProductsForHostStores(5,"295,158",null,true);
$this->productsWallpapers = $modelInfo->getLastProductsForHostStores(5,"295,158",null,false);
$this->countSupporters = $modelInfo->getCountActiveSupporters();

$featuredProducts = $modelInfo->getFeaturedProductsForHostStores(100);
if ($featuredProducts->getTotalItemCount()) {
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $offset = (int)$request->getParam('page');
    $irandom = rand(1,$featuredProducts->getTotalItemCount());
    $featuredProducts->setItemCountPerPage(1);
    $featuredProducts->setCurrentPageNumber($irandom);
    $this->featureProducts = $featuredProducts;
}

$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$helpPrintDate = new Default_View_Helper_PrintDate();

$item;
foreach ($this->featureProducts as $i) {
   $item = $i;
   break;
}
$helpCategories = new Default_View_Helper_FetchCategoriesForProductAsString();

$feature = array(
    'project_id' => $item['project_id'],
    'member_id' =>  $item['member_id'],
    'username' =>  $item['username'],
    'profile_image_url' =>  $item['profile_image_url'],
    'featured' =>  $item['featured'],
    'description' =>  $item['description'],
    'title' =>  $item['title'],
    'category' =>  $helpCategories->fetchCategoriesForProductAsString($item['project_id']),
    'image_small' =>  $item['image_small'],
    'laplace_score' =>  $item['laplace_score'],
    'count_likes' =>  $item['count_likes'],
    'count_dislikes' =>  $item['count_dislikes'],
    'changed_at' =>  $item['changed_at'],
    'created_at' =>  $item['created_at'],
    'count_comments' =>  $item['count_comments']
);
$response = array(
    "productsThemesGTK" => Zend_Json::encode($this->productsThemesGTK),
    "productsThemesPlasma" => Zend_Json::encode($this->productsThemesPlasma),
    "productsWindowmanager" => Zend_Json::encode($this->productsWindowmanager),
    "productsIconsCursors" => Zend_Json::encode($this->productsIconsCursors),
    "productsScreenshots" => Zend_Json::encode($this->productsScreenshots),
    "productsApps" => Zend_Json::encode($this->productsApps),
    "productsAddons" => Zend_Json::encode($this->productsAddons),
    "productsWallpapersOriginal" => Zend_Json::encode($this->productsWallpapersOriginal),
    "productsWallpapers" => Zend_Json::encode($this->productsWallpapers),
    "featureProducts" => Zend_Json::encode($feature)
);


?>
<link type="text/css" rel="stylesheet" href="/theme/react/assets/css/homepage.css"/>

<main id="explore-content" class="startpage-store">

    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12 sidebar-left">
      <?php  echo $this->render('explore/partials/filter.phtml'); ?>
    </div>

    <div class="col-lg-7 col-md-7 col-sm-8 col-xs-12  content">
      <div id="main-content"></div>
      <script type="text/javascript">
        var data = <?php echo Zend_Json::encode($response)?>;
        var featuredProduct = <?php echo Zend_Json::encode($feature)?>;
      </script>
      <script src="/theme/react/opendesktop-home.js" type="text/javascript"></script>
    </div>

    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 sidebar-right">
      <aside  id="explore-sidebar" >
        <?php
            echo $this->render('/home/partials/common_rightsidebar.phtml');
        ?>
        <div>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Responsive New Displayblock -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-1150932386931372"
                 data-ad-slot="1024407251"
                 data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
      </aside>
    </div>

  <div class="tooltip_templates" style="display:none">
      <span id="tooltip_content">
          <i class="fa fa-spinner"></i>
      </span>
  </div>

</main>
