<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$modelMemberToken = new Default_Model_DbTable_MemberToken();
$tokenData = $modelMemberToken->fetchRow('token_member_id = ' . Zend_Auth::getInstance()->getIdentity()->member_id . ' and token_deleted is null and token_provider_name = "github_personal"');
$tokenValue = isset($tokenData->token_value) ? $tokenData->token_value : null;
?>


<div class="panel-collapse " id="github-collapse">
    <div class="panel-body">
        <form class="standard-form partial well" action="<?= $this->github->getAction(); ?>"
              method="<?= $this->github->getMethod(); ?>" data-target="#form-github"
              data-trigger="#github-trigger">
            <div class="row">
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                  <?= $this->github->link_github
                      ->setAttrib('tabindex', 11)
                      ->setAttrib('class', 'form-control')
                      ->setAttrib('pattern', '^\w+-?\w+(?!-)$')
                  ?>
                  <p class="help-block small">Insert your Github username here.</p>
                </div>
            </div>
          <div class="row">
            <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                <?= $this->github->token_github
                    ->setAttrib('tabindex', 11)
                    ->setAttrib('class', 'form-control')
                    ->setAttrib('pattern', '^[\w\-\.\/\+~]+$')
                    ->setValue($tokenValue)
                ?>
              <p class="help-block small">Insert your personal access token from Github here.</p>
            </div>
          </div>
          <!-- /.row-fluid -->
            <hr>
            <div class="row">
                <div class="box pull-left margin-left-15" style="padding-left: 15px;">
                    <?php echo $this->formResult($this->github, $this->save, null, 'Changes saved.'); ?>
                </div>
                <button type="submit" class="btn btn-submit btn-native pull-right"
                        tabindex="12"><?= $this->translate('Save &amp; Update') ?>
                </button>
            </div>
        </form>
    </div>
</div>