<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>


<div class="panel-collapse " id="password-collapse">
    <div class="panel-body">
        <form class="standard-form well partial" action="<?= $this->passwordform->getAction(); ?>"
              method="<?= $this->passwordform->getMethod(); ?>" data-target="#form-password"
              data-trigger="#password-trigger">
            <div class="row">
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                    <?= $this->passwordform->passwordOld->setAttrib('tabindex', 15) ?>
                </div>
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                    <?= $this->passwordform->password1->setAttrib('tabindex', 16) ?>
                </div>
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                    <?= $this->passwordform->password2->setAttrib('tabindex', 17) ?>
                </div>
            </div>
            <!-- /.row-fluid -->
            <hr>
            <div class="row">
                <div
                    class="box pull-left margin-left-15"  style="padding-left: 15px;"><?= $this->formResult($this->passwordform, $this->save); ?></div>
                <button type="submit" class="btn btn-native pull-right"
                        tabindex="18"><?= $this->translate('Save &amp; Update') ?></button>
            </div>
        </form>
    </div>
</div>