<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<style type="text/css">
    
    .settings-main #form-picture-background .image-preview > img {
      width: 200px !important;
        height: 46px !important;  
    }
</style>

<!--partialajaxbg-->
<div class="panel-collapse " id="picture-bg-collapse">
    <div class="panel-body">
        <form class="standard-form partialajaxbg well" action="<?= $this->pictureformbg->getAction(); ?>"
              method="<?= $this->pictureformbg->getMethod(); ?>" data-target="#form-picture-background"
              data-trigger="#picture-background-trigger" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4 center">
                    <?= $this->pictureformbg->profile_picture_background_upload ?>
                    <?= $this->pictureformbg->profile_image_url_bg ?>                                      
                </div>
                <!-- /.span4 -->
                <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
                    <div class="image-info">
                        <p>
                            <em class="icon info-icon"></em>
                        </p>
                      
                        <p class="italic">
                            <?= $this->translate('You can use <br><span class="purple">JPG, PNG, GIF</span> formats') ?>
                        </p>
                    </div>
                </div>
                <!-- /.span4 -->
            </div>
            <!-- /.row-fluid -->
            <hr>
            <div class="row">
                <div class="box pull-left margin-left-15"  style="padding-left: 15px;">
                    <?php echo $this->formResult($this->pictureformbg, $this->save, true, 'Changes saved. Some picture elements will be updated at next login.'); ?>
                </div>
                <button type="submit" class="btn btn-native pull-right"
                        tabindex="14"><?= $this->translate('Save &amp; Update') ?></button>
            </div>
        </form>
        <!-- /.standard-form -->
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        ImagePreview.initProfilePictureBackground();
        PartialFormsAjaxMemberBg.setup();
    });
</script>