<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperFetchCategory = new Default_View_Helper_CatTitle();
$helperFetchCatParent = new Default_View_Helper_CatParent();
$getAuthUser = new Default_View_Helper_GetAuthUser();
$helperBuildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$auth = Zend_Auth::getInstance();
$member = $getAuthUser->getAuthUser();
$serverUrl = $this->serverUrl();

$baseurl = Zend_Registry::get('config')->settings->client->default->baseurl;
$sname = Zend_Registry::get('store_host');  
$store_config = Zend_Registry::get('store_config');
$store_order = $store_config->order;
$store_name = $store_config->name;
$is_show_title = $store_config->is_show_title;
$last_char_store_order = substr($store_order, -1); 

echo $this->render('partials/header/metaheader.phtml'); ?>

    <style>

        header a {
            color:  <?=$this->template['header-nav-tabs']['link']['color']?>;
        }

        header div.container.header {
            background-image: <?=$this->template['header']['background-image']?>;
            background-color: <?=$this->template['header']['background-color']?>;
            color: <?=$this->template['header']['color']?>;
            height: <?=$this->template['header']['height']?>;
        }

        header .logo-header {
            background-image: <?=$this->template['header-logo']['background-image']?>;
            display: block;
            height: <?=$this->template['header-logo']['height']?>;
            left: <?=$this->template['header-logo']['left']?>;
            position: absolute;
            top: <?=$this->template['header-logo']['top']?>;
            width: <?=$this->template['header-logo']['width']?>;
            z-index: 999;
            overflow: hidden;
        }

        header ul li:active {
            background: <?=$this->template['header-nav-tabs']['background-color-active']?> none repeat scroll 0 0;
        }
        header ul li:hover {
            background: <?=$this->template['header-nav-tabs']['background-color-hover']?> none repeat scroll 0 0;
        }

        header ul li ul li:active {
            background: <?=$this->template['header-nav-tabs']['background-color-active']?> none repeat scroll 0 0;
        }

        header ul li ul li:hover {
            background: <?=$this->template['header-nav-tabs']['background-color-hover']?> none repeat scroll 0 0;
        }
        header ul li:active > a {
            color: <?=$this->template['header-nav-tabs']['link']['color-active']?>;
        }
        header ul li:hover > a {
            color: <?=$this->template['header-nav-tabs']['link']['color-hover']?>;
        }
        header ul li ul li:hover a {
            color: <?=$this->template['header-nav-tabs']['link']['color-hover']?>;
        }

        ul.menu-nav-tabs li {
            background-color: <?=$this->template['header-nav-tabs']['background-color']?>;
            border-color: <?=$this->template['header-nav-tabs']['border-color']?>;
            border-image: none;
            border-radius: <?=$this->template['header-nav-tabs']['border-radius']?>;
            border-style: <?=$this->template['header-nav-tabs']['border-style']?>;
            border-width: <?=$this->template['header-nav-tabs']['border-with']?>;
            height: <?=$this->template['header-nav-tabs']['height']?>;
            line-height: 24px;
            margin-right: <?=$this->template['header-nav-tabs']['margin-right']?>;
        }


        ul.menu-nav-tabs li.active {
            background: <?=$this->template['header-nav-tabs']['background-color-active']?> none repeat scroll 0 0;
        }

        .absolute-left {
            left: <?=$tabs_left?>px;
        }

        .absolute-right {
            right: <?=$this->template['header-nav-tabs']['absolute-right']?>;
        }

        .header_cat_link {
              bottom: 0; position: absolute; color: blue; font-size: 18pt; left: <?= $cat_title_left ?>px;
        } 

        .nav-divider-pling{
            color:#E2E2E2;
        }
        .nav-pills > li + li {
                margin-left: 10px;
            }
            .dropdown-menu > li > a{
                font-size: 12px;
            }
        .metamenu .dropdown:hover .dropdown-menu {
            margin-left: -16px;
        }
        .metamenu .dropdown-menu li{
            width: 100%;
        }

        .metamenu ul.dropdown-menu  li span{ color:#999; }
        .metamenu ul.dropdown-menu  li.active span{ color:#eee; }
    </style>


    <header id="page_header" xmlns="http://www.w3.org/1999/html">
        <div class="container header" style="position: relative;">

            <?php if (false === $auth->hasIdentity() && empty($member->username)) {
                $helperEncryptUrl = new Default_View_Helper_EncryptUrl();
                $redirectString = '/redirect/' . $helperEncryptUrl->EncryptUrl(Zend_Controller_Front::getInstance()->getRequest()->getScheme() . '://' . Zend_Controller_Front::getInstance()->getRequest()->getHttpHost().$_SERVER["REQUEST_URI"]);
                ?>
                <ul class="menu-nav-tabs absolute-right" style="position: absolute;bottom: 0px;">
                    <li role="presentation"
                        class="<?php echo(strpos($_SERVER["REQUEST_URI"], 'register') ? 'active' : '') ?>">
                        <a href="<?=$serverUrl?>/register" rel="nofollow">Register</a></li>
                    <li role="presentation"
                        class="<?php echo(strpos($_SERVER["REQUEST_URI"], 'login') ? 'active' : '') ?>">
                        <a href="<?=$serverUrl?>/login<?php echo strpos($_SERVER["REQUEST_URI"], 'login') ? '' : $redirectString ?>" rel="nofollow">Login</a>
                    </li>
                </ul>
            <?php } ?>

            <section class="container">
            <section class="wrapper">

                    <section>

                        <figure class="logo-header">                           
                           <a href="http://<?php echo $last_char_store_order=='1'?$sname:$baseurl.'/s/'.$store_name ?>">
                                <img width="<?= $this->template['header-logo']['width'] ?>" border="0"
                                     src="<?= $this->template['header-logo']['image-src'] ?>">
                            </a>
                        </figure>

                        <nav id="nav-top">
                            <div class="pull-left col-lg-5 col-md-5 col-sm-5 col-xs-5">
                            </div>

                            <div class="pull-right col-lg-7 col-md-7 col-sm-7 col-xs-7">
                                <?php if ($auth->hasIdentity() && !empty($member->username)) { ?>
                                <img src="https://gitlab.pling.cc/external/setcookie.php?id=<?= $member->member_id ?>" height="0" width="0">
                                <img src="https://forum.opendesktop.cc:8443/setcookie.php?id=<?= $member->member_id ?>" height="0" width="0">
                                <img src="https://forum.opendesktop.cc:8443/setdata.php?id=<?= $member->member_id ?>&name=<?= $member-username ?>&mail=<?= $member->mail ?>&avatar=<?= $member->profile_image_url ?>" height="0" width="0">
                                    <ul class="menu pull-right">
                                        <li class="link relative profile-menu-container">
                                            <a rel="profile-menu" class="menu-trigger">
                                                <div class="absolute header-profile-image">                                                        
                                                            <img
                                                            src="<?= $helperImage->Image($member->profile_image_url,
                                                                array('width' => 30, 'height' => 30)) ?>"/>
                                                        
                                                </div>
                                                <span><?= $member->username ?></span>
                                            </a>
                                            <ul class="profile-menu menu-dropdown">
                                                <div class="dropdown-header"></div>
                                                <li class="link first">
                                                    <a href="/product/add/"><?= $this->translate('Add Product') ?></a>
                                                </li>
                                                <li class="link">
                                                    <a href="<?= $helperBuildMemberUrl->buildMemberUrl($member->username, 'products') ?>"><?= $this->translate('Products') ?></a>
                                                </li>
                                                <li class="link">
                                                    <a href="<?= $helperBuildMemberUrl->buildMemberUrl($member->username, 'plings') ?>"><?= $this->translate('Plings') ?></a>
                                                </li>
                                                <li class="link">
                                                    <a href="/settings/"><?= $this->translate('Settings') ?></a>
                                                </li>
                                                <li class="link">
                                                    <a href="<?=$serverUrl?>/logout/"><?= $this->translate('Logout') ?></a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                <?php } else { ?>
                                <?php } ?>
                                <form id="search" class="pull-right" action="/search">
                                    <input type="text" name="projectSearchText" class="content-search">

                                    <div class="icon-search-input absolute cursor-hand"
                                         onclick="$('#search').submit()"></div>
                                </form>
                            </div>
                        </nav>
                    </section>

                </section>
            </section>

            <?php if($is_show_title==1): ?>
            <section class="container">
                <section class="wrapper">
                    <span class="header_cat_link" id="header_cat_link">
                       <?php /* <a href="/browse/cat/<?= isset($this->cat_id) ? $this->cat_id : 'all' ?>/order/latest"> */?>
                        <a href="http://<?php echo $last_char_store_order=='1'?$sname:$baseurl.'/s/'.$store_name ?>">
                            <?=$store_name?>
                        </a>
                    </span>
                </section>
            </section>
        <?php endif; ?>
        </div>
    </header>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
                MenuHover.setup();
                Popuppanel.setup();                    
                LoginContainer.update();
                PlingsRedirect.setup();
            });
        ');

