<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div class="productrow"><div class="row">            
 <div class="col-lg-3">
    <span class="num"><?=$this->rownum ?>.</span>
        <div class="text-center">
            <img class="productimg" src="<?=$this->Image($this->product['image_small'], array('width' => 90, 'height' => 90))?>" />
        </div>
 </div>
 <div class="col-lg-6">
        <a href="<?=$this->buildProductUrl($this->product['project_id'],'')?>"><?=$this->product['title']?>
            <span class="version"><?=\Application\Model\Service\HtmlPurifyService::purify($this->product['version'])?>
            </span>
        </a><br>
        <?=$this->fetchCategoriesForProductAsString($this->product['project_id'])?> 
        <br>
        <?php
           
            $count_comments = $this->product['count_comments'];
            echo ($count_comments>0 ? '<span class="cntComments">'.$count_comments.' comment':'').($count_comments>1?'s':'').($count_comments>0?'</span>':'') ;
            
        ?>
 </div>
 <div class="col-lg-3">
    <div class="rating">
        <?php                
              
                echo $this->partial(
                    'application/partials/circle.phtml', array(
                        "r" => 30,
                        "fontSize" =>Application\Model\Service\ConstCircle::small30,
                        "score" => $this->product['laplace_score']/10
                    )
                );  
        ?>
    </div>
    <span class="time"><?=$this->printDate($this->product['changed_at']==null?$this->product['created_at']:$this->product['changed_at'])?>
    </span>
</div>
</div>
</div >