<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$ids = explode(",", $this->stores);
$titles = explode(",", $this->title);
?>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">  
<div class="blockContainer">    
    <div class="header">
<span class="title">
    <?php
    $i = 0;
    $t = '';
    foreach ($ids as $catid) {
        if($i>0) $t=$t.', ';
        $t =$t. '<a href="/s/'.$catid.'">'.$titles[$i++].'</a>';        
    }
    echo $t;
    ?>	
    </span>
    </div>    
    <div class="prod-widget-box new-products" >
    <?php                                    
    foreach ($this->products as $this->product) {
        include __DIR__.'/product_plingcom.phtml';                                      
    }           
    ?>
    </div>
</div>                                                                                                                                          
</div>
