<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$this->headTitle($this->headTitle);
$this->tab = 'likes';

$pageCount = $this->likes->count();
?>
<main class="user-admin-page">
<?php include __DIR__.'/partials/userHeader_top.phtml';?>
    <section class="body-wrap">
        <section class="wrapper product-page">
            <!-- PAGE BODY -->
            <section class="my-products-page">
                <!-- NAVIGATION -->
                <?php include __DIR__.'/partials/userHeader.phtml';?>    
                <!-- /NAVIGATION -->
             
              <div class="my-products-heading">
                   <h1 class="page-title left"><?= $this->translate('Favs') ?></h1>                   
               </div>


                <div class="my-downloadshistory-list" id="my-downloadshistory-list">

                <div class="row">
                    <div class="col-lg-12">
                    <small class="pull-right">
                        <div class="row totaldownloads"><?=$this->likes->getTotalItemCount()?> Favs</div>
                        <?php if ($pageCount > 1) echo $this->paginationControl($this->likes, 'Sliding'
                                ,'application/partials/paginatorAjax.phtml'
                                ,array(
                                    'route' => 'application_user'
                                   ,'action' => 'likes'
                                   ,'username' => $this->member->username
                                   ,'dom_target' => 'div#my-downloadshistory-list')); ?>
                      </small>                    
                    </div>
                </div>              

                    <?php  
                    	$i=0;
                         foreach($this->likes as $file){                                                                                            
                                echo $this->partial('partials/loopLike.phtml',  array(
                                        "file"  => (object)$file,
                                        "member_id" =>$this->member->member_id,
                                        "authMember" =>$this->member,
                                        "counter" => $i++
                                    ));                                                                                                  
                            }
                    ?>        
                </div>
            </section>

            <!-- /PAGE BODY -->

        </section>

    </section>

</main>
