<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-6 col-container">
    <div class="well about-me-sidebar-section">
        <div class="sidebar-header">
            <h3><?= $this->translate('MEMBER INFO') ?></h3>
        </div>
        <div class="sidebar-content">
            <div class="row product-maker-sidebar">
                <div class="col-md-5 col-lg-5 col-sm-5 col-xs-5 product-maker-thumbnail relative">
                    <a target="_blank"
                       href="<?php echo $this->buildMemberUrl($this->member->username); ?>"
                       title="<?= $this->member->username ?>">
                        <div class="profile-image-overlay-4 absolute"></div>
                        <img src="<?= $this->Image($this->member->profile_image_url, array('width' => 100, 'height' => 100)); ?>" alt="member profile image" width="100"
                             height="100" class="sidebar-profile-image">
                    </a>
                </div>
                <div class="col-md-7 col-lg-7 col-sm-7 col-xs-7 product-maker-summary">
                    <h4><a target="_blank"
                           href="<?php echo $this->buildMemberUrl($this->member->username); ?>"><span
                                class="glyphicon glyphicon-link"></span> <?= $this->member->username; ?></a></h4>

                    <div
                        class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small"><?= $this->member->firstname ?> <?= $this->member->lastname ?></div>
                    <div
                        class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small"><?= $this->member->city ?> <?= $this->member->country ?></div>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small"><a
                            href="mailto:<?= $this->member->mail ?>"><span
                                class="glyphicon glyphicon-envelope"></span> <?= $this->member->mail ?></a></div>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small"><a
                            href="<?= $this->addDefaultScheme($this->member->link_website); ?>"
                            class="lightblue"
                            target="_blank"><span
                                class="glyphicon glyphicon-link"></span> <?= $this->member->link_website; ?></a>
                    </div>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small"><a
                            href="<?= $this->member->link_facebook ?>"
                            target="_blank"><?= $this->member->link_facebook ?></a></div>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small"><a
                            href="<?= $this->member->link_twitter ?>"
                            target="_blank"><?= $this->member->link_twitter ?></a></div>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small">Facebook Name: <?= $this->member->facebook_username ?></div>
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 small">Twitter Name: <?= $this->member->twitter_username ?></div>
                </div>
            </div>
        </div>
    </div>
</div>