#!/usr/bin/env php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$_SERVER['HTTP_HOST'] = 'localhost';

use Backend\Console\CMatrixCliCommand;
use Backend\Console\MemberPayoutCliCommand;
use Backend\Console\RssCliCommand;
use Symfony\Component\Console\Application;
use Laminas\Stdlib\ArrayUtils;

chdir(dirname(__DIR__));

require_once __DIR__ . '/../vendor/autoload.php'; // Composer autoloader

// Prepare application and service manager
$appConfig = require __DIR__ . '/../config/application.config.php';
if (file_exists(__DIR__ . '/../config/development.config.php')) {
    $appConfig = ArrayUtils::merge($appConfig, require __DIR__ . '/../config/development.config.php');
}
$application = Laminas\Mvc\Application::init($appConfig);
$serviceManager = $application->getServiceManager();

// Load modules
$serviceManager->get('ModuleManager')->loadModules();
//$config = $serviceManager->get('config');
//$routes = $config['console']['commands']; // This depends on your structure, this is what I created (see. 1.)

$application = new Application();

$application->add(new MemberPayoutCliCommand());
$application->add(new RssCliCommand());
$application->add(new CMatrixCliCommand());

$exit = $application->run();
exit($exit);