<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$users = $this->newUsers($limit = 216,'created_at','DESC'); 
$buildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helperImage = new Default_View_Helper_Image();
$this->inlineScript()->appendFile('/theme/flatui/js/lib/bootstrap-validator.min.js');
?>

    <!-- new code -->
    <main id="reg-page">

        <section class="wrapper" id="register-wrap">
            <div id="register" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
                <div id="register-box" class="col-lg-8 col-md-8 col-sm-8 col-xs-8">

                    <div id="login-form-box" class="well" style="width:100%;">
                        <h3><?= $this->translate('Please type in your new password.') ?></h3>

                        <div id="help-block" class="help-block">
                            <?= $this->translate('') ?>
                        </div>
                        <div id="error" class="center text-error help-block">
                            <?php if ($this->error && isset($this->errorText)): ?>
                                <p class="errors">
                                    <?= $this->translate($this->errorText) ?>
                                </p>
                            <?php endif; ?>
                        </div>
                        <form id="passwordForm" class="standard-form row-fluid center" action="<?=$this->action?>" method="post" role="form" data-toggle="validator">
                            <?php
                            if ($this->error) {
                                $this->form->mail->class = $this->form->mail->class . ' has-error';
                            }
                            ?>

                            <div class="form-group has-feedback">
                                <input name="password1" id="password1" value="" type="password" placeholder="Password" data-minlength="6" class="form-control" required data-minlength-error="Minimum of 6 characters"><div class="help-block with-errors"></div></div>
                            <div class="form-group has-feedback">
                                <input name="password2" id="password2" value="" type="password" placeholder="Confirm Password" class="form-control" data-minlength="6" required data-match="#password1" data-minlength-error="Minimum of 6 characters" data-match-error="Passwords don't match"><div class="help-block with-errors"></div></div>

                            <button name="change_it" id="change_it" type="submit" class="btn btn-min-width btn-native">Set new Password <i id="load-state" class="fa fa-spinner fa-pulse hidden" aria-hidden="true"></i></button>

                        </form>

                    </div>

                </div>
                <!-- END #login-box -->
                <div id="social-register" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                </div>
            </div>
        </section>

        <section id="thumbs">

            <?php foreach ($users as $key => $user) { ?>

                <div class="thumb">
                    <a href="<?php echo $buildMemberUrl->buildMemberUrl($user['username']); ?>">
                        <span></span>
                        <img src="<?php echo $helperImage->Image($user['profile_image_url'],array('width' => 110, 'height' => 110, 'crop' => 2)); ?>"/>
                    </a>
                </div>

            <?php } ?>

        </section>

    </main>
    <!-- /new code -->

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){
          
        });
    ');
