<div class="my-products-list">
    <?php
    $helperBuildProductUrl = new Default_View_Helper_BuildProductUrl();
    $helperImage = new Default_View_Helper_Image();
    $helperPrintDate = new Default_View_Helper_PrintDate();
    foreach ($this->userProducts as $product): ?>
        <div class="product mini-card col-lg-2 col-md-2 col-sm-3 col-xs-2">
            <div class="u-wrap">
                <a href="<?= $helperBuildProductUrl->buildProductUrl($product['project_id']); ?>">
                    <figure>
                        <img
                                src="<?php echo $helperImage->Image($product['image_small'], array('width' => 280, 'height' => 171)); ?>"
                                class="explore-product-image" width="101" height="81"/>
                    </figure>
                    <div class="u-content">
                        <h3><?php echo $product['title']; ?></h3>
                        <span class="productCategory"> <?php echo $product['catTitle']; ?> </span>

                        <span class="productCategory" style="width: 100%; float: left;">
                            <?= $helperPrintDate->printDate($product['project_changed_at']) ?>
                        </span>
                    </div>
                </a>

                <?php
                $this->widgetRating = new stdClass();
                $this->widgetRating->project_id = $product['project_id'];
                $this->widgetRating->laplace_score = $product['laplace_score'];
                $this->widgetRating->count_likes = $product['count_likes'];
                $this->widgetRating->count_dislikes = $product['count_dislikes'];
                echo $this->render('partials/widgetRating.phtml'); ?>

            </div>

        </div>
    <?php endforeach; ?>
</div>