<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

//backdore for admins
$helperUserRole = new Backend_View_Helper_UserRole();
$userRoleName = $helperUserRole->userRole();
$getAuthUser = new Default_View_Helper_GetAuthUser();
$auth = Zend_Auth::getInstance();
$member = $getAuthUser->getAuthUser();
if (Default_Model_DbTable_MemberRole::ROLE_NAME_ADMIN == $userRoleName) {
    $this->member_id = $this->member_id;
} else {
    $this->member_id = $member->member_id;
}

$txtUserFollows = '';
$urlUserFollows = $this->buildProductUrl($this->project_id, 'unfollow');
$imgFile = '/theme/flatui/img/icon-like-color.png';
if (false == $this->userFollowsProject($this->member_id, $this->project_id)) {
    $txtUserFollows = '';
    $urlUserFollows = $this->buildProductUrl($this->project_id, 'follow');
    $imgFile = '/theme/flatui/img/icon-like.png';
}
?><a href="<?= $urlUserFollows ?>" class="purple partial" data-target="#container-follow">
    <?= $txtUserFollows ?><img src="<?= $imgFile ?>" alt="love it">
</a>