<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$pageCount = $this->comments->count();

$helperBuildProductUrl = new Default_View_Helper_BuildProductUrl();
$helperFetchSubcategoriesForProduct = new Default_View_Helper_FetchCategoriesForProductAsString();
$helperPrintDate = new Default_View_Helper_PrintDate();
?>
<div  id="my-comments-tabs">
    <div id="my-comments-tabs-content">
    <div style="text-align:right">
    <small >        
        <?php
        if ($pageCount > 1) {
            echo $this->paginationControl($this->comments, 'Sliding', '/partials/paginationControlBootstrap.phtml', array('params' => array(), 'dom_target' => 'div#my-comments-tabs-content'));
        }
        ?>
    </small>        
    </div>


    <?php 

       $this->result = array();                                                
        foreach ($this->comments as $element) {
            $this->result[$element['project_id']][] = $element;
        }    

        foreach($this->result as $this->projects){                                                            
            $i = 0;
            foreach($this->projects as $file){  
                $file=(object)$file; 
                if($i==0){
        ?>
                <div class="productrow">

                <div class="row smaller " >
                  <div class="col-lg-5 col-md-5">
                      <figure>
                          <img src="<?php echo $this->Image($file->image_small, array('width' => 80, 'height' => 80)); ?>" class="project-image" />
                      </figure>   
                      <div>
                          <a href="/p/<?=$file->project_id?>"><?=$file->title?></a>
                          <p><?=$file->cat_title?> 
                          
                          <span class="cntComments">
                          <?php               
                              $count_comments = $file->count_comments;                             
                              echo ($count_comments>0 ? $count_comments.' comment':'').($count_comments>1?'s':'');            
                          ?>
                          </span>
                         
                      </div>
                  </div>      
                              
                  <div class="col-lg-2 col-md-2" style="white-space: nowrap; padding-top: 15px">         
                       by <a  href="<?php echo $this->buildMemberUrl($file->project_member_id); ?>" class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$file->project_member_id?>">
                       <?=$file->username?></a>
                  </div>

                  <div class="col-lg-2 col-md-2">             
                      <div class="rating text-center" >               
                          <?php                
                                  $this->widgetRating = new stdClass();
                                  $this->widgetRating->project_id =$file->project_id;
                                  $this->widgetRating->laplace_score = $file->laplace_score;
                                  $this->widgetRating->count_likes =$file->count_likes; 
                                  $this->widgetRating->count_dislikes =$file->count_dislikes;
                                  echo $this->render('partials/widgetRating.phtml'); 
                          ?>          
                         
                      </div>          
                       <span class="time"><?=$this->printDate($file->changed_at==null?$file->created_at:$file->changed_at)?>
                          </span>  
                  </div>

                
                </div>



                <div class="row">
                                <div class="col-lg-9 commenttext">                                 
                                    <?php 
                                        $comment_text = Default_Model_HtmlPurify::purify($file->comment_text);
                                    ?>
                                    <?= nl2br($file->comment_text,true) ?>                                    
                                  
                                    <span class="createat"> - <?= $helperPrintDate->printDate($file->comment_created_at); ?> </span>
                                    </div>
                                    
                </div>

        <?php
                        }else{
            ?>
                    <div class="row">
                                <div class="col-lg-9 commenttext">                                 
                                    <?php 
                                        $comment_text = Default_Model_HtmlPurify::purify($file->comment_text);
                                    ?>
                                    <?= nl2br($file->comment_text,true) ?>                                    
                                  
                                    <span class="createat"> - <?= $helperPrintDate->printDate($file->comment_created_at); ?> </span>
                                    </div>
                                    
                </div>
        <?php
                }   // end of else if                                                                                       
                $i++;                                                                            
            }

            echo '</div> <!--productrow-->';
        }

        ?>


    </div>
</div>
