<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$pageCount = $this->comments->count();

$helperBuildProductUrl = new Default_View_Helper_BuildProductUrl();
$helperFetchSubcategoriesForProduct = new Default_View_Helper_FetchCategoriesForProductAsString();
$helperPrintDate = new Default_View_Helper_PrintDate();
?>
<div  id="my-comments-tabs">
    <div id="my-comments-tabs-content">
    <div style="text-align:right">
    <small >        
        <?php
        if ($pageCount > 1) {
            echo $this->paginationControl($this->comments, 'Sliding', '/partials/paginationControlBootstrap.phtml', array('params' => array(), 'dom_target' => 'div#my-comments-tabs-content'));
        }
        ?>
    </small>        
    </div>


    <?php 

       $this->result = array();                                                
        foreach ($this->comments as $element) {
            $this->result[$element['project_id']][] = $element;
        }    

        foreach($this->result as $this->projects){                                                            
            $i = 0;
            foreach($this->projects as $product){   
                if($i==0){
        ?>
                <div class="productrow">
                <div class="row">            
                         <div class="col-lg-2 col-md-2">    
                                <div class="text-center">
                                    <img class="productimg" src="<?=$this->Image($product['image_small'], array('width' => 80, 'height' => 80))?>" />
                                </div>
                         </div>
                         <div class="col-lg-6 col-md-6">
                                <a href="<?=$this->buildProductUrl($product['project_id'],'')?>"><?=$product['title']?>
                                    <span class="version"><?=Default_Model_HtmlPurify::purify($product['version'])?>
                                    </span>
                                </a>
                                <span style="display: block; margin-bottom: 5px"><?=$product['cat_title']?></span>
                                
                               
                                <div class="productInfo">
                                
                                <span class="cntComments">
                                <?php               
                                    $count_comments = $product['count_comments'];                             
                                    echo ($count_comments>0 ? $count_comments.' comment':'').($count_comments>1?'s':'');            
                                ?>
                                </span>
                               
                                </div>
                         </div>
                         <div class="col-lg-2 col-md-2 small" style="white-space: nowrap; padding-top: 20px">
                         by <a  href="<?php echo $this->buildMemberUrl($product['member_id']); ?>" class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$product['member_id']?>"><?=$product['username']?></a>
                         </div>
                         <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                            
                                <?php                
                                        $this->widgetRating = new stdClass();
                                        $this->widgetRating->project_id = $product['project_id'];
                                        $this->widgetRating->laplace_score = $product['laplace_score'];
                                        $this->widgetRating->count_likes = $product['count_likes']; 
                                        $this->widgetRating->count_dislikes =$product['count_dislikes'];
                                        echo $this->render('partials/widgetRating.phtml'); 
                                ?>
                            
                            <span class="time"><?=$this->printDate($product['changed_at']==null?$product['created_at']:$product['changed_at'])?>
                            </span>
                        </div>
                </div>
                <div class="row">
                                <div class="col-lg-12 commenttext">
                                 
                                    <?php 
                                        $comment_text = Default_Model_HtmlPurify::purify($product['comment_text']);
                                    ?>
                                    <?= nl2br($comment_text,true) ?>                                    
                                  
                                    <span class="createat"> - <?= $helperPrintDate->printDate($product['comment_created_at']); ?> </span>
                                    </div>
                                    
                </div>

        <?php
                        }else{
            ?>
                    <div class="row">
                                <div class="col-lg-12 commenttext">
                                  
                                    <?php 
                                        $comment_text = Default_Model_HtmlPurify::purify($product['comment_text']);
                                    ?>
                                    <?= nl2br($comment_text,true) ?>   
                                    <span class="createat"> - <?= $helperPrintDate->printDate($product['comment_created_at']); ?> </span>                                
                                    </div>
                                    
                </div>
        <?php
                }   // end of else if                                                                                       
                $i++;                                                                            
            }

            echo '</div> <!--productrow-->';
        }

        ?>


    </div>
</div>
