

<div class="row smaller header" >
	<div class="col-lg-5 col-md-5">
		<figure>
		    <img src="<?php echo $this->Image($this->file->image_small, array('width' => 80, 'height' => 80)); ?>" class="downloadhistory-image" />
		</figure>	
		<div>
			<a href="/p/<?=$this->file->project_id?>"><?=$this->file->title?></a>
			<p><?=$this->file->cat_title?> 
		</div>
	</div>		
		    	
	<div class="col-lg-2 col-md-2">	
		
		<div class="rating text-center" >				
		    <?php                
		            $this->widgetRating = new stdClass();
		            $this->widgetRating->project_id =$this->file->project_id;
		            $this->widgetRating->laplace_score = $this->file->laplace_score;
		            $this->widgetRating->count_likes =$this->file->count_likes; 
		            $this->widgetRating->count_dislikes =$this->file->count_dislikes;
		            echo $this->render('partials/widgetRating.phtml'); 
		    ?>		    
		</div>
		
	</div>
	
	
	<div class="col-lg-1" >
		<div id="container-follow<?=$this->file->project_id?>" style="display: block;float:left;margin-right: 3px">		
		<?php 
		if($this->file->project_member_id<> $this->authMember->member_id){
			echo $this->partial(
			    '/product/follow.phtml',
			    array(
			        "authMember"  => $this->authMember,
			        "project_id" => $this->file->project_id
			    )
			);
		}
		?>

		
		</div>			
	</div>

	<div class="col-lg-2" >
	<?=$this->printDate($this->file->created_at)?>
	</div>
</div>

