<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helpProductUrl = new Default_View_Helper_BuildProductUrl();
?>
<div class="friend-activity row-fluid">
    <div class="span3 supporter-thumbnail relative">
        <div class="profile-image-overlay-3 absolute"></div>
        <img src="<?php echo $this->creator_profile_image_url; ?>" alt="user image" width="80">
    </div>
    <!-- /.supporter-thumbnail -->
    <div class="span9 friend-activity-summary">
        <a href="<?= $helpMemberUrl->buildMemberUrl($this->member_id) ?>"><?php echo $this->username; ?></a><?php echo $this->translate('User' . $this->type_text); ?>
        <a href="<?= $helpProductUrl->buildProductUrl($this->prj_project_id); ?>"><?= $this->obj_title ?></a>
    </div>
    <!-- /.friend-activity-summary -->
</div><!-- /.friend-activity -->
