<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$pageCount = $this->comments->count();

$helperBuildProductUrl = new Default_View_Helper_BuildProductUrl();
$helperFetchSubcategoriesForProduct = new Default_View_Helper_FetchCategoriesForProductAsString();
$helperPrintDate = new Default_View_Helper_PrintDate();
?>
<div  id="my-comments-tabs">
    <div id="my-comments-tabs-content">
    <small class="pull-right">
        
        <?php
        if ($pageCount > 1) {
            echo $this->paginationControl($this->comments, 'Sliding', '/partials/paginationControlBootstrap.phtml', array('params' => array(), 'dom_target' => 'div#my-comments-tabs-content'));
        }
        ?>
    </small>        
    <?php foreach ($this->comments as $elementComment): ?>
        <div class="row rownomargin" >
            <?= Default_Model_HtmlPurify::purify($elementComment['title']) ?>
            <span  class="category" ><?php echo $helperFetchSubcategoriesForProduct->fetchCategoriesForProductAsString($elementComment['project_id']) ?></span>
        </div>
        <div class="row rownomargin" >
            <div class="info">
                <div class="small">
                	<?php 
		              	$comment_text = Default_Model_HtmlPurify::purify($elementComment['comment_text']);
		           	?>
                    <a href="<?=$helperBuildProductUrl->buildProductUrl($elementComment['project_id'], '', null, true)?>"><?= nl2br($comment_text,true) ?></a>
                </div>
            </div>
        </div>
        <div class="row commentstore rownomargin" >
            <span class="createat"><?= $helperPrintDate->printDate($elementComment['comment_created_at']); ?> </span>
        </div>
    <?php endforeach;?>
    </div>
</div>