
<?php

$userRateData = $this->fetchRate($this->file->project_id, $this->member_id);
//if($this->issupport) // is Supporter
$userrate ="data-userrate='-1'";
$comment="data-comment=''";
if($userRateData){
	$userrate ="data-userrate='".$userRateData['user_like']."'";	
	$comment="data-comment='".$userRateData['comment_text']."'";		
}		
$formproject="data-project='".$this->file->project_id."'";
$attrhistory = $userrate.' '.$comment.' '.$formproject;

if($this->counter==0){
?>
<div class="row smaller header" >
	<div class="col-lg-6 col-md-6">
		<figure>
		    <img src="<?php echo $this->Image($this->file->image_small, array('width' => 80, 'height' => 80)); ?>"
		         class="downloadhistory-image" />
		</figure>	
		<div>
			<a href="/p/<?=$this->file->project_id?>"><?=$this->file->title?></a>
			<p><?=$this->file->catTitle?> 
		</div>
	</div>			    	
	<div class="col-lg-2 col-md-2">	
		
		<div class="rating text-center" >				
		    <?php                
		            $this->widgetRating = new stdClass();
		            $this->widgetRating->project_id =$this->file->project_id;
		            $this->widgetRating->laplace_score = $this->file->laplace_score;
		            $this->widgetRating->count_likes =$this->file->count_likes; 
		            $this->widgetRating->count_dislikes =$this->file->count_dislikes;
		            echo $this->render('partials/widgetRating.phtml'); 
		    ?>		    
		</div>
		
	</div>
	<div class="col-lg-2 nowrap">
		<?=$this->file->max_downloaded_timestamp?> 
	</div>		
	<div class="col-lg-2" >
		
		<?php 							 			
			if (false == $this->userFollowsProject($this->member_id, $this->file->project_id)) {
			    	$urlUserFollows = $this->buildProductUrl($this->file->project_id, 'follow');
			    	$heartatt = 'class="partialbutton lightgrey"';			   
			}else{
				$urlUserFollows = $this->buildProductUrl($this->file->project_id, 'unfollow');				
				$heartatt = 'class="partialbutton purple"';
			}
			$heartatt = $heartatt. 'role="button" data-fragment=""  '
				      .' data-target="#container-follow'.$this->file->project_id.'"'
				      .' data-href="'.$urlUserFollows.'"';
		?>
		<div id="container-follow<?=$this->file->project_id?>" style="display: block;float:left;margin-right: 3px">		
		<button <?=$heartatt?> >
		    <span class="glyphicon glyphicon-heart" alt="love it" ></span>
		</button>
		</div>			

		<?php						
			if($userRateData){
				if($userRateData['user_like']>0){
					echo '<span class="glyphicon glyphicon-plus" style="color:green; padding:10px;"></span>'
						.$userRateData['comment_text']
						.'   '.$this->printDate($userRateData['created_at']);

				}else{
					echo '<span class="glyphicon glyphicon-minus" style="color:red;padding:10px;"></span>'
						.$userRateData['comment_text']
						.'   '.$this->printDate($userRateData['created_at']);
				}
			}else{
					
		?>
		
		<button <?=$attrhistory ?>  class="partialReviewDownloadHistory votedown"  name="votedown"> <span class="glyphicon glyphicon-minus" ></span></button>
		<button <?=$attrhistory ?>  class="partialReviewDownloadHistory voteup"  name="voteup"> <span class="glyphicon glyphicon-plus" ></span></button>				    
		<?php } ?>
			
	</div>
</div>

<?php /*
<div class="row smaller " >
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4  subheader" >
	Filename
	</div>
	<div class="col-lg-1 subheader">
	Downloaded at
	</div>			    		
</div>
*/
?>
<div class="row smaller">
	<div class="col-lg-4 paddingLeft80" >
	<?=$this->file->file_name?> 		
	</div>
	<div class="col-lg-2 " >
	<?=$this->humanFilesize($this->file->file_size)?> 		
	</div>
	<div class="col-lg-2 " >
	<?=$this->file->file_type?> 		
	</div>
	<div class="col-lg-2 nowrap">

	<?=$this->file->downloaded_timestamp?> 
       
	</div>
		    
			
</div>

<?php
}else{
?>
<div class="row smaller">
	<div class="col-lg-4 paddingLeft80" >
	<?=$this->file->file_name?> 		
	</div>
	<div class="col-lg-2 " >
	<?=$this->humanFilesize($this->file->file_size)?> 		
	</div>
	<div class="col-lg-2 " >
	<?=$this->file->file_type?> 		
	</div>
	<div class="col-lg-2 nowrap">

	<?=$this->file->downloaded_timestamp?> 
       
	</div>
		    
			
</div>
<?php
}
?>