<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

?>
<style>
    .cell-default {
        line-height: 4em;
        vertical-align: middle;
    }
    .popover {
        min-width:350px;
    }
    
    .row-total {
        border-top: #1595ee solid thin;
        padding-top: 1em;
        padding-bottom: 1em;
        line-height: 30px;
        margin-left: 0px;
        margin-right: 0px;
    }
    
    .popover-title { 
        text-transform: none;
        font-size: 11pt;
    }
    
    .popover-content { 
        text-transform: none;
        font-size: 11pt;
    }
</style>

<ul class="nav nav-tabs margin-bottom-10 tabs-up" id="plingtabs">
<?php

$helperUserRole = new Backend_View_Helper_UserRole();
$userRoleName = $helperUserRole->userRole();
    
$isCurrentMonth = false;
$currentYear = date("Y",time());

$member = $this->view_member;

if($this->year) {
    $currentYear = $this->year;
}


$currentDate = date("Ym",time());
$currentMonth = '';
$monthlyDownload = null;
$allDownloads = array();
$css_active = 'active';

$printCurrentMonth = new DateTime($currentDate.'01');

$modelDownload = new Default_Model_StatDownload();
$downloadMonths = $modelDownload->getUserAffiliatesMonths($this->member->member_id, $currentYear);
$countDownloadsOverall = count($downloadMonths);
$minDate = null;

if ($countDownloadsOverall > 0) {  
    foreach ($downloadMonths as $download) {
        $printMonth = new DateTime($download['yearmonth'].'01');
        if($minDate == null) {
            $minDate = $download['yearmonth'];
        }
        
        $printDate = $printMonth->format('M Y');
        $printDateNow = $printCurrentMonth->format('M Y');
        
        if($printDateNow == $printDate) {
            $printDate = 'Current month';
            $isCurrentMonth = true;
        } else {
            $isCurrentMonth = false;
        }
        
        if ($printDate != $currentMonth) {
            $monthlyDownload = array();
            $currentMonth = $printDate;
        
    ?>
    
    <?php if($isCurrentMonth) {?>
    
    <li class="media_node span <?=$css_active?> ">
        <a href="/member/<?= $member->member_id ?>/sectionaffiliatesmonthajax?yearmonth=<?= $download['yearmonth'] ?>" data-toggle="tabajax" data-target="#pling-tab-content" id="tab_<?= $download['yearmonth'] ?>"><?= $printDate ?></a>
    </li>
    
    <?php } else { ?>
    
    <li class="media_node span <?=$css_active?> ">
        <a href="/member/<?= $member->member_id ?>/sectionaffiliatesmonthajax?yearmonth=<?= $download['yearmonth'] ?>" data-toggle="tabajax" data-target="#pling-tab-content" id="tab_<?= $download['yearmonth'] ?>"><?= $printDate ?></a>
    </li>
    
    <?php } ?>
    
    <?php
        }
        $css_active = '';
        $monthlyDownload[] = $download;
        $allDownloads[$download['yearmonth']] = $monthlyDownload;
    }
     
} else {
    $currentMonth = '';
    $currentDate = date("Ym",time());
    $printMonth = new DateTime($currentDate.'01');
    
    $printDate = $printMonth->format('M Y');
    $printDate = 'Current month';
    
    $minDate = $currentDate;
    
    ?>
    <li class="in active">
        <a href="/member/<?= $member->member_id ?>/sectionaffiliatesmonthajax?yearmonth=<?= $currentDate  ?>" data-toggle="tabajax" data-target="#pling-tab-content" id="tab_<?= $currentDate  ?>"><?= $printDate ?></a>
    </li>
<?php
}
?>
</ul>



<div class="container-fluid margin-bottom-12" style="padding-left: 0; padding-right: 0;">
    <div class="row">
        <div class="col-md-2 text-left text-uppercase nowrap" style="white-space: nowrap; min-width: 190px;"><strong>Section</strong></div>
        <div class="col-md-1 text-right text-uppercase nowrap" style="white-space: nowrap; min-width: 190px;"><strong>Affiliates</strong></div>
        <div class="col-md-1 text-right text-uppercase nowrap" style="white-space: nowrap; min-width: 190px;"><strong>Sum Doantions</strong></div>
        <div class="col-md-1 text-right text-uppercase nowrap" style="white-space: nowrap; min-width: 190px;"><strong>Percentage </strong></div>
        <div class="col-md-1 text-right text-uppercase nowrap" style="white-space: nowrap; min-width: 190px;"><strong>Sum Payout</strong></div>
    </div>
</div>



<div class="tab-content" id="pling-tab-content"><i class="fa fa-spinner"></i></div>