
<?php

$userRateData = $this->fetchRate($this->file->project_id, $this->member_id);
$userrate ="data-userrate='-1'";
$comment="data-comment=''";
if($userRateData){
	$userrate ="data-userrate='".$userRateData['user_like']."'";	
	$comment="data-comment='".$userRateData['comment_text']."'";		
}		
$formproject="data-project='".$this->file->project_id."'";
$attrhistory = $userrate.' '.$comment.' '.$formproject;

if($this->counter==0){
?>
<div class="row smaller header" >
	<div class="col-lg-5 col-md-5">
		<figure>
		    <img src="<?php echo $this->Image($this->file->image_small, array('width' => 80, 'height' => 80)); ?>" class="downloadhistory-image" />
		</figure>	
		<div>
			<a href="/p/<?=$this->file->project_id?>"><?=$this->file->title?></a>
			<p><?=$this->file->catTitle?> 
		</div>
	</div>		
	<div class="col-lg-2 nowrap">
		<?=$this->file->max_downloaded_timestamp?> 
	</div>			    	
	<div class="col-lg-2 col-md-2">	
		
		<div class="rating text-center" >				
		    <?php                
		            $this->widgetRating = new stdClass();
		            $this->widgetRating->project_id =$this->file->project_id;
		            $this->widgetRating->laplace_score = $this->file->laplace_score;
		            $this->widgetRating->count_likes =$this->file->count_likes; 
		            $this->widgetRating->count_dislikes =$this->file->count_dislikes;
		            echo $this->render('partials/widgetRating.phtml'); 
		    ?>		    
		</div>
		
	</div>
	
	<div class="col-lg-2" >
		<?php if($this->file->project_member_id<> $this->authMember->member_id)
			{
				$votedownactive = "";
				$voteupactive = "";
				if($userRateData && $userRateData['user_like']>0){				
					$voteupactive = "active";												
				}else{						
					if($userRateData) $votedownactive = "active";						
				}
								
			?>
			<button <?=$attrhistory ?>  class="btn btn-danger  partialReviewDownloadHistory voting votedown <?=$votedownactive?>"  name="votedown"> <span class="glyphicon glyphicon-minus" ></span></button>
			<button <?=$attrhistory ?>  class="btn btn-success partialReviewDownloadHistory voting voteup <?=$voteupactive?> "  name="voteup"> <span class="glyphicon glyphicon-plus" ></span></button>				    
		<?php 
			} 
		?>


	<?php						
		if($userRateData){
			echo $userRateData['comment_text'].'   '.$this->printDate($userRateData['created_at']);
		}
		?>

	</div>
	<div class="col-lg-1" >
		<div id="container-follow<?=$this->file->project_id?>" style="display: block;float:left;margin-right: 3px">		
		<?php 
		if($this->file->project_member_id<> $this->authMember->member_id){
			echo $this->partial(
			    '/product/follow.phtml',
			    array(
			        "authMember"  => $this->authMember,
			        "project_id" => $this->file->project_id
			    )
			);
		}
		?>

		
		</div>	

			
	</div>
</div>

<div class="row smaller">
	<div class="col-lg-3 paddingLeft80" style="overflow: hidden">
	<?=$this->file->file_name?> 		
	</div>
	<div class="col-lg-2 " >
	<?=$this->humanFilesize($this->file->file_size)?> 		
	</div>	
	<div class="col-lg-2 nowrap">

	<?=$this->file->downloaded_timestamp?> 
       
	</div>
	<div class="col-lg-3 " >
	<?=$this->file->file_type?> 		
	</div>    
			
</div>

<?php
}else{
?>
<div class="row smaller">
	<div class="col-lg-3 paddingLeft80" style="overflow: hidden">
	<?=$this->file->file_name?> 		
	</div>
	<div class="col-lg-2 " >
	<?=$this->humanFilesize($this->file->file_size)?> 		
	</div>
	
	<div class="col-lg-2 nowrap">

	<?=$this->file->downloaded_timestamp?> 
       
	</div>
	<div class="col-lg-3 " >
	<?=$this->file->file_type?> 		
	</div>
		    
			
</div>
<?php
}
?>