<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

//$plingData = $this->userPlings($this->project_id);
$productUpdates = $this->projectUpdates($this->project_id);
$loopProductId = 'product' . $this->project_id;
//    $statusPayPal = $this->partialLoop()->view->member->paypal_mail;
$object_text = (mb_strlen($this->description) < 300) ? $this->description : mb_substr($this->description, 0, 295, 'UTF-8') . ' ... ';
$addedOnDate = $this->humanTiming($this->created_at);
$addedOnText = $addedOnDate['age'] . ' ' . $addedOnDate['unit'];
$updatedOnDate = $this->humanTiming($this->changed_at);
$updatedOnText = $updatedOnDate['age'] . ' ' . $updatedOnDate['unit'];
$websiteOwner = new Local_Verification_WebsiteProject();
$websiteAuthCode = $websiteOwner->generateAuthCode(stripslashes($this->link_1));

$helperBuildCollectionUrl = new Default_View_Helper_BuildCollectionUrl();
$helperButton = new Default_View_Helper_ExternalPlingButton();
$helperButtonCode = new Default_View_Helper_ExternalPlingButtonSource();
$helperSupporterBox = new Default_View_Helper_ExternalSupporterBox();
$helperSupporterBoxSource = new Default_View_Helper_ExternalSupporterBoxSource();
$helperDonationList = new Default_View_Helper_ExternalDonationList();
$helperDonationListSource = new Default_View_Helper_ExternalDonationListSource();
$helperImage = new Default_View_Helper_Image();
?>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-product-item" id="<?= $loopProductId ?>">
    <!-- IMAGE -->
    <figure class="col-lg-1 col-md-3 col-sm-3 col-xs-3">
        <img src="<?php echo $helperImage->Image($this->image_small, array('width' => 280, 'height' => 167)); ?>"
             class="explore-product-image" width="101" height="81"/>
    </figure>
    <!-- /IMAGE -->
    <!-- CONTENT -->
    <article class="col-lg-11 col-md-9 col-sm-9 col-xs-9">
        <!-- title -->
        <div class="title">
        	<?php
                $versionTextOnly = $version = Default_Model_HtmlPurify::purify($this->version);
              	$description = Default_Model_HtmlPurify::purify($object_text);
           	?>
            <h3><a href="<?= $helperBuildCollectionUrl->buildProductUrl($this->project_id) ?>"><?php echo $this->title; ?> <?php echo $version; ?></a><span  style="font-weight: normal; font-size: small; color: #4e4e4e"> added </span><span  style="font-weight: 700; font-size: small; color: #4e4e4e"><?= $addedOnText ?> ago</span><span style="font-weight: 700; font-size: small; float: right; color: #4e4e4e"> <?= $updatedOnText ?> ago</span><span style="font-weight: normal; font-size: small; float: right; color: #4e4e4e">updated&nbsp;</span></h3>

        </div>
        <!-- /title -->
        <div>
        <span class="topics">
            <span class="topicslink">
            <?php        
            $tagmodel = new Default_Model_Tags();
            $tagsuser = $tagmodel->getTagsUser($this->project_id, Default_Model_Tags::TAG_TYPE_PROJECT);        
            $tagscat = $tagmodel->getTagsCategory($this->project_id, Default_Model_Tags::TAG_TYPE_PROJECT);  


            if(false === empty($tagscat))
            {                  
                foreach (explode(',',$tagscat) as $tag) { 
            ?>
            <a rel="nofollow" href="/search/projectSearchText/<?=$tag?>/t/<?=$tag?>/f/tags" class="topic-tag topic-tag-link usertagslabelcat"><?=$tag?></a>
             <?php 
                }                                       
             }        

            echo '<span class="topicsuser">';
            if(false === empty($tagsuser))
            {                  
                foreach (explode(',',$tagsuser) as $tag) { 
            ?>
            <a rel="nofollow" href="/search/projectSearchText/<?=$tag?>/t/<?=$tag?>/f/tags" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a>
             <?php 
                }                                       
             }
             echo '</span>';
             ?>        
            </span>                  
            <span id="tagsuserselectpanel<?=$this->project_id?>" class="tagsuserselectpanel" style="display: none">
                    <select   
                            id="tagsuserselect<?=$this->project_id?>"                                           
                            name="tagsuser"                
                            multiple="true"                                                                                                                        
                            class="taggingSelect2"
                            data-pid="<?php echo $this->project_id?>"
                            >
                        <option value=""></option>
                        <?php
                        $element_value =$tagsuser;
                        $value = empty($element_value) ? array() : explode(',',$element_value);
                        foreach ($value as $v) {
                            echo '<option value="'.$v.'" selected="selected">'.$v.'</option>';                
                        }
                        ?>         
                    </select>
            </span>

            <button id="topic-tags-btn<?=$this->project_id?>" class="btn-link topic-tags-btn"  type="button" >Manage tags</button>
            <span id="topic-tags-saved<?=$this->project_id?>" class="topic-tags-saved" style="display: none"><i class="fa fa-check"></i> Saved </span>

        </span>
        </div>

        
        <!-- info -->
        <div class="info">
            <ul>
                <?php
                $collection_cat_id = Zend_Registry::get('config')->settings->client->default->collection_cat_id;
                $ranking_cat_id = Zend_Registry::get('config')->settings->client->default->ranking_cat_id;
                $catText = "Collection";
                if($this->project_category_id == $ranking_cat_id) {
                    $catText = "Ranking";
                }
                ?>
                <li><span>in</span><span><?php echo $catText; ?></span></li>
                <?php /**<li><span><?= $this->translate('supporters') ?> </span><span><?= $plingData['plingers'] ?></span></li>
                <li><span><?= $this->translate('collected') ?> </span><span><?= $plingData['plings'] ?></span></li> **/?>
            </ul>
        </div>
        <!-- /info -->
        <!-- text -->
        <div class="text">
            <p><?= nl2br($description) ?></p>
        </div>

        

      

        <!-- /text -->
        <!-- buttons -->
        <div class="buttons">
            <div class="embed-btns pull-left">
                <!-- verification -->
               
                <!-- /verification -->
                <!-- embeded -->
                <?php /*
                <a href="#modal-button-code-<?= $loopProductId ?>"
                   class="btn btn-native"
                   data-toggle="modal"><?= $this->translate('Button') ?></a>
                   */ ?>

                   <?php /*
                <a href="#modal-list-code-<?= $loopProductId ?>"
                   class="btn btn-native"
                   data-toggle="modal"><?= $this->translate('List') ?></a>
                <a href="#modal-widget-code-<?= $loopProductId ?>"
                   rel="<?= $loopProductId ?>"
                   class="btn btn-native widget-button"
                   data-toggle="modal"><?= $this->translate('Widget') ?></a>
                   */ ?>
                <!-- /embeded -->
            </div>

            <!--  manage -->
            <div class="manage-btns pull-right margin-left-20">
                <a role="button" href="<?= $helperBuildCollectionUrl->buildProductUrl($this->project_id, 'edit') ?>" class="btn btn-native" style="padding: 3px 6px;font-size: 12px;">
                    <?= $this->translate('Edit') ?>
                </a>
                
                <!-- updates -->
                <a role="button" class="btn btn-native" href="#modal-updates"
                    style="padding: 3px 6px;font-size: 12px;"
                   data-toggle="modal"
                   data-product-id="<?= $this->project_id ?>"
                   data-product-title="<?= $this->title ?>"
                ><?= $this->translate('Changelog') ?></a>
                
                <?php /*20200618 ronald: TODO: rebuild validation process 
                <?php if ($this->link_1) { ?>
                    <a href="#msg-box-code-<?= $loopProductId ?>"
                        style="padding: 3px 6px;font-size: 12px;"
                       class="btn btn-native margin-right-10"
                       data-toggle="modal"><?= $this->translate('Verification') ?></a>
                <?php } ?>
                 * 
                 */?>


              <?php /*
                 <a href="#modal-box-code-<?= $loopProductId ?>"
                   class="btn btn-native"
                   data-toggle="modal"><?= $this->translate('Box') ?></a>
                  */
                   ?>
                  

                <!-- /updates -->
                <span class="publish-product-wrapper">
                    <?php $p_action = $this->isProjectActive($this->project_status) ? 'unpublish' : 'publish' ?>
                    <a href="<?= $helperBuildCollectionUrl->buildProductUrl($this->project_id, $p_action, array('m' => $this->member_id)) ?>"
                        style="padding: 3px 6px;font-size: 12px;" class="btn btn-native <?=($p_action=='unpublish')?'btn-pling-green':'btn-pling-red'?> " data-target="#<?= $loopProductId ?> .publish-product-wrapper">
                        <?=ucfirst($p_action) ?>
                    </a>
                </span>
                <form method="post" action="<?= $helperBuildCollectionUrl->buildProductUrl($this->project_id, 'delete', array('m' => $this->member_id)) ?>" class="inline">
                    <button data-title="Delete Confirmation" data-callback="defaultCallbackConfirmation" data-message="Do you really want to delete this product?<br>This is permanent and can not be undone!" aria-label="Delete" class="btn btn-native btn-pling-red remove" style="font-size: 12px;padding: 3px 6px;">
                        Delete
                    </button>
                </form>

            </div>
            <!-- /manage -->

        </div>
        <!-- /buttons -->
    </article>
    <!-- CONTENT -->
    <!-- MODALS -->

    <!-- verification code -->
    <?php
    $verificationPopup = new Default_View_Helper_VerificationCodePopup();
    echo $verificationPopup->verificationCodePopup($this, $this->link_1, 'msg-box-code-' . $loopProductId, $this); ?>
    <!-- /verification code -->

    <?php $this->inlineScript()->appendScript(
        '$(document).ready(function(){
                    ButtonCode.setupClipboardCopy(\'div#modal-box-code-' . $loopProductId . '\');
                    ButtonCode.setupClipboardCopy(\'div#modal-button-code-' . $loopProductId . '\');
                    ButtonCode.setupClipboardCopy(\'div#modal-list-code-' . $loopProductId . '\');
                });'
    );
    ?>
    <!-- /MODALS -->
</div>

<div class="my-product-divider col-lg-12 col-md-12 col-sm-12 col-xs-12"></div>
