<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$helperMember = new Default_View_Helper_BuildMemberUrl();
?><ul class="nav nav-tabs">
    
    <li class="<?php echo $this->tab == 'activities' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->member_id, 'activities'); ?>">
            <span class="glyphicon glyphicon-align-justify"></span>
            <?= $this->translate('Activities') ?>
        </a>
    </li>
    
    <li class="<?php echo $this->tab == 'products' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->member_id, 'products'); ?>">
            <span class="glyphicon glyphicon-th-list"></span>
            <?= $this->translate('My Products') ?>
        </a>
    </li>

    <li class="header-menu-left-item <?php echo $this->tab == 'add' ? 'active' : ''; ?>">
        <?php if ($this->mode == 'edit') : ?>
            <a href="<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri() ?>">
                <span class="glyphicon glyphicon-pencil"></span>
                <?= $this->translate('Edit Product') ?>
            </a>
        <?php else : ?>
            <a href="/product/add/">
                <span class="glyphicon glyphicon-plus"></span>
                <?= $this->translate('Add Product') ?>
            </a>
        <?php endif ?>
    </li>

    <li class="header-menu-left-item <?php echo $this->tab == 'earnings' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->member_id, 'income'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('My Income') ?>
        </a>
    </li>

    <li class="header-menu-left-item <?php echo $this->tab == 'payment' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->member_id, 'payments'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('My Payments') ?>
        </a>
    </li>

    <li class="header-menu-left-item <?php echo $this->tab == 'payout' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->member_id, 'payout'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('My plings') ?>
        </a>
    </li>

    <li class="header-menu-left-item <?php echo $this->tab == 'settings' ? 'active' : ''; ?>">
        <a href="/settings/">
            <span class="glyphicon glyphicon-cog"></span>
            <?= $this->translate('My Settings') ?>
        </a>
    </li>
</ul>