<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$helperMember = new Default_View_Helper_BuildMemberUrl();
$helperBase = new Default_View_Helper_BuildBaseUrl();
?>
<div  class="pling-nav-tabs">
<ul class="nav nav-tabs">
    
    <li class="header-menu-left-item <?php echo $this->tab == 'add' ? 'active' : ''; ?>">
        <?php if ($this->mode == 'edit') : ?>
            <a href="<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri() ?>">
                <span class="glyphicon glyphicon-pencil"></span>
                <?= $this->translate('Edit Product') ?>
            </a>
        <?php else : ?>
        <a href="<?php echo $helperBase->buildBaserUrl('product/add'); ?>">
                <span class="glyphicon glyphicon-plus"></span>
                <?= $this->translate('Add Product') ?>
            </a>
        <?php endif ?>
    </li>
    
    
    <li class="<?php echo $this->tab == 'products' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'products'); ?>">
            <span class="glyphicon glyphicon-th-list"></span>
            <?= $this->translate('Products') ?>
        </a>
    </li>
    

    
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->roleName == 'admin'){
    $identity = Zend_Auth::getInstance()->getStorage()->read();
    ?>
    <li class="header-menu-left-item <?php echo $this->tab == 'addcollection' ? 'active' : ''; ?>">
        <?php if ($this->mode == 'editcollection') : ?>
            <a href="<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri() ?>">
                <span class="glyphicon glyphicon-pencil"></span>
                <?= $this->translate('Edit Collection') ?>
            </a>
        <?php else : ?>
        <a href="<?php echo $helperBase->buildBaserUrl('collection/add'); ?>">
                <span class="glyphicon glyphicon-plus"></span>
                <?= $this->translate('Add Collection') ?>
            </a>
        <?php endif ?>
    </li>
    <li class="<?php echo $this->tab == 'collections' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'collections'); ?>">
            <span class="glyphicon glyphicon-th-list"></span>
            <?= $this->translate('Collections') ?>
        </a>
    </li>
     <?php } ?>

    <li class="header-menu-left-item <?php echo $this->tab == 'payout' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'payout'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('Payout') ?>
        </a>
    </li>
    
    <li class="header-menu-left-item <?php echo $this->tab == 'payouthistory' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'payouthistory'); ?>">                                   
            <span class="payouthistory-icon" aria-hidden="true"></span>
            <?= $this->translate('Payout-History') ?>
        </a>
    </li>
    <li class="<?php echo $this->tab == 'downloadhistory' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'downloadhistory'); ?>">
            <span class="glyphicon glyphicon-star"></span>
            <?= $this->translate('Download-History') ?>
        </a>
    </li>

    <li class="<?php echo $this->tab == 'likes' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'likes'); ?>">
            <i class="fa fa-heart" aria-hidden="true"></i>
            <?= $this->translate('Fan of') ?>
        </a>
    </li>
    
    <li class="<?php echo $this->tab == 'activities' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'activities'); ?>">
            <span class="glyphicon glyphicon-align-justify"></span>
            <?= $this->translate('Activities') ?>
        </a>
    </li>
    
    <li class="header-menu-left-item <?php echo $this->tab == 'settings' ? 'active' : ''; ?>">
        <a href="<?php echo $helperBase->buildBaserUrl('settings'); ?>">
            <span class="glyphicon glyphicon-cog"></span>
            <?= $this->translate('Settings') ?>
        </a>
    </li>
    
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->roleName == 'admin'){
    $identity = Zend_Auth::getInstance()->getStorage()->read();
    ?>
    
        <?php  if($this->isSupporter($this->member->member_id)){?>
        <li class="header-menu-left-item <?php echo $this->tab == 'supporter' ? 'active' : ''; ?>">           
             <a href="<?php echo $helperMember->buildMemberUrl($this->member->username, 'supporter'); ?>">        
                <i class="fa fa-user"></i>
                <?= $this->translate('Supporter') ?>
            </a>
        </li>
        <?php }?>
    
    <?php }?>
    

   <?php /*

   <li class="header-menu-left-item <?php echo $this->tab == 'supporterbox' ? 'active' : ''; ?>">
        <a href="<?php echo $helperBase->buildBaserUrl('supporterbox'); ?>/<?=$identity->member_id?>">            
            <i class="fa fa-user"></i>
            <?= $this->translate('Supporter box') ?>
        </a>
    </li>
    <li class="header-menu-left-item <?php echo $this->tab == 'earnings' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->member_id, 'income'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('My Income') ?>
        </a>
    </li>
 
    <li class="header-menu-left-item <?php echo $this->tab == 'payment' ? 'active' : ''; ?>">
        <a href="<?php echo $helperMember->buildMemberUrl($this->member->member_id, 'payments'); ?>">
            <span class="glyphicon glyphicon-usd"></span>
            <?= $this->translate('My Payments') ?>
        </a>
    </li>
    */ ?>
    
</ul>
</div>