<!DOCTYPE html>
<html>
<head>
    <script>
        function loadComplete(){
            alert("Completed Setting Cookies");
        }
    </script>
</head>
<body onload="loadComplete()">
<p>
    Please Wait...
</p>
<?php
$config = Zend_Registry::get('config')->settings->domain;
?>
<img src="//<?=$config->openid->host?>/logout" style="display:none;" />
<img src="//<?=$config->forum->host?>/logout" style="display:none;" />
<img src="//<?=$config->opencode->host?>/logout" style="display:none;" />
</body>
</html>