<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
							 			
if (false == $this->userFollowsProject($this->authMember->member_id, $this->project_id)) {
    	$urlUserFollows = $this->buildCollectionUrl($this->project_id, 'follow');
    	$heartatt = 'class="partialbutton lightgrey"';			   
}else{
	$urlUserFollows = $this->buildCollectionUrl($this->project_id, 'unfollow');				
	$heartatt = 'class="partialbutton purple"';
}
$heartatt = $heartatt. 'role="button" data-fragment=""  '
	      .' data-target="#container-follow'.$this->project_id.'"'
	      .' data-href="'.$urlUserFollows.'"';
?>
		
<button <?=$heartatt?> >
    <span class="glyphicon glyphicon-heart" alt="love it"></span>
</button>

