<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

use Application\Model\Service\HtmlPurifyService;
use Laminas\View\Helper\Doctype;

$this->headTitle($this->headTitle);
$identity = $this->ocs_user;

$isAdmin = false;
if ($this->ocs_user->member_id && 'admin' == $this->userRoleName) {
    $isAdmin = true;
}

$isModerator = false;
if ($this->ocs_user->member_id && 'moderator' == $this->userRoleName) {
    $isAdmin = true;
}

$uri = $_SERVER['REQUEST_URI'];
$redirect = new \Laminas\Uri\Uri($_SERVER['REQUEST_URI']);
$redirect->setHost(null)->setScheme(null);
$loginUrl = $this->url('application_login');
if ($uri != '/' AND $uri != '') {
    $loginUrl .= "redirect/" . $this->urlEncrypt($redirect->toString());
}
//$loginUrl = '/login?redirect=' . $this->urlEncrypt($this->request->getUriString(), true);
$viewSidebar = 'partials/productAboutSidebar.phtml';
$viewClaimBox = false;
if ($this->product->claimable == 1) {
    $viewClaimBox = 'partials/productClaimTopHeader.phtml';
}


$this->product->title = strip_tags(HtmlPurifyService::purify($this->product->title));
$this->product->description = Application\Model\Service\BbcodeService::renderHtml(HtmlPurifyService::purify($this->product->description));
$description_meta = strip_tags(HtmlPurifyService::purify($this->product->description));
$this->product->version = strip_tags(HtmlPurifyService::purify($this->product->version));
//$this->product->embed_code =\Application\Model\Service\HtmlPurifyService::purify($this->product->embed_code,\Application\Model\Service\HtmlPurifyService::ALLOW_EMBED);
$this->product->link_1 = HtmlPurifyService::purify($this->addDefaultScheme($this->product->link_1), HtmlPurifyService::ALLOW_URL);
$this->product->source_url = HtmlPurifyService::purify($this->product->source_url, HtmlPurifyService::ALLOW_URL);
$this->product->facebook_code = HtmlPurifyService::purify($this->product->facebook_code, HtmlPurifyService::ALLOW_URL);
$this->product->twitter_code = HtmlPurifyService::purify($this->product->twitter_code, HtmlPurifyService::ALLOW_URL);
$this->product->google_code = HtmlPurifyService::purify($this->product->google_code, HtmlPurifyService::ALLOW_URL);


$this->doctype(Doctype::XHTML1_RDFA);

$this->headMeta()->setName('description', $this->truncate($description_meta, 200, '...', false, true))->setAutoEscape(false);
$this->headMeta()->setName('title', $this->truncate($this->product->title, 200, '...', false, true))->setAutoEscape(false);
$this->headMeta()
     ->appendProperty('og:url', $this->buildProductUrl($this->product->project_id, '', null, true))
     ->setAutoEscape(false);
$this->headMeta()->appendProperty('og:type', 'website')->setAutoEscape(false);
$this->headMeta()->appendProperty('og:title', $this->product->title)->setAutoEscape(false);
$this->headMeta()
     ->appendProperty('og:description', $this->truncate($description_meta, 200, '...', false, true))
     ->setAutoEscape(false);
$this->headMeta()
     ->appendProperty('og:image', $this->Image($this->product->image_small, array('width' => 400, 'height' => 400)))
     ->setAutoEscape(false);

$userRoleName = $this->userRoleName;

$productJson = $this->productJson;
$xdgTypeJson = \Laminas\Json\Encoder::encode($this->catXdgType($this->product->project_category_id));

$isowner = false;
if($this->ocs_user->member_id && $this->ocs_user->member_id==$this->product->member_id){
    $isowner = true;
}

?>
<style type="text/css">
    .collection-panels{
        background: none repeat scroll 0 0 #fff;
        height: auto;     
        border-radius: 0;
        padding: 15px;
        float: left;
        width: 100%;
        margin: 0;
      
    }
    span.downloadlink
    {
        white-space: normal; color: #23527c;
    }
    span.filesize
    {
        float: right;
    }

    div.row-collection
    {
        padding-top: 10px;
        border-top: 1px solid lightgray; 
        margin-top: 10px;
    }
    div.row-collection:first-child
    {
        padding-top: 0px;
        border-top: 0px; 
        margin-top:0px;
       
    }
    div.row-detail
    {
        padding-top: 10px;
        font-size: small;
    }
    
    #product-discussion h3 {
        color: #2673b0;
        margin-bottom: 20px;
        margin-top: 0;
    }
</style>


    <link href="/theme/react/assets/css/get-it.css" type="text/css" rel="stylesheet"/>

    <!-- facebook -->
    <div id="fb-root"></div>
    <?php if ($this->ocs_user->member_id) {
        ?>
    <div id="report-product-<?= $this->product->project_id ?>" class="modal report-product" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <form id="product-report" class="full-width partialjson" action="/report/product/"
                      data-target="#report-product-<?= $this->product->project_id ?>-message">
                    <input type="hidden" name="p" value="<?= $this->product->project_id ?>">
                    <div id="report-product-<?= $this->product->project_id ?>-message">
                        <p>Do you really want to report this product?</p>
                        <div class="modal-footer">
                            <button type="submit" class="small">
                                <span class="glyphicon glyphicon-share-alt"></span> Yes
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div id="report-product-fraud-<?= $this->product->project_id ?>" class="modal report-product-fraud" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <form id="product-report-fraud" class="full-width partialjsonfraud" action="/report/productfraud/"
                      data-target="#report-product-fraud-<?= $this->product->project_id ?>-message" >
                    <input type="hidden" name="p" value="<?= $this->product->project_id ?>">
                    <div id="report-product-fraud-<?= $this->product->project_id ?>-message" class="message" style="padding: 20px">
                        <div>Please specify why this product is misused (min 5 chars):
                           <textarea class="" id="report-text" name="t" cols="50" rows="3"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="small">
                                <span class="glyphicon glyphicon-share-alt"></span> Report
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


     <div id="report-product-clone-<?= $this->product->project_id ?>" class="modal report-product-clone" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                                <h2 class="modal-title">This product is based on:</h2>
                </div>
                <form id="product-report-clone" class="full-width partialjson" action="/report/productclone/"
                      data-target="#report-product-clone-<?= $this->product->project_id ?>-message">
                    <input type="hidden" name="p" value="<?= $this->product->project_id ?>">
                    <div id="report-product-clone-<?= $this->product->project_id ?>-message" class="message" style="padding: 20px">
                        <div>
                            <label class="form-label">Original product ID on opendesktop:  </label><br/>
                            <input name="pc" onkeyup="this.value=this.value.replace(/[^\d]/,'')"/><br/><br/>
                            <label class="form-label">External link to original product: </label><br/>
                            <input name="l" style="width: 440px;" />
                            <br/><br/>
                            <label class="form-label">Additional message: </label>
                            <br/>
                           <textarea class="" id="report-text" name="t"  rows="3" style="width: 440px;"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="small">
                                <span class="glyphicon glyphicon-share-alt"></span> add credits
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <?php } ?>




    <?php if ($this->ocs_user->member_id) {
        ?>
    <div id="like-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <div class="modal-body">
                 <form class="full-width " action="/" method="post">
                            <input type="hidden" name="p" value="<?= $this->product->project_id ?>"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>
                            <input type="hidden" name="pm" value="<?=$this->product->member_id?>" id="productcreator"/>
                </form>
                </div>
            </div>
        </div>
    </div>

    <?php
    } else { ?>

    <div id="like-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
           <div class="modal-content" style="min-height: 100px; ">
               <span style="text-align: center; display: block; padding-top: 30px">Please login. <br/><a href="<?=$loginUrl?>">Login</a></span>
           </div>
         </div>
    </div>

    <?php } ?>

    <?php if ($this->ocs_user->member_id) { ?>
    <div id="review-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <div class="modal-body">
                 <form class="full-width product-add-comment-review" action="/productcomment/addreplyreview/" method="post" >
                            <input type="hidden" name="p" value="<?= $this->product->project_id ?>"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>
                            <input type="hidden" name="v" value="1" id="voteup"/>
                            <input type="hidden" name="pm" value="<?=$this->product->member_id?>" id="productcreator"/>
                            <input type="hidden" name="otxt" value="<?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?>" id="otxt"/>
                            <input type="hidden" name="userrate" value="<?=$this->ratingOfUser==null?-1:$this->ratingOfUser['user_like']?>" id="userrate"/>
                            <textarea name="msg" class="full-width" id="commenttext"><?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?></textarea>
                            <button type="submit" class="small pull-right">Rate Now</button>
                </form>
                </div>
            </div>
        </div>
    </div>

    <div id="score-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <form class="full-width product-add-comment-review-new" action="/productcomment/addreplyreviewnew/" method="post" id="reviewform">
               <div class="modal-body">
                 
                            <input type="hidden" name="p" value="<?= $this->product->project_id ?>"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>                            
                            <input type="hidden" name="pm" value="<?=$this->product->member_id?>" id="productcreator"/>
                            <input type="hidden" name="otxt" value="<?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?>" id="otxt"/>
                            
                            <input type="hidden" name="userscore" value="<?=$this->ratingOfUser==null?-1:$this->ratingOfUser['score']?>" id="userscore"/>
                            <input type="hidden" name="s" value="<?=$this->ratingOfUser==null?-1:$this->ratingOfUser['score']?>" id="userscorevalue"/>
                            <textarea name="msg" class="full-width" id="commenttext"><?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?></textarea>
                                   
                </div>
                <div class="modal-footer">
                            <button type="button" class="small" id="modal-btn-cancel" style="margin-right:20px ">Cancel</button>                             
                            <button type="submit" class="small pull-right" id="modal-btn-onsubmit">Rate Now</button>
                </div>
                </form>
            </div>
        </div>
    </div>

    <?php } else {?>
        <div id="review-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
               <div class="modal-content" style="min-height: 150px; ">
                   <span style="text-align: center; display: block; padding-top: 30px">
                    Please login.
                    <br/>
                    <a href="<?=$loginUrl?>" rel="nofollow"> Login </a>
                   <?php /*
                    Only registered members with an active supporting can vote<br/>to limit spam and fraud voting.<br/>
                    <a href="/support">Become a supporter</a>
                    <br/><br/>You can still 'Like' a product, but that doesn't affect its score.
                        */
                    ?>
                    </span>
               </div>
             </div>
        </div>

        <div id="score-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
               <div class="modal-content" style="min-height: 150px; ">
                   <span style="text-align: center; display: block; padding-top: 30px">
                    Please login.
                    <br/>
                    <a href="<?=$loginUrl?>" rel="nofollow"> Login </a>                   
                    </span>
               </div>
             </div>
        </div>

    <?php } ?>


    <link href="/theme/flatui/css/product-page.css" type="text/css" rel="stylesheet"/>

    <main id="product-page-content">
        <div id="product-page-view" class="disply-flex">
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12 sidebar-left" style="">
                <?php include __DIR__ . '/../explore/partials/filter.phtml'; ?>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12" id="product-main">
                <div class="flex-row imgsmall" id="product-main-img-container">
                    <div class="product-main-img flex-item-24" id="product-main-img">
                        <div id="product-title-div" class="product-title-div">
                            <div  class="product-title">
                            <div class="product-logo-container">
                                  <img class="logo" src="<?= $this->Image($this->product->image_small,
                                      array('width' => 85, 'height' => 85, 'crop' => 'crop')); ?>"/>
                                </div>
                                <div id="product-header-info-container">

                                    <div id="product-header-title">
                                        <?= $this->product->title; ?>
                                    <?php
                                                if($this->product->featured=='1'){
                                        ?>
                                            <span class=" label label-info right" style="font-size: 13px;padding: .2em .6em .3em;"> Featured</span>
                                    <?php }?>
                                    </div>


                                    <p class="product_category">
                                    <?php
                                    echo '<a href="/browse/cat/' . $this->product->project_category_id . '/order/latest">' . $this->product->cat_title . ' </a>';
                                    ?>

                                    <?php
                                    echo '<span class="topics">';

                                    $tagsuser = $this->tagsuser;
                                    echo '<span class="topicslink">';
                                    if(false === empty($tagsuser))
                                    {
                                        foreach (explode(',',$tagsuser) as $tag) {
                                    ?>
                                    <a rel="nofollow" href="<?=$this->buildSearchTagUrl($tag)?>" class="topic-tag topic-tag-link usertagslabel"><?=$tag?></a>
                                     <?php
                                        }
                                     }
                                     echo '</span><!--end of topicslink-->';
                                     if($isowner){
                                            $this->headLink()->appendStylesheet('/theme/flatui/css/select2.min.css');
                                            $this->headLink()->appendStylesheet('/theme/flatui/css/select2.custmized.css');
                                            $this->inlineScript()->appendFile('/theme/flatui/js/lib/select2.min.js');
                                        ?>
                                        <span class="tagsuserselectpanel" style="display: none; ">
                                            <select
                                                    id="tagsuserselect"
                                                    name="tagsuser"
                                                    multiple="true"
                                                    class="taggingSelect2"
                                                    data-pid="<?php echo $this->product->project_id?>"
                                                    >
                                                <option value=""></option>
                                                <?php
                                                $element_value =$tagsuser;
                                                $value = empty($element_value) ? array() : explode(',',$element_value);
                                                foreach ($value as $v) {
                                                    echo '<option value="'.$v.'" selected="selected">'.$v.'</option>';
                                                }
                                                ?>
                                            </select>
                                        </span>

                                        <button class="btn-link topic-tags-btn"  type="button" >Manage tags</button>
                                        <span class="topic-tags-saved"><i class="fa fa-check"></i> Saved </span>
                                    <?php
                                            $this->inlineScript()->appendScript(
                                                '    $(document).ready(function(){
                                                        TagingProductDetail.setup();
                                                    });
                                                ');
                                         }
                                    echo '</span>';
                                     ?>

                                </div>
                            </div>

                            <div class="product-title-right" >


                                <div class="projectdtailHeart">
                                        <div id="container-follow<?=$this->product->project_id?>" class="container-pling">
                                        <?php
                                            echo $this->partial(
                                                '/partials/projectlike.phtml',
                                                array(
                                                    "authMember"  => $identity,
                                                    "project_id" => $this->product->project_id
                                                )
                                            );
                                        ?>
                                        </div>
                                </div>

                                 <?php if ($isAdmin ){  ?>
                                <div class="projectdetailRating" style="clear: right; font-style:italic">
                                        <?php include __DIR__ . '/../partials/sidebarRating.phtml'; ?>
                                </div>
                                <div class="projectdetailRating" style="clear: right;font-style:italic">
                                        <?php include __DIR__ . '/../partials/sidebarScore.phtml'; ?>
                                </div>
                                <?php } ?>
                                <div class="projectdetailRating" style="clear: right">                                   
                                    <?php include __DIR__ . '/../partials/score.phtml'; ?>
                                </div>
                               


                            </div>
                        </div>

                        <div style="padding-left: 25px;">   
                            <article>
                                <b>Description:</b> <br/><br/>
                                <?=$this->product->description ?>
                             </article>
                        </div>
                    </div>
                </div>

                

                <div class="flex-item-24" id="product-tabs-container">
                    <!-- TABS -->
                    <div id="product-tabs" class="pling-nav-tabs">
                        <ul class="nav nav-tabs ">
                            <?php /*
                            <li class="active"><a href="#about-panel" data-toggle="tab">Info</a></li>
                            */?>
                        <?php if(count($this->collection_projects)>0){ ?>
                            <li class="active"><a href="#products-panel" data-toggle="tab">Products <?php echo '('.count($this->collection_projects).')';  ?></a></li>
                        <?php } ?>
                        <?php if(count($this->updates)>0){ ?>
                            <li><a href="#updates-panel" data-toggle="tab">Changelogs <?php echo '('.count($this->updates).')';  ?></a></li>
                        <?php } ?>


                        <?php /*if ($isAdmin ){  ?>
                        <li><a href="#ratings-panel" data-toggle="tab">Ratings & Reviews <?php echo '('.$cntRatingsActive.')';  ?></a></li>
                       <?php } */?>
                        
                        <li><a href="#ratings-panel2" data-toggle="tab">Ratings & Reviews <?php echo '('.count($this->ratings).')';  ?></a></li>   

                         <?php if(count($this->likes)>0){ ?>
                            <li><a href="#likes-panel" data-toggle="tab">Fans <?php echo '('.count($this->likes).')';  ?></a></li>
                        <?php } ?>
                        <?php if(count($this->projectplings)>0){ ?>
                            <li><a href="#plings-panel" data-toggle="tab">Plings <?php echo '('.count($this->projectplings).')';  ?></a></li>
                        <?php } ?>
                        </ul>
                    </div>
                    <!-- /TABS -->

                    <!-- PANELS -->

                    <div class="tab-content row collection-panels" id="product-panels">

                        <!-- collectionProducts -->
                        <?php
                        if (count($this->collection_projects) > 0) { ?>
                        <div class="tab-pane active" id="products-panel">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                
                                <article>
                                    <div id="collectionProductsContainer">
                                    <?php
                                           echo $this->render('partials/collectionProjects.phtml');
                                      ?>
                                      </div>
                                </article>

                                <!-- comments -->
                                <div id="product-discussion" class="comment-containers">
                                    <?php
                                    $testComments = $this->commentsTree;
                                    $this->comments = $testComments;
                                    echo $this->render('partials/productCommentsUX1.phtml');
                                    ?>
                                </div>
                                <!-- /comments -->
                                
                            </div>
                            
                            
                                
                        </div>
                        <?php } ?>

                        <!-- updates panel -->
                        <?php  if (count($this->updates) > 0) { ?>
                        <div class="tab-pane" id="updates-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                            <article>
                                <?php
                                    foreach ($this->updates as $this->productUpdate) {
                                       echo $this->render('partials/productUpdatesV1.phtml');
                                    }
                                  ?>
                            </article>
                            </div>
                        </div>
                        <?php } ?>

                        <!-- ratings panel2 -->
                        
                        <div class="tab-pane" id="ratings-panel2">
                            <div id="ratings-panel-wrapper2" class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <article>
                                <div id="productRatingContainer2">
                                <?php
                                       echo $this->render('partials/productRating2.phtml');
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>

                        <!-- likes panel -->
                        <?php  if (count($this->likes) > 0) { ?>
                        <div class="tab-pane" id="likes-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <article>
                                <div id="productLikesContainer">
                                <?php
                                       echo $this->render('partials/productLikes.phtml');
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>
                        <?php } ?>

                        <!-- plings panel -->
                        <?php  if (count($this->projectplings) > 0) { ?>
                        <div class="tab-pane" id="plings-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <article>
                                <div id="productPlingsContainer">
                                <?php
                                       echo $this->render('partials/productPlings.phtml');
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                    <!-- /PANELS -->
                </div>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 flex-right" id="product-maker">
                <div>
                    <div class="project-share-new col-lg-12 col-md-12 col-sm-12 col-xs-12">                        
                        <?php if (empty($this->product->claimable)) { ?>
                            <div class="prod-widget-box prod-user right ">
                                <div class="sidebar-content">
                                    <div class="product-maker-sidebar">
                                        <div class="product-maker-thumbnail relative">
                                            <a href="<?php echo $this->buildMemberUrl($this->product->username); ?>"
                                               title="<?= $this->product->username ?>"  class="tooltipuserleft" data-tooltip-content="#tooltip_content" data-user="<?=$this->product->member_id?>">
                                               <?php
                                                    if($this->isSupporter($this->product->member_id)) {
                                                        $isSupporterActive = $this->isSupporterActive($this->product->member_id);
                                                ?>
                                                    <span class="supporter-badge <?=($isSupporterActive?'':'inactive')?>" >S</span>
                                                <?php } ?>
                                                <img src="<?= $this->Image($this->product->profile_image_url,
                                                    array('width' => 80, 'height' => 80)) ?>"
                                                     alt="product-maker" width="15" height="15"
                                                     class="sidebar-profile-image">
                                            </a>
                                        </div>
                                        <div class="product-maker-summary">
                                            <h5>
                                                <a href="<?php echo $this->buildMemberUrl($this->product->username); ?>" class="tooltipuserleft" data-tooltip-content="#tooltip_content" data-user="<?=$this->product->member_id?>">
                                                    <?= $this->product->username; ?>
                                                </a>
                                            </h5>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>

                        <div>
                            <?php
                            $this->moreProducts = $this->moreProductsOfUser;
                            $this->moreProductsTitle = 'More ' . $this->product->cat_title . ' from ' . $this->product->username;

                            if (count($this->moreProducts) > 0) {
                            echo $this->render('partials/productMoreProductsWidgetV1.phtml');
                            } ?>
                        </div>
                        
                        <div>
                            <?php
                            $this->moreProducts = $this->moreProductsOfOtherUsers;
                            $this->moreProductsTitle = 'Other ' . $this->product->cat_title;

                            if (count($this->moreProducts) > 0) {
                            echo $this->render('partials/productMoreProductsWidgetV1.phtml');
                            } ?>
                        </div>
                        <!-- /MORE PRODUCTS -->


                        <?php echo $this->render('partials/details.phtml'); ?>                                                

                        <?php echo $this->render('partials/tags.phtml'); ?>



                    </div>
                </div>

            </div>
        </div>
         <div class="tooltip_templates" style="display: none">
            <span id="tooltip_content">
                <i class="fa fa-spinner"></i>
            </span>
        </div>
    </main>


<script type="application/javascript">
    // tool tips
    $('body').on('mouseenter', '.product-thumbnail, .supporter-thumbnail', function () {
        $(this).popover('show');
    });

    $('body').on('mouseleave', '.product-thumbnail, .supporter-thumbnail', function () {
        $(this).popover('hide');
    });
</script>


<script type="text/javascript">
  var product = <?php echo $productJson ?>;
  var xdgTypeJson = <?php echo $xdgTypeJson ?>;
</script>

<?php
$this->inlineScript()->appendScript(
        '    $(document).ready(function(){
            InitActiveHashTab.setup();
            PartialJson.setup();
            PartialJsonFraud.setup();
            PartialJsonClone.setup();
            ProductDetailCarousel.setup();
            PartialCommentReviewForm.setup();
            PartialCommentReviewFormNew.setup();
            PartialsButtonHeartDetail.setup();
            PartialsButtonPlingProject.setup();
            TooltipUser.setup("tooltipuserleft","left");
            AppimagequestionOnClick.setup();
            Opendownloadfile.setup();
            CreateScoreRatingPopup.setup();
            PagedetailModeratorDeprecated.setup(' . $this->product->project_id . ');
            $(\'.tooltipheart\').tooltipster({theme: [\'tooltipster-light\', \'tooltipster-light-customized\'],
                    contentCloning: true,
                    contentAsHTML: true,
                    interactive: true});

        });
    ');