<div style="padding-top: 20px">
<h3>About OpenDesktop.org</h3>

Started in 2001, OpenDesktop.org is one of the largest websites for the Free Software and Content community.
<br>
<br>


<h3>Purpose</h3>

Our goal is the advancement of free and open source software and libre content.
Therefore we use all libre software for our services, while participating on any part of the platform is completely free.
<br>
<br>


<h3>Openess</h3>

Our goal is the advancement of free and open source software and libre content.
<br>
Therefore participating on all parts of the platform is completely free.
<br>
<br>

<h3>Portal</h3>

Part of openDesktop.org are sites such as Pling.com, Appimagehub.com, Opencode.net and many more, offering services like libre File and Data storage, Coding + CI, a federated chat + messaging and a Store for publishing and pledging libre content to break the dependency on proprietary offerings.
<br>
<br>




<h3>Community</h3>
Building friendships via publishing content, working on projects, commenting and supporting projects is at the heart of the openDesktop community.
<br>
As of today, it counts more than 100K+ registered users and 2.6 million unique visitors each month.
<br>
<br>


<br>
<br>
</div>


