

<h3>Blog</h3>
2016-06-05
Hello Opendesktop.org users,

welcome to Opendesktop.org community page here on facebook.
As some might have noticed, we are in the process of activating some of our social channels again, posting news and updates about whats going on around the OD services.
Right now we are slowly transitioning opendesktop.org stores to new servers and also a new backend. All products users and comments should be reserved. All account logins should be kept. If you experience any issues, please post them here or send us an email, we're counting on your feedback and listening.
Note that if from time to time some categories or products may not showing up temporarily, give us a hint, stay calm and be assured: Everything is being saved and will be preserved and made avilable again.
One of the biggest transitions will be kde-look.org, which will take the most time, since OD resources are tightly integrated into Plasmas GHNS service. Therefore the whole transition could take 10-15 weeks while cleaning and evaluating 15 years of opendesktop.org products and services. Meanwhile some stores and products may still be on the to be superseeded server, while others may already show up on our new servers and frontpage.

One of the first features of our new backend is an unlimited file upload service, so no more need for posting links to 3rd party storages.
Any feedback is welcomed, so let us know what you think in the comments or per email.

Your OpenDesktop Team


<br>
<h3>About openDesktop.org</h3>

<br>
Started in 2007, openDesktop.org today is one of the largest communities where developers, artists and users share applications, tools, wallpapers, themes and other artwork.

<br>
<br>

<h3>Content</h3>
Our focus is on free user generated content for libre software applications and desktop environments. Everyone in our network can upload and download free and libre artwork, applications, documents and other files. Building friendships with other free software users and developers via commenting, voting and donating are at the core of the opendesktop community.

<br>
<br>

<h3>Network</h3>
openDesktop.org is the umbrella site summarizing the content of all the sites in the network. Part of this network are sites such as KDE-Look.org, GNOME-Look.org, XFCE-Look.org and many other similar sites. That´s why content uploaded by you on one of these sites, are also displayed on other sites part of openDesktop.org.

<br>
<br>

<h3>Openess</h3>
Since openDesktop.org is dedicated to the open source community, participating on all the platforms is completely free. There are no fees taken from any donations or membership. Our goal is the advancement of free software and libre content. We therefore also developed the Open Collaborative Services API on ocs-project.org to expand the reach of Open Standards into the mainstream.

<br>
<br>


<h3>Community</h3>
openDesktop.org is made by a team of developers from all over the world with more than 100k registered users and 2.6 million visitors each month.
