	<faq id="faq-content">
            <div class="panel-group" id="accordion_1">
            <br />
            <br />
                <h3>General Questions</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_11">What is Pling?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_11">
                        <div class="panel-body">Pling.com is a site where creators can publish their libre products and get small compentsation (Pling) each time a product is downloaded.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_12"> Who is pling for? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_12">
                        <div class="panel-body">Pling.com is for creators who want to publish their products, get feedback from users and earn money for their efforts. Pling is for users who want to discover new apps, artwork, books, music and videos and like to support the platform via a monthly or yearly subscription.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_13">How does supporting a creator works?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_13">
                        <div class="panel-body">Users can become supporter of the platform via a monthly or yearly donation. A smallest amount starts at 99 $ Cents per month.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_14">Why would people support the platform? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_14">
                        <div class="panel-body">Because their creators gave them something that they value and like to use.</div>
                    </div>
                </div>
            </div>
            
            <hr>
            <div class="panel-group" id="accordion_2">
                <h3>How does Pling work</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_24">I'm a creator. How do I get started? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_24">
                        <div class="panel-body">Simply register at Pling and start publishing your products! Registering on Pling.com makes sure that people who are interested in your work can see it all in one place and start getting compensated for it.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_23">What payment providers does pling support? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_23">
                        <div class="panel-body">Currently, Pling supports Paypal.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_25">How does a product get compensated? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_25">
                        <div class="panel-body">Each download gets you Plings. A Pling is 1/10 USD Cent. How many Plings you get for download shows the following table.
                            <br><br>
                            <section class="body-wrap" id="cat-list">
                                <section class="wrapper">
                                    <div class="row title" style="background-color: #ccc;height: 30px;">
                                        <div class="col-md-6">
                                            <span class="label lable-default left" style="padding-top: 10px;padding-left: 0;">
                                                    Category
                                            </span>
                                        </div>
                                        <div class="col-md-3">    
                                            <span class="label lable-default right" style="padding-top: 10px;padding-left: 0;">
                                                    Plings
                                            </span>
                                        </div>
                                        <div class="col-md-3">
                                            <span class="label lable-default right"  style="padding-top: 10px;padding-left: 0;">
                                                    Source-Link required
                                            </span>

                                        </div>
                                    </div>            
                                    <?php
                                    $categories = $this->listCategories();
                                    foreach ($categories as $key => $element) {                                	                                    
                                        $depth = (int)$element['depth'];
                                        $cls = 'depth'.$depth;
                                        $countSubCat = (int)$element['rgt'] - (int)$element['lft'] - 1;
                                        $plingFactor='';
                                        $sourceRequired='';
                                        if($countSubCat==0){
                                                $plingFactor = '<span class="right factor">'. ($element['dl_pling_factor']*10).'</span>';  
                                                $sourceRequired = ($element['source_required']?'Yes':'No');
                                        }
                                        /*
                                        echo '<div class="row">'; 
                                        echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 '.$cls.'">' . $this->translate($element['title']) 
                                              . $plingFactor.'<span class="right factor">' . $element['source_required'].'</span></div>';                                                                                
                                        echo '</div>';
                                        */
                                        echo '<div class="row" style="padding-left: 15px; padding-right: 15px;">';
                                        echo '    <div class="col-md-6 cell-default '.$cls.'">'. $this->translate($element['title']).'</div>';
                                        echo '    <div class="col-md-3 text-right cell-default">'.$plingFactor.'</div>';
                                        echo '    <div class="col-md-3 text-right cell-default">'.$sourceRequired.'</div>';
                                        echo '</div>   ';

                                    }
                                    ?>

                                </section>
                            </section>
                        
                        
                        
                        </div>
                        
                    </div>
                </div>
            </div>
            <hr>
             
            <div class="panel-group" id="accordion_3">
                <h3>Registering a Pling Account</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_21">Is registration free? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_21">
                        <div class="panel-body">Yes, it is absolutely free to register at pling.com.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_31">How do I register at pling? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_31">
                        <div class="panel-body">Click on 'Join' and provide the necessary information. Or just use the 'Facebook connect' button to log in with your Facebook information.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_32">Why can't I log in even though I'm typing in the right username and password? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_32">
                        <div class="panel-body">You can recover your password by using the 'Forgot your password?' in the 'Login' popup. If you're still having trouble, write us an email to <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a> so we can sort things out for you.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_33">I forgot my pling password. What should I do?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_33">
                        <div class="panel-body">Press on the 'Forgot password' button in the 'Login' popup and we'll send you your password to your registered email adress.</div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="panel-group" id="accordion_5">
                <h3>Additional Information</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_40"> Does pling keep a percentage from each donation? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_40">
                        <div class="panel-body">No, each donation goes fully to the creator of the product. The only fees might be those of the payment provider, e.g. Paypal.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_52"> I have a special request and want to tell you about it. How can I do that? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_52">
                        <div class="panel-body">Write an email to <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a>.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_53"> How can I get in touch with you? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_53">
                        <div class="panel-body">Email us at <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a>.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_54">Who is developing pling? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_54">
                        <div class="panel-body">We are team of dedicated people from all over the world, who value the freedom of open source software and libre content.</div>
                    </div>
                </div>
            </div>
	</faq>