	<faq id="faq-content">
            <div class="panel-group" id="accordion_1">
            <br />
            <br />
                <h3>General Questions</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_11">What is Pling?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_11">
                        <div class="panel-body">Pling (short for PubLishING) a site where creators can publish any products for free, so others can discover and support these products with donations.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_12"> Who is pling for? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_12">
                        <div class="panel-body">Pling.com is for creators who want to publish their products for free, get feedback from users and earn money for their efforts. Pling is for users who want to discover new apps, artwork, books, music and videos and like to support the creators.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_13">How can someone support a creator?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_13">
                        <div class="panel-body">There is a donation button for each product that makes it very easy for users to give creators money for their efforts. This button can also be embedded on your own site, blog, or in your social media profile.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_14">Why would people support me and my product? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_14">
                        <div class="panel-body">Because you gave them something that they value and like to use.</div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="panel-group" id="accordion_2">
                <h3>Setup Questions</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_24">I'm a creator. How do I get started? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_24">
                        <div class="panel-body">Simply register at Pling and start publishing your products! Registering on Pling.com makes sure that people who are interested in your work can see it all in one place and reward you for it.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_23">What payment providers does pling support? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_23">
                        <div class="panel-body">Currently, Pling supports Paypal.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_25">How do I support a project? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_25">
                        <div class="panel-body">Simple click on the "Donate" button, choose the amount you want to give and confirm your donation in the Paypal Popup.</div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="panel-group" id="accordion_3">
                <h3>Registering a Pling Account</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_21">Is registration free? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_21">
                        <div class="panel-body">Yes, it is absolutely free to register at pling.com.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_31">How do I register at pling? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_31">
                        <div class="panel-body">Click on 'Join' and provide the necessary information. Or just use the 'Facebook connect' button to log in with your Facebook information.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_32">Why can't I log in even though I'm typing in the right username and password? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_32">
                        <div class="panel-body">You can recover your password by using the 'Forgot your password?' in the 'Login' popup. If you're still having trouble, write us an email to <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a> so we can sort things out for you.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_33">I forgot my pling password. What should I do?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_33">
                        <div class="panel-body">Press on the 'Forgot password' button in the 'Login' popup and we'll send you your password to your registered email adress.</div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="panel-group" id="accordion_5">
                <h3>Additional Information</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_40"> Does pling keep a percentage from each donation? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_40">
                        <div class="panel-body">No, each donation goes fully to the creator of the product. The only fees might be those of the payment provider, e.g. Paypal.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_52"> I have a special request and want to tell you about it. How can I do that? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_52">
                        <div class="panel-body">Write an email to <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a>.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_53"> How can I get in touch with you? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_53">
                        <div class="panel-body">Email us at <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a>.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_54">Who is developing pling? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_54">
                        <div class="panel-body">We are team of dedicated people from all over the world, who value the freedom of open source software and libre content.</div>
                    </div>
                </div>
            </div>
	</faq>