<style>
    #cat-list .wrapper .depth1 {
        padding-left: 30px;
    }
    
    #cat-list .wrapper .depth2 {
        padding-left: 50px;
    }
    
    #cat-list .wrapper .depth3 {
        padding-left: 70px;
    }
    
    #cat-list .wrapper .depth4 {
        padding-left: 90px;
    }
    
    #cat-list .wrapper .depth5 {
        padding-left: 110px;
    }
    
    #cat-list .wrapper .row:not(:first-child):hover {
        background-color: #eef;
    }
    
</style>


        <faq id="faq-content">
            <div class="panel-group" id="accordion_1">
            <br />
            
                <h3>Pling FAQ</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_11">What is Pling?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_11">
                        <div class="panel-body">Pling.com is part of Opendesktop.org. It is the Store section, where creators can publish their libre products and content and get a small compensation each time a product is downloaded or media is viewed, limited on the amount of donations available for each section.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_12"> Who is Pling for? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_12">
                        <div class="panel-body">Pling.com is for creators who want to publish their products and get compensated for their creations. On the user side Pling is for people who want to discover new apps, artwork, books, music and videos and like to support the platform via a monthly or yearly subscription for various sections.</div>
                    </div>
                </div>
                <hr>
                <h3>For Users</h3>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_31">How do I register? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_31">
                        <div class="panel-body">Click on 'Join' and validate your email adress. If you already have an account on opendesktop.org, you can use it also for pling.com or any other side part of the opendesktop.org network.</div>
                    </div>
                </div>
                

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_21">Is registration free? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_21">
                        <div class="panel-body">Yes, registration it is absolutely free and there are no platform fees or hidden costs to join or use this platform.</div>
                    </div>
                </div>

                <hr>
                <h3>For Supporters</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_13">How does supporting work?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_13">
                        <div class="panel-body">A user can become a supporter of the platform via a monthly or yearly donation of one or more sections. The smallest amount starts at 99 Cents a month.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_14">Is there a fee? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_14">
                        <div class="panel-body">There is no additional fee for the platform. There is only the paypal fee and taxes.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_1" data-toggle="collapse" href="#collapse_15">Why would you support a section? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_15">
                        <div class="panel-body">Because you find things in this section that you value and love to use.</div>
                    </div>
                </div>
            </div>
            
            <hr>
            <div class="panel-group" id="accordion_2">
                <h3>For Creators</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_24">How do I get started? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_24">
                        <div class="panel-body">It's simple: Register an account and start publishing your products!</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_23">What payment providers does pling support? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_23">
                        <div class="panel-body">Currently, Pling supports Paypal.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_2" data-toggle="collapse" href="#collapse_25">How does compensation work? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_25"> 
                        <div class="panel-body">
                            <p>Contributors to any part of the Pling platform get a compensation each time their contribution/product is downloaded or media is viewed, based on certain criteria. Valid download-clicks or mediaviews are converted into monetary value based on the following terms:
                            </p>
                            <p>Payout = valid Downloads/Mediaviews * Pling-Factor * 1 $-cent,</p>
                            <p>where each product category is valued by a so-called “Pling-Factor”.</p>
                            <p>You can see the value of each category in the list below.</p>
                            <p>Valid Downloads and Mediaviews are determined by various factors, e.g. double clicks on the same product are neglected. The maximum payout for each section is limited by the funds avialable each month. Based on the actual amount of content and downloads, we may adjust these values at any time. For the full terms, please see our <a href="/terms/payout">Payout Terms & Conditions</a>.
                            
                            <br><br>
                            <section class="body-wrap" id="cat-list">
                                <section class="wrapper">
                                    <div class="row title" style="background-color: #ccc;height: 30px;">
                                        <div class="col-md-6">
                                            <span class="label lable-default left" style="padding-top: 10px;padding-left: 0;">
                                                    Category
                                            </span>
                                        </div>
                                        <div class="col-md-3">    
                                            <span class="label lable-default right" style="padding-top: 10px;padding-left: 0;">
                                                    Pling Factor
                                            </span>
                                        </div>
                                        <div class="col-md-3">
                                            <span class="label lable-default right"  style="padding-top: 10px;padding-left: 0;">
                                                    Source-Link required
                                            </span>

                                        </div>
                                    </div>            
                                    <?php
                                    $categories = $this->listCategories();
                                    foreach ($categories as $key => $element) {                                	                                    
                                        $depth = (int)$element['depth'];
                                        $cls = 'depth'.$depth;
                                        $countSubCat = (int)$element['rgt'] - (int)$element['lft'] - 1;
                                        $plingFactor='';
                                        $sourceRequired='';
                                        if($countSubCat==0){
                                                $plingFactor = '<span class="right factor">'. ($element['dl_pling_factor']).'</span>';  
                                                $sourceRequired = ($element['source_required']?'Yes':'No');
                                        }
                                        /*
                                        echo '<div class="row">'; 
                                        echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 '.$cls.'">' . $this->translate($element['title']) 
                                              . $plingFactor.'<span class="right factor">' . $element['source_required'].'</span></div>';                                                                                
                                        echo '</div>';
                                        */
                                        echo '<div class="row" style="padding-left: 15px; padding-right: 15px;">';
                                        echo '    <div class="col-md-6 cell-default '.$cls.'">'. $this->translate($element['title']).'</div>';
                                        echo '    <div class="col-md-3 text-right cell-default">'.$plingFactor.'</div>';
                                        echo '    <div class="col-md-3 text-right cell-default">'.$sourceRequired.'</div>';
                                        echo '</div>   ';

                                    }
                                    ?>

                                </section>
                            </section>
                        
                        
                        
                        </div>
                        
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_52"> I have a special request and want to tell you about it. How can I do that? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_52">
                        <div class="panel-body">Write an email to <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a>.</div>
                    </div>
                </div>
            </div>
            <hr>
             
            <div class="panel-group" id="accordion_5">
                <h3>Additional Information</h3>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_32">Why can't I log in even though I'm typing in the right username and password? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_32">
                        <div class="panel-body">
                            Please make sure you only use lowercase characters. If none of that works, you can recover your password by using the 'Forgot your password?' in the 'Login' popup. If you're still having trouble, write us an email to <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a> so we can sort things out for you.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_3" data-toggle="collapse" href="#collapse_33">I forgot my password. What should I do?</a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_33">
                        <div class="panel-body">Press on the 'Forgot password' button in the 'Login' popup and we'll send you your password to your registered email adress.</div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_53"> How can I get in touch with you? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_53">
                        <div class="panel-body">Email us at <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a>.</div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-parent="#accordion_5" data-toggle="collapse" href="#collapse_54">Who is developing Pling? </a></h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapse_54">
                        <div class="panel-body">We are team of dedicated people from all over the world, who value the freedom of open source software and libre content.</div>
                    </div>
                </div>
            </div>
	</faq>