<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/


?>


   <div style="padding-top: 20px">
      <h3>Opencode FAQ</h3>
        <p>Opencode uses 100% libre solutions, like e.g. Gitlab.</p>

        <br/>
        <p>For usable GIT clients, look here:
        	<p> <a href="https://forum.opendesktop.org/t/git-client-list/7104">https://forum.opendesktop.org/t/git-client-list/7104</a></p>
    </div>

