<br>
<br>
<h3>Imprint</h3>
<br>
<p class="">Hive01 GmbH</p>

<p class="">Am Speksel 10</p>

<p class="">33649 Bielefeld</p>

<p class="">Germany</p>

<p class="">Fon +49 0521 417 699-0</p>

<p class="">Email contact@opendesktop.org</p>

<p class="">Geschäftsführer: Marc Jünger</p>

<p class="">Amtsgericht Bielefeld HRB 42225</p>

<p class="">Umsatzsteuer-Identifikationsnummer DE261388879</p>

<br><br>
<h3>Questions</h3>
<br>
<p>If you have questions or suggestions, please contact us: <a href="mailto:contact@opendesktop.org">contact@opendesktop.org</a></p>
<br>