
<div class="container" style="min-height: 500px">
<h3>OCS-API</h3>

<a href="https://en.wikipedia.org/wiki/Open_Collaboration_Services" target="_blank">https://en.wikipedia.org/wiki/Open_Collaboration_Services</a>
<br/>
<a href="https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/" target="_blank">https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/</a>

</div>


