

<div class="container" style="min-height: 500px;padding-top: 20px">
<h3>OCS-API</h3>
<br/>
<a href="https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/" target="_blank">https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/</a>
<br/>

<a href="https://en.wikipedia.org/wiki/Open_Collaboration_Services" target="_blank">https://en.wikipedia.org/wiki/Open_Collaboration_Services</a>

<br/>
<br/>

<h3>OCS-API in use</h3>

<br/>ocs-url: <a href="https://www.opendesktop.org/p/1136805/"  target="_blank"> https://www.opendesktop.org/p/1136805/ </a> 


<br/>KDE Attica Library: <a href="https://techbase.kde.org/Development/Tutorials/Collaboration/Attica/Introduction"  target="_blank"> https://techbase.kde.org/Development/Tutorials/Collaboration/Attica/Introduction </a> 

<br/>KDE KNewStuff Frontend: <a href="https://techbase.kde.org/Development/Tutorials/Collaboration/HotNewStuff" target="_blank">https://techbase.kde.org/Development/Tutorials/Collaboration/HotNewStuff</a>

<br/>NX Software Center: <a href="https://github.com/Nitrux/nx-software-center" target="_blank">https://github.com/Nitrux/nx-software-center</a>
</div>


