
<style>
    #cat-list {
        padding-top: 30px;
        padding-bottom: 30px;
    }
    
    #cat-list .wrapper .depth1 {
        padding-left: 30px;
    }
    
    #cat-list .wrapper .depth2 {
        padding-left: 50px;
    }
    
    #cat-list .wrapper .depth3 {
        padding-left: 70px;
    }
    
    #cat-list .wrapper .depth4 {
        padding-left: 90px;
    }
    
    #cat-list .wrapper .depth5 {
        padding-left: 110px;
    }
    
    #cat-list .wrapper .row:not(:first-child):hover {
        background-color: #eef;
    }
    
</style>
<br>
<br>
<h1>Payout Terms & Conditions</h1>
<br>
<br>

        <div class="term">
            <div class="term-description">

                <p>This service will become active on May, 1st 2017. All previous months are shown for internal testing only. </p>
                        <p>This service is considered Beta until otherwise announced.</p>
                        <br>
                        <p>TOS:</p>
                        <p>This payout service is completely voluntarily. It is within Hive01's full rights to decide at any time:</p>
                        <p>a) when and</p>
                        <p>b) how much of the shown calculated amount is to be paid or</p>
                        <p>c) to cancel partly or complete payment without giving any reasons (reasons are most likely cheating or inflating download numbers).</p>
                        <p>d) Any PLING-FACTOR can be changed at any time and any rate (even to "0") to adjust the payout amount for products, even for a previous still to-be-paid-out pending month as long as it has not been paid out yet.</p>
                        <p> All products require a valid license. Certain products also require a link to an online source repository, like e.g. cgit.kde.org or github. If we find those requirements are set in a misleading way, we reserve the right to exclude the product or user temporarily or completely from receiving plings at any time.
                        </p>
                        <p><br>A valid PayPal address must be maintained in your settings at the time of the payout. The total payout amount for a completed month must be at least one dollar. Lesser amounts will not be paid out and can not be transferred to the next month. If you do not meet these requirements, we can not pay you out anything that month. Non-paid-out months will not be retroactively paid out in the future. We will check these requirements every month. Downloads are counted of all files during that month, be it active or inactive. If all requirements were met and we have no reasons to decide otherwise you will likely be receiving the payout amount to your PayPal account within the following month.</p>
                <br/>
                
                <p>Contributors to any part of the Pling platform get a compensation each time their contribution/product is downloaded or a media is viewed. Download-clicks and Mediaviews are converted into monetary value based on the following terms:</p>
                <p></p>
                <p>Payout = Number of valid Downloads/Mediaviews * Pling-Factor * 1 $-cent,</p>
                <p></p>
                <p>where each product category is valued by a so-called “Pling-Factor”.</p>
                <p></p>
                <p>You can see the value of each category in the list below.</p>
                <p></p>
                <p>Valid Downloads and Mediaviews are determined by various factors, e.g. double clicks on the same product are neglected. The maximum payout for each section is limited by the funds avialable each month. Based on the actual amount of content and downloads, we may adjust these values at any time, even during a month.</p>
                <p></p>
                <p>Payouts are voluntary and we reserve the right to cancel any single product or payout or all payouts without any reason.</p>
                <p></p>                
                <p>Any product to be paid out requires a libre license. Certain products also require a link to the online source repository (see list below), like e.g. cgit.kde.org or github. This is different from just providing the source-code, but to provide an easy setup for collaboration and transparent changes.</p>
                <p></p>
                <p>In order to receive any payouts, you need to provide a valid PayPal option under your OpenDesktop account settings.</p>
                <p>Note that the amount arriving at your account is the actual payout minus any fees from paypal for the transaction or conversion of USD into your currency.</p>
                <p></p>
                <p>We hope this form of compensation values those who put time and effort into creating free and open source software & content and leads to an ever increase of quality and sustainability.        </p>

            </div>
        </div>
        <section class="body-wrap" id="cat-list">
            <section class="wrapper">
                <div class="row title" style="background-color: #ccc;height: 30px;">
                    <div class="col-md-6">
                        <span class="label lable-default left" style="padding-top: 10px;padding-left: 0;">
                                Category
                        </span>
                    </div>
                    <div class="col-md-3">    
                        <span class="label lable-default right" style="padding-top: 10px;padding-left: 0;">
                                Pling Factor
                        </span>
                    </div>
                    <div class="col-md-3">
                        <span class="label lable-default right"  style="padding-top: 10px;padding-left: 0;">
                                Source-Link required
                        </span>

                    </div>
                </div>
                <?php
                $categories = $this->listCategories();
                foreach ($categories as $key => $element) {
                    $depth = (int)$element['depth'];
                    $cls = 'depth'.$depth;
                    $countSubCat = (int)$element['rgt'] - (int)$element['lft'] - 1;
                    $plingFactor='';
                    $sourceRequired='';
                    if($countSubCat==0){
                            $plingFactor = '<span class="right factor">'. $element['dl_pling_factor'].'</span>';
                            $sourceRequired = ($element['source_required']?'Yes':'No');
                    }
                    /*
                    echo '<div class="row">';
                    echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 '.$cls.'">' . $this->translate($element['title'])
                          . $plingFactor.'<span class="right factor">' . $element['source_required'].'</span></div>';
                    echo '</div>';
                    */
                    echo '<div class="row" style="padding-left: 15px; padding-right: 15px;">';
                    echo '    <div class="col-md-6 cell-default '.$cls.'">'. $this->translate($element['title']).'</div>';
                    echo '    <div class="col-md-3 text-right cell-default">'.$plingFactor.'</div>';
                    echo '    <div class="col-md-3 text-right cell-default">'.$sourceRequired.'</div>';
                    echo '</div>   ';

                }
                ?>

            </section>
        </section>
        