
<style>
    #cat-list .wrapper .depth1 {
        padding-left: 30px;
    }
    
    #cat-list .wrapper .depth2 {
        padding-left: 50px;
    }
    
    #cat-list .wrapper .depth3 {
        padding-left: 70px;
    }
    
    #cat-list .wrapper .depth4 {
        padding-left: 90px;
    }
    
    #cat-list .wrapper .depth5 {
        padding-left: 110px;
    }
    
    #cat-list .wrapper .row:not(:first-child):hover {
        background-color: #eef;
    }
    
</style>
<br>
<br>
<h1>Payout Terms & Conditions</h1>
<br>
<br>

        <div class="term">
            <div class="term-description">
                <p>Contributors to any part of the Opendesktop platform get a compensation each time their contribution/product is downloaded. Download-clicks are converted into monetary value based on the following terms:</p>
                <p></p>
                <p>Payout = Number of Downloads * Pling-Factor * 1 $-cent,</p>
                <p></p>
                <p>where each product category is valued by a so-called “Pling-Factor”.</p>
                <p></p>
                <p>You can see the value of each category in the list below.</p>
                <p></p>
                <p>Based on the actual amount of content and downloads, we may adjust these values at any time, even during a month.</p>
                <p></p>
                <p>Payouts are voluntary and we reserve the right to cancel any single product or payout or all payouts without any reason.</p>
                <p></p>
                <!--<p>We are currently evaluating using Bitcoin as a payout method in the future.-->
                <p>Any product to be paid out requires a libre license. Certain products also require a link to the online source repository (see list below), like e.g. cgit.kde.org or github. This is different from just providing the source-code, but to provide an easy setup for collaboration and transparent changes.</p>
                <p></p>
                <p>In order to receive any payouts, you need to provide a valid PayPal option under your OpenDesktop account settings.</p>
                <p></p>
                <p>We hope this form of compensation values those who put time and effort into creating free and open source software & content and leads to an ever increase of quality and sustainability.        </p>

            </div>
        </div>
        <section class="body-wrap" id="cat-list">
            <section class="wrapper">
                <div class="row title" style="background-color: #ccc;height: 30px;">
                    <div class="col-md-6">
                        <span class="label lable-default left" style="padding-top: 10px;padding-left: 0;">
                                Category
                        </span>
                    </div>
                    <div class="col-md-3">    
                        <span class="label lable-default right" style="padding-top: 10px;padding-left: 0;">
                                Pling Factor
                        </span>
                    </div>
                    <div class="col-md-3">
                        <span class="label lable-default right"  style="padding-top: 10px;padding-left: 0;">
                                Source-Link required
                        </span>

                    </div>
                </div>
                <?php
                $categories = $this->listCategories();
                foreach ($categories as $key => $element) {
                    $depth = (int)$element['depth'];
                    $cls = 'depth'.$depth;
                    $countSubCat = (int)$element['rgt'] - (int)$element['lft'] - 1;
                    $plingFactor='';
                    $sourceRequired='';
                    if($countSubCat==0){
                            $plingFactor = '<span class="right factor">'. $element['dl_pling_factor'].'</span>';
                            $sourceRequired = ($element['source_required']?'Yes':'No');
                    }
                    /*
                    echo '<div class="row">';
                    echo '<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 '.$cls.'">' . $this->translate($element['title'])
                          . $plingFactor.'<span class="right factor">' . $element['source_required'].'</span></div>';
                    echo '</div>';
                    */
                    echo '<div class="row" style="padding-left: 15px; padding-right: 15px;">';
                    echo '    <div class="col-md-6 cell-default '.$cls.'">'. $this->translate($element['title']).'</div>';
                    echo '    <div class="col-md-3 text-right cell-default">'.$plingFactor.'</div>';
                    echo '    <div class="col-md-3 text-right cell-default">'.$sourceRequired.'</div>';
                    echo '</div>   ';

                }
                ?>

            </section>
        </section>
        