<br>
<br>
<h1>General Terms</h1>
<br>
<p class="">Version: January 1st, 2016</p>
        <br>

        <div class="term"><br>
            <h3 class="lightblue">1. Scope of Validity, Definition of Terms</h3>
            <br>
            <div class="term-description"><ol>
                    <li>These General Terms and Conditions apply to the use of the OpenDesktop.org website and all of its affiliate websites (hereinafter called "OpenDesktop.org"). OpenDesktop.org is managed by Hive01 GmbH, Am Speksel 10, 33649 Bielefeld (hereinafter called "Hive").</li>
                    <li>By registering on OpenDesktop.org the User (hereinafter called "User") enters into a licensing agreement with Hive and declares that he/she accepts the terms set out below. The Agreement is concluded for an indefinite period of time.</li>
                    <li>Users who have not yet reached the age of 18 may only use the facilities provided by OpenDesktop.org under the supervision and with the consent of a parent or guardian.</li>
                    <li>Using the service, website or any part of OpenDesktop.org is only possible in conjunction with these Terms and Conditions. Users accordingly accept that these Terms and Conditions form the basis for the use of OpenDesktop.org.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">2. Facilities provided</h3>
            <br>
            <div class="term-description"><ol>
                    <li>Creative individuals can use OpenDesktop.org to display products. Such contributors (hereinafter called "Makers") of such products (hereinafter called "Products") can present their work via OpenDesktop.org.</li>
                    <li>Products shall be deemed to include digital work, such as videos, music, software, applications or graphics, etc.</li>
                    <li>Anyone on OpenDesktop.org (hereinafter called "Users") can view, listen to, use or download the products etc., while the Makers can stipulate what scope will be accorded to the Users.</li>
                    <li>Placing Products on OpenDesktop.org is only possible for registered Users.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">3. Registration, General Obligations</h3>
            <br>
            <div class="term-description"><ol>
                    <li>Registration on OpenDesktop.org website is free of charge.</li>
                    <li>These Terms of Use apply for all Users who have registered with OpenDesktop.org. Registration will be deemed valid if a User has conducted the registration process properly and has provided accurate particulars in full before clicking on "Register".</li>
                    <li>No General Terms and Conditions on the part of the User or any other Conditions that deviate from or contradict these Terms shall be applicable.</li>
                    <li>Users may not provide any registration data (member’s name, profile image) that is vulgar or offensive to others, nor are they permitted to impersonate other individuals or create a false identity (through the use of a celebrity or company name).</li>
                    <li>When registering on OpenDesktop.org, Users are obliged to complete all the fields on the registration form truthfully and correctly. Registration is only possible when all the compulsory fields have been filled in.</li>
                    <li>Users may not take any action that might place an unreasonable or excessive burden on OpenDesktop.org or the facilities provided by OpenDesktop.org.</li>
                    <li>Users may only register on OpenDesktop.org with one user account at a time. If a User loses his/her registration data, he/she undertakes to contact OpenDesktop.org without delay.</li>
                    <li>Users should add OpenDesktop.org’s email addresses to the Safe Senders List, for instance, to ensure that emails with the domain ending "@opendesktop.org" are not mistakenly marked as spam.</li>
                    <li>The purpose of entering the email address on the registration form is to allow OpenDesktop.org to identify the Users and get in touch with them. OpenDesktop.org is entitled to send Users messages pertaining to technical matters, the operation and the functions of the facilities provided. To this end, Users must ensure that their email address is always kept up-to-date. If OpenDesktop.org is unable to contact a User at the email address in OpenDesktop.org’s database and the fault lies with the User (out-of-date address, failure to check his/her inbox, etc.), any disadvantages resulting thereof will be interpreted to the detriment of the User, i.e. the email will be deemed delivered.</li>
                    <li>When registering, Users have to choose a password with which to log on to OpenDesktop.org using their member name. Users undertake to change their password at regular intervals and to employ passwords of an appropriate length (8 alphanumeric characters consisting of both letters and numbers). The password may not be passed on to third parties.</li>
                    <li>It is not permitted to sell or transfer the members account to any third parties. The same applies to other persons using a member’s account.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">4. Makers’ Obligations, Indemnification</h3>
            <br>
            <div class="term-description"><br><br><ol>
                    <li>Makers are themselves responsible for the contents they offer. This applies to all legal matters relating to the Product. In this connection we draw particular attention to intellectual property and trademark rights (this list is not exhaustive).</li>
                    <li>In so far as OpenDesktop.org provides assistance with the promotion of Products, this is done under exclusion of any liability.</li>
                    <li>Makers who insert their own contributions on OpenDesktop.org (uploads, embedding, framing, etc.), declare that neither the contents nor the Products breach any existing laws or violate common standards of decency. In particular, the Makers give their assurance that they are entitled to use and disseminate the contents of the Products, that the Products are not offensive and are suitable to be viewed by individuals of all age groups. The Makers are entirely responsible for checking the relevant legal regulations (copyright and proprietary rights, trademark rights, etc.).</li>
                    <li>Makers shall indemnify OpenDesktop.org against any claims lodged by other Makers, Users or third parties on the alleged grounds that Products or contents posted on OpenDesktop.org infringe certain rights. Indemnity also covers the necessary financial outlay involved in OpenDesktop.org’s legal defence including all court costs and lawyers’ fees at the statutory rate.</li>
                    <li>In addition, the Makers are obliged to support OpenDesktop.org in the event of any action brought by third parties, other Makers or Users by providing all the information etc. required for investigating the claims and setting up the defence &ndash; in full, truthfully and promptly.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">5. Users’ Obligations</h3>
            <br>
            <div class="term-description"><ol>
                    <li>Users acknowledge that the Products are not connected to OpenDesktop.org in any way and the latter is accordingly unable to accept any liability for the Products. The Makers themselves are responsible for the respective Products.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">6. Costs</h3>
            <br>
            <div class="term-description"><ol>
                    <li>Registration on OpenDesktop.org is free.</li>
                </ol></div>
        </div>
        <div class="term"><br>
            <h3 class="lightblue">7. Suspension of Members’ Accounts, Termination of Membership</h3>
            <br>
            <div class="term-description"><ol>
                    <li>Hive exercises domiciliary rights over OpenDesktop.org. In the event of any breach of these Terms and Conditions, laws and/or any other regulations, OpenDesktop.org is entitled to exclude Users temporarily or permanently from using the OpenDesktop.org Network and the services provided without prior notice and to issue a house ban.</li>
                    <li>To this end, Users will allow OpenDesktop.org to block their user accounts or the contents thereof and to delete Products or suspend functions at any time.</li>
                    <li>OpenDesktop.org also retains the right to discontinue providing the services or parts thereof. Users will be notified in an appropriate manner (usually per email) in good time (usually with 2 weeks’ notice) before services are discontinued or functions are changed that might cause Users’ data to become lost, to give Users the opportunity to protect their own data.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">8. Liability according to the German Telemedia Act, Disclaimer</h3>
            <br>
            <div class="term-description"><ol>
                    <li>Users should take note that OpenDesktop.org cannot accept responsibility for any contents that it has not posted on OpenDesktop.org or of which it is not aware.</li>
                    <li>Except in cases involving the infliction of life-threatening injuries, bodily harm or endangering a person’s health and the breach of major contractual obligations (cardinal obligations), OpenDesktop.org can only accept liability for damage that is intentional or due to gross negligence. This also applies to indirect consequential damage including but not limited to loss of profit.</li>
                    <li>The limitation of liability of these Terms and Conditions applies similarly to the staff and subcontractors of OpenDesktop.org.</li>
                    <li>Liability claims based on mandatory national legislation shall remain unaffected.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">9. Rights of Use</h3>
            <br>
            <div class="term-description"><ol>
                    <li>By posting contents on OpenDesktop.org, Makers grant OpenDesktop.org a simple, temporally and spatially unlimited and royalty-free right to use the contributions within the context of OpenDesktop.org. This right of use includes in particular the right to make contents publicly accessible worldwide via OpenDesktop.org or, under certain circumstances, other media, to duplicate and distribute them or to transfer them to third parties (such as Facebook, press images, blogs).</li>
                    <li>Granting these rights does not enable OpenDesktop.org to appropriate the Makers‘ contents in the context of any liability standards but serves merely to simplify the administrative work and the implementation of the contents when operating OpenDesktop.org or promoting the Products.</li>
                </ol></div>
        </div>
        <!-- /.term -->
       
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">11. Data Protection</h3>
            <br>
            <div class="term-description"><ol>
                    <li>OpenDesktop.org processes the personal particulars of its Users for specific purposes in accordance with the statutory provisions. The personal data (name, email address, address, account data etc.) required for registration for membership are used by OpenDesktop.org to conclude and comply with the Utilisation Agreement. These data are treated as confidential and will not be forwarded to any third parties who are not involved in the contractual or payment process. Users have the right to ask for details of the personal particulars OpenDesktop.org has saved in their case. This information will be provided free of charge. Users are also entitled to have any incorrect particulars rectified or all their personal data blocked or deleted, on request, unless this contravenes any statutory obligation to safeguard business records.</li>
                    <li>OpenDesktop.org outsources its accounting to external services. Proper care will be taken to safeguard all confidential matters pertaining to the Users in accordance with the statutory regulations. The data will not be passed on to any other third parties. </li>
                    <li>Please refer to the data security information <a href="../../../../content/privacy">www.OpenDesktop.org/privacy</a>, which forms part of these General Terms and Conditions, for further details regarding the handling of data and means of contact.</li>
                </ol></div>
        </div>
        <!-- /.term -->
        <p>&nbsp;</p>
        <div class="term"><br>
            <h3 class="lightblue">12. Amendments to the General Terms and Conditions</h3>
            <br>
            <div class="term-description"><ol>
                    <li>OpenDesktop.org is entitled to change these General Terms and Conditions and the data security guidelines. Amendments will only be made when there are sufficient, valid grounds and provided they do not distort the contractual balance between the Users and OpenDesktop.org. Such reasons might include legal or technical changes, experience with user behaviour or unintentional gaps in the provisions. Users will be advised of any changes per email and/or when they next visit OpenDesktop.org.</li>
                    <li>Users are entitled to challenge the changes. In the event of any opposition, OpenDesktop.org reserves the right to terminate its contractual relationship with the member concerned with immediate effect.</li>
                    <li>The changes shall be deemed to be acknowledged and binding if Users have not opposed them within the course of 14 days.</li>
                </ol></div>
        </div>
        <!-- /.term -->