<br>
<br>
<h1>COOKIE POLICY </h1>
<p class="">Version: July 1st, 2019</p>
<br>
<br>

<div class="term"><br>
<div class="term-description">
<h3>INTRODUCTION</h3>
We may use cookies, web beacons,
tracking pixels, and other tracking technologies when you visit our website pling.com, 
including any other media form, media channel, mobile website, or
mobile application related or connected thereto (collectively, the “Site”) to help
customize the Site and improve your experience.
We reserve the right to make changes to this Cookie Policy at any time and for any
reason. We will alert you about any changes by updating the “Last Updated” date of
this Cookie Policy. Any changes or modifications will be effective immediately upon
posting the updated Cookie Policy on the Site, and you waive the right to receive
specific notice of each such change or modification.
You are encouraged to periodically review this Cookie Policy to stay informed of
updates. You will be deemed to have been made aware of, will be subject to, and will
be deemed to have accepted the changes in any revised Cookie Policy by your
continued use of the Site after the date such revised Cookie Policy is posted.

<h3>USE OF COOKIES</h3>
A “cookie” is a string of information which assigns you a unique identifier that we
store on your computer. Your browser then provides that unique identifier to use
each time you submit a query to the Site. We use cookies on the Site to, among
other things, keep track of services you have used, record registration information,
record your user preferences, keep you logged into the Site, facilitate purchase
procedures, and track the pages you visit. Cookies help us understand how the Site
is being used and improve your user experience.
<h3>TYPES OF COOKIES</h3>
The following types of cookies may be used when you visit the Site:
<h4>Advertising Cookies</h4>
Advertising cookies are placed on your computer by advertisers and ad servers in
order to display advertisements that are most likely to be of interest to you. These
cookies allow advertisers and ad servers to gather information about your visits to
the Site and other websites, alternate the ads sent to a specific computer, and track
how often an ad has been viewed and by whom. These cookies are linked to a
computer and do not gather any personal information about you.
<h4>Analytics Cookies</h4>
Analytics cookies monitor how users reached the Site, and how they interact with
and move around once on the Site. These cookies let us know what features on the
Site are working the best and what features on the Site can be improved.
<h4>Our Cookies</h4>
Our cookies are “first-party cookies”, and can be either permanent or temporary.
These are necessary cookies, without which the Site won't work properly or be able
to provide certain features and functionalities. Some of these may be manually
disabled in your browser, but may affect the functionality of the Site.
<h4>Personalization Cookies</h4>
Personalization cookies are used to recognize repeat visitors to the Site. We use
these cookies to record your browsing history, the pages you have visited, and your
settings and preferences each time you visit the Site.
<h4>Security Cookies</h4> 
Security cookies help identify and prevent security risks. We use these cookies to
authenticate users and protect user data from unauthorized parties.
<h4>Site Management Cookies</h4>
Site management cookies are used to maintain your identity or session on the Site
so that you are not logged off unexpectedly, and any information you enter is
retained from page to page. These cookies cannot be turned off individually, but you
can disable all cookies in your browser.
<h4>Third-Party Cookies</h4>
Third-party cookies may be place on your computer when you visit the Site by
companies that run certain services we offer. These cookies allow the third parties to
gather and track certain information about you. These cookies can be manually
disabled in your browser.

<h3>CONTROL OF COOKIES</h3>
Most browsers are set to accept cookies by default. However, you can remove or
reject cookies in your browser’s settings. Please be aware that such action could
affect the availability and functionality of the Site.
For more information on how to control cookies, check your browser or device’s
settings for how you can control or reject cookies.

In addition, you may opt-out of some third-party cookies through the Network
Advertising Initiative’s Opt-Out Tool.



</div>