<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<a id="anker_<?php echo $this->project_id; ?>"></a>
<div class="post">
    <h3 class="post-title light lightblue">Update: <?php echo $this->title; ?></h3>

    <div class="post-date lightgrey small">posted on <?php echo $this->created_at ?></div>
    <div class="post-body">
        <?php echo $this->description; ?>
    </div>
</div><!-- END .post -->

