<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperBuildProductUrl = new Default_View_Helper_BuildProductUrl();
$helperImage = new Default_View_Helper_Image();
?>
<div class="product">
    <div class="product-wrap">
        <a href="<?= $helperBuildProductUrl->buildProductUrl($this->project_id); ?>">
            <img src="<?php echo $helperImage->Image($this->image_small, array('width' => 160, 'height' => 90)); ?>"
                 title="<?php echo $this->title; ?>" class="thumbsAlignleft" alt="product image">

            <h3><?php echo $this->title; ?></h3>
        </a>
    </div>
</div>