<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$helperImage = new Default_View_Helper_Image();
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
?><div class="supporter-image alignleft">
    <div class="image-overlay-64">
        <a href="<?php echo $helpMemberUrl->buildExternalUrl($this->member_id); ?>"><img src="/images/system/user-profile-image-overlay-white-64-bg.png"></a>
    </div>
    <a href="<?php echo $helpMemberUrl->buildExternalUrl($this->member_id); ?>">
        <img src="<?php echo $helperImage->Image($this->profile_image_url,array('width' => 64, 'height' => 64, 'crop' => 2)); ?>"
              alt="supporter image"
              title="<?php echo $this->username; ?>"
              width="64">
    </a>
</div><!-- END .supporter-image -->