<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$plingData = $this->userPlings($this->hits->project_id);
$plingMoney = $this->plingMoney($this->hits->project_id);
/*$latestPling = $this->humanTiming($this->hits->created_at);*/
?>

<div class="explore-product col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <figure class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <a href="<?= $this->hits->showUrl ?>">
            <img src="<?php echo $this->Image($this->hits->image_small, array('width' => 280, 'height' => 167)); ?>"
                 class="explore-product-image" width="101" height="81"/>
        </a>
    </figure>
    <div class="explore-product-details col-lg-7 col-md-7 col-sm-7 col-xs-7">
        <h3><a href="<?= $this->buildProductUrl($this->project_id); ?>"><?= $this->hits->title ?></a></h3>
        <span>By <b><?= $this->hits->username ?></b></span>
        <span>In <b><?php echo $this->hits->category; ?></b></span>
    </div>
    <div class="explore-product-plings col-lg-3 col-md-3 col-sm-3 col-xs-3">
        <div class="progress">
            <div class="bar no-goal"></div>
        </div>
        <div class="collected">
            <span class="count"><?= $this->toCurrency($this->count_amount) ?></span>
            <span><? /*=$latestPling['age']?> <?=$latestPling['unit']*/ ?> ago</span>
        </div>
    </div>
</div><!-- END .explore-product -->