<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$cssNoVotes = (($this->product->count_likes+$this->product->count_dislikes) == 0) ? ';opacity:0.5;' : '';

$model = new Default_Model_DbTable_ProjectRating();
$score2 = $model->getScore($this->product->project_id);   
$score2 = round($score2/100,2);

$blue2 = $red2 = $green2 = $default2=200;
if($score2>=5) {
    $red2=dechex($default2-(($score2*10-50)*4));
    $green2=dechex($default2);
    $blue2=dechex($default2-(($score2*10-50)*4));
}elseif($score2<5) {
    $red2=dechex($default2);
    $green2=dechex($default2-((50-$score2*10)*4));
    $blue2=dechex($default2-((50-$score2*10)*4));
}
if(strlen($green2)==1) $green2='0'.$green2;
if(strlen($red2)==1) $red2='0'.$red2;

$userScore=0;
if($this->ratingOfUser)
{
    $userScore = $this->ratingOfUser['score'];
}

$options = array(1 => 'ugh', 2=>'really bad',3=>'bad',4=>'soso',5=>'average', 6=>'okay',7=>'good', 8=>'great', 9=>'excellent',10=>'the best');
?>
<div id="widget-rating" class="prod-widget-box right" style="border:0px !important">    
    <table cellpadding="0" cellspacing="0" width="100%">
        <tbody>
        <tr>
            
            <td style="padding-left:0.2em;padding-right: 0.2em; width: 80%">
                <div class="rating">
                    <div class="rating-text">
                        <small class="center-block text-center">
                        <span >Score: <?=number_format($score2,2)?></span>                      
                        </small>
                    </div>
                    <div class="progress" style="margin-bottom: 0;height:12px;background-color: transparent; box-shadow: none; padding:2px;">
                        <div class="progress-bar" style="background-color: #<?=$red2.$green2.$blue2?>;width: <?= floor($score2)*10 ?>%;">
                            
                        </div>
                        <div class="progress-bar" style="background-color:#eeeeee;width: <?= floor(100 - $score2*10) ?>%;<?=$cssNoVotes?>">
                          
                        </div>
                    </div>
                </div>
            </td>
           
        </tr>
        </tbody>
    </table>

    <div style="text-align: center;">        
         <select id="ratingoptions">
            <?php
             if($userScore){
                echo '<option value="-1">Remove Rating</option>';
             }else{
                echo '<option value="0">Give a Rating</option>';
             }
             foreach ($options as $key => $value) {
                $selected = '';
                if($userScore==$key) $selected=' selected';
                echo '<option value='.$key.$selected.'>'.$key.' '.$value.'</option>';                
            } ?>         
        </select> 
    </div>
</div>
<script type="text/javascript">    
     $(document).ready(function(){                        
             $('#ratingoptions').find('option').click(function () {
             var optionSelected = $(this);
             var valueSelected  = optionSelected.val();
             var textSelected   = optionSelected.text();

             var loginuser = $('#score-product-modal').find('#loginuser').val();
             var productcreator = $('#score-product-modal').find('#productcreator').val();
             if (loginuser == productcreator) {
                // ignore
                $('#score-product-modal').find('#votelabel').text('Project owner not allowed');
                $('#score-product-modal').find('.modal-body').empty();
                $('#score-product-modal').modal('show');
                return;
             }
             
             var userscore = $('#score-product-modal').find('#userscore').val();
                // -1 = no rate yet. 
             if(userscore>0)
             {
                $('#score-product-modal').find('#votelabel').empty()
                    .append('Score '+userscore+' is given already with comment:'+$('#score-product-modal').find('#otxt').val());                

             }else
             {                
                $('#score-product-modal').find('#votelabel').empty()
                    .append('Add Comment (min. 1 char):');               
             }
             $('#score-product-modal').find(':submit').css("display", "block").removeAttr("disabled");
             $('#score-product-modal').find('#commenttext').removeAttr("disabled");
             $('#score-product-modal').find('#commenttext').val(textSelected);
             $('#score-product-modal').find('#userscorevalue').val(valueSelected);
             
             if(valueSelected=='-1')
             {
                $('#score-product-modal').find(':submit').text("Remove Rating");                             
             }else
             {
                $('#score-product-modal').find(':submit').text("Rate Now");                          
             }
             
             $('#score-product-modal').modal('show');
           });


        });
</script>


