<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperImage = new Default_View_Helper_Image();
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
$this->myCounter = $this->myCounter + 1;

if (($this->partialCounter<4 && $this->partialCounter  % 5 == 0) || ($this->partialCounter>4 && $this->partialCounter  % 4 == 0)):?>
</div>
<?php endif; ?>

<?php if (($this->partialCounter < 4 && $this->partialCounter % 5 == 0) || ($this->partialCounter > 4 && $this->partialCounter % 4 == 0)): ?>
<div class="row-fluid">
    <?php endif; ?>

    <div class="span3 post">
        <div class="clearfix">
            <div class="supporter-thumbnail relative">
                <?php echo $this->myCounter; ?>
                <a href="<?php echo $helpMemberUrl->buildExternalUrl($this->member_id); ?>">
                    <div class="profile-image-overlay-3 absolute"></div>
                    <img src="<?= $helperImage->Image($this->profile_image_url,array('width' => 89, 'height' => 80, 'crop' => 2)); ?>" alt="<?= $this->username ?>" width="80">
                </a>
            </div>
            <!-- /.supporter-thumbnail -->

            <div class="supporter-details">
                <h3 class="supporter-name?>"><?php echo $this->username; ?></h3>
                <?php if ($this->comment) { ?>
                    <div class="supporter-comment">
                        <?php echo $this->comment; ?>
                    </div>
                <?php } ?>
                <span>
            	$<?= $this->amount ?>
            </span>

            </div>
        </div>
    </div>
    <!-- END .post -->