<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

 // product detail follow single project button				 			
$cntheart = $this->fetchHeartsForProject($this->project_id);
$isFollower = false;
$member_id = null;
if($this->authMember){
	$member_id = $this->authMember->member_id;
	$isFollower = $this->userFollowsProject($member_id, $this->project_id);
}

//$heartatt = 'class="partialbuttonheartdetail"';    	
$heartatt = '';    	
if ($member_id && $isFollower) {
	$urlUserFollows = $this->buildProductUrl($this->project_id, 'unfollowp');					
}else{
	$urlUserFollows = $this->buildProductUrl($this->project_id, 'followp');    			   
}

$heartatt = $heartatt. 'role="button" data-fragment=""  '
	      .' data-target="#container-follow'.$this->project_id.'"'
	      .' data-href="'.$urlUserFollows.'"'
	      .' data-auth="'.$member_id.'"';
//$out = '<button ' .$heartatt.'>';
$out = '';
if($cntheart>0){
       if ($isFollower){
            $out = $out. '<i class="fa fa-heart heartproject partialbuttonheartdetail" aria-hidden="true" '.$heartatt.'></i>';
            $out = $out. '<span class="heartnumber small">'.$cntheart.'</span>';
       }else{
            $out = $out. '<i class="fa fa-heart-o heartgrey partialbuttonheartdetail" aria-hidden="true" '.$heartatt.'></i>';
            $out = $out. '<span class="heartnumber heartnumberpurple small">'.$cntheart.'</span>';
       }
}else{
            $out = $out. '<i class="fa fa-heart-o heartgrey partialbuttonheartdetail" aria-hidden="true" '.$heartatt.'></i>';        
}

 //$out = $out.'</button>';

echo $out;