<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helpAddDefaultScheme = new Default_View_Helper_AddDefaultScheme();
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helpEncryptUrl = new Default_View_Helper_EncryptUrl();
$helpImage = new Default_View_Helper_Image();
$helpTruncate = new Default_View_Helper_Truncate();
$helpProductUrl = new Default_View_Helper_BuildProductUrl();
$helpBBCode = new Default_View_Helper_Bbcode2html();

$identity = Zend_Auth::getInstance()->getStorage()->read();

$loginUrl = '/login?redirect=' . $helpEncryptUrl->encryptUrl(Zend_Controller_Front::getInstance()->getRequest()
        ->getRequestUri(), true);
$viewSidebar = 'product/partials/productAboutSidebar.phtml';
$viewClaimBox = false;
if ($this->product->claimable == 1) {
    $viewClaimBox = 'product/partials/productClaimTopHeader.phtml';
}


$this->headTitle($this->product->title . ' - ' . $_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);

$this->headMeta()->setName('description',
    $helpTruncate->truncate($this->product->description, 200, '...', false, true));
$this->headMeta()->setName('title',
    $helpTruncate->truncate($this->product->title, 200, '...', false, true));
$this->headMeta()->appendProperty('og:url', $helpProductUrl->buildProductUrl($this->product->project_id, '', null, true));
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', $this->product->title);
$this->headMeta()->appendProperty('og:description',
    $helpTruncate->truncate($this->product->description, 200, '...', false, true));
$this->headMeta()->appendProperty('og:image',
    $helpImage->Image($this->product->image_small, array('width' => 400, 'height' => 400)));

$this->headLink()->appendStylesheet('/theme/flatui/css/explore_index.css');
$this->headLink()->appendStylesheet('/theme/react/lib/mdl/material.min.css');
$this->headLink()->appendStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons');
$this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Ubuntu:300,400,500');
$this->headLink()->appendStylesheet('/theme/react/assets/css/style.css');

?>

<main id="explore-content"></main>

<script type="text/javascript" src="/theme/react/lib/react/react.js"></script>
<script type="text/javascript" src="/theme/react/lib/react-dom/react-dom.js"></script>
<script type="text/javascript" src="/theme/react/lib/redux/redux.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/redux/react-redux.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/mdl/material.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/timeago/timeago.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/md5/md5.js"></script>

<script type="text/javascript">
var view = "product";
var product = <?php echo $this->productJson ?>;  // product info. title, category, image ...
var updatesJson = <?php echo $this->updatesJson ?>; // Tab changelogs
var ratingsJson = <?php echo $this->ratingsJson ?>; //  Tab Ratings & Reviews
var ratingOfUserJson = <?php echo $this->ratingOfUserJson ?>;  // Rating of user if exist
var likeJson = <?php echo $this->likeJson ?>;    // Tab Favs
var projectplingsJson = <?php echo $this->projectplingsJson ?>; // Tab Plings
var galleryPicturesJson = <?php echo $this->galleryPicturesJson ?>;

var originsJson = <?php echo $this->originsJson ?>; // rightsidebar origins products = Based on
var relatedJson = <?php echo $this->relatedJson ?>;// rightsidebar Variants
var moreProductsJson = <?php echo $this->moreProductsJson ?>; // rightsidebar more proudcts of category
var moreProductsOfOtherUsrJson = <?php echo $this->moreProductsOfOtherUsrJson ?>; // rightsidebar more products of user
var tagsuserJson = <?php echo $this->tagsuserJson ?>;  // user tags
var tagssystemJson = <?php echo $this->tagssystemJson ?>;  // rightsidebar bottom system tags
var commentsJson = <?php echo $this->commentsJson ?>; // comments  TODO Paging
var filesCntJson = <?php echo $this->filesCntJson ?>;   // Tab( active files cnt )
var filesJson  = <?php echo $this->filesJson ?>;  // Tab files

var authMemberJson = <?php echo $this->authMemberJson ?>  // authMember
</script>
<script type="text/javascript" src="/theme/react/all.js"></script>
