<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helpAddDefaultScheme = new Default_View_Helper_AddDefaultScheme();
$helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
$helpEncryptUrl = new Default_View_Helper_EncryptUrl();
$helpImage = new Default_View_Helper_Image();
$helpTruncate = new Default_View_Helper_Truncate();
$helpProductUrl = new Default_View_Helper_BuildProductUrl();
$helpBBCode = new Default_View_Helper_Bbcode2html();

$identity = Zend_Auth::getInstance()->getStorage()->read();

$loginUrl = '/login?redirect=' . $helpEncryptUrl->encryptUrl(Zend_Controller_Front::getInstance()->getRequest()
        ->getRequestUri(), true);
$viewSidebar = 'product/partials/productAboutSidebar.phtml';
$viewClaimBox = false;
if ($this->product->claimable == 1) {
    $viewClaimBox = 'product/partials/productClaimTopHeader.phtml';
}
$helpProjectFiles = new Default_View_Helper_ProjectFiles();
$productFileInfos = $helpProjectFiles->projectFiles($this->product->ppload_collection_id);

$this->product->title = Default_Model_HtmlPurify::purify($this->product->title);
$this->product->description = Default_Model_BBCode::renderHtml(Default_Model_HtmlPurify::purify($this->product->description));
$this->product->version = Default_Model_HtmlPurify::purify($this->product->version);
$this->product->embed_code = Default_Model_HtmlPurify::purify($this->product->embed_code, Default_Model_HtmlPurify::ALLOW_VIDEO);
$this->product->link_1 = Default_Model_HtmlPurify::purify($helpAddDefaultScheme->addDefaultScheme($this->product->link_1),Default_Model_HtmlPurify::ALLOW_URL);
$this->product->github_code = Default_Model_HtmlPurify::purify($this->product->github_code,Default_Model_HtmlPurify::ALLOW_URL);
$this->product->facebook_code = Default_Model_HtmlPurify::purify($this->product->facebook_code,Default_Model_HtmlPurify::ALLOW_URL);
$this->product->twitter_code = Default_Model_HtmlPurify::purify($this->product->twitter_code,Default_Model_HtmlPurify::ALLOW_URL);
$this->product->google_code = Default_Model_HtmlPurify::purify($this->product->google_code,Default_Model_HtmlPurify::ALLOW_URL);

$this->headTitle($this->product->title . ' - ' . $_SERVER['HTTP_HOST'], 'SET');
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);

$this->headMeta()->setName('description',
    $helpTruncate->truncate($this->product->description, 200, '...', false, true));
$this->headMeta()->setName('title',
    $helpTruncate->truncate($this->product->title, 200, '...', false, true));
$this->headMeta()->appendProperty('og:url', $helpProductUrl->buildProductUrl($this->product->project_id, '', null, true));
$this->headMeta()->appendProperty('og:type', 'website');
$this->headMeta()->appendProperty('og:title', $this->product->title);
$this->headMeta()->appendProperty('og:description',
    $helpTruncate->truncate($this->product->description, 200, '...', false, true));
$this->headMeta()->appendProperty('og:image',
    $helpImage->Image($this->product->image_small, array('width' => 400, 'height' => 400)));
$tableProject = new Default_Model_Project();

$tableProjectUpdates = new Default_Model_ProjectUpdates();
$this->updates = $tableProjectUpdates->fetchProjectUpdates($this->product->project_id);

$tableProjectRatings = new Default_Model_DbTable_ProjectRating();
$this->ratings = $tableProjectRatings->fetchRating($this->product->project_id);
if (Zend_Auth::getInstance()->hasIdentity()){
    // login user  ini rating for current product
    $this->ratingOfUser = $tableProjectRatings->getProjectRateForUser($this->product->project_id,$identity->member_id);  
} 

?>

    <!-- facebook -->
    <div id="fb-root"></div>

    <div id="report-product-<?= $this->product->project_id ?>" class="modal report-product" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <form id="product-report" class="full-width partialjson" action="/report/product/"
                      data-target="#report-product-<?= $this->product->project_id ?>-message">
                    <input type="hidden" name="p" value="<?= $this->product->project_id ?>">
                    <div id="report-product-<?= $this->product->project_id ?>-message">
                        <p>Do you really want to report this product?</p>
                        <div class="modal-footer">
                            <button type="submit" class="small">
                                <span class="glyphicon glyphicon-share-alt"></span> Yes
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <?php /** 20180111 ronald: vorerst entfernt: if (Zend_Auth::getInstance()->hasIdentity() && $this->isSupporter($identity->member_id)) {**/ ?>
    <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
    <div id="review-product-modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding-bottom: 20px">
               <div class="modal-header">
                    <label id="votelabel"> </label>
                   <button type="button" class="close col-md-1" data-dismiss="modal" aria-label="Close"><span
                               aria-hidden="true">&times;</span></button>
               </div>
               <div class="modal-body">
                 <form class="full-width product-add-comment-review" action="/productcomment/addreplyreview/" method="post">
                            <input type="hidden" name="p" value="<?= $this->product->project_id ?>"/>
                            <input type="hidden" name="m" value="<?= $identity->member_id ?>" id="loginuser"/>
                            <input type="hidden" name="v" value="1" id="voteup"/>
                            <input type="hidden" name="pm" value="<?=$this->product->member_id?>" id="productcreator"/>
                            <input type="hidden" name="userrate" value="<?=$this->ratingOfUser==null?-1:$this->ratingOfUser['user_like']?>" id="userrate"/>
                            <textarea name="msg" class="full-width" id="commenttext"><?=$this->ratingOfUser!=null?$this->ratingOfUser['comment_text']:''?></textarea>
                            <button type="submit" class="small pull-right">Rate Now</button>
                </form>
                </div>
            </div>
        </div>
    </div>
    
    <?php } else {?>
        <div id="review-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
           <div class="modal-content" style="min-height: 100px; ">
                <span style="text-align: center; display: block; padding-top: 30px">Please login.</span>
           </div>
         </div>          
        </div>
    <?php }?>

    <?php /**} else {?>
        <div id="review-product-modal" class="modal fade noid" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
           <div class="modal-content" style="min-height: 100px; ">
               <span style="text-align: center; display: block; padding-top: 30px">Only registered members with an active supporting can vote. <a href="/support">Become a supporter</a> </span>
           </div>
         </div>          
        </div>
    <?php } **/ ?>

    <main id="product-page-content">
        <div class="flex-column">
            <div class="flex-item-4 sidebar-left" style="">
                <?php  echo $this->render('explore/partials/filter.phtml'); ?>          
            </div>

            <div class="flex-item-16 " id="product-main">
                <div class="flex-row imgsmall" id="product-main-img-container">
                    <div class="product-main-img flex-item-24" id="product-main-img">
                        <div id="product-title-div">
                            <span id="product-title" >
                              
                                <?php if (false === empty($this->product->link_1)): ?><a
                                    href="<?php echo $this->product->link_1; ?>"
                                    target="_NEW"
                                    title="<?php echo $this->product->link_1; ?>"
                                    rel="nofollow"
                                    > <?= $this->product->title; ?> <span class="fa fa-external-link"></span></a>
                                <?php else : ?>
                                    <?= $this->product->title; ?>
                                <?php endif; ?>


                                <div class="product-logo-container">
                                  <img class="logo" src="<?= $helpImage->Image($this->product->image_small,
                                      array('width' => 85, 'height' => 85, 'crop' => 'crop')); ?>"/>
                                </div>
                                <span class="product_category" style="white-space: nowrap;">                                                
                                <?php
                                echo '<a href="/browse/cat/' . $this->product->project_category_id . '/order/latest">' . $this->product->cat_title . ' </a>';
                                ?>                        
                                </span>
                                <span class="light small">
                                <?php if (false === empty($this->product->github_code)):
                                    echo '<a target="_blank" href="' . $this->product->github_code . '" rel="nofollow">' . $this->product->github_code
                                        . ' <span class="fa fa-external-link"></span></a>';
                                endif;
                                ?>
                                
                                </span>
                            </span>
                            <div style="float: right; width:150px; z-index: 100">
                            <?php echo $this->render('partials/sidebarRating.phtml'); ?>
                            </div>
                        </div>
                        <div id="carouselContainer" class="carouselContainer">
                            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">

                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <?php
                                    $this->galleryPictures = $tableProject->getGalleryPictureSources($this->product->project_id);
                                    if (count($this->galleryPictures) > 0) {
                                        $cnt = 1;
                                        foreach ($this->galleryPictures as $picture): ?>
                                            <li data-target="#myCarousel" data-slide-to="<?php echo $cnt ?>"
                                                class="<?php if (!$this->product->ppload_collection_id && $cnt == 1) {
                                                    echo 'active';
                                                } ?>"></li>
                                            <?php
                                            $cnt++;
                                        endforeach;
                                    }
                                    ?>
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <?php
                                    $cnt = 1;
                                    foreach ($this->galleryPictures as $picture): ?>
                                        <div class="item <?php if (!$this->product->ppload_collection_id && $cnt == 1) {
                                            echo 'active';
                                        } ?>">
                                            <img src="<?php echo $helpImage->Image($picture, array('height' => '600')); ?>"/>
                                        </div>
                                        <?php
                                        $cnt++;
                                    endforeach; ?>
                                </div><!-- End Carousel Inner -->

                                <!-- Controls -->
                                <?php if (count($this->galleryPictures) > 1) { ?>
                                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </a>
                                <?php } ?>
                            </div><!-- End Carousel -->
                        </div>

                        
                    </div>
                </div>

                <div class="flex-item-24" id="product-tabs-container">
                    <!-- TABS -->
                    <div id="product-tabs" class="pling-nav-tabs">
                        <ul class="nav nav-tabs ">
                            <li class="active"><a href="#about-panel" data-toggle="tab">Product</a></li>
                            <?php if (null != ($this->product->embed_code)) { /*OR count($this->galleryPictures) > 0 */ ?>
                                <li>
                                    <a href="#media-panel" data-toggle="tab">
                                        <?php if (null != ($this->product->embed_code)) { ?>
                                            Media
                                        <?php }
                                        ?>
                                    </a>
                                </li>
                            <?php } ?>
                            <li><a href="#files-panel" data-toggle="tab">Files <span id="files-counter"></span></a></li>
                        <?php if(count($this->updates)>0){ ?>
                            <li><a href="#updates-panel" data-toggle="tab">Changelogs <?php echo '('.count($this->updates).')';  ?></a></li>
                        <?php } ?>
                        <?php if(count($this->ratings)>0){ ?>
                            <li><a href="#ratings-panel" data-toggle="tab">Ratings & Reviews <?php echo '('.count($this->ratings).')';  ?></a></li>
                        <?php } ?>
                        </ul>
                    </div>
                    <!-- /TABS -->

                    <!-- PANELS -->

                    <div class="tab-content row" id="product-panels">

                        <!-- ABOUT -->
                        <div class="tab-pane active" id="about-panel">


                            <div id="product-about" class="col-lg-9 col-md-9 col-sm-9 col-xs-9">

                                <div>
                                    <article>
                                        <b>Description:</b> <br/><br/>
                                        <?=$this->product->description ?>
                                    </article>


                                    <article>
                                        <?php
                                        if (count($this->updates) > 0) {
                                            $this->productUpdate = $this->updates[0];
                                            ?>
                                            <b>Last changelog:</b>

                                            <?= $this->render('product/partials/productUpdatesV1.phtml'); ?>

                                        <?php } ?>
                                    </article>

                                    <!-- comments -->
                                    <div id="product-discussion">
                                        <?php
                                        $modelComments = new Default_Model_ProjectComments();
                                        $offset = $this->paramPageId;
                                        $testComments = $modelComments->getCommentTreeForProject($this->product->project_id);
                                        $testComments->setItemCountPerPage(25);
                                        $testComments->setCurrentPageNumber($offset);
                                        $this->comments = $testComments;
                                        echo $this->render('product/partials/productCommentsUX1.phtml');
                                        ?>
                                    </div>
                                    <!-- /comments -->
                                </div>

                            </div>

                            <?php if ($viewClaimBox) {
                                echo $this->partial(
                                    $viewClaimBox,
                                    array(
                                        "member"  => $this->member,
                                        "product" => $this->product
                                    )
                                );
                            }
                            ?>


                        </div>
                        <!-- /ABOUT -->

                        <!-- MEDIA -->
                        <div class="tab-pane" id="media-panel">
                            <?php if (null != ($this->product->embed_code)): ?>
                                <?= $this->product->embed_code ?>
                            <?php endif; ?>
                        </div>
                        <!-- /MEDIA -->

                        <!-- updates panel -->
                        <?php  if (count($this->updates) > 0) { ?>
                        <div class="tab-pane" id="updates-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                            <article>
                                <?php 
                                    foreach ($this->updates as $this->productUpdate) {
                                       echo $this->render('product/partials/productUpdatesV1.phtml');
                                    }
                                  ?>
                            </article>
                            </div>
                        </div>
                        <?php } ?>

                        <!-- ratings panel -->
                        <?php  if (count($this->ratings) > 0) { ?>
                        <div class="tab-pane" id="ratings-panel">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                            <article>
                                <div id="productRatingContainer">
                                <?php                                    
                                       echo $this->render('product/partials/productRating.phtml');                                   
                                  ?>
                                  </div>
                            </article>
                            </div>
                        </div>
                        <?php } ?>
                        
                        <div class="tab-pane" id="files-panel">
                            <div class="col-lg-12">
                                <?php
                                echo $this->render('product/partials/ppload.phtml');
                                ?>
                            </div>
                        </div>


                    </div>

                    <!-- /PANELS -->


                </div>


            </div>
            <div class="flex-item-4 flex-right" id="product-maker">
                <div>
                    <div class="project-share-new col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <script type="text/javascript">
                            function fbs_click(a) {
                                u = location.href;
                                t = document.title;
                                window.open(a.getAttribute('href') + '&t=' + encodeURIComponent(t), 'sharer', 'toolbar=0,status=0,width=626,height=436');
                                return false;
                            }

                        </script>


                        <div class="row">
                            <a class="share-button facebook"
                               href="http://www.facebook.com/sharer.php?u=<?= $this->dataUrl ?>&title=<?= $this->product->title ?>"
                               target="_blank" onclick=" return fbs_click(this);">
                                <span class="share-verb">Share</span>
                            </a>

                            <a class="share-button twitter"
                               href="http://twitter.com/share?text=I like this <?= $this->product->title ?>&amp;url=<?= $this->dataUrl ?>&amp;related=plingit"
                               target="_blank"
                               onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=436,width=626');return false;">
                                <span class="share-verb">Tweet</span>
                            </a>

                            <span style="margin-left: 5px;padding-top: 5px">
                              <a class="g-plus" data-action="share" data-annotation="bubble" data-width="120"
                                 data-height="24"></a>
                              </span>
                        </div>

                        <script>
                            window.___gcfg = {
                                lang: 'en-US',
                                parsetags: 'onload'
                            };
                        </script>
                        <script src="https://apis.google.com/js/platform.js" async defer></script>

                        <?php if (empty($this->product->claimable)) { ?>
                            <div class="prod-widget-box prod-user right ">
                                <div class="sidebar-content">
                                    <div class="product-maker-sidebar">
                                        <div class="product-maker-thumbnail relative">
                                            <a href="<?php echo $helpMemberUrl->buildMemberUrl($this->product->member_id); ?>"
                                               title="<?= $this->product->username ?>">
                                               <?php 
                                                    if($this->isSupporter($this->product->member_id)) {
                                                ?>
                                                    <span class="supporter-badge" >S</span> 
                                                <?php } ?>                                               
                                                <img src="<?= $helpImage->Image($this->product->profile_image_url,
                                                    array('width' => 80, 'height' => 80)) ?>"
                                                     alt="product-maker" width="15" height="15"
                                                     class="sidebar-profile-image">
                                            </a>
                                        </div>
                                        <div class="product-maker-summary">
                                            <h5>
                                                <a href="<?php echo $helpMemberUrl->buildMemberUrl($this->product->member_id); ?>">
                                                    <?= $this->product->username; ?>
                                                </a>
                                            </h5>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>

                        <?php /* echo $this->render('partials/sidebarRating.phtml');  */ ?>
                        
                        <div>
                            <div class="prod-widget-box right">
                                <div  class="btn-group dropleft" style="width: 100%">
                                    <button style="width: 100%" id="project_btn_download" class="btn btn-primary dropdown-toggle active disabled" type="button" data-toggle="dropdown">Download
                                    </button>
                                    <ul class="dropdown-menu hide" id="dropdown_downloads">
                                    </ul>
                                </div> 
                                <br>
                                <br>
                                <div  class="btn-group dropleft" style="width: 100%">
                                    <button style="width: 100%" id="project_btn_install" class="btn btn-primary dropdown-toggle active disabled" type="button" data-toggle="dropdown">Install
                                    </button>
                                    <ul class="dropdown-menu hide" id="dropdown_installs">
                                    </ul>
                                </div> 
                            </div>
                        </div>


                        <!-- MORE PRODUCTS -->

                        <div>
                            <?php
                            $this->moreProducts = $tableProject->fetchMoreProjects($this->product, 8);
                            $this->moreProductsTitle = 'More ' . $this->product->cat_title . ' from ' . $this->product->username;

                            if (count($this->moreProducts) > 0) {
                            echo $this->render('product/partials/productMoreProductsWidgetV1.phtml');
                            } ?>
                        </div>

                        <div>
                            <?php
                            $this->moreProducts = $tableProject->fetchMoreProjectsOfOtherUsr($this->product, 8);
                            $this->moreProductsTitle = 'Other ' . $this->product->cat_title;

                            if (count($this->moreProducts) > 0) {
                            echo $this->render('product/partials/productMoreProductsWidgetV1.phtml');
                            } ?>
                        </div>
                        <!-- /MORE PRODUCTS -->


                        <?php echo $this->render('partials/sidebarCcLicense.phtml'); ?>

                        <?php echo $this->render('product/partials/details.phtml'); ?>

                        <?php echo $this->render('product/partials/tags.phtml');?>

                    </div>
                </div>

            </div>

        </div>
    </main>

    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

<script>
    (function (collection_id) {
        if (!collection_id) {
            return;
        }
        $.ajax({
            url: '<?= PPLOAD_API_URI ?>files/index',
            type: 'GET',
            data: {
                format: 'json',
                status: 'active',
                collection_id: collection_id,
                perpage: 100
            },
            dataType: 'json',
            success: function (response_data, textStatus, jqXHR) {
                var amount;
                if (response_data.status === 'success') {
                    amount = response_data.pagination.totalItems;
                    if (0 < parseInt(amount)) {
                        $('#files-counter').append('('+amount+')');
                    }
                }
            }
        });
    }(<?=$this->product->ppload_collection_id?>));
</script>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){       
            PartialJson.setup();
            ProductDetailCarousel.setup();
          //  AjaxForm.setup("form.product-add-comment-review", "div#productRatingContainer");
            PartialCommentReviewForm.setup();
            
        });
    ');
