<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

 // product detail pling single project button	
$plings = new Default_Model_DbTable_ProjectPlings();			 			
$cntplings = count($plings->getPlings($this->project_id));
$isPlinged = false;
$member_id = null;
$isSupporter = false;
if($this->authMember){
	$member_id = $this->authMember->member_id;
	$tmp = $plings->getPling($this->project_id,$member_id);
      if($tmp)
      {
            $isPlinged = true;
      }
      $isSupporter = $this->isSupporter($member_id);
}


 	
$heartatt = '';    	
if ($member_id && $isSupporter && $isPlinged) {
	$urlUserFollows = $this->buildProductUrl($this->project_id, 'unplingproject');					
}else{
	$urlUserFollows = $this->buildProductUrl($this->project_id, 'plingproject');    			   
}

$heartatt = $heartatt. 'role="button" data-fragment=""  '
	      .' data-target="#container-follow'.$this->project_id.'"'
	      .' data-href="'.$urlUserFollows.'"'
            .' data-issupporter="'.$isSupporter.'"'
	      .' data-auth="'.$member_id.'"';
$out ='<div role="button" class="partialbuttonplingproject" '.$heartatt.'>';
if($cntplings>0){
       if ($isPlinged){
            $out = $out. '<i class="fa fa-check heartproject " aria-hidden="true" '.$heartatt.'></i>';
            $out = $out. '<span class="heartnumber small " >'.$cntplings.'</span>';
       }else{
            $out = $out. '<i class="fa fa-check heartgrey " aria-hidden="true" '.$heartatt.'></i>';
            $out = $out. '<span class="heartnumber heartnumberpurple small  " >'.$cntplings.'</span>';
       }
}else{
            $out = $out. '<i class="fa fa-check heartgrey " aria-hidden="true" '.$heartatt.'></i>';        
}

 $out = $out.'</div>';
echo $out;
?>


