<?php

/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
class Default_Model_DbTable_MediaViews extends Local_Model_Table
{
    const MEDIA_TYPE_VIDEO = 1;
    const MEDIA_TYPE_MUSIC = 2;
    const MEDIA_TYPE_BOOK = 3;
    /** @var  Zend_Cache_Core */
    protected $cache;
    protected $_name = "media_views";
    protected $_keyColumnsForRow = array('media_view_id');
    protected $_key = 'media_view_id';

    public function getNewId()
    {
        $result = $this->getAdapter()->query('SELECT UUID_SHORT()')->fetch();

        return $result['UUID_SHORT()'];
    }

    /**
     * @inheritDoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->cache = Zend_Registry::get('cache');
    }

    public function fetchCountViewsTodayForFile($collection_id, $file_id)
    {
        if (empty($collection_id)) {
            return 0;
        }

        $today = (new DateTime())->modify('-1 day');
        $filterDownloadToday = $today->format("Y-m-d H:i:s");

        $sql = "    SELECT COUNT(1) AS cnt
                    FROM media_views f
                    WHERE f.collection_id = " . $collection_id . "
                    AND f.file_id = " . $file_id . "
                    AND f.start_timestamp >= '" . $filterDownloadToday . "'               
                   ";
        $result = $this->_db->query($sql)->fetchAll();

        return $result[0]['cnt'];
    }


    public function fetchCountViewsForFileAllTime($collectionId, $file_id)
    {
        if (empty($file_id) || empty($collectionId)) {
            return 0;
        }

        $sql = "    SELECT COUNT(1)  AS cnt
                    FROM media_views f
                    WHERE f.collection_id = " . $collectionId . " 
                    AND f.file_id = " . $file_id . "
                   ";
        $result = $this->_db->query($sql)->fetchAll();

        return $result[0]['cnt'];
    }

    public function fetchCountViewsTodayForProject($project_id)
    {
        if (empty($project_id)) {
            return 0;
        }

        $today = (new DateTime())->modify('-1 day');
        $filterDownloadToday = $today->format("Y-m-d H:i:s");

        $sql = "    SELECT COUNT(1) AS cnt
                    FROM media_views f
                    WHERE f.project_id = " . $project_id . "
                    AND f.start_timestamp >= '" . $filterDownloadToday . "'               
                   ";
        $result = $this->_db->query($sql)->fetchAll();

        return $result[0]['cnt'];
    }


    public function fetchCountViewsForProjectAllTime($project_id)
    {
        if (empty($project_id)) {
            return 0;
        }

        $sql = "    SELECT COUNT(1)  AS cnt
                    FROM media_views f
                    WHERE f.project_id = " . $project_id . "
                   ";
        $result = $this->_db->query($sql)->fetchAll();

        return $result[0]['cnt'];
    }

}