<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>

        <div class="downloadDiv" >
            <a href="https://www.opendesktop.org/p/1175480/" target="_blank"><img src="/images/system/download-app.png" /></a>
        </div>

        <div class="supportDiv" >
        <?php 
                $identity = Zend_Auth::getInstance()->getIdentity();
                if(null == $identity || (null != $identity && !$this->isSupporter($identity->member_id))) {                                                  
        ?>
            <a href="/support" class="btn btn-primary btn-lg active btn-block" role="button" aria-pressed="true">Become a Supporter</a>
        <?php   } else if((null != $identity && $this->isSupporter($identity->member_id))) { ?>
            <a href="/support" class="btn btn-primary btn-lg active btn-block" role="button" aria-pressed="true">Thank you for your support!</a>
        <?php   }?>
        </div>

        <div  class="supportDiv  withborder" >    
        <span><b><?=$this->countSupporters?></b> people support </span>        
        <span style="display: block">
        those who support freedom
         </span>
         <div class="row">
            <?php 
                    $i=0;
                   foreach ($this->supporters as $user) {                                                      
                    if($i++>6) break;
               ?>         
               <a href="<?php echo $this->buildMemberUrl($user['member_id']); ?>" class="tooltipuserleft" data-tooltip-content="#tooltip_content" data-user="<?=$user['member_id']?>">                   
                    <img height="25" width="25" src="<?php echo $this->Image($user['profile_image_url'], array('width' => '25', 'height' => '25', 'crop' => 2)); ?>" class="supporterx" />                   
               </a>
               <?php } ?>
         </div>
        </div>

        <div  class="row sidebar-right-info" >       
            
            <span class="newsTitle"> News </span>
            <div class="prod-widget-box right bgwhite " id="rss-feeds"> </div>                  

        
            <span class="newsTitle"> Forum </span>
            <div class="prod-widget-box right bgwhite " id="blogJson"> </div>     
           
            
            <?php  if (count($this->comments) > 0) {
                ?>
            <span class="newsTitle"> Comments </span>
            <div class="prod-widget-box right bgwhite" id="lastcomments">
                <?php
                foreach ($this->comments as $this->comment) {
                    echo $this->render('explore/partials/comment.phtml');
                }
                ?>
            </div>          
            <?php } ?>
        </div>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){                               
                RssNews.setup();   
                BlogJson.setup();                    
            });
        ');