<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
$modelInfo = new Default_Model_Info();
$this->supporters = $modelInfo->getNewActiveSupporters(9);

$helpPrintDate = new Default_View_Helper_PrintDate();

$git_url = Zend_Registry::get('config')->settings->server->opencode->host;
?>

<style>
.s40 {
    min-width: 40px;
    min-height: 40px;
}
.s40.avatar, .s40.avatar-container {
    width: 40px;
    height: 40px;
    margin-right: 10px;
}
.avatar, .avatar-container {
    border-radius: 3px;
}

.avatar-container .avatar {
    border-radius: 0;
    border: 0;
    height: auto;
    width: 100%;
    margin: 0;
    align-self: center;
}
.identicon.bg2 {
    background-color: #e8eaf6;
}
.identicon.s40 {
    font-size: 16px;
    line-height: 38px;
}

.git-project {
    border-bottom: 1px solid #ccd4d8;
    padding-top: 5px;
    padding-bottom: 5px;
    overflow: hidden;
}

.git-project:last-child {
    border-bottom: none;
}

</style>    


        <div class="downloadDiv" >
            <a href="https://www.opendesktop.org/p/1175480/"><img src="/images/system/ocsstore-download-button.png" /></a>
        </div>

        <div  class="supportDiv  withborder" >    
            <span><b><?=$this->countSupporters?></b> people support </span>        
            <span style="display: block">
            those who create freedom
             </span>
             <div class="row">
                <?php 
                        $i=0;
                       foreach ($this->supporters as $user) {                                                      
                        if($i++>6) break;
                   ?>         
                   <a href="<?php echo $this->buildMemberUrl($user['username']); ?>" class="tooltipuserleft" data-tooltip-content="#tooltip_content" data-user="<?=$user['member_id']?>">                   
                        <img height="25" width="25" src="<?php echo $this->Image($user['profile_image_url'], array('width' => '25', 'height' => '25', 'crop' => 2)); ?>" class="supporterx" />                   
                   </a>
                   <?php } ?>
             </div>
             <span>
                    <a href="/community#supportersPanel">see all</a>
             </span>
        </div>

        <?php echo $this->render('/home/partials/support_box.phtml'); ?>

        <div  class="row sidebar-right-info" >       
            <?php
                if ($this->storeabout) {
                ?>
                    <div class="prod-widget-box right catabout" id="storecontent">
                        <?php include $this->storeabout; ?>
                    </div>
                <?php
                }
                ?>
            
             <?php
                if ($this->catabout) {
                ?>
                    <div class="prod-widget-box right catabout" id="catcontent">
                        <?php include $this->catabout; ?>
                    </div>
                <?php
                }
                ?>

            <?php
                $storeConfig = Zend_Registry::isRegistered('store_config') ? Zend_Registry::get('store_config') : null;
                if($storeConfig->config_id_name=='kde-store' || $storeConfig->config_id_name=='kde' )
                {
                        $this->moderators = $modelInfo->getModeratorsList();
                       ?>
                       <span class="newsTitle"> Moderators  </span>
                       <div class="prod-widget-box right bgwhite" >
                            <?php 
                                 foreach ($this->moderators as $mod) {
                            ?>
                            <a href="<?php echo $this->buildMemberUrl($mod['username']); ?>" class="tooltipuserleft" data-tooltip-content="#tooltip_content" data-user="<?=$mod['member_id']?>">                   
                                <img height="25" width="25" src="<?php echo $this->Image($mod['profile_image_url'], array('width' => '25', 'height' => '25', 'crop' => 2)); ?>" class="supporterx" />                   
                           </a>
                            <?php }?>
                       </div>
                       <?php 
                }
            ?>
                       
            <?php
                
                $store_config = Zend_Registry::get('store_config');
                $is_show_blog_news = $store_config->is_show_blog_news;
                if($is_show_blog_news==1 && $this->is_startpage == true) {
            ?>           
            
            <span class="newsTitle"> News </span>
            <div class="prod-widget-box right bgwhite " id="rss-feeds"> </div>                  
            
            <?php
                }
            ?>
            
            <?php
                
                $is_show_forum_news = $store_config->is_show_forum_news;
                if($is_show_forum_news==1) {
            ?>
        
            <span class="newsTitle"> Forum </span>
            <div class="prod-widget-box right bgwhite " id="blogJson"> </div>     
           
            <?php
                }
            ?>            
            
            <?php
                
                $is_show_git_projects = $store_config->is_show_git_projects;
                if($is_show_git_projects==1 && $this->show_git == true) {
            ?>
            
            <span class="newsTitle"> Git-Projects </span>
             <div class="prod-widget-box right bgwhite" id="lastgitprojects"></div>          
            
            <?php
                }
            ?>
            
            <?php  if (count($this->comments) > 0) {
                ?>
            <span class="newsTitle"> Comments </span>
            <div class="prod-widget-box right bgwhite" id="lastcomments">
                <?php
                foreach ($this->comments as $this->comment) {
                    echo $this->render('explore/partials/comment.phtml');
                }
                ?>
            </div>          
            <?php } ?>

            
        </div>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){                               
                RssNews.setup();   
                BlogJson.setup();   
                GitlabNewProjectsJson.setup("'.$git_url.'");   
            });
        ');