<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
        $helpTruncate = new Default_View_Helper_Truncate();
        $helpImage = new Default_View_Helper_Image();
        $helpProductUrl = new Default_View_Helper_BuildProductUrl();
        $helpCategories = new Default_View_Helper_FetchCategoriesForProductAsString();
        $helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
        $helpDate = new Default_View_Helper_PrintDate();
        //$pageCount = $this->featureProducts->count();
?>
    <div id="featureProducts"  class="carousel slide" data-ride="carousel" data-interval="false">       
       
        <div id="featureProducts-content"  class="carousel-inner">
        <?php        
        foreach ($this->featureProducts as $this->product): ?>            
                    <div style=" " class="feature_container">                      
                        <span style="" class="feature_title"> Featured Product</span>
                        <div style="" class="main_container">
                            <a class="feature_image" style="" title="<?=$helpTruncate->truncate($this->product['description'], 200, '...', false, true)?>" href="<?=$helpProductUrl->buildProductUrl($this->product['project_id'],'')?>">
                               <img  src="<?=$helpImage->Image($this->product['image_small'], array('width' => 300, 'height' => 230 ,'crop' => 1))?>"  style=""/>
                            </a>
                               <div class="feature_text" >
                               <a href="<?=$helpProductUrl->buildProductUrl($this->product['project_id'],'')?>"><?=$this->product['title']?></a>
                               <span  class="feature_text_title" style=""><?=$helpCategories->fetchCategoriesForProductAsString($this->product['project_id'])?> </span>

                               <span class="feature_text_auth" style="">
                               <a  class="auto_link" href="<?php echo $helpMemberUrl->buildMemberUrl($this->product['member_id']); ?>" style="">
                                   <figure >
                                       <img src="<?php echo $helpImage->Image($this->product['profile_image_url'], array('width' => '50', 'height' => '50', 'crop' => 2)); ?>" style=""/>
                                   </figure>
                                        
                               </a>
                                  <span class="created_by" style=""> created by <?php echo $this->product['username']; ?> </span>
                               </span>
                              

                                <span class="feature_text_comments" style="">
                                <?php                                    
                                    $count_comments = $this->product['count_comments'];                                                                        
                                    echo ($count_comments>0 ? '<span class="cntComments">'.$count_comments.' comment':'').($count_comments>1?'s':'').($count_comments>0?'</span>':'') ;                                    
                                ?>
                                </span>
                                
                                <span class="feature_text_description" style="">                                  
                                        <?=$helpTruncate->truncate($this->product['description'], 300, '...', false, true)?>
                                </span>
                                
                                <span class="time" style=""><?=$helpDate->printDate($this->product['changed_at']==null?$this->product['created_at']:$this->product['changed_at'])?>
                                </span>


                                </div>
                              
                                  <div style="clear: left"></div>
                                  <span class="button_next small">
                                         <a type="button" class="ajaxPartialFeatureProduct" href="/showfeatureajax/page/1">next</a>                                          
                                 </span>   

                          </div>      
                                                                   
                    </div>                           
        <?php endforeach;?>        
        
      </div>

         
           <?php /*
       <?php if ($pageCount > 1) echo $this->paginationControl($this->featureProducts, 'Sliding', 'home/partials/paginationControl.phtml',
                    array('params' => array(), 'dom_target' => 'div#featureProductsContainer')); 
                    ?>
                    */
              ?>
        
    </div>

    





