<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
        $helpTruncate = new Default_View_Helper_Truncate();
        $helpImage = new Default_View_Helper_Image();
        $helpProductUrl = new Default_View_Helper_BuildProductUrl();
        $helpCategories = new Default_View_Helper_FetchCategoriesForProductAsString();
        $helpMemberUrl = new Default_View_Helper_BuildMemberUrl();
        $helpDate = new Default_View_Helper_PrintDate();
        //$pageCount = $this->featureProducts->count();
?>
    <div id="featureProducts"  class="carousel slide" data-ride="carousel" data-interval="false">       
       
        <div id="featureProducts-content"  class="carousel-inner">
        <?php        
        foreach ($this->featureProducts as $this->product): ?>            
                    <div style=" " class="feature_container">                      
                        
                            <span  class="feature_title">In the Spotlight</span>
                         
                        <div  class="main_container">
                               
                             <span class="small label label-info label_featured" style="float: right; <?php if($this->product['featured']<>1) echo 'visibility:hidden'; ?>">                                    
                                    Featured
                            </span>   
                                                        
                              <a class="feature_image"  title="<?=$helpTruncate->truncate($this->product['description'], 200, '...', false, true)?>" href="<?=$helpProductUrl->buildProductUrl($this->product['project_id'],'')?>">
                                 <img  src="<?=$helpImage->Image($this->product['image_small'], array('width' => 300, 'height' => 230 ,'crop' => 1))?>"  />
                              </a>

                               <div class="feature_text" >
                               <div style="display: flex">
                                        <div style="width:340px"><a href="<?=$helpProductUrl->buildProductUrl($this->product['project_id'],'')?>"><?=$this->product['title']?></a>
                                                  <span  class="feature_text_title" ><?=$helpCategories->fetchCategoriesForProductAsString($this->product['project_id'])?> </span>
                                        </div>
                                        <div style="flex: 1; text-align: right; width: 80px;padding-right:10px;padding-top: 5px;">
                                              <div class="rating" style="font-size: small;">
                                                  <?php                
                                                          $this->widgetRating = new stdClass();
                                                          $this->widgetRating->project_id = $this->product['project_id'];
                                                          $this->widgetRating->laplace_score = $this->product['laplace_score'];
                                                          $this->widgetRating->count_likes = $this->product['count_likes']; 
                                                          $this->widgetRating->count_dislikes =$this->product['count_dislikes'];
                                                          echo $this->render('partials/widgetRating.phtml'); 
                                                  ?>
                                              </div>
                                              <span class="time text-center" style="font-size: smaller;display: block"><?=$helpDate->printDate($this->product['changed_at']==null?$this->product['created_at']:$this->product['changed_at'])?>
                                              </span>
                                        </div>
                                </div>
                               <div class="feature_text_auth" >
                               <a  class="auto_link" href="<?php echo $helpMemberUrl->buildMemberUrl($this->product['member_id']); ?>" >
                                   <figure >
                                       <img src="<?php echo $helpImage->Image($this->product['profile_image_url'], array('width' => '50', 'height' => '50', 'crop' => 2)); ?>" />
                                   </figure>                                        
                               </a>
                                  <span class="created_by" > created by <?php echo $this->product['username']; ?> </span>

                                  
                               </div>
                              

                                <span class="feature_text_comments" >
                                <?php                                    
                                    $count_comments = $this->product['count_comments'];                                                                        
                                    echo ($count_comments>0 ? '<span class="cntComments">'.$count_comments.' comment':'').($count_comments>1?'s':'').($count_comments>0?'</span>':'') ;                                    
                                ?>
                                </span>
                                
                                <span class="feature_text_description" >                                  
                                        <?=$helpTruncate->truncate($this->product['description'], 300, '...', false, true)?>
                                </span>
                                
                          


                                </div>
                              
                                  <div style="clear: left"></div>
                                  <span class="button_next small">
                                         <a type="button" class="ajaxPartialFeatureProduct" style="padding-right: 20px" href="/showfeatureajax/page/0">random</a>                                          
                                         <a type="button" class="ajaxPartialFeatureProduct" href="/showfeatureajax/page/1">featured</a>                                          
                                 </span>   

                          </div>      
                                                                   
                    </div>                           
        <?php endforeach;?>        
        
      </div>

         
           <?php /*
       <?php if ($pageCount > 1) echo $this->paginationControl($this->featureProducts, 'Sliding', 'home/partials/paginationControl.phtml',
                    array('params' => array(), 'dom_target' => 'div#featureProductsContainer')); 
                    ?>
                    */
              ?>
        
    </div>

    





