<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
if (false === isset($this->params)) {
    $this->params = array();
}
?>


<a class="left carousel-control ajaxPartial" style="height:350px;margin-top: 105px;" href="<?php echo isset($this->previous) ?'/showfeatureajax/page/'.$this->previous : '/showfeatureajax/page/1000'; ?>" data-slide="prev">
                          <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>

<a class="right carousel-control ajaxPartial " style="height:350px;margin-top: 105px;" href="<?php echo isset($this->next) ? '/showfeatureajax/page/'.$this->next : '/showfeatureajax/page/1'; ?>" data-slide="next">
  <span class="glyphicon glyphicon-chevron-right"></span>
</a>

<?php /*
<ul class="pagination pagination-sm" style="margin: 0;padding:0;">
    <li class="<?php echo isset($this->previous) ? '' : 'disabled' ?>">
        <a class="<?php echo isset($this->previous) ? 'ajaxPartial' : '' ?>" href="<?php echo isset($this->previous) ? $this->url(array_merge($this->params,
            array('page' => $this->previous))) : 'javascript:;'; ?>"><span
                class="glyphicon glyphicon-chevron-left"></span></a></li>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li><a class="ajaxPartial" href="/showfeatureajax/page/<?=$page?>"><?php echo $page; ?></a></li>
        <?php else: ?>
            <li class="active"><a class="ajaxPartial" href="/showfeatureajax/page/<?=$page?>"><?php echo $page; ?></a>
        <?php endif; ?>
    <?php endforeach; ?>

    <li class="<?php echo isset($this->next) ? '' : 'disabled' ?>">
        <a class="<?php echo isset($this->next) ? 'ajaxPartial' : ''?>" href="<?php echo isset($this->next) ? '/showfeatureajax/page/'.$this->next : 'javascript:;'; ?>"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
</ul>
*/
?>