<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div  style="width: 200px; background-color: #f1f1f1; float: left; border:1px solid #ddd; margin:2px; height:220px">
         
     <div style="display: block; background-color: #fff; " class="text-center">        
            <img class="productimg" src="<?=$this->Image($this->product['image_small'], array('width' => 100, 'height' => 100))?>" style="margin:10px; width: 100px; height:100px; "/>
            <a style="display: block" href="<?=$this->buildProductUrl($this->product['project_id'],'')?>"><?=$this->product['title']?>                
            </a>
     </div>

     <div style="padding:5px;">
     
          
            <span style="font-size: smaller;"><?=$this->fetchCategoriesForProductAsString($this->product['project_id'])?> </span>
            
     
     
        <div class="rating" style="padding-top: 5px">
            <?php                
                    $this->widgetRating = new stdClass();
                    $this->widgetRating->project_id = $this->product['project_id'];
                    $this->widgetRating->laplace_score = $this->product['laplace_score'];
                    $this->widgetRating->count_likes = $this->product['count_likes']; 
                    $this->widgetRating->count_dislikes =$this->product['count_dislikes'];
                    echo $this->render('partials/widgetRating.phtml'); 
            ?>
        </div>
        <?php /*
        <span class="time"><?=$this->printDate($this->product['changed_at']==null?$this->product['created_at']:$this->product['changed_at'])?>
        </span>
        */
        ?>

    
    </div>
</div >

