<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

  $helperBuildExploreUrl = new Default_View_Helper_BuildExploreUrl();
  $modelInfo = new Default_Model_Info();
  $modelCategory = new Default_Model_DbTable_ProjectCategory();
  $this->dataCategory = $modelCategory->findSingleRow($this->cat_id);
  $this->countSupporters = $modelInfo->getCountActiveSupporters();
  $this->supporters = $modelInfo->getNewActiveSupporters(7);
  $this->headLink()->appendStylesheet('/theme/flatui/css/explore_index.css');
  $this->headLink()->appendStylesheet('/theme/react/lib/mdl/material.min.css');
  $this->headLink()->appendStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons');
  $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,500');
  $this->headLink()->appendStylesheet('/theme/react/assets/css/style.css');
?>

<main id="explore-content"></main>

<script type="text/javascript" src="/theme/react/lib/react/react.js"></script>
<script type="text/javascript" src="/theme/react/lib/react-dom/react-dom.js"></script>
<script type="text/javascript" src="/theme/react/lib/redux/redux.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/redux/react-redux.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/mdl/material.min.js"></script>
<script type="text/javascript" src="/theme/react/lib/timeago/timeago.min.js"></script>

<script type="text/javascript">
  <?php
    $js_products = $this->productsJson;
    $js_filters = $this->filtersJson;
    $js_catid = $this->cat_idJson;
    $js_topprods =$this->topprods;
    $js_comments = $this->commentsJson;
  ?>

  var products = <?php echo $js_products ?>;
  var filters = <?php echo $js_filters ?>;
  var catId = <?php echo $js_catid ?>;
  var comments = <?php echo $js_comments ?>;
  var view = "explore";
  console.log(view);

</script>
<script type="text/javascript" src="/theme/react/all.js"></script>
