<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/


  $modelInfo = new Default_Model_Info();
  
  $this->supporters = $modelInfo->getNewActiveSupporters(7);
  
  $helperBuildBaseUrl = new Default_View_Helper_BuildBaseUrl();
  $basrUrl = $helperBuildBaseUrl->buildBaseUrl();
?>

<main id="explore-content"></main>


<script type="text/javascript">
  var categories = <?php echo $this->categoriesJson ?>;
  var catId = <?php echo $this->cat_idJson ?>;
  var filters = <?php echo $this->filtersJson ?>;
  var products = <?php echo $this->productsJson ?>;
  var topProducts = <?php echo $this->topprodsJson ?>;
  var comments = <?php echo $this->commentsJson ?>;
  var supporters = <?php echo json_encode($this->supporters) ?>;
  var pagination = {
    totalcount:<?php echo $this->totalcount ?>,
    page:<?php echo $this->page ?>,
    pagelimit:<?php echo $this->pageLimit ?>
  }
  var view = "explore";
  var baseUrl = <?php echo Zend_Json::encode($basrUrl)?>;
  
  var browseListType = "<?php echo $this->browseListType ?>";
  
</script>
<script type="text/javascript" src="/theme/react/bundle/appimagehub-home-bundle.js"></script>
