<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div>
    <?php if (($this->page - 1) <= count($this->products)) :
        // The Zend_Paginator Interface gives back the page count overall, not count of the products we have to display. We have to test by our self the point
        // where we are. Damned stupid interface.
        echo $this->partialLoop('explore/partials/product.phtml', $this->products);
    endif;
    echo $this->formHidden('page', $this->page, array('id' => 'page'));
    echo $this->formHidden('ranking', $this->inputFilter['ranking'], array('id' => 'ranking'));
    echo $this->formHidden('category', $this->inputFilter['category'], array('id' => 'category'));
    ?></div>