<?php 
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<div id="content" class="container page-container">

    <div class="wrapper">
        <h1 class="search-heading"><?= $this->translate('NO SEARCH RESULTS') ?></h1>

        <div id="items">
            <hr class="item-divider">
            <?php echo $this->translate('<p>Your search - ' . $this->searchText . ' - did not match any documents.</p>

<p>Suggestions:
<ul>
<li>Make sure all words are spelled correctly.</li>
<li>Try keywords which are min 3 characters long.</li>
<li>Try different keywords.</li>
<li>Try more general keywords.</li>
<li>Try fewer keywords.</li>
<li>Use key words which start without wildcard symbols like "*" or "?".</li>
</ul>
</p>') ?>
        </div>

        <div class="searchFooter">
        </div>
    </div>

</div>
