<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?>
<footer>
    <section class="wrapper">
        <section>
            <div class="pull-left col-lg-10 col-md-10 col-sm-9 col-xs-9">
                <h3 id="footer-heading" class="lightblue"><?=$this->template['footer_heading']?> - <?=$this->template['domain']?></h3>
                <nav id="footer-nav">

                    <ul class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <!-- <li><a href="/faq">What is <?=$this->template['domain']?>?</a></li> -->
                        <!-- <li><a href="http://www.ocsmag.com/" target="blank">Blog</a></li>  -->
                        <li><a href="/terms">Terms & Conditions</a></li>
                        <li><a href="/privacy">Privacy Policy</a></li>
                        <li><a href="/contact">Contact</a></li>
                        <li><a href="/imprint">Imprint</a></li>
                        <li><span style="color:#666;">&#169; <?=date('Y')?> <?=$this->template['domain']?> - <?=$this->template['footer_heading']?></span></li>

                        <li style="display: block; margin-left:0px; padding-top:5px;color:#666;">All rights reserved. All trademarks are copyright by their respective owners. All contributors are responsible for their uploads.
                         </li>
                    </ul>

                </nav>
            </div>



            <div class="pull-right col-lg-2 col-md-2 col-sm-3 col-xs-3" style="height:66px; ">
                <div style="position:absolute;bottom:3px;color:#666;right: 0;">
                Powered by opendesktop.org
                </div>
                <div class="pull-right" style="position: absolute;bottom: 20px;right: 0px;">
                    <h3 id="footer-social-heading">Follow us on</h3>

                    <div id="footer-social">
                        <a href="https://www.facebook.com/opendesktop.org"
                           id="facebook"
                           target="_blank"
                           rel="nofollow"><img src="/theme/flatui/img/new/f_icon_fb.png"/></a>
                        <a href="https://twitter.com/opendesktop"
                           id="twitter"
                           target="_blank"
                           rel="nofollow"><img src="/theme/flatui/img/new/f_icon_tw.png"/></a>
                    </div>
                </div>
            </div>
        </section>
    </section>



</footer>
