<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperImage = new Default_View_Helper_Image();
$newUsers = new Default_View_Helper_NewUsers();
$users = $newUsers->newUsers($limit = 12);

$recentDonations = new Default_View_Helper_FetchRecentDonations();
$donations = $recentDonations->fetchRecentDonations($limit = 12);

$buildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$humanTiming = new Default_View_Helper_HumanTiming();
$buildProductUrl = new Default_View_Helper_BuildProductUrl();
$membersCount = new Default_View_Helper_FetchTotalMembersCount();
$totalAMountSupported = new Default_View_Helper_FetchTotalAmountSupported();

?>
<main id="community-page">

    <section class="head-wrap">

        <section class="wrapper">

            <div class="page-title">
                <div class="center">
                    <div><h1>Community</h1></div>
                </div>
                <hr/>
            </div>

            <div class="row">

                <div class="banner col-lg-5 col-md-5 col-sm-6 col-xs-8">

                    <div class="top">
                        <div class="large"><?= $membersCount->fetchActiveMembersInStoreCount($this->categories) ?></div>
                        <div class="small margin-bottom-10">contributors of</div>

                        <div class="large"><?= $membersCount->fetchTotalMembersCount() ?></div>
                        <div class="small margin-bottom-10">members</div>
                        <?php /*
                        <div class="small">Donating a total of</div>
                        <div class="large">$<?= $totalAMountSupported->fetchTotalAmountSupported() ?></div>
                        */
                        ?>
                    </div>

                    <div class="bottom">

                        <a class="btn btn-native" href="/register">Register</a> to join the community

                    </div>

                </div>

            </div>

        </section>

    </section>

    <section class="body-wrap">

        <section class="wrapper" id="user-lists">


            <div id="community-tabs" style="margin-bottom:20px;">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#recentDonationsPanel" data-toggle="tab"><?= $this->translate('Recent Donations') ?></a></li>
                    <li><a href="#newMemberPanel" data-toggle="tab"><?= $this->translate('New Members') ?></a></li>                  
                </ul>
            </div>
        
        <div class="tab-content" id="communityPanels">
            <div class="row tab-pane active"  id="recentDonationsPanel">
                <div class="list col-lg-10 col-md-10 col-sm-10 col-xs-10 " id="top-supporters">

                   
                    <?php foreach ($donations as $key => $user) {
                        $age = $humanTiming->humanTiming($user['create_time']);
                        ?>

                        <div class="user col-lg-1 col-md-4 col-sm-4 col-xs-4">
                            <div class="u-wrap">
                                <a href="<?= $buildProductUrl->buildProductUrl($user['project_id'], '') ?>">
                                    <figure class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <img src="<?php echo $user['profile_image_url']; ?>"/>
                                    </figure>
                                    <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $user['username']; ?></h3>

                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 u-content">
                                        <span><?= $this->translate('supported') ?>
                                            <b><?= $this->truncate($user['title'], 25) ?></b></span>
                                        <span><?= $this->translate('with') ?> <b>$<?= $user['amount'] ?></b></span>
                                    </div>
                                    <p class="small"><b><?= $age['age'] ?></b> <?= $age['unit'] ?></p>
                                </a>
                            </div>
                        </div>

                    <?php } ?>

                </div>
               
            </div> <!-- end row -->
            <div class="row tab-pane" id="newMemberPanel">
                <div class="list col-lg-10 col-md-10 col-sm-10 col-xs-10 "
                     id="new-members">              
                    <?php foreach ($users as $key => $user) {
                        $age = $humanTiming->humanTiming($user['created_at']);
                        ?>

                        <div class="user col-lg-1 col-md-2 col-sm-2 col-xs-2">
                            <div class="u-wrap">
                                <a href="<?php echo $buildMemberUrl->buildMemberUrl($user['member_id']); ?>">
                                    <figure >
                                        <img src="<?php echo $helperImage->Image($user['profile_image_url'], array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
                                    </figure>
                                    <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $user['username']; ?></h3>

                                    <p class="small"><b><?= $age['age'] ?></b> <?= $age['unit'] ?></p>
                                </a>
                            </div>
                        </div>

                    <?php } ?>

                </div>
            </div> <!-- end row -->

        </div>
        </section>

    </section>

</main>