<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

$helperImage = new Default_View_Helper_Image();
$modelInfo = new Default_Model_Info();
$users = $modelInfo->getNewActiveMembers(100);
$topusers = $modelInfo->getTopScoreUsers(100);
$supporters = $modelInfo->getNewActiveSupporters(100);
$plingproducts = $modelInfo->getNewActivePlingProduct(100);

$buildMemberUrl = new Default_View_Helper_BuildMemberUrl();
$buildProductUrl = new Default_View_Helper_BuildProductUrl();
$membersCount = new Default_View_Helper_FetchTotalMembersCount();
//$totalAMountSupported = new Default_View_Helper_FetchTotalAmountSupported();

?>
<main id="community-page">

    <section class="head-wrap">

        <section class="wrapper">

            <div class="page-title">
                <div class="center">
                    <div><h1>Community</h1></div>
                </div>
                <hr/>
            </div>

            <div class="row">

                <div class="banner col-lg-5 col-md-5 col-sm-6 col-xs-8">

                    <div class="top">
                        <div class="large"><?= $membersCount->fetchActiveMembersInStoreCount($this->categories) ?></div>
                        <div class="small margin-bottom-10">support</div>

                        <div class="large"><?= $membersCount->fetchTotalMembersCount() ?></div>
                        <div class="small margin-bottom-10">members</div>
                       
                    </div>

                    <div class="bottom">

                        <a class="btn btn-native" href="/register">Register</a> to join the community

                    </div>

                </div>

            </div>

        </section>

    </section>

    <section class="body-wrap">

        <section class="wrapper" id="user-lists">


            <div id="community-tabs" style="margin-bottom:20px;">
                <ul class="nav nav-tabs">
                  
                    <li class="active"><a href="#newMemberPanel" data-toggle="tab"><?= $this->translate('New Members') ?></a></li>
                    <?php if(Zend_Auth::getInstance()->hasIdentity() AND Zend_Auth::getInstance()->getIdentity()->roleName == 'admin') {
                        ?>
                        <li><a href="#topMemberPanel" data-toggle="tab"><?= $this->translate('Top Members') ?></a></li>
                  <?php 
                  }?>
                    
                    <li><a href="#supportersPanel" data-toggle="tab"><?= $this->translate('Latest Supporters') ?></a></li>
                    <li><a href="#plingedproductsPanel" data-toggle="tab"><?= $this->translate('Recently plinged Products ') ?></a></li>
                    
                </ul>
            </div>
        
        <div class="tab-content" id="communityPanels">
           
           

            <div class="row tab-pane active" id="newMemberPanel">
                <div class="list"
                     id="new-members">
                    <?php foreach ($users as $key => $user) {                      
                        ?>

                        <div class="user">
                            <div class="u-wrap">
                                <a href="<?php echo $buildMemberUrl->buildMemberUrl($user['member_id']); ?>">
                                    <figure >
                                        <img class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$user['member_id']?>" src="<?php echo $helperImage->Image($user['profile_image_url'], array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
                                    </figure>
                                    <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $user['username']; ?></h3>

                                    <span class="small"><?= $this->printDate($user['created_at'])?><span class="small">
                                </a>
                            </div>
                        </div>

                    <?php } ?>

                </div>
            </div> <!-- end row -->

            <?php if(Zend_Auth::getInstance()->hasIdentity() AND Zend_Auth::getInstance()->getIdentity()->roleName == 'admin') {
                        ?>
            <div class="row tab-pane" id="topMemberPanel">
                    <div class="list  ">
                        <?php 
                        $nr = 1;
                        foreach ($topusers as $key => $user) {                      
                            ?>
                            <div class="user ">
                                <div class="u-wrap" >
                                    <a href="<?php echo $buildMemberUrl->buildMemberUrl($user['member_id']); ?>">
                                        <figure >
                                            <img class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$user['member_id']?>" src="<?php echo $helperImage->Image($user['profile_image_url'], array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
                                        </figure>
                                        <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $user['username']; ?></h3>                                        
                                        <span class="rank">#<?=$nr++?></span>
                                           <span class="small"><?=number_format($user['score'],0,'.',',') ?><span class="small">                                                                 
                                    </a>
                                </div>
                            </div>

                        <?php } ?>
                    </div>
                </div> <!-- end row -->
                <?php } ?>

                <div class="row tab-pane" id="supportersPanel">
                        <div class="list  ">
                                    <?php                                        
                                       foreach ($supporters as $key => $user) {                      
                                           ?>
                                           <div class="user ">
                                               <div class="u-wrap" >
                                                   <a href="<?php echo $buildMemberUrl->buildMemberUrl($user['member_id']); ?>">
                                                       <figure >
                                                           <img class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$user['member_id']?>"  src="<?php echo $helperImage->Image($user['profile_image_url'], array('width' => '200', 'height' => '200', 'crop' => 2)); ?>"/>
                                                       </figure>
                                                       <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $user['username']; ?></h3>                                                                                                      
                                                           <span class="small"><?= $this->printDate($user['created_at'])?><span class="small">                                                                                    
                                                   </a>
                                               </div>
                                           </div>
                                    <?php } ?>           
                        </div>
                </div> <!-- end row -->

                 <div class="row tab-pane" id="plingedproductsPanel">
                        <div class="list ">
                                  <?php 
                                              foreach ($plingproducts as $p) {                                  
                                          ?>
                                              <div class="user " >
                                                  <div class="u-wrap" style=" background-repeat: no-repeat; background-image: url('<?php echo $this->Image($p['image_small'], array('width' => '115', 'height' => '75', 'crop' => 2)); ?>');">                
                                                      <a href="<?php echo $this->buildProductUrl($p['project_id']); ?>" style="" >
                                                          <div  class="product-thumbnail-startpage " style="height: 50px;width: 115px;"
                                                                   data-toggle="popover"
                                                                   data-trigger="hover"
                                                                   data-html="true"
                                                                   data-placement="top"
                                                                  data-content="<div class='profile-img-product center'>
                                                                       <img class='imgpopover'  src='<?php echo $this->Image($p['image_small'], array('width' => '200', 'height' => '160', 'crop' => 1)); ?>'/>
                                                                       </div>
                                                                         <div class='content'>
                                                                             <div class='title'>
                                                                                 <p><?=Default_Model_HtmlPurify::purify($this->truncate($p['title'],20).' - '.$this->truncate($p['catTitle'],20) )?></p>
                                                                             </div>                                                             
                                                                         </div>">         
                                                          </div>         
                                                          <figure style="">                            
                                                              <img class="tooltipuser" data-tooltip-content="#tooltip_content" data-user="<?=$p['member_id']?>" 
                                                                      src="<?php echo $this->Image($p['profile_image_url'], array('width' => '50', 'height' => '50', 'crop' => 2)); ?>" 
                                                                      style="width:40px; height: 40px"                                   
                                                                      />
                                                          </figure>
                                                          <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo Default_Model_HtmlPurify::purify($p['username']); ?></h3>
                                                                                                    
                                                      </a>
                                                       <span class="small created_at" >
                                                          <a class="tooltipuserplings" data-tooltip-content="#tooltip_content" data-user="<?=$p['project_id']?>" ><img src="/images/system/pling-btn-active.png" style="width: 15px; height: 15px" /> </a>
                                                          <?=$p['sum_plings']; ?>
                                                       </span>
                                                  </div>
                                              </div>
                                      <?php } ?>        
                        </div>
                </div> <!-- end row -->


        </div>

       
        </section>

    </section>
<div class="tooltip_templates" style="display: none">
    <span id="tooltip_content">
        <i class="fa fa-spinner"></i>
    </span>
</div>
</main>

<script type="application/javascript">
    // tool tips
    $('body').on('mouseenter', '.product-thumbnail-startpage', function () {
        $(this).popover('show');
    });

    $('body').on('mouseleave', '.product-thumbnail-startpage', function () {
        $(this).popover('hide');
    });
</script>

<?php $this->inlineScript()->appendScript(
    '    $(document).ready(function(){                                             
                TooltipUser.setup("tooltipuser","right");
                TooltipUser.setup("tooltipuserleft","left");             
                TooltipUserPlings.setup("tooltipuserplings","right");
            });
        ');