<?php
/**
 *  ocs-webserver
 *
 *  Copyright 2016 by pling GmbH.
 *
 *    This file is part of ocs-webserver.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

namespace Backend\Controller;

use Application\Model\Entity\Member;
use Application\Model\Service\Interfaces\MemberServiceInterface;
use Laminas\View\Model\JsonModel;

class LetteravatarController extends BackendBaseController
{
    const DATA_ID_NAME = 'member_id';
    private $memberService;

    public function __construct(
        MemberServiceInterface $memberService
    ) {
        parent::__construct();
        $this->memberService = $memberService;
        $this->_model = $memberService;
        $this->_modelName = Member::class;
        $this->_pageTitle = 'Users with avatar type unknown';
        $this->_defaultSorting = 'member_id desc';
    }

    public function listAction()
    {

        $startIndex = (int)$this->params()->fromQuery('jtStartIndex');
        $pageSize = (int)$this->params()->fromQuery('jtPageSize');
        $sorting = $this->params()->fromQuery('jtSorting');
        if ($sorting == null) {
            $sorting = $this->_defaultSorting;
        }


        $result = $this->_model->getMembersAvatarOldAutogenerated($sorting, $pageSize, $startIndex);
        $resultCnt = $this->_model->getMembersAvatarOldAutogeneratedTotalCount();

        $jTableResult = array();
        $jTableResult['Result'] = self::RESULT_OK;
        $jTableResult['Records'] = $result;
        $jTableResult['TotalRecordCount'] = $resultCnt;

        return new JsonModel($jTableResult);
    }

    public function updateAction()
    {

    }

} 